### ISSUE TITLE
Go docs 404: manual instrumentation file needs alias definitions

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1006]
Visit the following, previously valid, URL: https://opentelemetry.io/docs/instrumentation/go/instrumentation/ and you'll get a 404. That shouldn't happen. The link should redirect.

---

There's file name change in that submodule update of #1003: `website_docs/instrumentation.md → website_docs/manual_instrumentation.md ` via https://github.com/open-telemetry/opentelemetry-go/pull/2437. I missed that why reviewing #1003 (because I didn't dig into the submodule changes).

@cartermp - could you fix that? Every time you rename a file you need to add an alias to the front-matter that contains the old file name. Something like this:

```yaml
aliases: [/docs/instrumentation/go/instrumentation]
```

Also, given #997, could you rename the file to `manual.md` and then add a second alias (🤷‍♂️):

```yaml
aliases: [/docs/instrumentation/go/instrumentation, /docs/instrumentation/go/manual_instrumentation]
```

/assign @cartermp 
/cc @austinlparker 

p.s. Yet another reason why all the docs should be in this repo. :)

**Comment by chalin** [comment]
While you're at it, could you also make the following changes?

- Rename `website_docs/using_instrumentation_libraries.md` --> `libraries.md`
  - And add an alias
  - Add `linkTitle: Libraries`
- Add `linkTitle: Exporting data` (or maybe just "Data") to `exporting_data`

**Comment by chalin** [comment]
(@cartermp, if you comment on this issue, I'll be able to assign it to you.)

**Comment by cartermp** [comment]
Yep! Will do.

**Comment by cartermp** [comment]
This one is resolved now!

**Comment by chalin** [comment]
Great, thanks! (Let's close this issue once the changes land in this repo.)

**Comment by cartermp** [comment]
Just now managed to get the site to build off of my fork from a submodule, so hopefully less downstream link breakage moving forward 😄
