### ISSUE TITLE
Rework the top-level registry page.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#103]
The list of items in the registry top-level page isn't great for a couple of reasons:

1: Client-side search is nice but we're pretty limited in what we can easily do through the search templating. You lose the ability to do loops or whatever, for example, like you might in Hugo. Might be a way to tackle this in the JS but I'd need to look at it more, I remember having trouble with it for the original implementation of the registry on opentracing.

2: The card layout doesn't scale well. My druthers is towards something that's more of a list to increase information density.

3: The information architecture is a bit confusing. I think we should generally hew to whatever the main project is going with in terms of order/versioning, so that leaves us with a few basic categories (api, sdk, instrumentation, whatever) and a maturity schema for them (these are in-progress issues). That said, should we consider languages the primary key and roll things up under that, or should we group by type, etc. etc.? 

Mostly using this thread to collect ideas/notes on what we should do, we can figure out a plan to do it later down the line.

**Comment by MikeGoldsmith** [comment]
I think grouping projects by type and project maturity will help a lot with the page. It's not easy to discern the difference between projects right now.

I think it would be useful to either make the language tag more easily recogniseable and/or make the language a requirement in the project title. We have duplicate project names for different languages, which is super confusing.

**Comment by austinlparker** [comment]
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/4140740/81607374-9448b780-93a2-11ea-979b-1b130d9a5363.png">

current WIP of filtering/grouping

**Comment by austinlparker** [comment]
Closed by #183
