### ISSUE TITLE
Java - Manual Instrumentation - add @WithSpan annotation

### ISSUE THREAD

**Issue by algattik** [open-telemetry/opentelemetry.io#1033]
Annotation-driven code generation greatly reduces boilerplate. It's documented at https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/manual-instrumentation.md, and should be added to https://opentelemetry.io/docs/instrumentation/java/manual_instrumentation/

**Comment by cartermp** [comment]
There's a little discussion about it here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4524

+1 on adding it, it should be in the manual instrumentation docs here, and perhaps also linked to from the automatic instrumentation docs.

Happy to review a PR if you got one! I've had this on my backlog for a bit but haven't been able to get to it for a while.
