### ISSUE TITLE
Add OT to OTel migration page

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1037]
Add OpenTracing migration page:

- [x] #1083 
- [x] #1089
- [x] #1090
- [x] #1227

Depends on:

- #1036

(Per 22/01/13 Comms meeting discussions.)

**Comment by chalin** [comment]
@tedsuo - are we ready to publish the OT migration page? If so, I'll remove the `draft` param and get it published. If not, what needs to be done before we publish it? (I'll address #1132 separately, as proposed in https://github.com/open-telemetry/opentelemetry.io/issues/1132#issuecomment-1063377580.)

/cc @austinlparker

**Comment by chalin** [comment]
@tedsuo, this is a follow up ping (since it's been almost two weeks). 

I believe that the [OT migration page] is ready (pending the review and acceptance of #1227). I noticed that [opentelemetry-specification/specification/compatibility/opentracing.md], on which the OT migration page is inspired by, has been published since March 2021 (over a year ago), so I'd like to propose the following:

- If there are no objections between now and the end of the Comms meeting Thursday of this week, then I'll go ahead and publish the OT migration page.

How does that sound @tedsuo? /cc @carlosalberto @yurishkuro @jmacd 

[OT migration page]: https://deploy-preview-1227--opentelemetry.netlify.app/docs/migration/opentracing/
[opentelemetry-specification/specification/compatibility/opentracing.md]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md

**Comment by yurishkuro** [comment]
+1 to publish, I think the value of having a guide in public is much higher than the concerns over possible inaccuracies that can be fixed incrementally. I assume it will be linked under Migration page, which is currently empty.

**Comment by chalin** [comment]
> +1 to publish

@yurishkuro - thanks for your feedback.

> I assume it will be linked under Migration page

Correct.

**Comment by chalin** [comment]
I'm going to be a bit preemptive relative to my [original suggestion](https://github.com/open-telemetry/opentelemetry.io/issues/1037#issuecomment-1075490509) (since we've been working on this page since January), and go with @yurishkuro's +1 because I'd like to submit some followup PRs.

**Comment by tedsuo** [comment]
Thanks for publishing! 👍
