### ISSUE TITLE
.NET Automatic Instrumentation page title

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1042]
_Originally posted in https://github.com/open-telemetry/opentelemetry.io/pull/1015#discussion_r784668409_

@cartermp - I'd like to suggest that we use the same title and linkTitle here as the corresponding page in the Java docs, namely:

```yaml
title: Automatic Instrumentation
linkTitle: Automatic
```

**Comment by cartermp** [comment]
So this one might be a little point of contention. My understanding is it is inaccurate to call it automatic instrumentation because it documents how to initialize instrumentation libraries. That said, I have seen a lot of people also refer to this as automatic instrumentation anyways, so it's a question of technical accuracy vs. familiarity in my mind.

**Comment by chalin** [comment]
What might be missing from that page so warrant it being about automatic instrumentation? Let's discuss this at the next Comms meeting.

**Comment by chalin** [comment]
Was discussed during [2022/01/27 Comms meeting](https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY/edit#heading=h.rpg501xxtq16). There was a general consensus for using "Automatic Instrumentation".

**Comment by cijothomas** [comment]
@cartermp @chalin This change is incorrect. Automatic instrumentation is well defined in the spec repo : https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#automatic-instrumentation

In case of Java (https://opentelemetry.io/docs/instrumentation/java/automatic/) the term is correct, as it is talking about the actual auto instrumentation. For .NET, auto-instrumentation is work in progress https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation#status

**Comment by chalin** [comment]
Hi @cijothomas - thanks for the information and link. I've added an entry to the agenda for discussion at our next Comms/Website meeting this coming Thursday. In case you'd like to join, the meeting info is available in the [minutes doc](https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY).

In the meantime, feel free to respond here @cartermp @tedsuo @austinlparker if you prefer.

**Comment by cijothomas** [comment]
> Hi @cijothomas - thanks for the information and link. I've added an entry to the agenda for discussion at our next Comms/Website meeting this coming Thursday. In case you'd like to join, the meeting info is available in the [minutes doc](https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY).
> 
> In the meantime, feel free to respond here @cartermp @tedsuo @austinlparker if you prefer.

I think this is something to be discussed in Maintainers/Spec meeting. The fundamental question I am asking is "If one uses instrumentation libraries to get automatic spans from the library, is that called "Auto-Instrumentation" ?
