### ISSUE TITLE
Opentelemetry PHP SDK Icon

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry.io#1059]
**Desired feature or idea.**
What would you like to see happen?

We'd love an OpenTelemetry PHP icon similar to the ones that the rest of the SIGs have on the website: 
https://opentelemetry.io/docs/instrumentation/

Thanks in advance!

cc:\ @tidal

**Comment by austinlparker** [comment]
@jkowall Would we be able to get your designer to create logos for the SIGs that weren't covered by the original drop? PHP, Rust, Swift, and C++ are missing iconography. 

We also have a few more top-level concepts on the docs that could use icons.

**Comment by dyladan** [comment]
I see that there is a JS icon, but other than the list on the website is there anywhere else these icons are meant to be used? I saw @trask used it for the java bot user. Are there other suggested applications?

**Comment by austinlparker** [comment]
Yeah - presentations, workshops, internal slide decks, etc.

**Comment by jkowall** [comment]
> @jkowall Would we be able to get your designer to create logos for the SIGs that weren't covered by the original drop? PHP, Rust, Swift, and C++ are missing iconography.
> 
> We also have a few more top-level concepts on the docs that could use icons.

Yes I can get Ella to help us with more icons. Do you have an idea as to what we should base them off? The open source project icons or do you want us to be creative? I am sure Ella has a lot of ideas for us. 

Let me know if this is the list or we need anymore graphics work.

**Comment by austinlparker** [comment]
There's probably some other stuff that we'll want to get later, but it'd be great to get the languages filled out for now. I think the icons should look consistent with the existing Otel ones.

**Comment by jkowall** [comment]
Okay, cool. I will get it going.

**Comment by jkowall** [comment]
You can assign to me or @ella-bz

**Comment by Ella-bz** [comment]
Guys, I have a question. I have the icons for PHP, Rust, Swift, and C++. Do I understand right that you want me to add the sign of SDK like I did for some other languages or it just got lost in files somewhere? 
![image](https://user-images.githubusercontent.com/73476445/152173594-b235930c-08f5-4da9-9135-11f5f7b2db5b.png)

**Comment by bobstrecansky** [comment]
@Ella-bz - would love to see the PHP one when you get a chance!

**Comment by Ella-bz** [comment]
![Net](https://user-images.githubusercontent.com/73476445/152737649-b8698e8f-f4df-4654-8145-88d4062b4286.svg)
![PHP](https://user-images.githubusercontent.com/73476445/152737652-46a4043c-34d7-4ee0-a5eb-aa75439ff505.svg)
![Rust](https://user-images.githubusercontent.com/73476445/152737653-249e13c7-0702-490a-b2b7-c1634302af2c.svg)
![Swift](https://user-images.githubusercontent.com/73476445/152737655-51295e24-5b0e-412c-819c-b310aa207c8c.svg)
These are what you mentioned. Let me know if it's working fine for you, cause it's exported from Figma.

**Comment by bobstrecansky** [comment]
I'm able to see them here.  Thank you!

**Comment by svrnm** [comment]
Looks like this issue & #392 are related.

**Comment by svrnm** [comment]
Will be fixed via #1694
