### ISSUE TITLE
CI: check markdown formatting and common gotchas

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1063]
Now that we starting to have more and more contributors, the project would benefit from standardizing Markdown formatting, and a prettifier and linter could help in this respect.

- I've (@chalin) started experimenting with [Prettier](https://prettier.io), e.g., see:
  - #1290
  - https://github.com/open-telemetry/opentelemetry.io/pulls?q=is%3Apr+prettier+is%3Aclosed
- Note that there's module for formatting Go templates. [Read more](https://discourse.gohugo.io/t/formatter-for-go-templates/38403)

---

- [x] #2286
- [x] #2292
- [x] #2302
- [x] #2309
- [x] #2311
- [x] #2315
- [x] #2316
- [x] #2338
- [x] #2363
- [x] #2368
- [x] #2377
- [x] #2372
- [x] Go docs
  - [x] #2394
  - [x] https://github.com/open-telemetry/opentelemetry-go/pull/3762
  - [x] #2380
- [x] #2389
- [x] #2390
- [x] #2392
- [x] #2393
- [x] #2398
- [x] #2399
- [x] #2408
- [x] #2412
- [x] Community pages: #2414
- [x] Data files and more: #2414

**Comment by chalin** [comment]
@svrnm - I've noticed that lately you've been running a markdown linter/prettifier and submitting PRs. Thanks for those.

It would be good if we could agree on the same tool. I'd like to suggest [Prettier](https://prettier.io). I'm open to discussing this at the next Comms meeting if you have a strong preference for another tool.

You can run Prettier as follows:

```console
$ npx prettier --write path/to/the/markdown/file.md
```

/cc @cartermp @austinlparker

**Comment by austinlparker** [comment]
I'm fine with Prettier

**Comment by svrnm** [comment]
> @svrnm - I've noticed that lately you've been running a markdown linter/prettifier and submitting PRs. Thanks for those.
> 
> It would be good if we could agree on the same tool. I'd like to suggest [Prettier](https://prettier.io). I'm open to discussing this at the next Comms meeting if you have a strong preference for another tool.

I'm fine with prettier, I just had setup markdownlint to check MD files automatically for me when I open them up, but I can work with prettier as well!

**Comment by svrnm** [comment]
@chalin -- if we add a `.prettierrc.json` to the project vscode and other editors should be able to pick it up and use prettier (instead of markdownlint in my case). Sounds like a non-invasive first step, wdyt?

**Comment by chalin** [comment]
> if we add a `.prettierrc.json` to the project vscode and other editors should be able to pick it up and use prettier (instead of markdownlint in my case). Sounds like a non-invasive first step, wdyt?

Sounds good. FYI, there is prettier config already in https://github.com/open-telemetry/opentelemetry.io/blob/25f41e27fc07e62c7e692a7f107e137b49e5eac4/package.json#L52-L54

Is that good enough -- i.e., do tools pick that up? If not, I can factor it out.

Btw, we'll have to be careful with the use of Prettier. It doesn't do a great job with Hugo template syntax. So I'd like to continue experimenting with it before we consider adding it to CI checks. My 2 cents.

**Comment by chalin** [comment]
I'll keep this open until we'll included all or most of the docs.

**Comment by chalin** [comment]
Closed by #2414
