### ISSUE TITLE
Contributing: nvm arguments are different under Windows

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1071]
_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry.io/issues/1066#issuecomment-1019306352_:

> Thanks for the feedback @mic-max. It's unfortunate that the `nvm` command for Windows accepts different arguments. I'll see how we can capture that in the instructions.

References:

- https://github.com/coreybutler/nvm-windows
- https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows

**Comment by rahuldimri** [comment]
@chalin Can we add above URLs in the document section ?

**Comment by chalin** [comment]
Thanks for the ping @rahuldimri. I had something in mind already, see #1603.
