### ISSUE TITLE
.NET Docs: document how to start independent spans

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1073]
Sourced from this discussion: https://cloud-native.slack.com/archives/C01N3BC2W7Q/p1642882241025300

When creating a new activity or span, you need to explicitly ~not~ associate it with a parent, such as calling this API: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource.createactivity?view=net-6.0#system-diagnostics-activitysource-createactivity(system-string-system-diagnostics-activitykind-system-string-system-collections-generic-ienumerable((system-collections-generic-keyvaluepair((system-string-system-object))))-system-collections-generic-ienumerable((system-diagnostics-activitylink))-system-diagnostics-activityidformat)

```csharp
using var act = activitySource.StartActivity("asdf", ActivityKind.Internal, parentId: someId)
```

We should probably document the best way to do this and give it an appropriate scenario description.

**Comment by NinoFloris** [comment]
Relevant https://github.com/dotnet/runtime/issues/65528
