### ISSUE TITLE
Cooperation invitation from Apache APISIX community

### ISSUE THREAD

**Issue by yzeng25** [open-telemetry/opentelemetry.io#1076]
Hi ,

I am Yilin, from the Apache APISIX community. Apache APISIX is a Cloud-native API gateway, and it is the top-level project of the Apache Software Foundation. You can get more details from our GitHub repository[1].

We have developed a plugin for open-telemetry[2] to integrate it with Apache APISIX. I think the plugin is very meaningful for developers and both communities. In addition, it will help open-telemetry and Apache APISIX publicize and let more developers and companies know about us.

We are writing an article for this plugin, are you interested in posting this article on your website's blog[3] or some other places?

Thanks!

[1] https://github.com/apache/apisix
[2] https://github.com/apache/apisix/pull/6119
[3] https://opentelemetry.io/blog/

**Comment by chalin** [comment]
Hi Yilin. You can [submit a proposed blog post](https://github.com/open-telemetry/opentelemetry.io#submitting-a-blog-post), and we'll gladly review your submission.

**Comment by chalin** [comment]
I'll close this issue for now since, I believe, your question was answered. We'll be looking forward to your PR.

**Comment by yzeng25** [comment]
Awesome! Thanks!
