### ISSUE TITLE
represent API and production maturity of the many components of OTel

### ISSUE THREAD

**Issue by bhs** [open-telemetry/opentelemetry.io#109]
Per https://github.com/open-telemetry/community/pull/290, OTel is a "wide" project with many decoupled components that can and should mature on different schedules. The YAML file in that PR is an attempt to define the "schema" for maturity of both APIs and implementations across OTel.

This issue is a place to discuss how we might represent the maturity matrix on opentelemetry.io. As certain languages reach beta (and others do not), it's vitally important that OTel end-users can easily assess the maturity of the project for their environment, ideally without having to visit individual repos and try to read the tea leaves that way.

Here's an intentionally rough wireframe showing how this could look... of course we'd want a designer to clean this up before implementing, my goal here is just to get feedback about the basic approach:

![image](https://user-images.githubusercontent.com/2251553/74112826-8d689980-4b54-11ea-8bc5-e86450386dc3.png)

If you're interested in making a counterproposal, feel free to copy-pasta any of the "slides" (sic) in this deck:

https://docs.google.com/presentation/d/1CyBn74KtRMQCMMKLl4ckIfopsdHUL9owVWIGfvMeQSg/edit#slide=id.g6ecdd256ae_0_5

TIA for any feedback!

**Comment by mtwo** [comment]
It _may_ make more sense to represent non-language-specific projects like the collector and operator as items under individual headings rather than making them part of the main table, but I don't feel strongly about this

**Comment by bhs** [comment]
@mtwo re

>It may make more sense to represent non-language-specific projects like the collector and operator as items under individual headings

Totally... had the same thought. I don't feel strongly about that.

IMO the most confusing thing about my proposal is that we have two concepts of "an API"... both for context/trace/metrics, and then for every component across the board as part of the "maturity level". From a nomenclature standpoint that is not great, even if the distinction can be defined. I don't have a better suggestion, though, or I would have made it. ;)

**Comment by austinlparker** [comment]
Some thoughts -

Externally, it seems like the most important things to me would be an 'overall' gauge of readiness. We should be able to hide the details in a dropdown or collapsible row. We can also do some iconography/badges to represent maturity/doneness. The following illustration is a rough sketch of what a collapsible element would look like, I think.

![image](https://user-images.githubusercontent.com/4140740/74272473-87dd9180-4cc3-11ea-928c-b04a66252951.png)

In addition, we can link from the language to the registry for that language.

**Comment by austinlparker** [comment]
left unspoken in my prior comment is a general question of 'ok, so what's the "overall" doneness and imo it should be the SDK maturity

**Comment by cartermp** [comment]
This is basically accomplished for overall maturity, and each language SDK represents this info in its respective place. The statuses get bumped by maintainers as well, so the system seems like it works! I'll close this out
