### ISSUE TITLE
"View page source" and "Edit this page" button broken

### ISSUE THREAD

**Issue by mic-max** [open-telemetry/opentelemetry.io#1096]
**What happened?**
When visiting the link to "View page source" on the right side it 404s

**What is the name + path of the page where you encountered the issue?**
https://opentelemetry.io/docs/instrumentation/go/
Go | OpenTelemetry

**Additional context**
It works for this page https://opentelemetry.io/docs/instrumentation/net/ so I believe it has to do with the go documentation being a submodule.

---

Edit @chalin. A fix is needed for all language SIGs brought in via a submodule:

- Go
  - [x] https://github.com/open-telemetry/opentelemetry-go/pull/2580
  - [x] #1103
- PHP
  - [x] https://github.com/open-telemetry/opentelemetry-php/pull/578
  - [x] #1119
- [x] Python - #1112
- Ruby
  - [x] https://github.com/open-telemetry/opentelemetry-ruby/pull/1121
  - [x] #1098

**Comment by chalin** [comment]
Strange, I'm sure that was working earlier. I'll have to figure out what changed. Thanks for reporting the issue!
