### ISSUE TITLE
Add .svg logo files to the website for easier access

### ISSUE THREAD

**Issue by mangotron** [open-telemetry/opentelemetry.io#110]
We should make these available for folks who wish to print their own stickers/swag to make it easier to get.

Ideally both RGB and CMYK versions in full color should be added. I can create the files we need, but not sure if the best bet is to put these on a "brand" page of some kind?

**Comment by lucperkins** [comment]
It may be easier to send people here: https://branding.cncf.io/projects/opentelemetry

**Comment by SergeyKanzhelev** [comment]
we have it mentioned here: https://github.com/open-telemetry/community#logos-and-brand-guide should we have it on website as well?

**Comment by mangotron** [comment]
Ah I didn't know the CNCF had a repo for this - maybe just a simple link to that repo from the website then? Website is the _first_ place I would look for this type of asset (speaking as someone who orders a lot of swag, I would not immediately try to find it in Github). 

For some additional context, the question came up in the community gitter channel earlier today - going forward I'm more than happy to point people directly to the link shared above if that's the preferred solution. 

@lucperkins I noticed that this repo doesn't specify whether the files for the full-color version of the logo are in RGB or CMYK color format, but that would probably be helpful information to append to the filename (and ideally, it would be great if we could provide both variations so that folks could choose the appropriate one based what they need). Would it be possible to update that repo accordingly?

**Comment by lucperkins** [comment]
@mangotron I honestly don't know how to discern the difference in images. As for updating that repo, that's not really feasible. The logos are highly standardized across all CNCF projects and any change we make would need to be synced across all of them.

**Comment by austinlparker** [comment]
@mtwo Can we get a link to the CNCF branding page for #126

**Comment by austinlparker** [comment]
I think this would still be useful, especially in regard to #267 - gonna leave it for someone else to pick up, but what would be great is a page (linked from the community page) that collects the visual assets for the project (icon library, slide templates, logos, etc.) and makes them easily accessible.

**Comment by harshita19244** [comment]
I would like to work on it, could you assign me the issue and specify the exact requirement?

**Comment by harshita19244** [comment]
@austinlparker I am developing a visual aid page linked to the community page. I have taken the first step and added a simple icon library. Let me know if I am on the right track with this implementation. 
![Screenshot (13)](https://user-images.githubusercontent.com/60603854/113497176-02e4b580-951f-11eb-8c28-f8058775e1cf.png)

**Comment by austinlparker** [comment]
I think we just need a link from the community page to the otel icons and to the cncf logo page for otel.

**Comment by harshita19244** [comment]
Cool I will do that
