### ISSUE TITLE
Migrate Python docs to this repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1109]
This is the Python part of

- #833

The decision to migrate the Python (non-API) docs was recorded in

- https://github.com/open-telemetry/opentelemetry-python/issues/2172#issuecomment-1029324910.

---

- [x] Update Python submodule - #1110
- [x] Handle `website_docs` (https://github.com/open-telemetry/opentelemetry-python/tree/main/website_docs) pages:
  - [x] Move `website_docs` pages into this repo
    - [x] #1111
    - [x] #1112
    - [x] Create and test a Hugo-shortcode equivalent of RTD `literalinclude ` - #1113
  - [x] Remove `website_docs` from the Python repo - https://github.com/open-telemetry/opentelemetry-python/pull/2452
- [x] Migrate `*.rst` pages:
  - [x] Create markdown versions (in this repo) of the Python `*.rst` doc pages
    - [x] #1116
    - [x] #1118
  - [x] Remove the `*.rst` pages from the Python repo 
    - [x] https://github.com/open-telemetry/opentelemetry-python/pull/2453, 
    the counterpart to #1116
    - [x] https://github.com/open-telemetry/opentelemetry-python/pull/2498
    the counterpart to #1118 
    - [x] [TBC, ... shim section pages]
  - [x] Drop the `scripts/generate_website_docs.sh` script -- for context, see https://github.com/open-telemetry/opentelemetry-python/pull/2452#discussion_r801975284

**Comment by chalin** [comment]
@cartermp - are there specific pages you wanted to see migrated? If so, after https://github.com/open-telemetry/opentelemetry-python/pull/2453 lands (assuming it will), could you tell which pages you specifically require to be migrated? Otherwise, I'll just continue to migrate what seems most reasonable to move over. Thanks!

**Comment by cartermp** [comment]
Everything non-API docs, so the following will be off-limits to move:

* Core Packages (API and SDK)
* Exporters
* Shims

There are some module-level docs in each of those that _might_ be useful to bring over, but we can do that in a phase 2 as needed.

**Comment by svrnm** [comment]
I argue this is complete? cc @open-telemetry/python-approvers

**Comment by cartermp** [comment]
I would say the same
