### ISSUE TITLE
Ensure the consistency of signal names

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry.io#1121]
Currently Trace/Tracing/Traces, Metrics, and Logging/Logs are used in various places to name the OpenTelemetry signals. It would be great to ensure these are named consistently at least in the status section for each language implementation.

Edit (@chalin): for context, see https://github.com/open-telemetry/opentelemetry.io/pull/1116#discussion_r804878218.

**Comment by svrnm** [comment]
While I agree with this, I don't see a way to get this fix besides going through all pages and double check if those terms are used properly (if I crawl for "Tracing" I get matches for "OpenTracing" and there is some places where "Tracing" might be the right term, same for Logs & Logging)

Looks like something we have to fix gradually, so I tag this with "help wanted" and "good first issue" hoping for some help :-)
