### ISSUE TITLE
Getting Started linux instructions

### ISSUE THREAD

**Issue by dimitrisfinas** [open-telemetry/opentelemetry.io#1126]
I have downloaded and installed on debian version 0.39.0 of otel collector package, and the name of the service started is "otelcol" and not "otel-collector" as put in Linux Packaging documentation

**Comment by chalin** [comment]
@dimitrisfinas - which documentation page(s) were you using, and that illustrate this issue?

**Comment by dimitrisfinas** [comment]
> @dimitrisfinas - which documentation page(s) were you using, and that illustrate this issue?
I am referring to this page:
https://opentelemetry.io/docs/collector/getting-started/#linux-packaging

**Comment by jpkrohling** [comment]
That's true, it's a reflection of our recent change to using the builder and allowing multiple distribution instances to be available at the same time:

https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/otelcol.service
https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/otelcol-contrib.service

**Comment by chalin** [comment]
So, did #1134 fully address this issue? /cc @rogercoll

**Comment by dimitrisfinas** [comment]
Thanks

**Comment by rogercoll** [comment]
@chalin Yes, the issue can be closed.
