### ISSUE TITLE
Consider adding a section page for `/schemas`

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1144]
Folks are trying to visit the section root and getting 404. It would seem like a reasonable use case to want to list the contents of that section.

Thoughts @tigrannajaryan @carlosalberto?

**Comment by tigrannajaryan** [comment]
I would prefer not to. We may define a formal machine-readable format for `/schemas` page in the future and I want to make sure the URL remains available and is not populated by some human-readable page.

**Comment by chalin** [comment]
Closing, based on @tigrannajaryan's feedback
