### ISSUE TITLE
Migrate PHP website_docs back to this repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1154]
- PHP part of #833
- [x] Update PHP submodule - #1155, somewhat of a formality since `website_docs` hasn't been updated since our last update of the submodule.
- [x] Make PHP pages local, and remove repo-link front-matter override - #1156
- [x] Drop [website_docs](https://github.com/open-telemetry/opentelemetry-php/tree/15785689ab681a707b299512179db2c224a270c2/website_docs) - https://github.com/open-telemetry/opentelemetry-php/pull/585

Related:

- https://github.com/open-telemetry/opentelemetry-php/issues/423#issuecomment-1042389408
- https://github.com/open-telemetry/opentelemetry-php/issues/405

/cc @bobstrecansky @cartermp @austinlparker

**Comment by cartermp** [comment]
@chalin this can be closed no?

**Comment by chalin** [comment]
If I look at #833, I see that there's a related task left to complete (which maybe should be mentioned here?):

> <img width="500" alt="image" src="https://user-images.githubusercontent.com/4140793/198909163-65d2fcaa-75bf-4f8a-855b-2aaa71219ad5.png">

That might be why this is still open. But the web docs folder has been moved, so I agree with you, let's close this.
