### ISSUE TITLE
Migrate integration pages from PHP repo docs folder?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1157]
@bobstrecansky @cartermp: might it also make sense to migrate the integration pages under [PHP repo `docs`](https://github.com/open-telemetry/opentelemetry-php/tree/main/docs) here too?

- https://github.com/open-telemetry/opentelemetry-php/blob/main/docs/laravel-integration.md
- https://github.com/open-telemetry/opentelemetry-php/blob/main/docs/symfony-integration.md

**Comment by chalin** [comment]
@cartermp - if you agree, how do you see these pages fit into the PHP section organization?

**Comment by cartermp** [comment]
I think at first, it would be fine to have these be individual pages. In the future it might be better to find a way to consolidate common content and make it more uniform w.r.t. other languages.

**Comment by theletterf** [comment]
@open-telemetry/php-maintainers Still up for migrating these?
