### ISSUE TITLE
C# syntax highlighting is wrong of identifiers starting with an underscore

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1159]
There's been a similar problem before, see:

- https://github.com/alecthomas/chroma/issues/507
- https://github.com/gohugoio/hugo/issues/8532

Visit https://opentelemetry.io/docs/instrumentation/net/netframework/, notice the `_` in `_tracerProvider` is highlighted differently:

> <img width="400" src="https://user-images.githubusercontent.com/4140793/154690301-c8bcc650-f662-4624-95ae-9ffb8238bcf6.png">

The entire identifier should be highlighted the same, like this:

```csharp
 private readonly TracerProvider _tracerProvider;
```

As of the time of writing this, we're using Hugo 0.9.2, which uses `v0.9.4`, the version of Chroma specified here: https://github.com/gohugoio/hugo/blob/cdf6a0d6228eef4df2a82a1483f016c11f4a6019/go.mod#L7

Maybe this has been fixed in the more recent 0.x version or Chroma v2? Not sure if/when Hugo will jump to v2.

To do:

- [x] Test if latest version of Chroma still has the issue
- [x] File an issue: https://github.com/alecthomas/chroma/issues/613
- [x] Propose a fix: https://github.com/alecthomas/chroma/pull/614
- [ ] Wait for the next Chroma release
- [ ] Open an issue over Hugo to update Chroma?
- [ ] Upgrade Hugo

😅

**Comment by cartermp** [comment]
So I think this can be closed...insofar as the presence of the underscore doesn't seem to impact colorization anymore. The colorization isn't particularly knowledgeable about C# constructs as a whole, but uhhh, it's at least consistently dissatisfying.

**Comment by chalin** [comment]
Yes, all done.
