### ISSUE TITLE
Link to Java examples is incorrect

### ISSUE THREAD

**Issue by kevinearls** [open-telemetry/opentelemetry.io#1160]
**What needs to be changed?**
The link to the Java examples is incorrect.  It currently points to https://github.com/open-telemetry/opentelemetry-java/tree/main/examples but should be https://github.com/open-telemetry/opentelemetry-java-docs

**What is the name + path of the page that needs changed?**
On https://opentelemetry.io/docs/instrumentation/java/, i.e docs/instrumentation/java in the **API reference and examples** section

**Comment by chalin** [comment]
Closed by #1161
