### ISSUE TITLE
Outdated documentation for local core collector run

### ISSUE THREAD

**Issue by hardik-epifi** [open-telemetry/opentelemetry.io#1180]
**What needs to be changed?**
Update documentation/docker command for otel core collector local run

**What is the name + path of the page that needs changed?**
https://opentelemetry.io/docs/collector/getting-started/#docker

**Additional context**
Command given to run the local otel core collector is wrong, their is no go file inside anymore.

```console
$ git clone git@github.com:open-telemetry/opentelemetry-collector.git; \
    cd opentelemetry-collector/examples; \
    go build main.go; ./main & pid1="$!";
    docker run --rm -p 13133:13133 -p 14250:14250 -p 14268:14268 \
      -p 55678-55679:55678-55679 -p 4317:4317 -p 8888:8888 -p 9411:9411 \
      -v "${PWD}/local/otel-config.yaml":/otel-local-config.yaml \
      --name otelcol otel/opentelemetry-collector \
      --config otel-local-config.yaml; \
    kill $pid1; docker stop otelcol
```

**Comment by jpkrohling** [comment]
I think this second example should be removed from the getting started. To someone getting started, it's not entirely clear what's going on there.

**Comment by pmm-sumo** [comment]
> I think this second example should be removed from the getting started. To someone getting started, it's not entirely clear what's going on there.

I agree it might be too complex for "Getting started". Also, the port numbers seem outdated
