### ISSUE TITLE
Distributions - creating a distribution - language specific best practices.

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1200]
**Desired feature or idea.**

When going to the [distributions page](https://opentelemetry.io/docs/concepts/distributions/) checking for some guidance on "creating my own distribution" I can only find details for the OpenTelemetry collector. 

It would be great to also have some details for the language specific SDKs/auto-instrumentations:

* Java provides an [extension mechanism](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md). From my understanding the right approach for creating a distribution of that is building extension
* Python provides a [opentelemetry-distro package](https://opentelemetry.io/docs/instrumentation/python/distro/). I assume that building/extending this package is much more efficient than cobbling everything together yourself
* JavaScript provides the [SDK for Node.js](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-sdk-node). Again, I assume it could be a best practice to build on top of it. 
* ...

While I don't want to prescribe vendors (and others) how to build their own distribution of opentelemetry, it would be great to provide some starting points & guidance. I see the following advantages:

* Having a "common structure" makes it easier for distributions to make use of existing installation/injection mechanisms like the K8s operator, (https://github.com/open-telemetry/opentelemetry-operator/issues/752 is one of the reasons why I opened this issue)
* Building on top of existing "base distributions" is also valuable for the OTel community: vendors might reconsider building their own stuff and prefer adding features to the existing packages and therefor help the community to make their implementations better.

**Next Steps**

I first of all wanted to check if this is a good/bad idea, and if it is reasonable, I think the next step would be to work with the individual language-specific SIGs to get an idea from them what they think a good practice for their language would look like. Maybe a first step is just linking from that page to existing work as mentioned before (Java Extension Mechanism, Python Base Distro, SDK for Node.js,...)

**Comment by austinlparker** [comment]
I like the idea, but I'm not sure if 'distribution' is really the right concept we should be capturing. Maybe each language should have an 'extensibility' section that we can file docs like this under? Or, to reverse it, there should be an 'Extensibility' topic that has items like, 'Building a custom OTel Collector', 'Building a custom Java Agent', 'Extending the Node.JS SDK', etc. etc.

**Comment by svrnm** [comment]
> I like the idea, but I'm not sure if 'distribution' is really the right concept we should be capturing.

Not sure if I understand: do you mean that we should replace the existing page on "Distributions" with "Extensibility", or do you think that those are two separate (but related topics)? 

> Maybe each language should have an 'extensibility' section that we can file docs like this under? Or, to reverse it, there should be an 'Extensibility' topic that has items like, 'Building a custom OTel Collector', 'Building a custom Java Agent', 'Extending the Node.JS SDK', etc. etc.

I see advantages in both. Maybe have it per language and some common place like "Distrubtions" (or rename it to "Extensibility & Distributions"?
