### ISSUE TITLE
Migrate Java Agent doc pages to this repo, starting with Agent config

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1229]
@trask @jack-berg et al., as part of the work on

- https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4523

What do you think about migrating selected Java-Agent pages from [opentelemetry-java-instrumentation/docs] to this repo under [Docs > Instrumentation > Java > Automatic]. Good candidate page to start off with might be:

- [x] [docs/agent-config.md] 
  - [x] #1233
  - [x] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5683
- [x] [docs/suppressing-instrumentation.md]
  - [x] #1237
  - [x] Factor out part to be left in code repo: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5693
  - [x] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5694
  - [x] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5712
- [x] [docs/config/common.md]
  - [x] #1246
  - [x] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5707
  - Followup: #1247
- [x] https://github.com/open-telemetry/opentelemetry.io/issues/1247
- [ ] ...

/cc @austinlparker @cartermp @svrnm 

[Docs > Instrumentation > Java > Automatic]: https://opentelemetry.io/docs/instrumentation/java/automatic/
[opentelemetry-java-instrumentation/docs]: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/docs
[docs/agent-config.md]: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md
[docs/suppressing-instrumentation.md]: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/3ab1b8516feb5a0065d5b1e0d6a242049f2c7aea/docs/suppressing-instrumentation.md
[docs/config/common.md]: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/4ef6d165a9de883b2cebd727d7794c9cc530be97/docs/config/common.md

**Comment by trask** [comment]
I support this

cc @open-telemetry/java-instrumentation-approvers

**Comment by jack-berg** [comment]
@chalin Did you have any heuristics / rules of thumb in mind for how to decide whether content is better suited for the docs website or the source repository?

**Comment by chalin** [comment]
@jack-berg - our _general_ objective is to migrate all non-API docs -- the tracking issue is:

- #833

**Comment by chalin** [comment]
@trask, I'm looking at migrating [suppressing-instrumentation.md] next (possibly embedding it in the Agent config page).

I'm thinking that it might make sense to use Hugo to **generate the "Suppressing specific agent instrumentation" table from data** -- possibly using the command you wrote here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/14372adb6872624b89022e2531073752ff095ce8/buildscripts/check-suppressing-instrumentation-docs.sh#L18-L21. WDYT? How do you propose deriving the **Library/Framework** name?

I haven't fully thought this out, but wanted to gather at least some initial feedback about possible data-driven approach to generating the table. Thanks.

[suppressing-instrumentation.md]: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/suppressing-instrumentation.md

**Comment by chalin** [comment]
Or another thought would be to use a manually-curated data file to generate the table, and a separate script (like the one you wrote) to simply cross-check if any new matching `*Module.java` files are missing. I'll let this simmer and try out a few things tomorrow.

**Comment by cartermp** [comment]
@chalin it looks like every specific sub-task is complete. Should this issue remain open?

**Comment by trask** [comment]
@chalin I think this can be closed

**Comment by chalin** [comment]
@trask - are you saying that all of the files left in https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/docs should not be moved here?

**Comment by zeitlinger** [comment]
> @trask - are you saying that all of the files left in https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/docs should not be moved here?

yes, that is internal
