### ISSUE TITLE
Collector 'Getting Started' shell commands do not work in Powershell

### ISSUE THREAD

**Issue by geff10** [open-telemetry/opentelemetry.io#1252]
This line does not work for me in Powershell:

```command
./bin/otelcorecol_* --config ./examples/local/otel-config.yaml

Error message: "./bin/otelcorecol_* : The term './bin/otelcorecol_*' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
 again.
At line:1 char:1
+ ./bin/otelcorecol_* --config ./examples/local/otel-config.yaml
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./bin/otelcorecol_*:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"
```

**Comment by austinlparker** [comment]
Thanks -- there is a note under those instructions that say the commands only work in bash.

**Comment by geff10** [comment]
Actually, it did not work neither in bash shell, but I realized that it was partly about the lack of `make` in Windows, so I downloaded the Windows version of it. However, it still does not work neither with git bash: "makefile:153: *** multiple target patterns.  Stop.", neither with PS or cmd. Powershell tells bit more: "FIND: Parameter format not correct
Access denied -" - which I assume means that there is no FIND on Windows, which is not a surprise, but this part of documentation should be about Windows. Am I missing something?

**Comment by austinlparker** [comment]
That part of the documentation isn't about running the collector on Windows specifically, it's supposed to be general instructions for running it locally.

**Comment by rahuldimri** [comment]
@geff10 @austinlparker can I work on this, updating the note section ?

**Comment by austinlparker** [comment]
Go for it

**Comment by rahuldimri** [comment]
@austinlparker thank you very much !!. Could you please assign this to me.

**Comment by rahuldimri** [comment]
@austinlparker do you want me to update the note section or we need to define the steps for the windows users?

**Comment by svrnm** [comment]
@rahuldimri are you still up for this?
