### ISSUE TITLE
Add link to LF trademark usage

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1269]
Context:

- https://clomonitor.io/projects/cncf/open-telemetry#community_legal:
  > <img width="500" alt="image" src="https://user-images.githubusercontent.com/4140793/161403739-9673522b-ede5-4314-830b-30251137b1bd.png">
- [Checks reference documentation](https://github.com/cncf/clomonitor/blob/main/docs/checks.md#legal)

I'd like to repeat what I did for [gRPC], and add [linuxfoundation.org/trademark-usage](https://www.linuxfoundation.org/trademark-usage) to the footer:

> <img width="350" alt="image" src="https://user-images.githubusercontent.com/4140793/161403782-c9221b8e-9ee4-47b3-9a7d-191a7e224a38.png">

This might require upstreaming the gRPC footer changes.

/cc @caniszczyk

**Comment by austinlparker** [comment]
Would it also make sense to add the marketing guidelines (https://github.com/open-telemetry/community/blob/main/marketing-guidelines.md) to the footer as well? They're kinda buried right now.

**Comment by austinlparker** [comment]
🙃 the limitations of iconography I suppose

**Comment by svrnm** [comment]
this seems to be still relevant?

**Comment by chalin** [comment]
Legal status is now green in CLOmonitor, https://clomonitor.io/projects/cncf/open-telemetry#community_legal, closing.
