### ISSUE TITLE
JS example: fix "do work" loop

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1284]
_Originally posted by @blumamir in https://github.com/open-telemetry/opentelemetry.io/pull/1230#discussion_r838522784_:

> not related to this PR which fixes typos, but the line `Math.floor(Math.random() * 40000000)` will be re-evaluated again and again for each iteration which is probably not what was intended

Notes:

- There are multiple instances of that code in the page.
- Also see https://github.com/search?q=org%3Aopen-telemetry+%22Math.random%22&type=code

**Comment by chalin** [comment]
Note that there are multiple instances of that code in the page.

**Comment by cartermp** [comment]
I feel like we can just close this one. It's super low priority and just illustrative.
