### ISSUE TITLE
Host Mission page on website from community repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1289]
- Current location of the page: https://github.com/open-telemetry/community/blob/main/mission-vision-values.md
- Subtask of #833

Subtasks:
- [x] Add page to this repo
- ~Remove page from https://github.com/open-telemetry/community~
- [x] #1809
- [x] https://github.com/open-telemetry/community/pull/1369
- [x] https://github.com/open-telemetry/community/pull/1370
- [ ] #2381

/cc @austinlparker @bhs

**Comment by chalin** [comment]
@svrnm Thanks for migrating the mission page. Might you be willing to remove the source page from the community repo (see the subtask list above). If you'd prefer that I do it, let me know.

**Comment by svrnm** [comment]
fixed? https://github.com/open-telemetry/community/pull/1056 @chalin

**Comment by svrnm** [comment]
deleted my last comment, it's not fixed per the last comment on the community ticket https://github.com/open-telemetry/community/pull/1056:

> Discussed in the GC call. GC recommendation is to use the same publishing mechanism for Community repo that we already use for including Specification into the website pages.
