### ISSUE TITLE
On /status page, need to update expectation statement on header

### ISSUE THREAD

**Issue by horovits** [open-telemetry/opentelemetry.io#1291]
**What needs to be changed?**
On opentelemetry.io/status/ page, the header contains a forward looking statement:
"We expect metrics to reach the same status in the second half of 2021 and are targeting logs in 2022."
as Metrics hasn't reached that status in 2021 and we're in Q2 '22, we'd better update the expectation statement. 

**What is the name + path of the page that needs changed?**
https://opentelemetry.io/status/
https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/status.md

**Additional context**
to align with the achieved maturity status

**Comment by cartermp** [comment]
This can be closed now I think, since the page doesn't have this kind of statement anymore.
