### ISSUE TITLE
Getting started example code does not compile with NodeJS/Typescript 

### ISSUE THREAD

**Issue by pabagan** [open-telemetry/opentelemetry.io#1302]
Hi! 
I am beginner with Open Telemetry and was trying to get the code at [Getting Started](https://opentelemetry.io/docs/instrumentation/js/getting-started/nodejs/) to run in a typescript application but getting the following error: 
<img width="852" alt="image" src="https://user-images.githubusercontent.com/1871204/163810599-de579558-dd3b-4fad-8744-ab20bf477ddb.png">

```sh
os: maOS Monterey 12.3.1
node: 16.13.2

# Project dependencies
@opentelemetry/api: 1.0.4,
@opentelemetry/auto-instrumentations-node: 0.28.0
@opentelemetry/sdk-node: 0.27.0
typescript: 4.6.3
express: 4.17.2
```

It would be great if the code at the example page would work for Typescript :) 

On a side note. The code for tracing worked great: 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/1871204/163811788-8e84f358-3da1-4a9f-87c4-05562e9a5f9f.png">

I am getting excited with Open Telemetry. Thanks for it :)

**Comment by cartermp** [comment]
Yeah, probably expected, since metrics are still experimental in the SDK.

I wonder if the example could be simplified a bit to just map the path to the counter with this notion of "binding", which isn't a part of the API anymore as far as I can tell.

**Comment by svrnm** [comment]
Thanks for calling this out, tbh, I never tested that code with typescript.

Actually this reminds me that I wanted to take the code out from the text and make it testable (like python binds the source code from somewhere else)

**Comment by cartermp** [comment]
THIS WAS THE ONE I knew existed but had forgotten about.

This will be resolved by https://github.com/open-telemetry/opentelemetry.io/pull/1534

https://github.com/open-telemetry/opentelemetry.io/issues/1400 is also a duplicate, but since it's more specific to the issue I'll keep that one open.
