### ISSUE TITLE
Document Node.js context propagation

### ISSUE THREAD

**Issue by paulius-valiunas** [open-telemetry/opentelemetry.io#1315]
**What needs to be changed?**
Node.js (or just Javascript) documentation should have at least a short introduction to Context Propagation and how it works in the JS API. Practical usage examples would be nice too.

**What is the name + path of the page that needs changed?**
`instrumentation/js/getting-started/nodejs/`

**Additional context**
Examples:
https://opentelemetry.io/docs/instrumentation/java/manual/#context-propagation
https://opentelemetry.io/docs/instrumentation/ruby/context-propagation/
https://opentelemetry.io/docs/instrumentation/go/manual/#propagators-and-context

**Comment by cartermp** [comment]
What sort of content would you expect to be here, showing how to use B3 propagation instead of W3C?

I mainly ask because in Go, context propagation isn't on by default and so it needs to be explicitly called out.

**Comment by paulius-valiunas** [comment]
> What sort of content would you expect to be here, showing how to use B3 propagation instead of W3C?
> 
> I mainly ask because in Go, context propagation isn't on by default and so it needs to be explicitly called out.

well, neither W3C nor B3 propagation is even mentioned there, so documenting either of them would be nice. I've been told the Express.js auto-instrumentation includes some form of context propagation, but even that wasn't mentioned in the Node.js documentation. I'd say anything that would put someone who doesn't use auto-instrumentation (or if auto-instrumentation is not available for the packages they're using) on the right track would be helpful.

**Comment by cartermp** [comment]
In this case of JS (and most languages), context propagation is one by default ([source](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts#L55-L62)) and it's set to W3C because that's the default format chosen for OpenTelemetry. You may be able to find a way to trace without context propagation, but I think you'd have to really go out of your way to do that.

Would it be helpful to just explicitly call this out?

**Comment by paulius-valiunas** [comment]
wait, so what does this default do, how do I use it? I mean, someone has to take the trace id from HTTP headers or wherever else it's being sent through and feed it to a propagator.

**Comment by cartermp** [comment]
When you instrument either via exclusively automatic instrumentation, or you manually use one of `BasicTracerProvider`/`NodeTracerProvider`/`WebTracerProvider` then context propagation will be on by default (Node and Web both subclass `BasicTracerProvider`). These are the ways we document how to instrument, and what is used in all examples.

Technically, you could write your own TracerProvider that doesn't have context propagation on. And then yes, you would have to be concerned with pulling a trace ID out of a header somewhere. There are also some services that don't work with W3C or B3 context propagation yet (such as some AWS services) and might require you to manually pull IDs out of other headers. These aren't documented here, though.

I think it's valuable to have a section in the JS docs that tells you how to configure context propagation to B3, and reiterate that it's already on for W3C. Do you think there should also be more?

**Comment by paulius-valiunas** [comment]
correct me if I'm wrong, but if I don't use http auto instrumentation, there's nothing that will pull the trace id out of (or insert into) my http headers, even if I use W3C propagation in my network requests, because the http library is not instrumented by default.

**Comment by paulius-valiunas** [comment]
In other words, context propagation will only work if something pulls the trace id (and other fields) out of http requests, and that is only possible by instrumenting Node.js http API, and as far as I know `@opentelemetry/sdk-trace-base` doesn't do that, and neither does `@opentelemetry/sdk-trace-node`. Only `@opentelemetry/instrumentation-http` can do that, which is optional and I might opt not to use it.

If I'm making a wrong assumption here and one of the trace packages actually intercepts network requests and parses their headers, I think that's the first thing that should be documented.

**Comment by cartermp** [comment]
Gotcha, sorry, I think I misunderstood your questions here.

Yes, if you don't have instrumentation for calls across service boundaries, then context cannot propagate across those boundaries automatically. Your only other option to propagate context is to pluck things out of headers yourself.

What the JS SDK does, though, is ensure that between these network calls context is still propagated so that instrumentation libraries and any manual plucking-out of these IDs works.

Are you looking for an example of manually plucking things out of headers, for a scenario where you're using the JS SDK but intentionally not using instrumentation libraries?

**Comment by paulius-valiunas** [comment]
@cartermp yes, this does sound more like what I'm looking for. Either intentionally not using instrumentation libraries, or when such libraries don't exist for my use case, such as an in-house network protocol using plain (or web-) sockets, or IPC...

To be even more specific, I think extending the `TextMapPropagator` class is what I'm looking for, but I can't figure out where it should be plugged in.

Now I'm a little confused because you mentioned the W3C standard in your previous comment. I don't quite understand how that applies here because this default "propagation" never crosses process boundaries so it doesn't need to be serialized.

**Comment by cartermp** [comment]
Another example where this could be helful: https://twitter.com/RichSeviora/status/1585849264286334976

**Comment by cartermp** [comment]
Closing this as it's more or less addressed in https://github.com/open-telemetry/opentelemetry.io/pull/1951 and can be improved, but it _Exists_ now.
