### ISSUE TITLE
OT appears ahead of OTel in searches

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1316]
@austinlparker posted on Slack, https://cloud-native.slack.com/archives/C02UN96HZH6/p1650296911544559:

> https://twitter.com/bwplotka/status/1515715889299136517
> [@bwplotka](https://twitter.com/@bwplotka)
It's crazy and confusing to NOT see [@opentelemetry](https://twitter.com/opentelemetry) on the first page of [@Google](https://twitter.com/Google) search for "tracing Go" or Go client for tracing...:crying_cat_face:
[@opentracing](https://twitter.com/opentracing) docs pop up and are nice (deprecated though).
I don't what happened, but this needs some work, especially for new in the ecosystem:see_no_evil:

- [x] https://github.com/opentracing/opentracing.io/pull/462

**Comment by chalin** [comment]
I'll track the GA/GSC for a little while before closing this.

**Comment by austinlparker** [comment]
Added you to the OpenTracing GA, check email.

**Comment by chalin** [comment]
Thanks @austinlparker. Could you grant me edit access so that I can also view the Google Search Console results?

**Comment by chalin** [comment]
OT no longer appears before OTel pages -- though there are other pages before any OTel website pages show up. I'm going to close this now that the original concern has been addressed.
