### ISSUE TITLE
No Mention of the Docker Image Distribution of the Collector Anywhere

### ISSUE THREAD

**Issue by Grunet** [open-telemetry/opentelemetry.io#1327]
**What needs to be changed?**
There is no way to figure out that a dockerized distribution of the collector exists from the site's documentation.

**What is the name + path of the page that needs changed?**
These 3 pages don't mention it

https://opentelemetry.io/docs/collector/getting-started/
https://opentelemetry.io/docs/collector/configuration/
https://opentelemetry.io/docs/collector/distributions/

**Additional context**
I eventually saw there was a "most recent change" note at the bottom of the Getting Started page that pointed to [this commit](https://github.com/open-telemetry/opentelemetry.io/commit/a32822c8300640f7e750344cc09530db017e24b4) and [this issue](https://github.com/open-telemetry/opentelemetry.io/issues/1180) about removing mentions of it.

This plus subsequent digging through the collector repo, and then eventually finding its releaser repo, and then eventually finding where an image was built and published [led me to the DockerHub repository](https://hub.docker.com/r/otel/opentelemetry-collector)

But overall that was kind of hard to figure out, especially when I only had a hunch that a dockerized version existed somewhere and wasn't actually sure it existed at the start.

(Fwiw I went looking for a dockerized version after failing to get the Getting Started steps for Linux to work for me quickly)

**Comment by cartermp** [comment]
I think something like this (in a pr branch for something else) is required: https://deploy-preview-1326--opentelemetry.netlify.app/docs/instrumentation/net/getting-started/#configure-and-run-a-local-collector

Would be curious what others think?

**Comment by svrnm** [comment]
I added it here  https://github.com/open-telemetry/opentelemetry.io/pull/1332 (not pointing to dockerhub but to ghcr.io, can update that)

**Comment by Grunet** [comment]
Yeah personally speaking I like both of those approaches. As long as it's at a minimum mentioned somehow somewhere among the other options.

Also somewhat related but I got bitten by leaving off the version tag (as DockerHub suggested) when trying to get things working (I couldn't get the volume mount to work with that image) which I noticed @svrnm you call out explicitly, which I liked.

**Comment by svrnm** [comment]
@Grunet: how about now: https://opentelemetry.io/docs/collector/getting-started/#docker?

**Comment by Grunet** [comment]
Yeah that seems like a solid starting point to me. 

I'd maybe like to see other things (like setting up with Docker compose and how to override the config) but that could probably live elsewhere outside of this Getting Started page.

I think this alone gets at my original root concern well.

**Comment by cartermp** [comment]
I'll close this and we can use https://github.com/open-telemetry/opentelemetry.io/issues/1395 to track docker-compose
