### ISSUE TITLE
docs-approvers membership

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1365]
@cartermp - we'd like to add you to the [docs-approvers](https://github.com/orgs/open-telemetry/teams/docs-approvers) team, but for that you need to be part of the [open-telemetry](https://github.com/open-telemetry) organization. Can you put in a request for that and let @austinlparker and me know when that is done?

**Comment by cartermp** [comment]
Registered here: https://github.com/open-telemetry/community/issues/1057

**Comment by arminru** [comment]
I invited @cartermp and added him to the team.

**Comment by chalin** [comment]
Thanks @arminru! (I'm not seeing @cartermp in [the team list](https://github.com/orgs/open-telemetry/teams/docs-approvers/members), but I'll assume that it's because he hasn't accepted the invite yet.)
