### ISSUE TITLE
what is the difference between state and status?

### ISSUE THREAD

**Issue by vincentff7** [open-telemetry/opentelemetry.io#1366]
when naming metric name and attribute name,
what is the difference between **state** and **status**?

in https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/system-metrics/: 
system.cpu.time, **state**=idle, user, system, interrupt, etc.
system.memory.usage, **state**=used, free, cached, etc.
system.processes.count, **status**=running, sleeping, etc.

**Comment by svrnm** [comment]
This content is copied from the spec directly, would you mind opening the same issue at https://github.com/open-telemetry/opentelemetry-specification

**Comment by vincentff7** [comment]
> This content is copied from the spec directly, would you mind opening the same issue at https://github.com/open-telemetry/opentelemetry-specification

done, thx!
