### ISSUE TITLE
Update status of Logs OTLP and Logs Data model to stable

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry.io#1373]
- OTLP Logs are now Stable: https://github.com/open-telemetry/opentelemetry-proto#maturity-level
- Log Data model is also Stable: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md

---
Edit(@chalin):

- [x] Update Logs note "The data model is experimental and released as part of the OTLP protocol" - #1379
- [x] Wait for https://github.com/open-telemetry/opentelemetry-specification/pull/2565
- [x] After the next official release of the spec (>v1.11.0), update this repo's spec git-submodule to a commit including the fix of https://github.com/open-telemetry/opentelemetry-specification/pull/2565
- Optional items: see below --> moved to #1492

Also, while we're making updates to the **Status** page:

- Add link into the spec's baggage section from the Baggage header (as is done for Metrics) once the spec is updated (since the spec's Baggage section has a landing page now). --> see #1492
- Make similar updates to the other sections (e.g., Logging) if those spec sections have landing pages too. --> see #1492

**Comment by chalin** [comment]
1. The OTLP-logs status is automatically extracted from the spec (currently at v1.11.0). But even in the spec `@HEAD`, the status is still showing as `beta`, see https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/protocol/otlp.md#L57:

    > * Logs: **Beta**

    So an issue would need to be open over the spec. Would you like for me to create one?

2. Where does the "log data model" status show up in the status page?

**Comment by tigrannajaryan** [comment]
> 1. So an issue would need to be open over the spec. Would you like for me to create one?

Created: https://github.com/open-telemetry/opentelemetry-specification/pull/2565

**Comment by tigrannajaryan** [comment]
> 2\. Where does the "log data model" status show up in the status page?

See "The data model is experimental and released as part of the OTLP protocol.":

![image](https://user-images.githubusercontent.com/4194920/169578563-8829a4ab-89bd-4505-97bd-c2c6f463aff8.png)

**Comment by chalin** [comment]
@tigrannajaryan - how about if I update that bullet to read the following instead:

> - The **data model** is released as part of the OTLP protocol

**Comment by tigrannajaryan** [comment]
@chalin sounds good, thanks.

**Comment by chalin** [comment]
Closed by #1464
Optional items moved to #1492
