### ISSUE TITLE
Status page title refers to old banner announcement text

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1377]
PR #1376 updated the banner on the homepage from:

- The OpenTelemetry tracing specification is now 1.0!

to

- OpenTelemetry metrics release candidates are now available!

The heading of the [Status page](https://opentelemetry.io/status/) reads:

- Status: OpenTelemetry Tracing Specification now 1.0!

This refers to the old banner text. I see two reasonable approaches to fixing this:

 1. Just drop the part after the colon
 2. Update the part after the colon to match the new banner text.

Thoughts @austinlparker? (My preference would be for the first option.)

/cc @tigrannajaryan @dyladan

**Comment by austinlparker** [comment]
First is fine
