### ISSUE TITLE
Details on "novel problems" you can handle with observability

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1406]
Follow up to #1401. The following sentence in the [observability primer](https://opentelemetry.io/docs/concepts/observability-primer/) requires additional details (emphasis are mine):

> Observability lets us understand a system from the outside, by letting us ask questions about that system without knowing its inner workings. Furthermore, allows us to easily troubleshoot and **handle novel problems (i.e. “unknown unknowns”)**, and helps us answer the question, “Why is this happening?”

My suggestion is to have either a subsection on that page or (my preference) a subpage in concepts on the topic "problems you can solve with observability/OpenTelemetry" (or a more detailed "Why Observability?" "Why OpenTelemetry?")

There's  a lot of writing on this topic out there from multiple vendors we can source for that. I would really like to see something comprehensive (and vendor neutral) on the OpenTelemetry page. 

I am happy to get something started.

@cartermp , @avillela , @chalin , @austinlparker : thoughts?

**Comment by cartermp** [comment]
That'd be a good idea, yeah.

**Comment by austinlparker** [comment]
+1 to this, yes.

One thing I'd like for authors to be very circumspect about; Try to avoid 'about observability' verbiage that is overly... vendor-specific. "unknown unknowns" is an example of this.
