### ISSUE TITLE
Rename / Restructure "OTel concepts"

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1407]
The page "OTel concepts" contains a lot of valuable material, but from the title it's not clear what it contains and it's also confusing from a reader's perspective that there's a "OTel concepts" navigation item below "Concepts" on the OpenTelemetry page.

I was thinking about renaming it and merging it with "Data Sources", but that's not 100% accurate.

My suggestiond would be to fork out `Tracing & Spans`, `Metrics`, `Logs` & `Baggage` in 4 pages below "concepts" or below a parent page called "Signals", "Data Sources", "Building Blocks", ...?

Another option would be to rename "Concepts" to something different like "Basics" or "Foundations", ...

**Comment by cartermp** [comment]
I think breaking it up is okay (and better to do this earlier since it's already being linked to within other docs)

I think I prefer the first suggestion, breaking it up into the 4 pages. Signals is a technically correct term that could work too, but I feel like I've only ever heard that in the context of the spec rather than when people talk about what you generate with OTel.

**Comment by svrnm** [comment]
See #1411 

> I think breaking it up is okay (and better to do this earlier since it's already being linked to within other docs)

Agreed.

> I think I prefer the first suggestion, breaking it up into the 4 pages. Signals is a technically correct term that could work too, but I feel like I've only ever heard that in the context of the spec rather than when people talk about what you generate with OTel.

I tried both, having 4 additional pages without context / grouping looked not appealing to me, so I went with **Signals**, although I agree with you that it's not used that commonly outside of the spec (it's used in the observability primer and I also updated the glossary to replace "data sources" with signals)
