### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by hari-hara** [open-telemetry/opentelemetry.io#1419]
Hi Support,
Can you please share us the step by step configuration of Open telemetry  configuration of a collector and config files.

Thanks & Regards,
Hari

**Comment by svrnm** [comment]
@hari-hara you will find all documentation for OpenTelemetry at https://opentelemetry.io/docs/ — there are instructions for setting up the collector and for the different language SDKs. If any of these documentations does not provide you the help you’re looking for, raise a specific question in an issue so we can triage if this needs to be added to the documentation. 

Please note that you’re not interacting with a support team here, but with an opensource community that tries to provide great documentation. If you need guidance for OpenTelemetry and the vendor of your choice please reach out to their specific support

**Comment by hari-hara** [comment]
Hi support,

If we use below command to build open telemetry . What will be the server
url to access the the details of server and client

 git clone ***@***.***:open-telemetry/opentelemetry-collector-contrib.git;
\    cd opentelemetry-collector-contrib/examples/demo; \
docker-compose up -d

**Comment by cartermp** [comment]
I'm going to close this since as mentioned, this OSS repo is not a support forum.

@hari-hara if you have a specific documentation issue or question about the docs, please feel free to create another issue and we can engage there.

**Comment by hari-hara** [comment]
Hi Severin Neumann,
i want the details document for open Telemetry server setup and  java application agent setup with jaeger.

is there any support group to call and discuss?

Thanks ,
Hari
