### ISSUE TITLE
End User Discussion Group Website Updates

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#1449]
- [x] Write blog post
- [x] Add to community page
- [x] Update banner

cc @sharrmander

**Comment by Santosh1176** [comment]
Hey @austinlparker, I would love to be part of this website update.

**Comment by austinlparker** [comment]
Cool beans -- this is mostly a tracking issue, Sharr should be able to pop some more detail in about the specifics.

**Comment by sharrmander** [comment]
Hi,

I've got the blog post drafted (and the private slack channel created).

I just need to get the first discussion group on the community calendar, then we'll be ready to publish the post.

Draft here: https://docs.google.com/document/d/1OUBGZCOQIzO3yULjn2WA4XVKiQQiRMY3F6UMXJ_0KyU/edit?usp=drivesdk --open to feedback!

**Comment by Santosh1176** [comment]
Hi @sharrmander that’s a nice intro.👍

**Comment by sharrmander** [comment]
All of this work is complete now, right?

**Comment by austinlparker** [comment]
Did you want to add something to https://opentelemetry.io/community/ about it? Otherwise we can close it
