### ISSUE TITLE
Docs Instrumentation PHP Getting Started

### ISSUE THREAD

**Issue by issraee** [open-telemetry/opentelemetry.io#1499]
The example shown in the documentation, what trace data is generated (the source). And how to add a source application that we want to instrument. (for example wordpress : there's no example in the internet for this case).

**Comment by svrnm** [comment]
> The example shown in the documentation, what trace data is generated (the source). 

I am not sure if I understand, can you be more specific what you are missing in the documentation? 

> And how to add a source application that we want to instrument. (for example wordpress : there's no example in the internet for this case).

Are you asking for a wordpress example in the documentation?

**Comment by issraee** [comment]
Hello, yes a wordpress example since it hasn't been done yet anywhere.
Also, in the example that you provided I want to know what php application
you're getting trace from, there isn't a name or path of the app that you
instrumented like what's the source of the trace?
Thank you very much.

Le jeu. 30 juin 2022 à 16:18, Severin Neumann ***@***.***> a
écrit :

**Comment by svrnm** [comment]
> Hello, yes a wordpress example since it hasn't been done yet anywhere. 

Indeed, there's none, but the otel php community is currently still focused on working towards a stable implementation of otel itself, so I assume that's not a priority right now (cc: @open-telemetry/php-approvers)

> Also, in the example that you provided I want to know what php application you're getting trace from, there isn't a name or path of the app that you instrumented like what's the source of the trace? Thank you very much

the file is called `GettingStarted.php`, it's below the content of that file. Mentioning the filename above would improve readability indeed. Let me look into that.

**Comment by issraee** [comment]
Okay I got it. Thank you for your response and clarification.

Le lun. 4 juil. 2022 à 19:36, Severin Neumann ***@***.***> a
écrit :

**Comment by tidal** [comment]
>Indeed, there's none, but the otel php community is currently still focused on working towards a stable implementation of otel itself, so I assume that's not a priority right now (cc: https://github.com/orgs/open-telemetry/teams/php-approvers)

No it's not a priority and it likely never will be (just a nice-to-have).
In general we are of course interested in having instrumentations for "everything" in the PHP eco-system, and we are working on making (auto) instrumentations very easy to implement. But again this will likely not include WordPress due to its outdated architecture (not using composer etc.). When time comes, we are planning to reach out to the WordPress community to see if someone is interested in working on an instrumentation.
