### ISSUE TITLE
Consider a non-io URL

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry.io#15]
tl;dr: There are a few significant issues with the .io TLD.

* **Political issues:** There are some [political concerns](https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/) around the .io registry that many people feel strongly about. All debate about the actual concerns aside, it seems unnecessary to alienate users and potential users of OpenTelemetry by using a .io URL when we're in a great position to use something else, e.g., opentelemetry.dev.
* **Security:** [This article](https://thenewstack.io/researcher-hijacked-several-io-tld-nameservers/) explains a vulnerability in which a researcher hijacked nameservers, which would allow rogue redirection
* **Support:** As discussed [here](https://hackernoon.com/stop-using-io-domain-names-for-production-traffic-b6aa17eeac20), it sounds like the registry itself has pretty rough support

**Comment by SergeyKanzhelev** [comment]
I'm glad you brought it. It was raised as an issue and discussed in smaller forum before. We discussed that we want to keep it consistent to other projects even knowing of all the risks.

@tedsuo predicted this question in public. Quote (posting with his permission): 
> To address concerns, since they may be raised in public: It's not clear to me that bad domain management would effect this particular project significantly. We do not route production traffic through, or host code, at the .io domain. I do suggest we also keep opentelemetry.dev as a backup for the website. Though I'd love to have a long conversation over drinks about issues pertaining to national security and supply chain attacks on critical OSS software, I don't think that is the level we're talking about here. At least, I hope not. Because we are deeply screwed, in general, if that is the case.

So you can take him up for a conversation over drinks promise.

I suggest we open another issue like "Create a backup for the website on the domain in an alternative domain zone".
