### ISSUE TITLE
Collector "build a ..." pages -- update "what next" section

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1502]
_Originally posted by @rquedas in https://github.com/open-telemetry/opentelemetry.io/pull/1277#discussion_r911275619_:

> We can definitely do that. The Trace Receiver tutorial actually refers to this one, so we also need to make an update there once this one is merged.

**Comment by chalin** [comment]
@rquedas, shall I assign this to you?

**Comment by rquedas** [comment]
Yup
________________________________
