### ISSUE TITLE
`OpenTelemetrySdkAutoConfiguration` class doesn't exists

### ISSUE THREAD

**Issue by aivinog1** [open-telemetry/opentelemetry.io#1536]
**What needs to be changed?**
Right now [this section](https://opentelemetry.io/docs/instrumentation/java/manual/#auto-configuration) says that I should use the `OpenTelemetrySdkAutoConfiguration` class for autoconfiguration Open Telemetry. But as I can see there is no such class in the `1.15.0-alpha` version. I think, that this class was replaced by `AutoConfiguredOpenTelemetrySdk` so, the docs should be changed.

**What is the name + path of the page that needs changed?**
[Instrumentation -> Java -> Manual -> Auto Configuration](https://opentelemetry.io/docs/instrumentation/java/manual/#auto-configuration).

**Comment by aivinog1** [comment]
I guess it happened since this commit: https://github.com/open-telemetry/opentelemetry-java/commit/2fb3d633a0c39b74a645be2931cf51beb7cd24de#diff-946e384e90e9353b5ed9ea9dcf4f7bb69ef6f9c71f2cd0931aa5702fc056be70

**Comment by svrnm** [comment]
@aivinog1 would you mind opening a PR to fix that?

**Comment by aivinog1** [comment]
@svrnm Sure, but it seems that I am late :)
