### ISSUE TITLE
Structure of opentelemetry

### ISSUE THREAD

**Issue by pauldraper** [open-telemetry/opentelemetry.io#154]
Perhaps an overlap of #135. (Hard to read, that one.)

It seems like there isn't any good resource for what OpenTelemetry is, and how it's organized.

My best understanding:

* Concepts
  * [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification)
* Language-independent specification of programming interfaces:
  * [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification)
* Programming interfaces
    * [opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go)
    * [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java)
    * [opentelemetry-js](https://github.com/open-telemetry/opentelemetry-java)
* Implementations of programming interfaces
    * [opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go)
    * [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java)
    * [opentelemetry-js](https://github.com/open-telemetry/opentelemetry-java)
* Formats
  * [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto)
* Agent/collector service with extensible protocols
  * [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector)

Philosophical questions [plagued OpenTracing](https://github.com/opentracing/specification/issues/34), but I think it is nothing compared to what I think is the confusion over OpenTelemetry.

Which of the following is OpenTelemetry standardizing?

[ ] Semantics (a la REST)
[ ] Data formats and transmission protocols (a la Common Log Format, StatsD, Syslog)
[ ] Language interfaces (a la SLF4J) 
[ ] Configuration (a la resolv.conf)
[ ] Implementation (a la LLVM)

Just as important as what *is* being standardized is what *isn't.*

OpenTelemetry plane of operation and organization seems messy/unclear. I'd like something that tells me what level of abstraction OT provides, and how it is organized.

**Comment by austinlparker** [comment]
This is something we'd like to have available for the GA, yes. In the short term, I'd look at #147 and see if those changes address any of these issues as we're trying to make that more clear in the short term.

**Comment by austinlparker** [comment]
Some work was done on this in #293 but we'll continue to flesh it out. These sort of "high level" concepts can either go into the concepts section of the docs, or under the community page.

**Comment by chalin** [comment]
FYI, I just linked this to #770, which will be used to track progress on the IA rewrok.

**Comment by cartermp** [comment]
With the addition of a lot of content recently (under both /concepts and in language docs), we're a lot closer to what's proposed here now I think. I'll leave this open since there's clearly more work to be done, but it's kinda neat seeing that what's live today does represent what's in this issue more closely.

**Comment by svrnm** [comment]
what's still missing from this piece? Can we point to it and reduce it to that (e.g. in a new issue)?

**Comment by svrnm** [comment]
this looks fairly complete to me, closing it now, if any specific point is missing we can have it in a separate issue
