### ISSUE TITLE
Add summary table of the current status of Traces, Metrics and Logs in languages

### ISSUE THREAD

**Issue by trivikr** [open-telemetry/opentelemetry.io#1548]
**Desired feature or idea.**

The [OpenTelemetry Status Page][status] currently links to specifications compliance, and requests visitors to check README files of individual repos to check the status.

It would be helpful, if there's a single table which shows latest status across all languages as follows like the one shown in [Introduction to OpenTelemetry](https://www.youtube.com/watch?v=dfpGU9al_i4) video shown below:

<details>
<summary>OpenTelemetry Components Stability</summary>

![otel-components-stability](https://user-images.githubusercontent.com/16024985/178999888-3d06ac08-be3e-4633-923d-c1dc9a3ef4af.png)

</details>

This table can be shared either on the [Status page][status], or the [Instrumentation page][instrumentation].

**Additional context**
Slack thread on CloudNative Community: https://cloud-native.slack.com/archives/CJFCJHG4Q/p1652971086091609

[status]: https://opentelemetry.io/status/#current-status
[instrumentation]: https://opentelemetry.io/docs/instrumentation/

**Comment by trivikr** [comment]
Created feature requests in individual repos to show Project Status table in top section of README:

* https://github.com/open-telemetry/opentelemetry-java/issues/4611
* https://github.com/open-telemetry/opentelemetry-python/issues/2822
* https://github.com/open-telemetry/opentelemetry-js/issues/3095
* https://github.com/open-telemetry/opentelemetry-ruby/issues/1343
* https://github.com/open-telemetry/opentelemetry-rust/issues/838
* https://github.com/open-telemetry/opentelemetry-swift/issues/313
* https://github.com/open-telemetry/opentelemetry-erlang/issues/411
* https://github.com/open-telemetry/opentelemetry-php/issues/766

**Comment by cartermp** [comment]
Each language page should have this information in a table like so: https://opentelemetry.io/docs/instrumentation/java/#status-and-releases

It appears that not all are in a table though, so that could get updated. Does that help?

**Comment by trivikr** [comment]
> It appears that not all are in a table though, so that could get updated. Does that help?

Yes. That's why I created issues with individual GitHub repos.
I've proposed a standard for table based on existing project status tables.

> I think we could update the status page to point to these docs pages rather than github readmes.

I usually take GitHub as source of truth, as that lies closest to the source code.

What are the docs pages? Did you mean https://opentelemetry.io/docs/instrumentation/java/ for Java?
If they're updated from source code on GitHub, that would also work if it's convenient for developers.

**Comment by cartermp** [comment]
Yes, the docs pages are the official docs for each language on the website. While I think it's fine to have repos also track status, I would actually expect most users of opentelemetry to refer to the docs for this kind of information. The language SIG maintainers also do a good job of updating the docs when there's a meaningful status update.

**Comment by trivikr** [comment]
Should the status page link to the docs instead of GitHub repo READMEs then?

**Comment by chalin** [comment]
Thanks for this @trivikr. 

I agree with @cartermp, especially 

> expect most users of opentelemetry to refer to the docs for this kind of information.

In that respect, let's avoid adding tables across all of the language repos and instead add them to the appropriate language pages in this repo. /cc @austinlparker

**Comment by cartermp** [comment]
I think we can close this now that the status page has been revamped to point to each relevant page in docs.
