### ISSUE TITLE
Add OpenTelemetry Collector Builder docs

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry.io#1555]
**Desired feature or idea.**

Per https://github.com/open-telemetry/opentelemetry-collector-releases/pull/164, the OpenTelemetry Collector Contrib maintainers want to promote usage of the [OpenTelemetry Collector Builder](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder#opentelemetry-collector-builder) so that people build their own distribution with only the components they use.

To facilitate this, we could add a dedicated section explaining how the builder works and how to build a sample custom distribution.

**Additional context**

We use the OpenTelemetry Collector builder for building the official opentelemetry-collector and opentelemetry-collector-contrib distros. The [opentelemetry-collector manifest](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/manifest.yaml) is an example of real-world usage of the builder.

**Comment by cartermp** [comment]
@mx-psi awesome! We do have some docs on this here I believe, but I imagine it could be updated: https://opentelemetry.io/docs/collector/custom-collector/

But moreover, this sounds like more a _guidance_ issue than anything else. We could definitely have that documented. I'd propose that something also be added to the Getting Started pages here: https://opentelemetry.io/docs/collector/getting-started/

I'll gladly review a PR if you're up for it.

**Comment by svrnm** [comment]
Has https://opentelemetry.io/docs/collector/custom-collector/ evolved to satisfy what's needed to close this issue? @mx-psi

**Comment by mx-psi** [comment]
Yes, I think that page is clear enough :) Thanks for following up!
