### ISSUE TITLE
Deployment - consolidate into Data Collection page

### ISSUE THREAD

**Issue by melbgirl** [open-telemetry/opentelemetry.io#1560]
Some of the content here is already in https://opentelemetry.io/docs/concepts/data-collection/ - which makes sense. I'd suggest moving the rest of the content into that page and then removing this one. 
This makes it easier to understand when reading the documentation, as the user doesn't need to flip between two pages.

**Comment by tiffany76** [comment]
@melbgirl 

Looking back at some older issues. Does this still need done? The content seems to have moved, so I can't be sure.

**Comment by cartermp** [comment]
Great call out @tiffany76. I think we can probably close this, as we've shuffled around a lot of the pages (hopefully for the better).
