### ISSUE TITLE
Jaeger now supports OTLP directly - how should we document it for the SDKs?

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1567]
SDKs have all built Jaeger exporters because historically, Jaeger has not supported OTLP. But now they're not technically necessary: https://medium.com/jaegertracing/introducing-native-support-for-opentelemetry-in-jaeger-eb661be8183c

> With this new capability, it is no longer necessary to use the Jaeger exporters with the OpenTelemetry SDKs, or to run the OpenTelemetry Collector in front of the Jaeger backend. Using the OTLP exporter, the SDKs can be configured to send the data directly to the Jaeger backend. The OTLP receiver accepts data via gRPC and HTTP endpoints (gRPC mode had an issue that was patched in 1.35.1).

Given this, I think it's best to migrate our jaeger exporter documentation sections. I'd actually rather just get rid of the current pieces of docs that tell you how to install and use a jaeger exporter, and instead just have each subsection tell you how to install and run jaeger, then use the otlp exporter to talk to jaeger. An alternative is to document both, but I'd also rather not show both ways unless we clearly note that the non-otlp way of doing things is for older jaeger versions.

**Comment by svrnm** [comment]
+1, I like that idea!

**Comment by svrnm** [comment]
Tagged this with help wanted. Languages that mention jaeger still need to be updated:

- [x] [JavaScript](https://opentelemetry.io/docs/instrumentation/js/exporters/)
- [ ] [.NET](https://opentelemetry.io/docs/instrumentation/net/exporters/)
- [ ] [Go](https://opentelemetry.io/docs/instrumentation/go/exporting_data/)
- [ ] [Python](https://opentelemetry.io/docs/instrumentation/python/exporters/)

**Comment by Petrie** [comment]
I'll try  update the part of Go. @svrnm

**Comment by svrnm** [comment]
Thank you @Petrie!

**Comment by Petrie** [comment]
@svrnm Ah! I mean Golang, not .NET

**Comment by svrnm** [comment]
> @svrnm Ah! I mean Golang, not .NET

Thanks, that was just my mistake putting you in the wrong line!

**Comment by cartermp** [comment]
re-opening due to github automation closing it
