### ISSUE TITLE
Status page - make it a hub for language SDKs, spec, collector, etc.

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1570]
This was discussed in the 7/28/22 SIG meeting.

Today, the status page is actually the _specification_ status page. However, whenever we talk to end-users, this is not the primary thing that comes to mind when they want to know the "status" of something. Most of the time, they actually want to know if a given signal (e.g., metrics) is stable/alpha/beta in the language that they need to use. Spec and collector status do come up, but not as often.

Thus, there's a desire to rework this page so that we can link out to constituent statuses for different things:

- Language SDKs (each has a status section in the docs)
- Spec (we already have this page)
- Collector (a section and/or page would have to be created)

Very rough wireframe mocking up the idea:

> <img src="https://user-images.githubusercontent.com/6309070/181608699-c87da6f2-b403-4098-8816-c82cfcdef3ef.png" width=400>

The idea is that you can click a box/logo that takes you to the status for that _thing_.

This issue is a part of:

- #1574

**Comment by melbgirl** [comment]
I can take this one, I have some time later this week. Can someone point me to any exiting style elements (eg cards) ?

**Comment by chalin** [comment]
Thanks @melbgirl - note that there's some preparatory work to be done first (see the meeting notes) for a proposed "update plan".

**Comment by cartermp** [comment]
Also FWIW the iconography is at least all standard and usable: https://github.com/open-telemetry/opentelemetry.io/tree/main/iconography/512x512

**Comment by chalin** [comment]
Oops, sorry Libby, I was rushing to my next meeting and didn't realize that `@melbgirl` was your ID! So of course you know about the proposed update plan 🤷‍♂️.

**Comment by TylerHelmuth** [comment]
For the collector, are customers asking for the status of the collector as a whole or individual components within the collector (otlpexporter, hostmetricsreceiver, etc)? I have encountered both on the slack channel.

**Comment by cartermp** [comment]
@TylerHelmuth That's a good question. I've personally only fielded questions about the collector as a whole, and why some components aren't a part of the contrib distribution. Not necessarily about if a given component is stable. But I imagine that will come up sooner than later.

I think that in docs, we could probably do two things:

1. State the status of the collector itself
2. Make mention that components in the contrib distribution are of mixed maturity, and a maturity model may (will?) be established to better distinguish which are stable and which are not

Thoughts?

**Comment by TylerHelmuth** [comment]
Makes sense.  The collector SIG has established [Stability Levels](https://github.com/open-telemetry/opentelemetry-collector#stability-levels) for components and is [working towards getting all component READMEs updated](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10116) with that status (and more).  There has also been updates to allow components to print out their stability level on collector startup if the component is unmaintained or deprecated.  Hopefully that work is helpful in some way.

**Comment by chalin** [comment]
FYI: keeping this issue for the status-page-as-hub feature, I've created #1574 to track all of the Status page rework that was agreed to during the Comms/Website meeting.

**Comment by chalin** [comment]
@TylerHelmuth et all: FYI, here's the collector-specific issue:

- #1573

**Comment by melbgirl** [comment]
@chalin and @cartermp: I was thinking to use images as the 'boxes' in the design, rather than using an HTML table. What are your thoughts?

**Comment by cartermp** [comment]
I'd defer to @chalin on if that fits the overall technical goals for the repo, but I'm quite fine with that as an approach.

**Comment by chalin** [comment]
> ... rather than using an HTML table

We'll want a flex design that caters to viewing on mobile as well as desktop -- so not a table. As a first cut for the page design, I'd vote to use plain text (rather than images) either as a simple link or a button-role (rather than a card). That is, IMHO, we should aim to get a functional page first with the proper flex design (for mobile and desktop), then beautify it later. (But if you want to do it all in one go, that ok too :).

**Comment by melbgirl** [comment]
How do we think the page transformation is going? Are there other things we'd like to see, or can we consider this item complete?

**Comment by cartermp** [comment]
I'm happy with how it's looking right now. Always ways to improve, but it's got all the necessary information on it today. Let's close this out and if there's more enhancements people want to do, we can just create PRs and/or issues. Thanks, @melbgirl!

**Comment by melbgirl** [comment]
No worries Patrice, all good👍
