### ISSUE TITLE
Adding attributes to the SDK set up in the Java manual instrumentation

### ISSUE THREAD

**Issue by ppatierno** [open-telemetry/opentelemetry.io#1582]
**What needs to be changed?**
The SDK set up in the Java manual instrumentation page is missing to mention attributes to be set to get it working, like for example the service name which is the main one (as it is mentioned in the corresponding agent documentation https://opentelemetry.io/docs/instrumentation/java/automatic/#configuring-the-agent).
We would need to change the code snippet and the text to mention about attributes.

**What is the name + path of the page that needs changed?**
The page is at `content/en/docs/instrumentation/java/manual.md`

**Comment by ppatierno** [comment]
@mateuszrzeszutek you could assign this one to me as well :-)

**Comment by cartermp** [comment]
@ppatierno happy to review a PR!

**Comment by ppatierno** [comment]
@cartermp here the PR #1584!
