### ISSUE TITLE
Workshop code in python is outdated

### ISSUE THREAD

**Issue by arbiv** [open-telemetry/opentelemetry.io#1596]
**What happened?**
The workshop code in python is outdated. See [student](https://glitch.com/edit/#!/opentelemetry-python-student) and [instructor](https://glitch.com/edit/#!/opentelemetry-python-instructor) copies.

Workshop page is at [main/content/en/docs/workshop/resources.md](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/workshop/resources.md)

**Comment by arbiv** [comment]
I created an updated version [under my GitHub account](https://github.com/arbiv/opentelemetry-workshop-python), but I am not sure how to update the glitch project. I clicked the "request to join" button but got no feedback.

Maybe we should create a repo in open-telemetry org for this purpose? 

@austinlparker what do you think?

**Comment by svrnm** [comment]
following up on this.

@austinlparker: do we want to keep those resources (presentation, glitch) updated/maintained? Is opentelemetry.io the right place to discuss or does this belong to open-telemetry/community?

cc @cartermp , @chalin

**Comment by cartermp** [comment]
I would be in favor of dropping these assets in favor of the community demo.
