### ISSUE TITLE
Traces

### ISSUE THREAD

**Issue by truekonrads** [open-telemetry/opentelemetry.io#1599]
The sample span in [this documentation page ](https://opentelemetry.io/docs/concepts/signals/traces/#spans-in-opentelemetry) does not include neither "Trace Flags" nor "Trace State". This needs either a better example span or the documentation needs adjusting.

**Comment by svrnm** [comment]
@truekonrads can you provide a sample span that includes the missing details?

**Comment by svrnm** [comment]
@truekonrads, I am still not 100% sure what the issue is, can you provide an example?

**Comment by cartermp** [comment]
Closing this out since those are a part of `Span Context`, which is documented here: https://opentelemetry.io/docs/concepts/signals/traces/#span-context
