### ISSUE TITLE
Kubernetes yaml file is not correct

### ISSUE THREAD

**Issue by akalittle** [open-telemetry/opentelemetry.io#1610]
In the [getting-started page ](https://opentelemetry.io/docs/collector/getting-started/)

**Kubernetes** 
Deploys an agent as a daemonset and a single gateway instance.
``` shell
$ kubectl apply -f https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/main/examples/k8s/otel-config.yaml

```
In the yaml file, the image version is 
`otel/opentelemetry-collector:0.58.0`

But in the docker hub registry, there is no image `opentelemetry-collector:0.58.0`

**Comment by cartermp** [comment]
This sounds like it's just a point-in-time problem where the release was cut but images weren't uploaded to dockerhub yet: https://github.com/open-telemetry/opentelemetry-collector/pull/5891

I don't know if there's anything we should do in the docs. @bogdandrutu will the dockerhub push be imminent?

**Comment by akalittle** [comment]
Yep. It's not a big problem. After I viewed the dockerhub, I changed the version to the latest.
It‘s just a feedback.
