### ISSUE TITLE
open telemetry can't ingest dynatrace from aws lambda function with AWS Distro for OpenTelemetry

### ISSUE THREAD

**Issue by eulisesquidel** [open-telemetry/opentelemetry.io#1616]
We use AWS Distro for OpenTelemetry 

arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-5-0:1

We did a basic aws lamda function in nodejs:

const axios = require('axios');
const url = 'http://checkip.amazonaws.com/';

exports.handler = async (event) => {
    let response
    console.log('[START] - OpenTelemetry / Dynatrace');
    try {
        response = await axios({
            method: 'post', url:url
        });
        console.log('**************', response?.data)
    } catch (error) {
        console.log('ERR: ', error)
    }
    console.log('[END] - OpenTelemetry / Dynatrace');
    return response?.data;
}
Our collector.yaml config is: 

![image](https://user-images.githubusercontent.com/13561758/184207951-9bb01d5f-d256-4d08-83fc-87ad8ec8207c.png)

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
      http:
        endpoint: 0.0.0.0:55681
exporters:
  otlphttp:
    endpoint: "https://ico19512.live.dynatrace.com/api/v2/otlp/v1/traces"  
    headers: {Authorization: "Api-Token dt0c01......"}
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
      
Our enviroments variables:

![image](https://user-images.githubusercontent.com/13561758/184208328-beb0bb29-c09d-4604-a5f3-44c75615ea93.png)

Our lamda run ok, but we don't see ingested nothing.

![image](https://user-images.githubusercontent.com/13561758/184209082-4e976bb1-5d71-424a-8d27-30de96f69e25.png)

AWS Lambda function response was ok: "34.237.128.180"

Function Logs

START RequestId: b077aa35-b4bc-4604-8e5a-c67dbfa454ac Version: $LATEST
EXTENSION   Name: collector State: Ready    Events: [INVOKE,SHUTDOWN]
{"level":"debug","msg":"Received ","event :":"{\n\t\"eventType\": \"INVOKE\",\n\t\"deadlineMs\": 1660236861439,\n\t\"requestId\": \"b077aa35-b4bc-4604-8e5a-c67dbfa454ac\",\n\t\"invokedFunctionArn\": \"arn:aws:lambda:us-east-1:658913498668:function:dyna-otel\",\n\t\"tracing\": {\n\t\t\"type\": \"X-Amzn-Trace-Id\",\n\t\t\"value\": \"Root=1-62f5342f-1b4ce6bd6c1ebf2c6601dc57;Parent=29fc70b85a8376fd;Sampled=0\"\n\t}\n}"}
{"level":"debug","msg":"Waiting for event..."}
2022-08-11T16:54:09.465Z    b077aa35-b4bc-4604-8e5a-c67dbfa454ac    INFO    [START] - OpenTelemetry / Dynatrace
2022-08-11T16:54:09.806Z    b077aa35-b4bc-4604-8e5a-c67dbfa454ac    INFO    ************** 34.237.128.180

2022-08-11T16:54:09.806Z    b077aa35-b4bc-4604-8e5a-c67dbfa454ac    INFO    [END] - OpenTelemetry / Dynatrace
END RequestId: b077aa35-b4bc-4604-8e5a-c67dbfa454ac
REPORT RequestId: b077aa35-b4bc-4604-8e5a-c67dbfa454ac  Duration: 708.69 ms Billed Duration: 709 ms Memory Size: 128 MB Max Memory Used: 126 MB Init Duration: 1324.55 ms

Request ID
b077aa35-b4bc-4604-8e5a-c67dbfa454ac

**Comment by svrnm** [comment]
hey @eulisesquidel, this here is the project for the opentelemetry website, if you need vendor specific help, you can either reach out to dynatrace or aws via their support channels or you can try to get some help at CNCF slack at the #otel-vendor channel: https://cloud-native.slack.com/archives/C031SAMGV2A
