### ISSUE TITLE
Netlify config: are we still using `GH_TOKEN`?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1627]
Question sent to @austinlparker on stack. Adding the question here for tracking purposes.

See also:

- https://github.com/open-telemetry/opentelemetry.io/pull/2351#discussion_r1109051192

**Comment by svrnm** [comment]
@chalin is this question still open? I am not 100% sure what the context was

**Comment by chalin** [comment]
The env variable is gone (https://app.netlify.com/sites/opentelemetry/configuration/env#environment-variables), so closing this issue.
