### ISSUE TITLE
Repost exponential histogram blog post

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry.io#1639]
I recently wrote / published a blog post about otel exponential histograms on [New Relic's blog](https://newrelic.com/blog/best-practices/opentelemetry-histograms).

Its only got 1 or 2 vendor specific references that are easy to remove, after which its just a good run down of an awesome new open telemetry feature. I think it would be a good addition to the opentelemetry blog, but before I go through the process of converting it to markdown and making it completely vendor agnostic, I want to confirm that reposting existing content is ok.

Give me a 👍 and I'll get PR out there shortly.

**Comment by svrnm** [comment]
I would love seeing this published on the otel blog 👍
