### ISSUE TITLE
Add link to meeting recordings to community page

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1657]
Add a link to https://opentelemetry.io/community/ that points to the recordings of the OpenTelemetry SIG meetings: https://www.youtube.com/channel/UCHZDBZTIfdy94xMjMKz-_MA

**Comment by uday060** [comment]
I would like to take this task and do it. Should I add this link under "Learn and Connect" or "Develop and Contribute"?

Any description to add next to the link?

**Comment by svrnm** [comment]
thanks @uday060, put it below "Learn & Connect" with something like "Watch our meeting recordings on Youtube"

**Comment by uday060** [comment]
@svrnm Any Icon I need to select to keep before the description?

**Comment by svrnm** [comment]
@uday060 there's class="fab fa-youtube"

**Comment by uday060** [comment]
@svrnm Thank you for all your inputs, created the PR https://github.com/open-telemetry/opentelemetry.io/pull/1681

**Comment by svrnm** [comment]
fixed via #1681
