### ISSUE TITLE
Blog posts order differs in side-nav vs list

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1660]
Visit https://opentelemetry.io/blog/:

> <img width="774" alt="image" src="https://user-images.githubusercontent.com/4140793/186491593-b9f59c37-3461-4182-946a-344d6e4c1058.png">

I'll have to investigate: this might be a Docsy bug, or it might be due to local overrides.

**Comment by chalin** [comment]
I can reproduce the problem from a fresh Docsy site, so it's either a Docsy issue or a Hugo issue (or both) :). I'll track this from the Docsy repo:

- https://github.com/google/docsy/issues/1197

**Comment by uday060** [comment]
@chalin I am able to see in the same order when I visited the page now.

**Comment by chalin** [comment]
This was fixed upstream. I'll upgrade Docsy as soon as I can.

**Comment by chalin** [comment]
Nope, take that back, it wasn't fixed upstream, and it make [take a while before this is fixed](https://github.com/google/docsy/issues/1197#issuecomment-1272383847).

**Comment by svrnm** [comment]
@chalin would you mind if we close this as "won't fix"? It's tracked upstream, so I don't think we need to keep this issue here
