### ISSUE TITLE
Write blog post about instrumenting Kafka applications

### ISSUE THREAD

**Issue by ppatierno** [open-telemetry/opentelemetry.io#1668]
Hey team, a week ago I have got merged a PR about adding some more information on how to instrument Kafka clients. At the beginning, it was too much content and discussing on that PR it sounded to be a good idea to make it a blog post. As maintainer of the Strimzi project (Kafka on Kubernetes) I was going to write it on our blog but then I thought that, maybe, the OpenTelemetry blog could be the best place to do so. Are you willing to accept a blog post about how to instrument Kafka clients by using OpenTelemetry?

**Comment by svrnm** [comment]
Hey,
the title suggest that it belongs here:-) For my understanding can you share the link to the merged PR you have mentioned?

**Comment by ppatierno** [comment]
@svrnm can I assume that your "love" on my previous comment means something like "please go ahead we are happy to have you writing this blog post" ? 😉

**Comment by svrnm** [comment]
@ppatierno yes!!:-)

**Comment by ppatierno** [comment]
@svrnm quick question ... if I have to add some images, do I have to follow the structure of the exponential-histograms or instrument-ngix? So a folder with `index.md` and then images inside?

**Comment by svrnm** [comment]
index.md  and images in one folder would be great. We still need to update the blog instructions asking people to do it that way

**Comment by ppatierno** [comment]
@svrnm I just opened the corresponding PR. I plan to review it one more time but anyway would be great your feedback soon.

**Comment by svrnm** [comment]
closed via 1677
