### ISSUE TITLE
Replace "sample of the type of information ... present in a Span" image with a text

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1686]
At the top of section [Spans within Observability Primer](https://opentelemetry.io/docs/concepts/observability-primer/#spans) we use the following image to show a sample of a span:

![](https://opentelemetry.io/img/span_visualization.png)

I think this picture has a few issues: 

1. it is hard to read & for someone with a screenreader it is entirely inaccessible.
2. it looks like a vendor specific UI screenshot
3. it provides client side telemetry attributes, which are not the most common ones.

Especially (1) makes me think, that we should replace that image with a table showing keys & values of a common example (server side http request?)

**Comment by Gaurang-Patel** [comment]
I would like to work on this issue and will submit a draft pr for more inputs.

**Comment by svrnm** [comment]
thanks @Gaurang-Patel , assigned it to you!
