### ISSUE TITLE
Link to Iconography

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1693]
We link to the "Otel_iconography.zip" at the bottom of the page, when you click on that link you're redirected to the "fiel view of github" and still need to click on Download. A quick fix would be replacing it with a link to the download, but long term we should either have a page for it showing all the icons or at least have the zip included in the published website to accomplish #663 

Related: #1690 #1692

**Comment by uday060** [comment]
@svrnm I can fix this bug by converting the current hyperlink to a downloadable hyperlink

**Comment by svrnm** [comment]
this is fixed
