### ISSUE TITLE
Add icons for php, rust & swift

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1694]
Until #680 is fixed, we should nevertheless bring the missing icons we know have (PHP, Rust, Swift) to the descriptions of the languages:

https://opentelemetry.io/docs/instrumentation/

**Comment by uday060** [comment]
@svrnm  How to find out the rawgithub user content image hyperlinks for php, Rust and Swift?

**Comment by svrnm** [comment]
https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/32x32/Rust.svg
https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/32x32/PHP.svg
https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/32x32/Swift.svg

**Comment by uday060** [comment]
@svrnm Here is the PR with the fix https://github.com/open-telemetry/opentelemetry.io/pull/1702/files

**Comment by svrnm** [comment]
fixed via #1702
