### ISSUE TITLE
Collector "Configuration" page issues 

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1697]
- [ ] The config under the Configuration page, Exporters section, is a bit odd. For instance, the prometheus exporter specifies prometheus:8889 as the endpoint. As it refers to the same host, I would use either localhost or 0.0.0.0. Similarly, external URLs are following different patterns: "jaeger-all-in-one", "some.url", "example.com", "localhost". I would suggest having them all follow a pattern like "jaeger.example.com", "prometheus.example.com", "otlp.example.com", and "zipkin.example.com"
- [ ]  The configuration page is missing the telemetry attribute for the service
- [ ]  A link is desirable for "net/http" mentioned in "Proxy support"

Source: https://github.com/open-telemetry/opentelemetry.io/issues/1368#issuecomment-1178157486

**Comment by theletterf** [comment]
@svrnm What do you mean by

>  The configuration page is missing the telemetry attribute for the service

You mean `OTEL_SERVICE_NAME`?
