### ISSUE TITLE
APM definition in the glossary is bad

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1699]
The [glossary](https://opentelemetry.io/docs/concepts/glossary/) states that APM is "typically a back-end of the Tracing Data Source". This makes people think that APM is *only* doing traces and not metrics, logs or anything else, which is incorrect. Would be good to have a better description.

**Comment by shijiadong2022** [comment]
Is there a preferred APM description if I'd like to make my first contribution?

**Comment by svrnm** [comment]
So my minimal requirement is dropping that statement "typically a back-end of the Tracing Data Source", because APM is not only the backend and as said does more than tracing. The definition should capture that APM is about monitoring software applications, their performance (speed, reliability, availability, etc.) to detect issues, alerting and tooling for finding the root cause

**Comment by rahuldimri** [comment]
Can I work on the updating the document ?

**Comment by cartermp** [comment]
@rahuldimri sure thing! Let me assign you, and we can review a pull request you send our way.

**Comment by cartermp** [comment]
Closin', thanks @rahuldimri!
