### ISSUE TITLE
Revisit "Data Collection" page

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1700]
The [Data Collection](https://opentelemetry.io/docs/concepts/data-collection/) page is a duplication from the Collector pages, including some content we want to get rid of. 

Do we should get rid of it or transition it into something more general about "Data Collection" (whatever that might mean)?

**Comment by cartermp** [comment]
I think we should consider rewriting it, since it's an important conceptual topic. But I wouldn't really know what to say about it right now. I don't think it's actively harmful to have it there right now, though.

**Comment by theghostmac** [comment]
I have an idea on how to refactor both pages. I will make changes via a fork and send a PR.

**Comment by cartermp** [comment]
Awesome, thank you @theghostmac. I'll assign you to this issue for now.

**Comment by theghostmac** [comment]
I finished making the changes. I made two mistakes:
- not checking out to a new branch after cloning
- attempting a merge (ignorant of the PR procedure 😞 )

**Comment by svrnm** [comment]
this is no longer relevant since we removed that page
