### ISSUE TITLE
Add read from secret to oauth2client extension 

### ISSUE THREAD

**Issue by dansl1982** [open-telemetry/opentelemetry.io#1709]
**Desired feature or idea.**

If I'm not mistaken, currently, there is no way to read client_id and client_secret from the k8s secret file in the oauth2client extension configuration. As I see, there are two options, 
 1. To set `clinet_id` and `client_secret` explicitly.
 2. Environment variables https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables

example: 
`oauth2client:
    client_id: <READ FROM K8S SECRET>
    client_secret: <READ FROM K8S SECRET>
    token_url: https://example.com/oauth2/default/v1/token
    scopes: ["api.metrics"]`

**Additional context**

**Comment by svrnm** [comment]
@dansl1982 from the issue description it's not clear to me if this is a documentation issue (which belongs here) or an issue with the extension (which you should raise here: https://github.com/open-telemetry/opentelemetry-collector-contrib)

**Comment by dansl1982** [comment]
@svrnm 
issue/improvements for the extension, I opened a new request using the link you sent. Thanks!
