### ISSUE TITLE
/docs/ is not linked from the homepage and hard to find

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1711]
The [index](https://opentelemetry.io/docs/) of the "docs" section is only accessible via the following link:

![Screen Shot 2022-09-05 at 17 25 54](https://user-images.githubusercontent.com/1519757/188481578-95c79266-e726-48a9-bc79-fdd7f90d7136.png)

The "Learn More" on opentelemetry.io/ links to the Concepts page.

I looked for this page a few times already myself until I found it. Here's a few suggestions what to do with it:

1. We link the Learn More from the homepage to it and people dive into the material from there
2. We move the content of that page to the "Concepts" index and leave it almost empty.

**Comment by melbgirl** [comment]
I may be not understanding what you mean by index. There's the Docs link in the menu bar, which takes you to the above page.

**Comment by svrnm** [comment]
> I may be not understanding what you mean by index. There's the Docs link in the menu bar, which takes you to the above page.

Yes, I know, but I always find it hard to find, but maybe it's just me having that problem ;-)

**Comment by svrnm** [comment]
it's probably just me ;-)
