### ISSUE TITLE
[meta] Define labels for each SIG language

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry.io#1726]
Please create github labels per SIG, for example "sig:cpp", "sig:java", etc,
and tag issues accordingly,
so that "we" (maintainers of opentelemetry-cpp) can find all the issues related to the cpp documentation at once.

The suggestion is on purpose to not use the "lang:" namespace, to preserve it for translations later ("lang:en", "lang:fr", etc)

**Comment by svrnm** [comment]
I think that's a good idea, @cartermp let's discuss this later today in the comms meeting.

**Comment by svrnm** [comment]
We are going to do that!

I will create

sig:cpp
sig:dotnet
sig:erlang
sig:go
sig:java
sig:javascript
sig:php
sig:python
sig:ruby
sig:rust
sig:swift
sig:collector

and then we can grow from there if we need more.
