### ISSUE TITLE
End User Discussion Group should not live out of a blog

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1729]
Since these are regular we should give them a place outside of the blog, https://opentelemetry.io/blog/2022/new-end-user-resources/#monthly-discussion-group, maybe under [Community](https://opentelemetry.io/community/) or have a End User space on top on its own?

**Comment by reese-lee** [comment]
Big plus one!! I don't have a clear idea yet of what this should look like, but agree that it would be great to have a space like this.

**Comment by musingvirtual** [comment]
Enthusiastic second from me! It would also be great to have a place that we can update easily when we have topics and whatever rather than doing blog posts.

**Comment by svrnm** [comment]
@musingvirtual , @reese-lee : see my PR (#1730)

> It would also be great to have a place that we can update easily when we have topics and whatever rather than doing blog posts.

I guess that _could_ be doable via CODEOWNERS, let's do this as a second step.

**Comment by melbgirl** [comment]
+1 from me for a space for the WG

**Comment by svrnm** [comment]
As discussed during the last SIG meeting the plan is to turn the community (and enduser) section into something like the blog/docs.

cc: @chalin , @cartermp , @austinlparker

**Comment by chalin** [comment]
HI all

- #1804

awaits your feedback.
