### ISSUE TITLE
Sketch out how metrics should be documented for each language SIG

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1746]
In the last maintainer's meeting, we discussed the looming lack-of-metrics problem. Several SIG maintainers said that they won't consider metrics as fully released until there's docs. Yay! But they'd like some help.

The ask was that we come up with the general framework by which they can contribute some code. For example:

* Should there be metrics in getting started for each language? If so, where?
* Where should we show how to initialize metrics in code?
* What concepts in metrics should get documented with code samples?
* Should there be dedicated metrics pages, or should metrics be on the same page as tracing?

If we can get this sketched out, then several SIG maintainers (Go, JS) offered to contribute some basic docs and code samples that demonstrate how to initialize and use metrics APIs correctly. I mentioned that I can usually run with things once I have the initialization code done right, since it's not too hard to use APIs in a sample app and produce copy-pasteable snippets from there.

We can then go to a language SIG with this and work with them to get metrics documented soon!

**Comment by svrnm** [comment]
> Should there be metrics in getting started for each language? If so, where?

I would like seeing traces & metrics (and later logs and other potential signals) being combined in one "getting started", starting with traces for sure, but then going on with metrics is the natural flow and also shows that we think as them belonging together.

> Where should we show how to initialize metrics in code?

I think some of the SIGs are working on automatic things, so we can do it again like with traces: here is what you get automatically, here is what you can do manually, etc.

> What concepts in metrics should get documented with code samples?

Some/Most languages have a http example already, so doing some calls per minute, average response time, error rate, etc is a good starting point. 

> Should there be dedicated metrics pages, or should metrics be on the same page as tracing?

if possible: same.

**Comment by cartermp** [comment]
(follow python example for each language: https://opentelemetry.io/docs/instrumentation/python/getting-started/)

# Getting started
words
## Installation
install everything you need / set up an environment for it if the language calls for it
## Create sample http server
No instrumentation; just an http server that does a dice roll
## Add automatic instrumentation / Add instrumentation libraries
(title differs depending on if language has autoinstrumentation)
At a minimum, instruments the http call. Most likely to create a span since most libraries do that today.
## Run the instrumented app
Show how to run, show sample outpue
## Add manual instrumentation to automatic instrumentation
words
### Add tracing
Show how to create a span that connects with autoinstrumentation, run the app again, show example output
### Add metrics
**Show how to create a counter and up that counter on every request**
## Send telemetry to an OpenTelemetry Collector
words
### Configure and run a local collector
example of configuring and running the collector such that it logs telemetry output
### Modify the command to export spans and metrics via OTLP
show how to export to the collector via otlp exporter
### Run the application
same as previous run, but this time shows collector output
## Next steps
Point to autoinstrumentation/libraries article(s) and manual instrumentation article and exporters article

**Comment by cartermp** [comment]
(In manual instrumentation article)

# Manual instrumentation

words

## Tracing

...all the tracing stuff that's mostly documented now

## Metrics

words

### Initialization
Show how to correctly initialize metrics for manual instrumentation. Some things to consider:

* How to do it the "most correct" way
* resource attributes? which ones?
* should metrics get initialized differently based on if you have instrumentation libraries or autoinstrumentation configured?
* Explain what a meter is? Or should that go in language-agnostic concept docs and get linked to?

### Synchronous and asynchronous instruments

Explain synchronous and asynchronous instruments? Or should this just go into language-agnostic concept docs?

### Using Counters

Briefly say what a counter is/link to a definition, show code sample on how to create and use

### Using Asynchronous Counters

Briefly say what an async counter is/link to a definition, show code sample on how to create and use

### Using Histograms

Briefly say what a histogram is/link to a definition, show code sample on how to create and use

### Using UpDownCounters

Briefly say what a UpDownCounters is/link to a definition, show code sample on how to create and use

### Using Asynchronous UpDownCounters

Briefly say what a async UpDownCounters is/link to a definition, show code sample on how to create and use

### Using Asynchronous Gauges

Briefly say what a async gauge is/link to a definition, show code sample on how to create and use

### Adding attributes to an instrument

Show example(s) of adding attributes to one or more of the above instruments, with a code sample

## Next steps

Link to exporters page
Link to instrumentation libraries and/or autoinstrumentation page

**Comment by svrnm** [comment]
ok... that's much more than metrics 😆  but I like it... can you put that maybe in 2 markdown files (maybe in archetypes or some "temp" place), so that commenting is a little bit easier?

**Comment by svrnm** [comment]
> @svrnm @cartermp I'm currently doing some Python metrics work, and I've done a bunch of Python traces work, so I'd be happy to document both sides. 😁

awesome! There's already a bunch of stuff for python on tracing, and a little bit on metrics. So, while you work on that, double check if the python tracing stuff is up-to-date & if things can be added and for the metrics extend it to whatever is missing.
