### ISSUE TITLE
Instrumenting Apache Kafka clients with OpenTelemetry

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry.io#1781]
To observe the full trace on the backend, is it necessary to keep the producer's service name as same as the consumer's service name in the environment variables?

**Comment by svrnm** [comment]
@ppatierno can you help with that? Thanks.

**Comment by ppatierno** [comment]
@sweetxiaodai I guess your question is related to the one you opened on my own repo here https://github.com/ppatierno/kafka-opentelemetry/issues/10, let's keep the discussion in one place. I think the OpenTelemetry repo is the best place to discuss.
So, in general having the same service name on both side, helps for sure having all the spans to be in the same place on the Jaeger UI (not needed to jump across services). I have never tried if Jaeger UI is able to correlate if service names are different.
Said that, are you using the Java agent to instrument your producer and consumer? In this case, producing and consuming are correctly on different traces but they are referenced so that you can jump from receiving to producing. This is why in a messaging system like Kafka, everything happens async. You can read more about this in this blog post: https://opentelemetry.io/blog/2022/instrument-kafka-clients/ . See more detailed comments in the https://opentelemetry.io/blog/2022/instrument-kafka-clients/#instrumentation-in-action section.

**Comment by sweetxiaodai** [comment]
Thanks @ppatierno 
I've read the blog and keep the service name of producer and consumer as one. But how ever I still got a broke span.
I put my code in the two repositories, it will help you reproduce the issue. I don't think the issue could be closed. Sorry.

https://github.com/sweetxiaodai/kafka-otel-producer.git
https://github.com/sweetxiaodai/kafka-otel-consumer.git

Would you mind kindly use the code reproduce the issue or let me know where is the incorrect part of the configuration?

I also put my environment variables here to help you to identify the issue.
producer env:
jvm options:
-javaagent:/Users/genesis/otel/opentelemetry-javaagent.jar -Dotel.service.name=kafka-trace
'''
OTEL_TRACES_EXPORTER=jaeger;
OTEL_EXPORTER_JAEGER_ENDPOINT=http://localhost:14250;
OTEL_SERVICE_NAME=kafka-trace`
'''
consumer env:
jvm options:
-Dotel.service.name=kafka-trace -javaagent:/Users/genesis/otel/opentelemetry-javaagent.jar -Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=true
'''
OTEL_TRACES_EXPORTER=jaeger;
OTEL_EXPORTER_JAEGER_ENDPOINT=http://localhost:14250;
OTEL_SERVICE_NAME=kafka-trace
'''

**Comment by ppatierno** [comment]
What do you mean by broken trace?
Using my project at https://github.com/ppatierno/kafka-opentelemetry I was able to run a producer and consumer together with the opentelemetry agent. I get what I explained in the blog post.

- one producer span in its own trace
- two consumer span (receive and process) in its own trace but with ...

```json
"operationName": "my-topic process",
                    "references": [
                        {
                            "refType": "FOLLOWS_FROM",
                            "traceID": "506ab16d27fe0cdca459e90238096755",
                            "spanID": "15abd6951658f94e"
                        },
                        {
                            "refType": "CHILD_OF",
                            "traceID": "940a5b7ae354b0eaa0b3ab478fd76f4c",
                            "spanID": "cadbe6a14b07a315"
                        }
                    ],
```

... where the process span is CHILD_OF receive in the same consumer trace but it FOLLOWS_FROM the send in the producer trace.

**Comment by sweetxiaodai** [comment]
![Screenshot 2022-09-28 at 03 29 45](https://user-images.githubusercontent.com/90817719/192618280-c96adae8-454e-45f2-9b79-53ce3622248e.png)
Hi @ppatierno 
Sorry to make you confused. I attached the screen shot in jaeger. The send and receive span are in different trace looks like. Is there any way to link it together? I just developed two application, one is the consumer and the other one is the producer, but looks like the spans of sending and receiving cannot combine as a whole trace. 

I will try to use your code to verify again. I have same problem when I tested the Rocket MQ. Some incompatible dependencies's version caused the issue. Then I use lower version of the driver, then it works fine. I guess this time it was the similar problem.

**Comment by ppatierno** [comment]
As I mentioned in the blog post but even in my previous comment, as OpenTelemetry works with messaging is about having them leaving in two different traces but they are linked together (see my JSON above). Can you provide the JSON representation of your spans and traces to see that?

I also think this discussion could clarify your doubts https://github.com/open-telemetry/opentelemetry-specification/discussions/2695

**Comment by sweetxiaodai** [comment]
Ok, finally, I got your point. But it is different with otel rocketMQ. otel RocketMQ could put all spans in one trace.
I attached two json. 
I do find the follows_from's traceID is as same as the producer traceID. I will try to read your post to understand the mechanism. How did you figured out the produced trace and consumed trace belongs one message? 

Thanks so much for your patient. It is really helpful.
producer
```json
{
    "data": [
        {
            "traceID": "aff05b721bafcae46cca80290db1d9a6",
            "spans": [
                {
                    "traceID": "aff05b721bafcae46cca80290db1d9a6",
                    "spanID": "d4ddb09c305eef71",
                    "operationName": "KafkaController.publish",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "aff05b721bafcae46cca80290db1d9a6",
                            "spanID": "a9407380777c3dff"
                        }
                    ],
```
consumer
```json
    "data": [
        {
            "traceID": "9ad022e836cea34c065bafeaae86bb90",
            "spans": [
                {
                    "traceID": "9ad022e836cea34c065bafeaae86bb90",
                    "spanID": "5ad0544c9856e92c",
                    "operationName": "topic1 process",
                    "references": [
                        {
                            "refType": "FOLLOWS_FROM",
                            "traceID": "aff05b721bafcae46cca80290db1d9a6",
                            "spanID": "708058c7be78e595"
                        },
                        {
                            "refType": "CHILD_OF",
                            "traceID": "9ad022e836cea34c065bafeaae86bb90",
                            "spanID": "66397c1cf6b115cc"
                        }
```

**Comment by ppatierno** [comment]
I have never used RocketMQ, but I would expect to have the spans in the same trace when we are talking about a queue messaging pattern. Producer sends, just one consumer will get the message, process and delete it. Just one trace.
With Kafka, you can have consumers in different consumer groups getting the same message from the topic and also you could re-read the entire stream of events, so re-read the messages. Using one trace will make a mess in this scenarios. Better is having multiple traces (representing the send and receive on their own) but linked together.
I could expect the same if using a messaging system with pub-sub pattern.

**Comment by sweetxiaodai** [comment]
Thanks and close the issue.
