### ISSUE TITLE
OTLP exporters description in the registry is not accurate

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/opentelemetry.io#1793]
**What needs to be changed?**
I noticed that the description used in the OTLP exporter entries (e.g. [the Java one](https://github.com/open-telemetry/opentelemetry.io/blob/e53a8eb454da7ebbb73a5a175e595532a775fb72/content/en/registry/exporter-java-otlp.md?plain=1#L11)) in the registry is not accurate. It says:

> This library allows to export data to the OpenTelemetry Collector using the OpenTelemetry Protocol.

It's not accurate because OTLP exporters also allow sending data to other places outside the collector (e.g., directly to an o11y back-end).

**What is the name + path of the page that needs changed?**
`content/en/registry/exporter-{lang}-otlp`

**Additional context**
I initially spotted and discussed it here https://github.com/open-telemetry/opentelemetry.io/pull/1792#discussion_r984521837

Suggestion: 
@svrnm suggested in the PR above to use something like:

> This library allows to export telemetry data in the OpenTelemetry Protocol (OTLP) format to the OpenTelemetry Collector and OTLP-compliant backends/receivers

**Comment by svrnm** [comment]
@cartermp, thoughts on how this should be phrased?

@joaopgrassi would you be open to fix that for all the OTLP exporters?

**Comment by joaopgrassi** [comment]
@svrnm yes, I can send a PR to fix all the others, once we agree on the sentence.

**Comment by svrnm** [comment]
@joaopgrassi thanks!

@chalin , @cartermp I am also wondering if this would be something we could fix via a short code or other mechanisms? so have that repeated text stored away somewhere

**Comment by cartermp** [comment]
Regarding this proposed sentence:

> This library allows to export telemetry data in the OpenTelemetry Protocol (OTLP) format to the OpenTelemetry Collector and OTLP-compliant backends/receivers

I would propose something similar, just with one word change 🙂 

> This library allows exporting telemetry data in the OpenTelemetry Protocol (OTLP) format to the OpenTelemetry Collector and OTLP-compliant backends/receivers

**Comment by joaopgrassi** [comment]
I open a PR fixing all the registry entries in the upcoming day(s). Feel free to assign this to me if you want :)
