### ISSUE TITLE
Add TypeScript to "Getting Started"

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1799]
Child of #1772

@kaiwalyakoparkar

**Comment by svrnm** [comment]
@kaiwalyakoparkar please comment on this issue so I can assign it to you.

**Comment by kaiwalyakoparkar** [comment]
hey @svrnm 👋 kindly assign this issue to me

**Comment by svrnm** [comment]
Done

**Comment by kaiwalyakoparkar** [comment]
Hey @svrnm can you please tell me the file location I need to update (The previous issue has been been updated hence I lost track of file I need to update

**Comment by svrnm** [comment]
https://github.com/open-telemetry/opentelemetry.io/tree/main/content/en/docs/instrumentation/js/getting-started

Most important one is nodejs. You can do browser as well.

**Comment by kaiwalyakoparkar** [comment]
@svrnm perfect! few more things.
1) The content written on the page is just for nodejs. Do I need to change that to be generic to ts as well?
2) How do I check out if the tab thing is working (The default vs code preview does not render it as tabs)

**Comment by svrnm** [comment]
1. Yes, make sure that it works with TS as well. So if you need additional dependencies then list them. This means also the shell code will need tabbing. 
2. After cloning and pulling the repo on your local machine run `npm run serve`. This will start a local dev copy for you with auto refresh etc.

**Comment by cartermp** [comment]
Done!
