### ISSUE TITLE
Should we have a page for "Other Languages"?

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1807]
There are a few "inofficial" implementations of OpenTelemetry out there, I saw some for perl, haskell, deno, etc.

I am wondering if we should have a page http://localhost:1313/docs/instrumentation/other/ that calls out that opentelemetry is not limited to the languages we have, that the community is open to add further languages and that there are "inofficial" implementations (and we link them, or we add them to the registry and point to that?)

**Comment by cartermp** [comment]
I think so, yes. This is anecdotal, but the company I work for actually has more customers using Haskell + OTel than Rust + OTel even though Haskell is not an officially-supported language!

**Comment by chalin** [comment]
We can always start by listing **all** of the unofficial implementations on the [Instrumentation](https://opentelemetry.io/docs/instrumentation/) page and then promote them progressively to their own language-landing page. 

We might need some (at least minimal) guidelines for deciding which languages get promoted.
The GC might need to be involved? WDYT @austinlparker?

**Comment by svrnm** [comment]
Related: https://github.com/open-telemetry/opentelemetry.io/pull/1922

**Comment by svrnm** [comment]
Also related (Lua): https://github.com/open-telemetry/community/issues/1276

**Comment by svrnm** [comment]
Also related, dart: https://github.com/open-telemetry/community/issues/552#issuecomment-1311135028

**Comment by svrnm** [comment]
perl https://github.com/open-telemetry/community/issues/828

**Comment by trask** [comment]
Julia: https://github.com/open-telemetry/community/issues/898

**Comment by chalin** [comment]
Can this issue be closed @svrnm, now that the "Other languages" page has been published?

**Comment by svrnm** [comment]
yes, we can close this, ty
