### ISSUE TITLE
Consider how best to surface API references for each language

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1808]
Today, if you want to get to an API reference for a language's SDK, we have a link near the bottom of each language's index page on the website if there's something to link to. Example: https://opentelemetry.io/docs/instrumentation/js/#further-reading

While this technically fulfills the need to link to this kind of material, it's not terribly discoverable despite being fairly important for anyone doing manual instrumentation.

Instead, we should figure out a way, for each language, to make the API reference more prominent so that end-users can more easily find them.

It is not currently a goal to host or design a given language's API reference. If a SIG would prefer us to design and host their API docs we can consider what that may look like, but given that most languages have ways to generate reference docs themselves, and end-users often expect reference material to look a certain way (e.g., Java developers and javadoc), this is out of scope for now.

---

**Edit** (@chalin and @cartermp)

- [ ] Collector?
- [x] C++ - #1928
- [x] Erlang/Elixir: https://github.com/open-telemetry/opentelemetry.io/pull/1943
- [x] Go
  - [x] https://github.com/open-telemetry/opentelemetry-go/pull/3280
  - [x] Merge in updated Go content-module - #1882
- [x] Java API: - #1859
- [x] JS: https://github.com/open-telemetry/opentelemetry.io/pull/1936
- [x] Python: 
  - [x] #1934
  - [x] #1946
- [x] Ruby: https://github.com/open-telemetry/opentelemetry-ruby/pull/1394
- [x] .NET: https://github.com/open-telemetry/opentelemetry.io/pull/1947
- [x] Link-checker ignore-path regex for placeholder pages across language SIGs: #1950

**Comment by chalin** [comment]
This is how I set things up on grpc.io:

- Each language menu has an (external) **API** reference link (Dart language shown in the screenshot).
- There is also a link to the **API** reference in the language's landing page -- in particular because the side-nav doesn't appear by default on mobile.

> <img width="800" alt="gRPC.io Dart API" src="https://user-images.githubusercontent.com/4140793/194089720-d9b19bd0-e136-435a-a3c9-b659b1e6f170.png">

Would that work for y'all?

**Comment by cartermp** [comment]
Yes, that would be great I think! Will let @svrnm weigh in, though.

**Comment by chalin** [comment]
Can you provide links to the API references for the various languages here? Or should they be relatively easy to find?

**Comment by svrnm** [comment]
Let's go with the GRPC way of doing things, I like that. Here are some languages:

# JavaScript
JavaScript API: https://open-telemetry.github.io/opentelemetry-js-api/
JavaScript SDK: https://open-telemetry.github.io/opentelemetry-js/

# Java
(not sure if this is something official)
https://javadoc.io/doc/io.opentelemetry

# python
https://opentelemetry-python.readthedocs.io/en/latest/#

# c++
https://opentelemetry-cpp.readthedocs.io/en/latest/

# rust
https://docs.rs/opentelemetry_api/latest/opentelemetry_api/

**Comment by cartermp** [comment]
Sorry @chalin, this was on my TODO list. @svrnm has the list in the comment.

**Comment by chalin** [comment]
Does the collector have API reference docs?

**Comment by chalin** [comment]
@cartermp - for .NET, which link should be used for the **API reference**?

**Comment by cartermp** [comment]
So there's at least two places to link people to:

System.Diagnostics, of which a subset is related to OpenTelemetry (there is no opentelemetry subnamespace): https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics?view=net-6.0 (the history here is that the abstractions in this namespace predate opentelemetry, and so they have been repurposed for several reasons)

System.Diagnostics.Metrics, which is a namespace for metrics: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics?view=net-6.0

I am not sure if/where there is an API reference for the _SDK APIs_ like `Sdk.CreateTracerProvider`. @cijothomas would you be able to help here?

**Comment by cijothomas** [comment]
_if/where there is an API reference for the SDK APIs like Sdk.CreateTracerProvider_

Not available. Not the one like what we have for the API (Sytem.Diagnostics)

**Comment by cartermp** [comment]
I will close this for now. Collector API is indeed an open question, but also not independent of several other collector docs.
