### ISSUE TITLE
Create Vendor support page

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#182]
See https://github.com/open-telemetry/opentelemetry-specification/pull/594 for ongoing discussion about what the different support levels are.

**Comment by josemaia** [comment]
Is this supposed to go in https://opentelemetry.io/vendors/? It felt weird to me to click that link and see a blank page, considering, for example, the recent AWS release. Maybe add a placeholder there?

**Comment by austinlparker** [comment]
There is a stub page there but since I didn't convert it to the new format the text is hidden under the navbar, whoopsie. 🙃
