### ISSUE TITLE
Update Docker Instructions for Collector Getting Started to contain contrib and core in both cases

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1823]
The [getting started instructions for docker](https://opentelemetry.io/docs/collector/getting-started/#docker) right now distinguish between dockerhub & ghcr.io, for dockerhub the core collector is used, for ghcr.io the contrib is used, that's confusing. 

Although we plan to revamp that page entirely a good quick fix would be the following:

## Docker

Some that that there are different images

### from Dockerhub

use tabbing for core & contrib

### from ghcr.io

use tabbing for core & contrib

**Comment by SedemQuame** [comment]
Hi @svrnm I want to work on this can you assign it to me?

**Comment by svrnm** [comment]
sure! @SedemQuame

**Comment by SedemQuame** [comment]
Hi @svrnm
I just made the change, have a look at the image below and let me know what you think.
![7B442FE5-2DC2-49F8-962F-89151CFE2F31](https://user-images.githubusercontent.com/30062164/196857212-e650170a-eaac-4e1f-ba86-f9f3d2844355.jpeg)

**Comment by svrnm** [comment]
thank you @SedemQuame , let's discuss on the PR (https://github.com/open-telemetry/opentelemetry.io/pull/1885)

**Comment by svrnm** [comment]
this is not an issue anymore
