### ISSUE TITLE
Resources doc - reconsider use of service.name in example

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1830]
See here: https://github.com/open-telemetry/opentelemetry.io/pull/1795#discussion_r985571727

It's more likely that someone setting a service name will do so with the `OTEL_SERVICE_NAME` attribute, or in code, than just as a key-value pair. I would propose that we just put another example there, or remove it.

**Comment by geekrypter** [comment]
Hi @cartermp @svrnm, I would like to work on this issue! I am new to the Open Telemetry community and would like to start contributing!

**Comment by svrnm** [comment]
> Hi @cartermp @svrnm, I would like to work on this issue! I am new to the Open Telemetry community and would like to start contributing!

happy to hear that @geekrypter! If you think you know what needs to be done from the issue description, go ahead and raise a PR with us, we can help you from there. If you have any questions on the issue and what needs to be done upfront, just let us know, either here, in the slack channel (CNCF slack, #otel-comms) or in one of our meetings

**Comment by svrnm** [comment]
@geekrypter, thanks!

1. Remove it and add a few words about `OTEL_SERVICE_NAME` to set it
2. Raise one PR per language. Start with the language you feel comfortable with, we make this one good and then you can raise follow up PRs with the other languages.

**Comment by geekrypter** [comment]
Thanks for the clarification @svrnm! Working on the issue.
