### ISSUE TITLE
All schema files are returning 404

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry.io#1846]
**What happened?**
The schema file URLs that used to work are now returning 404. E.g. https://opentelemetry.io/schemas/1.7.1 or https://opentelemetry.io/schemas/1.14.0

**What did you expect would happen?**
It should be a 200 and return the content of relevant file from https://github.com/open-telemetry/opentelemetry-specification/tree/main/schemas

**What is the name + path of the page where you encountered the issue?**
`https://opentelemetry.io/schemas/*`

**What browser, OS, and platform were you using when you encountered the problem?**
Chrome Version 105.0.5195.125 (Official Build) (x86_64), Mac OS 12.5

**Comment by tigrannajaryan** [comment]
@open-telemetry/docs-approvers can someone help with this? I am not sure when exactly did we break this.

**Comment by tigrannajaryan** [comment]
The publishing of schema files was previously automated in https://github.com/open-telemetry/opentelemetry.io/pull/715

**Comment by cartermp** [comment]
@chalin would have the most context here.

**Comment by svrnm** [comment]
1.4.0 and 1.5.0 seem to work, so it looks like something broke with 1.6.0

**Comment by svrnm** [comment]
ok. the following versions work:

 1.10.0   1.11.0   1.12.0  1.4.0   1.5.0   1.6.1   1.7.0  1.8.0   1.9.0

**Comment by svrnm** [comment]
looks like the spec version has not been upgraded for 1.13 and 1.14. git submodule version is at `ae87c81640d18763d4df51b898c55c49e2370328`, which is 1.12

**Comment by tigrannajaryan** [comment]
@svrnm will you fix it or want me to take a look at this?

**Comment by svrnm** [comment]
> @svrnm will you fix it or want me to take a look at this?

I tried it but tbh my git skills are not advanced enough: I tried to pull the 1.14 commit in the Submodule and not HEAD but couldn’t figure it out 

So if you know how that would be appreciated

**Comment by tigrannajaryan** [comment]
Let me try.

**Comment by chalin** [comment]
Hi all. I'll be back at my desk in about 15 min. I can give it a try then if you'd like. Let me know.

**Comment by chalin** [comment]
Ok, back. Btw, there are some extra issues to be dealt with -- see #1495. I can address all of those in one go.

**Comment by tigrannajaryan** [comment]
> Ok, back. Btw, there are some extra issues to be dealt with -- see #1495. I can address all of those in one go.

Please do and ping me when done so that I can re-run the verification job on the spec repo: https://github.com/open-telemetry/opentelemetry-specification/pull/2868

**Comment by chalin** [comment]
@tigrannajaryan - I'm on it. The spec has changed, resulting in broken links, so I'm fixing that now.

**Comment by chalin** [comment]
@tigrannajaryan et al.: the PR is ready for review

- #1851

**Comment by chalin** [comment]
> The schema file URLs that used to work are now returning 404. E.g. https://opentelemetry.io/schemas/1.7.1 or https://opentelemetry.io/schemas/1.14.0

@tigrannajaryan - I don't see any 1.7.1 schema under https://github.com/open-telemetry/opentelemetry-specification/tree/main/schemas. Did you mean 1.6.1?

**Comment by chalin** [comment]
The new spec is live. If you would like any further changes, let me know and I'll include them in a followup PR.

**Comment by chalin** [comment]
> The publishing of schema files was previously automated in #715

To clarify: the schema files get published once the spec content-module is updated. The update of the spec isn't automated since it usually requires manual intervention, such as fixing broken links into the spec pages.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan - I don't see any 1.7.1 schema under https://github.com/open-telemetry/opentelemetry-specification/tree/main/schemas. Did you mean 1.6.1?

My mistake. I was looking for a schema that never existed.
