### ISSUE TITLE
Adding sub menu to collector docs.

### ISSUE THREAD

**Issue by Chinwendu20** [open-telemetry/opentelemetry.io#1874]
Please I  am currently working on this issue https://github.com/open-telemetry/opentelemetry-collector/issues/5675

I would like to work on the third checklist. Could anyone please direct me to where the file for effecting this change is. I am not so familiar with Hugo's architecture

**Comment by svrnm** [comment]
make a fork of this repo, clone the code to your local working machine, run `npm install` & `npm run serve` to have a local working version of opentelemetry.io

The files you are looking for are most likely at content/en/docs/collector

**Comment by Chinwendu20** [comment]
Thank you so much @svrnm. I checked out that folder and it seems to have only the content of the website. I would like to create a sub-menu that would encompass, thepost for creati n a trace reciever and creating a custom authenticator as per the issue raised in the referenced collector repo. I have cheked the layout directory but I cannot seem to find where the side menus are:

![image](https://user-images.githubusercontent.com/59079323/197125270-a46055b7-f435-43d6-83a3-237302aaeddb.png)

**Comment by svrnm** [comment]
Side Menus are auto generated for you, all you need to do is creating that file.

**Comment by svrnm** [comment]
@Chinwendu20 is this still relevant?

**Comment by Chinwendu20** [comment]
Heyy @svrnm. Incredibly grateful for all the help you have offered me so far. The issue is still open on the collector's repo, so I guess it is still relevant. Right now, I am a bit tight for time and limited in my knowledge of Hugo to work on this right now

**Comment by svrnm** [comment]
> Heyy @svrnm. Incredibly grateful for all the help you have offered me so far. The issue is still open on the collector's repo, so I guess it is still relevant.

Sure! Just wanted to check in, so let's keep this open

**Comment by svrnm** [comment]
@Chinwendu20 is this still relevant?

**Comment by cartermp** [comment]
I think this can be closed because the custom components folder exists now.
