### ISSUE TITLE
Add a section to CONTRIBUTING.md about writing/styling guidance

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1890]
Via SIG meeting, Oct, 20th:

* Add a section to the CONTRIBUTING.md, start with a list and extend it and if outgrows then we can look for alternatives
* When to use bold, cursive, inline-code with backticks, capitalization, etc. 
* Google style guide (informally followed):  [Google developer documentation style guide](https://developers.google.com/style/)
* Best-effort style guide

**Comment by melbgirl** [comment]
I can take this one, can someone assign it to me?

**Comment by cartermp** [comment]
@melbgirl done!

**Comment by windsonsea** [comment]
Good job. It's helpful to me 👍

**Comment by theletterf** [comment]
I'd be happy to take this one if folks are no longer up to it.

**Comment by svrnm** [comment]
> I'd be happy to take this one if folks are no longer up to it.

Sure!
