### ISSUE TITLE
Broken link in collector configuration docs

### ISSUE THREAD

**Issue by maksim77** [open-telemetry/opentelemetry.io#1899]
**What needs to be changed?**
At the very beginning of the article about the collector configuration there is a link to a non-existent file:
```markdown
[Security
  guidance](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security.md)
```

**What is the name + path of the page that needs changed?**
`content/en/docs/collector/configuration.md`

**Comment by svrnm** [comment]
this has been fixed a while ago
