### ISSUE TITLE
Link to privacy policy in footer is broken

### ISSUE THREAD

**Issue by raunaqgupta** [open-telemetry/opentelemetry.io#1918]
**What happened?**
Link to privacy policy: https://www.linuxfoundation.org/en/privacy/#:~:text=The%20Linux%20Foundation%27s%20core%20purpose,%2C%20a%20“Project”%29.&text=The%20Privacy%20Policy%20does%20not,employees%20or%20other%20TLF%20personnel. does not exist

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/623670/197941096-4597dced-0a0f-4384-94fe-5f9125d08ced.png">

**What did you expect would happen?**
Privacy policy link should take the user to: https://www.linuxfoundation.org/legal/privacy-policy

**What is the name + path of the page where you encountered the issue?**
Homepage: https://opentelemetry.io

**What browser, OS, and platform were you using when you encountered the problem?**
MacOS + Safari

**Comment by svrnm** [comment]
Oh, thanks! @raunaqgupta

**Comment by svrnm** [comment]
do you want to provide a PR for it?
