### ISSUE TITLE
Top-level docs entry-point --- coming from jaeger, zipkin, opentracing, opencencus

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1919]
We can probably break this into separate issues over time, but something that seems to come up often is people already have some older instrumentation from jaeger, zipkin, opentracing, or opencensus. How should they adopt opentelemetry?

I would propose that we have a new top-level entry point, or 2nd-level one: something to the effect of, "I already have instrumentation in $TECHNOLOGY", where $TECHNOLOGY is one of the ones listed.

There's really two paths for them: interoperate or replace.

To interoperate, your path will most likely involve the collector.  You instrument new services with opentelemetry and then set up a receiver for your existing services in the collector.

To replace, I would propose it's similar. Set up a receiver and then rewrite their instrumentation piecemeal, one service at a time.

The other thing to consider is version compatibility. Very old versions of Jaeger instrumentation would need to be upgraded to a minimum version to work with a receiver. Are there other versions involved?

**Comment by cartermp** [comment]
Yeah, we'd need to have one for jaeger at least, but ideally all of them.

I think that doc needs work as well since it doesn't involve the collector. But it's a good place to start.

**Comment by svrnm** [comment]
Maybe https://opentelemetry.io/docs/migration/ could have some of that generic info you mentioned:

> There's really two paths for them: interoperate or replace.
> To interoperate, your path will most likely involve the collector. You instrument new services with opentelemetry and then set up a receiver for your existing services in the collector.
> To replace, I would propose it's similar. Set up a receiver and then rewrite their instrumentation piecemeal, one service at a time.

**Comment by cartermp** [comment]
I think I'm gonna close this one out. We probably don't need it now that so many people are coming from OTel and there's enough bridges.
