### ISSUE TITLE
Improve links in OpenTelemetry Demo now Generally Available! Blog post 

### ISSUE THREAD

**Issue by saurabhdes** [open-telemetry/opentelemetry.io#1923]
1. Update vendor link to - https://github.com/open-telemetry/opentelemetry-demo#demos-featuring-the-astronomy-shop vs. https://github.com/open-telemetry/opentelemetry-demo#demos-featuring-online-boutique
2. Update docs link to - https://github.com/open-telemetry/opentelemetry-demo/tree/main/docs#opentelemetry-demo-documentation vs. https://github.com/open-telemetry/opentelemetry-demo/tree/main/docs

for more accuracy. The current links (listed in below image) do work but are not accurate enough in my opinion.
<img width="1121" alt="Screen Shot 2022-10-26 at 9 25 48 AM" src="https://user-images.githubusercontent.com/47896520/198085640-31eba227-63c4-4451-9875-48bf2289f20e.png">

@austinlparker - Wanted to get your thoughts as you authored above blog. If you think it makes sense then i can create a PR with updated links for review.

**Comment by cartermp** [comment]
@saurabhdes would you like to make a PR with these changes? I think they're better links to use indeed, and would love your contribution! 🙂

**Comment by saurabhdes** [comment]
thanks @cartermp ! Will create a PR.
