### ISSUE TITLE
Create a glossary page

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry.io#193]
Distributed Tracing and OpenTelemetry have their own set of definitions for words used elsewhere, and people are often confused about their meaning. We are also starting to have acronyms and there doesn't seem to be a place with their definitions. There is a page with a [glossary for terms used in the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/glossary.md), so, not sure it's suitable for the general audience.

I would then suggest creating a glossary page on the website, with definitions for:

- Tracing
- Tracer
- Trace
- Span
- Tags
- Events
- Sampling
- Exporter
- Receiver
- OTLP
- Tracing vs. Metrics vs. Logging
- Context propagation

**Comment by austinlparker** [comment]
Great idea! Adding this to the milestone for GA.
