### ISSUE TITLE
Move Go and Ruby docs into this repo

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1935]
Phase one: @cartermp talks to some maintainers in-person at kubecon, because face to face communication is awesome
Phase two: @cartermp files issues in each repo and offers to attend SIG meetings to discuss stuff

**Comment by chalin** [comment]
Progress:

- https://github.com/open-telemetry/opentelemetry-ruby/issues/1395

**Comment by svrnm** [comment]
anything on go?

**Comment by cartermp** [comment]
Not yet, I managed to get time off my calendar for the slot so I'll attend this week and propose

**Comment by svrnm** [comment]
> Not yet, I managed to get time off my calendar for the slot so I'll attend this week and propose

thank you! for whatever reason I was assuming that we moved them already, happily edited the docs and then figured out we didn't while preparing my PR ;-)

**Comment by chalin** [comment]
@cartermp - any update on the Go team? It's been 3 weeks and the following PR still hasn't been approved and merged:

- https://github.com/open-telemetry/opentelemetry-go/pull/3585

**Comment by chalin** [comment]
Status update @cartermp?

**Comment by chalin** [comment]
@cartermp - any update from the Go team?

**Comment by cartermp** [comment]
I haven't pushed the issue yet. Been too busy myself.

**Comment by chalin** [comment]
FYI, we have one positive response so far to:

- https://github.com/open-telemetry/opentelemetry-go/issues/4214
