### ISSUE TITLE
Set up bot for spec and collector contrib version bumps upon a release

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1963]
Do what we do with the java instrumentation.

**Comment by trask** [comment]
related: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/196 and https://github.com/open-telemetry/opentelemetry.io/pull/1838

**Comment by cartermp** [comment]
@svrnm took care of the collector bit and it works as per here: https://github.com/open-telemetry/opentelemetry.io/pull/2056

**Comment by chalin** [comment]
@cartermp - how about considering this closed by:

- #2351

We can open a separate issue for the spec, asking the spec folks if that's what they'd want. If so, handling the spec will be different (because we need to sync a submodule) from handling just a version update.

**Comment by cartermp** [comment]
Yep, let's consider it closed for now.
