### ISSUE TITLE
Add (more) guidance on blog writing

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1964]
New guidance as discussed during the 11/03 Comms meeting. For details, see [OpenTelemetry Communications SIG](https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY/edit#) meeting notes.

**Comment by theletterf** [comment]
I think we addressed this one already through the new contributing section?

**Comment by chalin** [comment]
Yes, I'm willing to consider this one as done, thx.
