### ISSUE TITLE
GH actions / cron jobs should not be run for forks

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2006]
Cron jobs should run only if executed from the https://github.com/open-telemetry org using a conditional something like the follow: `if: ${{ github.repository_owner == 'open-telemetry' }}`. This avoids issues with GH actions failing for various reasons when run from forks. WDYT @svrnm et al.?

**Comment by svrnm** [comment]
> Cron jobs should run only if executed from the https://github.com/open-telemetry org using a conditional something like the follow: `if: ${{ github.repository_owner == 'open-telemetry' }}`. This avoids issues with GH actions failing for various reasons when run from forks. WDYT @svrnm et al.?

I agree, that we should add some kind of rule like that, only downside is that if someone wants to improve the job the testing has to happen here **or** this needs to be updated while working on it and re-updated before committing, but maybe something like  `if: ${{ github.repository_owner == 'open-telemetry' || github.repository_owner == 'forked-repo-I-work-on-e.g.-svrnm' }}`

Let me look into that.
