### ISSUE TITLE
When i run the Opentelemetry i was facing the bellow issue

### ISSUE THREAD

**Issue by gauravesds** [open-telemetry/opentelemetry.io#2018]
Notice: Scope: missing call to Scope::detach() for scope #9, created at OpenTelemetry.Context.Context.activate(Context.php:86) at OpenTelemetry.API.Trace.Span.activate(Span.php:51) at {main}(GettingStarted.php:24) in C:\xampp\htdocs\openTelemetry\vendor\open-telemetry\opentelemetry\src\Context\DebugScope.php on line 63

Notice: Scope: missing call to Scope::detach() for scope #35, created at OpenTelemetry.Context.Context.activate(Context.php:86) at OpenTelemetry.API.Trace.Span.activate(Span.php:51) at {main}(GettingStarted.php:28) in C:\xampp\htdocs\openTelemetry\vendor\open-telemetry\opentelemetry\src\Context\DebugScope.php on line 63
OpenTelemetry welcomes PHP
Fatal error: Class has been replaced by Contrib\Otlp\SpanExporter + Transports in C:\xampp\htdocs\openTelemetry\vendor\open-telemetry\opentelemetry\src\SDK\Common\Dev\Compatibility\BC\OtlpExporter.php on line 19

**Comment by svrnm** [comment]
@open-telemetry/php-approvers please give this a look

**Comment by svrnm** [comment]
@gauravesds I recommend that you reach out to the PHP SIG either via CNCF slack at #otel-php or by raising the same question at https://github.com/open-telemetry/opentelemetry-php/discussions

**Comment by theletterf** [comment]
Technical question. Closing.
