### ISSUE TITLE
Add serverless documentation for more languages and serverless providers

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2021]
With [js/serverless](https://opentelemetry.io/docs/instrumentation/js/serverless/) we have a first documentation for the use of OpenTelemetry with lambda. As a next step we should have this replicated for other languages and other serverless/faas providers (gcp, azure, knative, etc.)

**Comment by Gaurang-Patel** [comment]
Hi @svrnm In the case of java should we move the below doc to this repo?
https://github.com/open-telemetry/opentelemetry-lambda/blob/main/java/README.md

**Comment by svrnm** [comment]
> Hi @svrnm In the case of java should we move the below doc to this repo? https://github.com/open-telemetry/opentelemetry-lambda/blob/main/java/README.md

@Gaurang-Patel that would be great, are you open to take this up?

**Comment by Gaurang-Patel** [comment]
yes, @svrnm I'll raise pr for the same.

**Comment by FeliciaSephodi** [comment]
Hi, I'd like to work on this.

**Comment by svrnm** [comment]
hey @FeliciaSephodi, thanks for your interest in helping with this issue! What language/faas provider would you be interested in tackling?

@open-telemetry/lambda-extension-approvers @cartersocha @open-telemetry/docs-approvers please take a look as well, if/how to proceed here.
