### ISSUE TITLE
Add a new persona: Software Architect

### ISSUE THREAD

**Issue by soft4rchitecture** [open-telemetry/opentelemetry.io#2045]
The architect must be able to know what opentelemetry does, and what's the architecture of the solution, so that he knows how it fit into a broader infrastructure.
The software Architect seems to need to know parts of the dev persona and parts of the ops  persona, but not everything.

**Comment by cartermp** [comment]
Hmm. If someone in this role needs to know both of those parts, should they not be able to read both and then understand what they will get out of adopting OpenTelemetry?

**Comment by soft4rchitecture** [comment]
Well, the whole point is that they don’t need the degree of details each rôle require by itself. They wont waste time telling the good from the bad, the details from the overall 
Rather a relevant architectural snapshot of this project, like… a getting started for the architect

**Comment by cartermp** [comment]
I've never worked with a software architect before, so I'm afraid I don't quite understand the need here. OpenTelemetry isn't really a component you drop into a system that you can neatly fit into any kind of useful architecture diagram. There are components to it, like the collector and k8s operator, that could potentially fit the bill there. But it's also a collection of SDKs and ecosystem of libraries that aren't even a part of the same github organization. So I'm not sure what kind of things an architect would need to see to be able to understand if it's a good fit for them. Could you elaborate in a little more detail what you'd look for when in that role?

**Comment by svrnm** [comment]
Stalled issue, closing this now, please follow up if needed @soft4rchitecture
