### ISSUE TITLE
Fill remaining JS Metrics docs gaps

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#2052]
The following concepts still need to be documented with working code samples and good commentary:

- [x] observable counter
- [x] observable updowncounter
- [x] observable gauge
- [ ] views

You can also use this as a guide, at least for Views: https://github.com/open-telemetry/opentelemetry-js/blob/main/doc/metrics.md

**Comment by Omkar-Waingankar** [comment]
Hi! I'd like to take on this issue - it will be my first across any OTEL github repo. I am very familiar with the Go SDK and have instrumented several micro-services at my startup with OTEL - this will be my first time looking at the JavaScript docs though.

**Comment by Omkar-Waingankar** [comment]
Should the code samples be added inline in metrics.md?

**Comment by cartermp** [comment]
@Omkar-Waingankar Thanks for offering! Code samples should be added inline, yes.

What I did with the first cut was:

* Use this as a bit of a reference: https://github.com/open-telemetry/opentelemetry-js/blob/main/doc/metrics.md (it has various gaps but it's a good point of reference)
* Build a sample app and tweak/document/tweak/document

I found the observable instruments ...difficult. Not necessarily difficult to use, but their behavior was confusing to me (e.g., being able to decrease a value in an observablecounter) and the spec wasn't entirely clear either. So it's worth a shot, but if you find yourself treading water then we can bubble it up to others.

**Comment by Omkar-Waingankar** [comment]
Thanks for the tips!

**Comment by Omkar-Waingankar** [comment]
https://github.com/open-telemetry/opentelemetry.io/pull/2144
^I've made a PR here, but I'm not sure how to link it to this issue

**Comment by Omkar-Waingankar** [comment]
@cartermp I've pushed a new set of updates to the PR above, where I address some comments from other contributors and add a section on views

**Comment by domdomegg** [comment]
Can we add tracking for Metric and Log Exporters - currently missing from https://opentelemetry.io/docs/instrumentation/js/exporters/

**Comment by svrnm** [comment]
> Can we add tracking for Metric and Log Exporters - currently missing from https://opentelemetry.io/docs/instrumentation/js/exporters/

Sure, this would be a worthwile addition

**Comment by svrnm** [comment]
I am closing this now due to the restructuring of the docs, see #5690

This might be still needed later on, so we can reopen or raise it again
