### ISSUE TITLE
Traces

### ISSUE THREAD

**Issue by jlderidder** [open-telemetry/opentelemetry.io#2065]
It is not clear in this documentation how to discriminate between "trace context", "span context" and "baggage."  Could you please provide explicit differentiation - or else call out which terms are synonymous, and what is the preferred term?

**Comment by cartermp** [comment]
Hello @jlderidder, which documentation are you referring to? We do describe each as independent in these pages:

https://opentelemetry.io/docs/concepts/signals/traces/#trace-context
https://opentelemetry.io/docs/concepts/signals/traces/#span-context
https://opentelemetry.io/docs/concepts/signals/baggage/

The phrase "context" may be overloaded a bit here and I don't think we've cross-linked everyhwere we'd like, though.

Stepping back a bit - is there a particular scenario you're after, and is it confusing which _thing_ is best-suited towards your scenario?

**Comment by jlderidder** [comment]
Thank you for reaching out.
We're trying to clarify our terminology around telemetry at my company, and
I am unable to tell the difference between these.
It appears that they are all information about the event in a span, that is
then shared to provide context.

"Trace Context is metadata about trace spans that provides correlation
between spans across service and process boundaries."
"Baggage refers to contextual information that's passed between spans.
" (appears
to be the same as above)
And Span Context just tells me what's in there, not what it is, though it's
clearly contextual information.

Do you have any definitions that clearly delineate the difference between
these?  Or are the terms simply interchangeable?

Thanks!
--jody

**Comment by cartermp** [comment]
Thanks for the context! I'll see if I can get some docs updates queued up to clarify. For now:

* Baggage a bag of key:value pairs, but its job is to actually propagate arbitrary metadata across services/process/etc. And so if you capture data in ServiceA and want to also have it be present in ServiceB (for whatever reason) it's a way to that.
* Span Context is an object that sits on each span that stores the trace ID, ID of the span it's for, and some other minor information. This is the data that is used to tell which spans are a part of the same trace, and it's propagated across service/process boundaries. The data in here is how tracing "works", basically, and it's not something you use yourself to store data into.

"Trace Context" is referring to the Context object, which is itself also an object that contains some key:value pairs, including data about what the "current/active span" is. While you can technically also use it to inject other data and propagate it, it's not _really_ designed for that and instead you should use Baggage. There are several propagation formats that OpenTelemetry supprts; the defualt (W3C), B3 (from zipkin), and any other arbitrary format that you have a propagator for. In general it's useful to just think of this as "how stuff works behind the scenes".

I think there's some things here that are confusing and worth a docs update. I'll see what I can do.

**Comment by jlderidder** [comment]
Thank you very much!  I look forward to more clarity.
It sounds as if:

   - Span Context simply is used to associate and order/track the Spans
   within a Trace;
   - Trace Context  may include information about contained Spans (such as
   which is active), but is about the Trace itself, which allows tracking of
   interactions across multiple services/processes;
   - Baggage contains other metadata that needs to be carried across
   service/process boundaries to provide context and usability.


Am I close?
--jody

**Comment by cartermp** [comment]
Yes, that's fairly accurate.

**Comment by jlderidder** [comment]
Thank you!

**Comment by jlderidder** [comment]
Please be sure to include this page in your updates.   https://opentelemetry.io/docs/concepts/signals/baggage/

It states "Baggage refers to contextual information that’s passed between spans" ... "In OpenTelemetry, 'Baggage' refers to contextual information that’s passed between spans. It’s a key-value store that resides within a trace context, making values available to any span created within that trace."

This is clearly the same definition as the one you say is "fairly accurate" for span context.  It's very confusing.  Thank you for sorting this out.
