### ISSUE TITLE
Manual Instrumentation

### ISSUE THREAD

**Issue by LoPan455** [open-telemetry/opentelemetry.io#2073]
In the [Setup ](https://opentelemetry.io/docs/instrumentation/java/manual/#setup) example code snippet, there is a reference to `ResourceAttributes.SERVICE_NAME`.  Since this comes from a package outside of the API and SDK packages, it would be helpful to know that this static function came from the Semantic Conventions (semconv) package.

**Comment by svrnm** [comment]
is #2030 fixing that?

**Comment by LoPan455** [comment]
Yes, looks like it.  Thank you for pointing it out.  I'll close out this issue.
