### ISSUE TITLE
Semantic conventions for hardware metrics appears blank

### ISSUE THREAD

**Issue by bertysentry** [open-telemetry/opentelemetry.io#2079]
Page https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/hardware-metrics/ is rendered as an empty page:
![image](https://user-images.githubusercontent.com/32521698/205900485-b71bc282-48a6-4033-9142-6c78c54d8e70.png)

Content that is expected: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/hardware-metrics.md

**Comment by svrnm** [comment]
@chalin when you're back can you give this a look? thanks

**Comment by chalin** [comment]
Addressed by #2109, PTAL.
