### ISSUE TITLE
Use of outdated collector API version in documentation

### ISSUE THREAD

**Issue by Chinwendu20** [open-telemetry/opentelemetry.io#2090]
I can see the documentation is based on version 0.53 of the collector API. I have opened this issue to discuss if the documentation should just reflect the latest version of collector API or better still there should be documentation for every collector release.

**Comment by cartermp** [comment]
In general I think the docs should use only the latest APIs. Right now the collector is still (technically) pre-release, and so we can expect any number of further breaking changes to the API until such a time that it's considered stable. Since those older APIs won't be supported, it's not worth documenting how to use them.

**Comment by svrnm** [comment]
> I can see the documentation is based on version 0.53 of the collector API.

where do you see use of 0.53 collector? We try to auto-update the collector versions on release, so if the version is hardcoded somewhere we should fix that.

**Comment by svrnm** [comment]
thanks, we will need to take the collector version variable we have in the getting started and use it in that page as well

**Comment by chalin** [comment]
We should avoid duplicating version info. I've updated the following umbrella issue with proposed solutions:

- #1194

**Comment by svrnm** [comment]
> We should avoid duplicating version info. I've updated the following umbrella issue with proposed solutions:
> 
> * [Create and use a config/section parameter for release versions for each language + collector #1194](https://github.com/open-telemetry/opentelemetry.io/issues/1194)

Agreed.

**Comment by chalin** [comment]
I'm going to close this since the problems reported here will be addressed (in part) and/or tracked elsewhere:

- #2260
- #2261
- #2262

If you think that something isn't covered by the items above, comment here.
