### ISSUE TITLE
Error in Trace receiver tutorial

### ISSUE THREAD

**Issue by Chinwendu20** [open-telemetry/opentelemetry.io#2094]
**What needs to be changed?**
Here the interval field was defined as a string:

![image](https://user-images.githubusercontent.com/59079323/207124775-17ac8eeb-61ad-4b97-9882-1228427d7a29.png)

While creating the createDefaultConfig function, a time.Duration type was assigned to that field, this would cause an error:

![image](https://user-images.githubusercontent.com/59079323/207125143-43004af7-c64c-4915-a4aa-686fb899cc48.png)

Proposed solution:
https://github.com/Chinwendu20/Tailtracer/blob/2b0e65243ca9bf4fb71665fc71b1539cde9debc8/factory.go#L14-L21

**Comment by svrnm** [comment]
@Chinwendu20 can you take your proposed solution and turn it into a PR, makes it easier for us to review. Thanks

**Comment by Chinwendu20** [comment]
Okay @svrnm

**Comment by Chinwendu20** [comment]
Trying to submit a PR, after cloning the repo and running an npm install, I get this error:
![image](https://user-images.githubusercontent.com/59079323/208074164-2761da40-1e8b-4859-b825-3ca3b8bd1a34.png)
I have posted this on the slack group, would be grateful for any help that I get

**Comment by svrnm** [comment]
https://cloud-native.slack.com/archives/C02UN96HZH6/p1671184942392839 leaving the discussion on the `npm install` here for reference.

**Comment by chalin** [comment]
I've created a separate issue to track the Windows-only (AFAIK) build problem, so that we can keep this issue focused on it's original topic:

- #2120

**Comment by cartermp** [comment]
I will also consolidate this issue with https://github.com/open-telemetry/opentelemetry.io/issues/1802 -- the issue is ultimately that the APIs are out of date w.r.t. the latest collector framework.
