### ISSUE TITLE
Spec status says "OpenTelemetry instrumentation is scheduled for this summer"

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2108]
Visit the following section of the **Specification status** page https://opentelemetry.io/docs/reference/specification/status/#instrumentation, and you'll see:

> ### Instrumentation
>
> An effort to expand the availability and quality of OpenTelemetry
instrumentation is scheduled for this summer.
> ...

This would seem outdated. Can someone propose some updated text for this section?

/cc @svrnm @cartermp @carlosalberto @tigrannajaryan

**Comment by chalin** [comment]
An option would be to drop that section of the status page.

**Comment by cartermp** [comment]
I would probably vote for dropping.

**Comment by svrnm** [comment]
isn't that an issue that needs to be fixed at the spec and we just copy it over?

**Comment by svrnm** [comment]
> @svrnm - you might recall that the spec status page contains the original content of /status, which was reworked to include the status of more things. So the page is unique to this repo.

oh... makes sense.

Then I agree with @cartermp , let's drop it.
