### ISSUE TITLE
Building a Trace Receiver

### ISSUE THREAD

**Issue by Gauravmeenu** [open-telemetry/opentelemetry.io#2110]
_@cartermp edit:_

_Pulling in from https://github.com/open-telemetry/opentelemetry.io/issues/2111_
> Please update the Trace Receiver Builder document according to @v0.67.0

--

In config.Receiver ( Receiver not declared by package config)

**Comment by Chinwendu20** [comment]
Heyy @Gauravmeenu are you using the latest version of the collector to create a trace receiver?

You could follow my implementation for the most up-to-date (as of v0.66 of the collector API ) implementation of the trace receiver

**Comment by Gauravmeenu** [comment]
Hey thank you much @Chinwendu20 for helping me out , I want to ask you  one more question can you please help me , whenever I am updating the go.sum (of custom colletor) with my tailtracer package my github repo  it willl give me an error like this 

github.com/stretchr/objx: github.com/Gauravmeenu/otel-collector/tailtracer@v0.1.0: reading https://github.com/Gauravmeenu/otel-collector@v0.1.0/github.com/%21gauravmeenu/otel-collector/tailtracer/@v/v0.1.0.mod: 404 Not Found
        server response: Not Found

**Comment by Chinwendu20** [comment]
So if I get you right, you are saying that when you want to include the tailtracer component that you created to the custom distribution that you created you get an error which is this:

github.com/stretchr/objx: github.com/Gauravmeenu/otel-collector/tailtracer@v0.1.0: reading https://github.com/Gauravmeenu/otel-collector@v0.1.0/github.com/%21gauravmeenu/otel-collector/tailtracer/@v/v0.1.0.mod: 404 Not Found
server response: Not Found

Did I get you right?

**Comment by Gauravmeenu** [comment]
Yeah you got the point, but this error will shown when I am updating the go.sum file with my repo package module

**Comment by Chinwendu20** [comment]
You are manually updating your go.sum file?

**Comment by Chinwendu20** [comment]
well, I do not know about manually updating the go.sum file.

**Comment by Chinwendu20** [comment]
Ohh okay as far as I know you can do that without manipulating the go.sum file. Just run this on your command line:

`go get <your trace reciever github url`

Then import in your code or if you have it locally, you could just import it directly. Please if I was not clear or if I am missing anything  let me know

**Comment by Gauravmeenu** [comment]
Hey @Chinwendu20, you didn't create a model.go file in your repository.

**Comment by cartermp** [comment]
Actually, I hadn't realized we already were tracking this here: https://github.com/open-telemetry/opentelemetry.io/issues/1802

@Chinwendu20 if you're still up for contributing updates, refer to that issue when closing it via PR, thanks!
