### ISSUE TITLE
Remove jQuery dependency from registry search

### ISSUE THREAD

**Issue by connorlindsey** [open-telemetry/opentelemetry.io#212]
The registry search currently uses jQuery which could be removed by refactoring the search.js script. Lighthouse lists removing jQuery as a good opportunity to increase our performance scores. I plan to replace any jQuery used with standard JS functions.

I would like to pick up this issue as well if the maintainers could please assign me to it. Thanks!

**Comment by austinlparker** [comment]
Closed by #218, thanks!
