### ISSUE TITLE
Building a custom collector

### ISSUE THREAD

**Issue by TheJacobWalters** [open-telemetry/opentelemetry.io#2147]
The tutorial supplies a configuration file called builder-config.yaml to be used during the tutorial. There is a small error in this configuration that causes the tutorial to not be able to be followed exactly as it is written

specifically there is a line that goes across two lines. The line break needs to be removed
"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter
      v0.64.0"
      
should be      

"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.64.0"

Additionally specifying the otelcol version in the builder configurations would probably be a good idea so that if a user has a version of the otel collector builder that is newer than 0.64.0, there wont be a conflict.

**Comment by TylerHelmuth** [comment]
@TheJacobWalters absolutely

**Comment by chalin** [comment]
Closed by #2148
