### ISSUE TITLE
Best Practices/Guidance omni-issue

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#2152]
This here's a big one. There's a large need for best practices and general guidance in OTel docs. I'll attempt to break it up a bit by category. We can split things up into individual issues as we go.

## General guidance

* What should I start with if I have no instrumentation? (as a developer and an operator)
* What should I start with if I have existing traces, metrics, or logs? (as a developer and an operator)

## Migration guidance

Tracing:

* What should I do when I have existing jaeger instrumentation?
* What should I do when I have existing zipkin instrumentation?
* What should I do when I have existing opentracing instrumentation?
* ...

Metrics:

* Should I migrate from prometheus? Why/why not? In what scenarios does that make sense/not make sense?
* ...

Logs:

* ... (too early today maybe?)

## Integrating with existing telemetry guidance

* What should I do when I have existing prometheus instrumentation?
* What should I do when I have existing statsd instrumentation?

## Language SDK guidance

* When should I use manual instrumentation from an SDK?
* When should I use an opentelemetry collector / when is it fine to just use an SDK?
* How many tracerproviders/tracers should I usually have?
* When would I want more than one tracerprovider or tracer per service? why?
* How many meterproviders/meters should I usually have?
* When would I want more than one meterprovider or meter per service? why?
* How should I generally name attributes?
* What common resources should I usually have enabled?
* Should I configure in code or with env vars? why/why not?

### JS

* ... (specific to JS)

### Java

* When should I use the `@withspan` annotations and other helpers? Why/why not?
* ... (specific to Java)

### Python

* ... (specific to Java)

### .NET

* https://github.com/open-telemetry/opentelemetry.io/issues/2024
* ... (specific to .NET)

### Go

* ... (specific to Go)

### Ruby

* https://github.com/open-telemetry/opentelemetry.io/issues/2022
* ... (specific to Ruby)

### ... (other languages)
...

## Collector guidance

* Why is a collector helpful? (as a developer -- operators probably already get it)
* What distribution should I use?
* What are typical deployment patterns?
* What are common receivers and processors I might consider using?

## Sampling guidance / managing data volume

* What is sampling and why should I do it?
* What are my options today?
* What should I use/not use today?

**Comment by svrnm** [comment]
big plus one!

**Comment by svrnm** [comment]
Just to add this here to find a place & way to represent that content, kubernetes docs have a structure we can learn from/take from:

https://kubernetes.io/docs/home/

[Home](https://kubernetes.io/docs/home/)
[Getting started](https://kubernetes.io/docs/setup/)
[Concepts](https://kubernetes.io/docs/concepts/)
[Tasks](https://kubernetes.io/docs/tasks/)
[Tutorials](https://kubernetes.io/docs/tutorials/)
[Reference](https://kubernetes.io/docs/reference/)
[Contribute](https://kubernetes.io/docs/contribute/)

**Comment by jpkrohling** [comment]
Thank you, @mhausenblas, for pointing me to this issue. I have written and/or know about the following topics and can contribute to this effort:

* What distribution should I use? -- I can write about this
* What are typical deployment patterns? -- https://grafana.com/docs/opentelemetry/collector/#use-cases
* All three items from the sampling area. Other folks can also write about this: hi @reese-lee!
* What should I do when I have existing jaeger/opentracing instrumentation? -- https://medium.com/jaegertracing/migrating-from-jaeger-client-to-opentelemetry-sdk-bd337d796759 . Although @VineethReddy02 is also skilled in this topic.

In addition to that, I authored the following article, which can probably be converted into an upstream document with minimal effort: [How to scale the OpenTelemetry Collector](https://grafana.com/docs/opentelemetry/collector/how-to-scale/)

**Comment by reese-lee** [comment]
Thank you for the mention @jpkrohling! Yes I could help with

- What is sampling and why should I do it?
- What are my options today?

On this one:
- What should I use/not use today?

I'd want to learn more about what we'd recommend/not recommend and the reasonings, and how we want to structure this piece -- e.g., by use case? by maturity? or?

**Comment by svrnm** [comment]
To add a topic I would like seeing:

* Privacy/Data Filtering&Sanitization -- there's a lot to say about this topic, a lot you can make wrong and a lot of things you can already just use.

**Comment by svrnm** [comment]
following up on this, I am also still looking for a place where apache&nginx module can be documented (https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation), it kind of feels odd to put them under Instrumentation > C++

**Comment by svrnm** [comment]
here's a first proposal on how I think we should structure this:

* Language specific guides/best practices should stay within the language
* collector specific guides/best practices should stay within the collector section
* Sampling should become a "concept" page, then there should be a guide on "managing data volume" that talks about sampling and other options
* We introduce a "Guides" section in doc with subsections "Migration", "Integration", "Instrumentation" like the following screenshot:

<img width="281" alt="Screenshot 2023-02-27 at 12 51 15" src="https://user-images.githubusercontent.com/1519757/221556685-a7d2ca84-c37f-4c75-b991-fc0f7297660d.png">

A few open questions: 
* "Guides" might not be the perfect word, leaving this to the native speakers to come up with something good. Maybe we can even do "Guides & Practices"?
* I linked to the k8s documentation for how to enable otel instrumentation with it, not sure if this is a good practice or creates precedence to link to many other places as well
* I am not happy with the titles "Integrations" & "Instrumentations" either because we use the same words at other places as well so it might get confusing?

What do you all think?

**Comment by svrnm** [comment]
This is also discussed (and will hopefully be addressed) via this discussion: https://github.com/open-telemetry/opentelemetry.io/discussions/4475#

if any points of this need to be moved over please add them as a comment to the discussion
