### ISSUE TITLE
Highlight new project roadmap

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2167]
We should highlight the existence of the [project roadmap](https://github.com/open-telemetry/community/blob/main/roadmap.md) via opentelemetry.io, a few things come to mind:

* We could update the banner with it
* Blog post?
* Have an official link somewhere or make a sync of it from the community repo?

**Comment by chalin** [comment]
I'd vote to have the roadmap published via the website.

**Comment by cartermp** [comment]
Agreed.
