### ISSUE TITLE
Consider hosting demo docs on the website and possibly migrating them to this repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2173]
Would it make sense to:

- Host the [demo's docs] on the OTel website?
- Migrate the [demo's docs] to this repo?

WDYT @austinlparker @svrnm @cartermp? This would be in the spirit of:

- #833

/cc @open-telemetry/demo-approvers 

[demo's docs]: https://github.com/open-telemetry/opentelemetry-demo/tree/main/docs

**Comment by austinlparker** [comment]
In the past we've discussed creating a subsection on the website to act as a home for functional demo documentation (versus developer guides)

**Comment by mviitane** [comment]
I like the idea. Currently, the demo docs don't have proper navigation. This new area could make it easier to find and use.

**Comment by cartersocha** [comment]
I am a bit worried about the doc syncing as well. I think it’ll be demo approver / maintainer responsibility to ensure the docs have an open PR too

Could demo approvers / maintainers get approval access on just the demo docs section of the website like we have the Java approvers tied to the ad service?

**Comment by cartermp** [comment]
@cartersocha Yep, you're all set w.r.t. approval already: https://github.com/open-telemetry/opentelemetry.io/blob/main/.github/CODEOWNERS#L33 -- we can adjust however we need should there be a different structure to the docs.

My main concern here would be in docs churn. We've been avoiding documenting some things (e.g., Go Metrics) because the underlying concepts are settled enough to make it worth the effort. If the demo's docs (at least those that are for end user consumption) aren't considered stable yet, or the underlying things they document aren't stable, then I wouldn't want to bring them in at the moment.

**Comment by cartersocha** [comment]
I don’t think I have any doc stability concerns! We have discussed some metric requirements clarifications so I’ll open a PR to fix that asap 

@open-telemetry/demo-approvers thoughts?

**Comment by mviitane** [comment]
I’m not concerned about the docs stability. I think the demo app doesn’t need to become stable in the same way as, for example, SDKs and specification.

**Comment by svrnm** [comment]
Maybe we should consider what parts of the demo docs we want to start migrate over and then see how frequently they are changed. I think the most important ones are concerned with running the demo, maybe a copy of the architecture & the scenarios & a link where&how people can contribute?

**Comment by chalin** [comment]
I'd vote to move the whole lot in one go. It'll be much easier that way.

@svrnm or @cartermp (or anyone else) did either of you want to do the move? If not, I can do it.

If we agree to move the demo docs in one go, then we / @open-telemetry/demo-approvers should probably:

- Merge all pending doc PRs in the demo repo
- Agree on a demo-repo docs freeze date
- I/we can then, as quickly as possible, move the demo docs here
- Then we can adjust relevant demo repo pages to refer to the docs published on the website
- Declare the demo-docs freeze as over

WDYT?

**Comment by cartermp** [comment]
@chalin I agree with your proposal. If you're up for it, go for it!
