### ISSUE TITLE
Automatic Instrumentation

### ISSUE THREAD

**Issue by neroux** [open-telemetry/opentelemetry.io#2184]
https://opentelemetry.io/docs/instrumentation/php/automatic/#setup explains how to use "pickle" to install the extension, but it only briefly mentions "from source code". It would be nice if it stressed that one needs a proper build environment.

**Comment by svrnm** [comment]
@open-telemetry/php-approvers please have a look

**Comment by theletterf** [comment]
Addressed in the PR.
