### ISSUE TITLE
Registry: eliminate entry pages?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2204]
I'd like to propose a little cleanup of the registry before considering a move (#2202). In particular, I'd like to suggest dropping the individual entry pages. Here's an example from https://opentelemetry.io/registry/instrumentation-js-angular:

> <img width="816" alt="image" src="https://user-images.githubusercontent.com/4140793/214694170-3a396c17-5faa-492f-a8ca-b6b2ce24c340.png">

Here is what is displayed on the Registry page for this entry:

> <img width="772" alt="image" src="https://user-images.githubusercontent.com/4140793/214694536-e65ddf5f-79ea-4592-a9a9-69c4666970ed.png">

How useful are the individual entry pages? Analytics show that they are consulted. For example:

- https://opentelemetry.io/registry/collector-exporter-elastic/ accounts for 1.7% of the Registry traffic in the past 6 months, but if you visit it now, this **link is now a 404**
- The Angular JS page referenced abvoe got 1.5% of the Registry traffic.

I'd like to suggest that we drop the individual entries pages. Folks who are interested in an entry, can visit the page/repo that it is linked to from the main Registry page. But I'm open to being convinced otherwise.

Thoughts @cartermp @svrnm @austinlparker

**Comment by svrnm** [comment]
I didn't even know those pages exist 😅

**Comment by chalin** [comment]
That's because the registry doesn't provide a link to them :) ... so very few people will know about these pages.

**Comment by cartermp** [comment]
I would agree with dropping them.
