### ISSUE TITLE
.NET Docs --> pin instrumentation versions to pre-1.4.x?

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#2210]
Hello @open-telemetry/dotnet-approvers - would like some of your guidance. Right now I'd like to stabilize the .NET docs w.r.t. packaging. Today, the code sample here is incorrect due to the changes to hosting: https://opentelemetry.io/docs/instrumentation/net/getting-started/#aspnet-core

But is it right to recommend this path, or use downgraded instrumentation and hosting packages to use a stable version of the base OTel package?

**Comment by cijothomas** [comment]
@CodeBlanch FYI.
We are going to have stable 1.4.0, along with Otel.Ext.Hosting stable pretty soon. (1-2 weeks or less).

We can wait for that (or the final RC before 1.4.0) and update all docs to use that ?

**Comment by cijothomas** [comment]
Unfortunately, no.
https://www.nuget.org/packages/OpenTelemetry/1.4.0-rc.3 was done ~5 days ago only (delayed), and if no issues found with this, we will be releasing stable. The general process is to give 2 weeks bake time after the last pre-release.

However, we can update the docs to use the rc.3 package - https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/AspNetCore/Program.cs this should already be the working code example with rc3.

**Comment by cartermp** [comment]
Can probably close this out now with the latest package updates.
