### ISSUE TITLE
Document python-specific configuration options

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#2214]
Examples:

https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib%20OTEL_PYTHON&type=code
https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib+OTEL_INSTRUMENTATION&type=code

Perhaps more deeper in the code. cc @srikanthccv

**Comment by hortonew** [comment]
I submitted https://github.com/open-telemetry/opentelemetry.io/pull/2664 for this.  @cartermp please let me know if this is sufficient or if you're prefer it in a different location/format.
