### ISSUE TITLE
Host operator docs on website?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2256]
Should https://github.com/open-telemetry/opentelemetry-operator/tree/main/docs be hosted on the OTel website too? Right now it only contains an API page (and #833 only targets non-API pages), but I figured that it would be worth asking the question.

@svrnm @cartermp et al., WDYT?

**Comment by cartermp** [comment]
I would say no for now, I expect that to be more of a developer-of-otel-tools resource, which would probably be more appropriate.

**Comment by chalin** [comment]
Ok. Thanks for the feedback. Closing.
