### ISSUE TITLE
Demo docs: Feature coverage icons

### ISSUE THREAD

**Issue by mviitane** [open-telemetry/opentelemetry.io#2280]
Feature coverage icons are not rendered properly. There should be icons to visualize the feature status. The problem is visible in these pages, using a preview of #2275 

https://deploy-preview-2275--opentelemetry.netlify.app/docs/demo/trace_service_features/
https://deploy-preview-2275--opentelemetry.netlify.app/docs/demo/metric_service_features/

![image](https://user-images.githubusercontent.com/74129181/217174722-b51acf15-4576-4d74-8324-5781368e65ef.png)

**Comment by svrnm** [comment]
looks like github markdown and hugo markdown are different once again, i.e. github markdown allows emoji shortcodes where hugo doesn't. 

I am just wondering what route to go, see if we can get this fixed via a plugin or by replacing those with their utf-8 equivalent or any other way of having such an emoji.

@chalin @cartermp wdyt?

**Comment by cartermp** [comment]
I think I'd prefer a plugin, but I'll defer to @chalin

**Comment by chalin** [comment]
Thanks for reporting the issue @mviitane. I'd vote for working with base hugo (no extra plugin). Let me submit a proposed fix.
