### ISSUE TITLE
Demo docs: Architecture picture fit

### ISSUE THREAD

**Issue by mviitane** [open-telemetry/opentelemetry.io#2281]
The demo architecture picture has quite large spaces around it. The picture would work better with removed extra spaces from the top, bottom, and side (if possible).

Using a preview of https://github.com/open-telemetry/opentelemetry.io/pull/2275
https://deploy-preview-2275--opentelemetry.netlify.app/docs/demo/current_architecture/

![image](https://user-images.githubusercontent.com/74129181/217177755-d8c24294-5e32-4b45-a920-00ce6c34919a.png)

---

Edit(@chalin): link to old repo docs showing the diagram, https://github.com/open-telemetry/opentelemetry-demo/blob/4b8bb4554b8888c712349d26679cca109f4c575e/docs/current_architecture.md

**Comment by svrnm** [comment]
looks like an issue with mermaid, the space comes from the rendered SVG?

**Comment by mviitane** [comment]
One more item to the wish list for the architecture picture: Zoom-in.
The main arch picture contains so much details that a feature to enlarge the picture with one click would be very useful when presenting / screen sharing.

**Comment by chalin** [comment]
Thanks for the continue feedback @mviitane. Yeah, I had seen the issue with the Mermaid-generated image, but didn't find a way to address it on first investigation. I'd dig deeper.

**Comment by chalin** [comment]
Sigh, #2318 doesn't fix it for Safari and Firefox so I'm reopening this.
