### ISSUE TITLE
Document OpAMP

### ISSUE THREAD

**Issue by mhausenblas** [open-telemetry/opentelemetry.io#2282]
**Desired feature or idea.**
As an operator, I'd like to understand what OpAMP is and how to use it. Currently, there is no docs entry.

**Additional context**
In addition to explaining concepts such as agent, supervisor, and server, I think it would be great to show them in action based on the [OpAMP Go example](https://github.com/open-telemetry/opamp-go/tree/main/internal/examples).

This is related to https://github.com/open-telemetry/opentelemetry.io/issues/1701 and @tigrannajaryan offered to review.

**Comment by mhausenblas** [comment]
I volunteer to write that docs entry, feel free to assign it to me @svrnm

**Comment by svrnm** [comment]
That would be awesome @mhausenblas, thanks! We stopped assigning issues, so please just go ahead! :-)

FYI, we had this blog post a while back by @nemoshlag on opamp: https://opentelemetry.io/blog/2022/opamp/, so maybe some of that can be helpful.

**Comment by mhausenblas** [comment]
https://opentelemetry.io/docs/collector/management/ is live now, closing.
