### ISSUE TITLE
Wrong timestamp for span event

### ISSUE THREAD

**Issue by sungam3r** [open-telemetry/opentelemetry.io#2287]
> A Span Event can be thought of as a structured log message (or annotation) on a Span, typically used to denote a meaningful, singular point in time **during the Span’s duration**.

But in example from https://opentelemetry.io/docs/concepts/signals/traces/#tracing-in-opentelemetry timestamp of the second event is greater than `end_time` of the span itself.

![изображение](https://user-images.githubusercontent.com/21261007/217281734-6a74ccb4-6a95-4909-8ce1-19358e27c40d.png)

**Comment by Neilblaze** [comment]
@cartermp Can I take this up? I think replacing the positions of those timestamps will fix the issue. Thanks! :)

**Comment by svrnm** [comment]
@Neilblaze, sure, please go ahead and raise a PR
