### ISSUE TITLE
Demo architecture link broken

### ISSUE THREAD

**Issue by MacNale** [open-telemetry/opentelemetry.io#2317]
**What happened?**
https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/current_architecture.md

returned 404

The link is not accessible from - https://opentelemetry.io/ecosystem/demo/

**Comment by chalin** [comment]
> **What happened?** https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/current_architecture.md
> 
> returned 404

Right, the demo docs were removed from the demo repo, so a 404 is expected. (GitHub doesn't support file redirects.)

> The link is not accessible from - https://opentelemetry.io/ecosystem/demo/

For the demo docs, see:

- https://opentelemetry.io/docs/demo/

For that specific page see:

- https://opentelemetry.io/docs/demo/current_architecture, or it's new canonical path at
- https://opentelemetry.io/docs/demo/architecture

Closing this issue. Feel free to comment if you have further questions.

**Comment by MacNale** [comment]
Shouldnt we fix link here ?

- How do I consider the [architecture](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/current_architecture.md) of a system using OpenTelemetry?

**Comment by chalin** [comment]
Oh, I'm so sorry, I misunderstood. You are right, that link does need to be fixed. Would you be willing to submit a PR, or would you like me to do it?

**Comment by chalin** [comment]
Closed by #2342
