### ISSUE TITLE
Register maintainers for notifications when the production build fails

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2345]
Hey fellow maintainers. Lately the production build has been failing silently, mainly because we've been merging in PRs that were first submitted _before_ CI formatting checks were enabled. This will likely happen again, and it's not a big deal. But it can be a problem if this goes unnoticed for too long (since when the production builds fail, the website doesn't, of course, get updated).

I'd suggest that one or more maintainers register for [Notifications](https://docs.netlify.com/monitor-sites/notifications) when there are build failures. WDYT?

**Comment by chalin** [comment]
Another option, while we continue to ramp up the formatting checks across all website files, would be to require all PRs to be up-to-date w.r.t. `main` before merging.

**Comment by svrnm** [comment]
> Hey fellow maintainers. Lately the production build has been failing silently, mainly because we've been merging in PRs that were first submitted _before_ CI formatting checks were enabled. This will likely happen again, and it's not a big deal. But it can be a problem if this goes unnoticed for too long (since when the production builds fail, the website doesn't, of course, get updated).
> 
> I'd suggest that one or more maintainers register for [Notifications](https://docs.netlify.com/monitor-sites/notifications) when there are build failures. WDYT?

I think we all should get notified, since we have some good timezone coverage, this could help us to fix this quickly. I see that there are "slack notifications", would that be an option (have a private slack space called #otel-website-deployments where we get updated). I would also prefer to only get notifications in a case of an issue.

> Another option, while we continue to ramp up the formatting checks across all website files, would be to require all PRs to be up-to-date w.r.t. main before merging.

It looks like github has a feature for that ( I think most other repos have that enabled ):

> Require branches to be up to date before merging
> This ensures pull requests targeting a matching branch have been tested with the latest code. This setting will not take > effect unless at least one status check is enabled (see below).

Shall we turn that on?

**Comment by cartermp** [comment]
Yep, let's get a notification when it fails. We can always turn it off if it feels too noisy for some reason.

**Comment by chalin** [comment]
FYI, I've registered my email address to receive deploy-failure notifications. I'll let y'all do the same, so you can use an email address of your preference.

I've also turned on the following option for `main`:

> <img width="564" alt="image" src="https://user-images.githubusercontent.com/4140793/220104994-02d02e37-f700-418b-9f9d-ce3f6a3ab7c4.png">

**Comment by chalin** [comment]
I suspect that we can close this now, right @cartermp @svrnm?

**Comment by cartermp** [comment]
yep yep
