### ISSUE TITLE
Python: performance benchmarks link results in 404

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2354]
The following link is no longer valid, so what should it be replaced by @open-telemetry/python-approvers?

https://github.com/open-telemetry/opentelemetry.io/blob/1dbf54f61d59b602add54bf91fe6132aef6a04f8/content/en/docs/instrumentation/python/_index.md?plain=1#L73-L74

**Comment by codeboten** [comment]
Benchmarks results have been disabled as of https://github.com/open-telemetry/opentelemetry-python/pull/2999
