### ISSUE TITLE
Website Sync still happening?

### ISSUE THREAD

**Issue by ffe4** [open-telemetry/opentelemetry.io#236]
According to the calendar these meetings still take place, but the most recent edit on the linked agenda notes was last year.

Quote from the community repo under Website SIG:
> Meeting notes are updated every sync.

**Comment by austinlparker** [comment]
Yes, but we're really bad at taking notes.

There's an open issue in community (https://github.com/open-telemetry/community/issues/427) about rolling the website SIG into a larger comms sig, so some changes might be happening soon.

**Comment by ffe4** [comment]
I was hoping for some info regarding the discussions around #203 but I also don't think there are any videos of your meetings on the OTEL YouTube? I think the last video with _Website SIG_ in the title coincides with the last entry in the agenda document.

If the SIG likely gets merged soon anyway there's probably no point in changing much now. I ~assume~ hope once it is a _Comms_ SIG that will become a non-issue.

Closing this issue.

**Comment by austinlparker** [comment]
for what it's worth, we didn't really have any discussions around #203 yet. I'm usually the only person on the calls, it's been a busy summer, but I hope we can kickstart things with the SIG revamp and the upcoming website work pre-GA.
