### ISSUE TITLE
Jaeger link is invalid in integrations page

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2361]
_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry.io/pull/2201#discussion_r1111078211_

---

@svrnm, the Jaeger link is no longer valid:

```console
$ curl -I https://www.jaegertracing.io/docs/latest/opentelemetry/
HTTP/2 301 
...
location: /docs/1.42/opentelemetry/
...
$ curl -I https://www.jaegertracing.io/docs/1.42/opentelemetry/
HTTP/2 404 
```

From https://www.jaegertracing.io/docs/1.42/getting-started/:

> Historically, the Jaeger project supported its own SDKs (aka tracers, client libraries) that implemented the OpenTracing API. The [Client Libraries](https://www.jaegertracing.io/docs/1.42/client-libraries) section provides information about how to use the OpenTracing API and how to initialize and configure Jaeger tracers. As of 2022, the Jaeger SDKs are no longer supported, and all users are advised to migrate to OpenTelemetry.

**Comment by yurishkuro** [comment]
I suggest
  * simply point to Jaeger home page, no need to deep-link
  * Add Go to the 2nd column (HotROD and tracegen now use OTEL SDK, more to come)
