### ISSUE TITLE
.NET page - missing logo

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry.io#2376]
See https://opentelemetry.io/docs/instrumentation/net/

![image](https://user-images.githubusercontent.com/5972917/220367022-bb9c0591-8009-42be-9002-f6312f9bd932.png)

The logo image is not available under `https://opentelemetry.io/img/logos/32x32/.NET.svg`

I suppose the reason is the filename (`.` at the beginning). Probably it should be renamed to DotNet.svg

**Comment by chalin** [comment]
Ah, right! Thanks for reporting this.
