### ISSUE TITLE
Add GH action to pull in latest release of the OTel specification

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2387]
@open-telemetry/specs-approvers - is this something that you'd like?

This is a followup to

- #1963 

which was closed since the collector (and Java) scripts have been updated (via #2351).

The processing of the spec will be different, since the check out of a submodule is involved, but I'm glad to put something together if it's automation that you'd like to see implemented. If there's another workflow that you had in mind, let me know.

- [x] #2666
- [x] #2667
- [x] #2674
  - [x] Add the spec version update to the automation config
  - [x] Also update the spec submodule, checking it out at the latest version
- [x] https://github.com/open-telemetry/opentelemetry-specification/pull/3481

/cc @trask

**Comment by svrnm** [comment]
@open-telemetry/specs-approvers please take a look

**Comment by tigrannajaryan** [comment]
Just to be clear, this is about automating something that is manual currently? It would be definitely nice to do!

**Comment by cartermp** [comment]
Yes, correct, it's still manual today.

**Comment by chalin** [comment]
Closed by #2674

**Comment by chalin** [comment]
Reopening until spec-side cleanup is merged.
