### ISSUE TITLE
Create bot action to run formatter and link checker

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2388]
A good number of contributors submit PRs through the GH web i/f. It would be nice if we could support them by offering a bot action that would run the formatter and the link checker (to update the refcache) and submit a commit, possibly triggered by an in-comment command like `/format` or something more general like `/run-checks`

I don't know what would be involved in setting this up, but I wanted to get a discussion started.

/cc @cartermp @svrnm @trask

**Comment by theletterf** [comment]
Has this been solved by `/fix:all`?

**Comment by chalin** [comment]
Yes, the various `/fix` directives that are in place address this. Closing.
