### ISSUE TITLE
Concept page about sampling

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2423]
@reese-lee , would you be ok if we take the first 2 sections from your blog post on sampling (https://opentelemetry.io/blog/2022/tail-sampling/) and turn this into a concept page about the same topic? 

We can have a "practical guide" then later, but I think this would be a good starting point.

**Comment by reese-lee** [comment]
Yes, of course!

**Comment by svrnm** [comment]
> Yes, of course!

You want to create the PR for that yourself?

**Comment by reese-lee** [comment]
I can, where should I create the file?

**Comment by svrnm** [comment]
Closed via #2434
