### ISSUE TITLE
Cross link monthly OTel-in-focus with monthly release?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2430]
Just a thought, but might y'all see value in cross linking the monthly release with the monthly ?

- https://github.com/open-telemetry/opentelemetry.io/releases/tag/2023.03
- https://opentelemetry.io/blog/2023/otel-in-focus-02/

At a minimum, we could edit the march release text to mention and link to the OTel-in-focus. Thought I think that there's value in linking back to the release. Thoughts @svrnm @austinlparker et al.?

**Comment by svrnm** [comment]
yeah, we should do that, I think we can edit the release notes.

**Comment by chalin** [comment]
Yes they can be edited.
