### ISSUE TITLE
Space out the weights of PHP pages

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2431]
_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry.io/pull/2415#discussion_r1120900286_

> Note to self and @cartermp @svrnm : after this lands we should "space out" the weights so that more pages can fit in between them.

As a rule of thumb, use tenths for individual pages so, e.g., 10, 20, etc.

**Comment by svrnm** [comment]
this is fixed
