### ISSUE TITLE
Confusing links to OpenTracing and OpenCensus

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry.io#245]
https://opentelemetry.io/about/ includes links under the FAQ: What is Observability section labeled [Tracing](https://opentracing.io/docs/overview/what-is-tracing) and [Metrics](https://opencensus.io/stats) that lead to OpenTracing and OpenCensus documentation, respectively.  This has led to confusion regarding whether the information provided at those pages is relevant to OpenTelemetry implementations.  Can we replace those links with links to the relevant portions of the specification or other OpenTelemetry-specific documentation?

**Comment by austinlparker** [comment]
sure
