### ISSUE TITLE
Add Libraries doc or section for Java, showing how to set up library instrumentation without an agent

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#2471]
There's scenarios where you may not want to/cannot use the java agent for autoinstrumentation, but _do_ want to get library instrumentation. This should be documented with code samples, similar to the .NET page: https://opentelemetry.io/docs/instrumentation/net/libraries/

**Comment by nerudadhich** [comment]
Hi @svrnm, I would like to contribute on this. I am planning to add a SpringBoot example for this, in case you have any other idea let me know I can explore that option as well.

Also would you mind assigning this to me ?

**Comment by svrnm** [comment]
HEy @nerudadhich, thanks for offering your help! For SpringBoot we have the following in process already:

https://github.com/open-telemetry/opentelemetry.io/pull/3377

SpringBoot seems to be a "special case" because of the Starter being available, I think in the library page there should be something easier and more clearer of beeing an Instrumentation Library. 

@open-telemetry/java-approvers any suggestions/comments?

**Comment by nerudadhich** [comment]
Hi @svrnm I am planning to add [java-http-client](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/java-http-client/library) end to end working example.

Plan:
1. build.gradle - For dependency
2. SampleAutoConfigure.java - To initialise otel sdk
3. TestOtelHttpClient.java - To make external http api call using HttpClient (This will generate traces)
4. Jaeger docker-compose link to start in local

Let me know if this looks fine to you ?

**Comment by nerudadhich** [comment]
Thanks @svrnm this sounds good to me. Will work and raise a PR.

**Comment by svrnm** [comment]
> Thanks @svrnm this sounds good to me. Will work and raise a PR.

nice :-)

**Comment by cartermp** [comment]
Also @tylerbenson don't feel ashamed to copy-paste from the JS docs or something else and just tweak! Especially for the commentary between code samples, more uniformity (if it makes sense) is generally good.

**Comment by nerudadhich** [comment]
Hi @svrnm I have raised the PR, the preview is available [here](https://deploy-preview-3568--opentelemetry.netlify.app/docs/instrumentation/java/libraries/). 

Please review and suggest if anything needs to update.
Thank you.

**Comment by jeanbisutti** [comment]
@cartermp 

>There's scenarios where you may not want to/cannot use the java agent for autoinstrumentation

What do you have in mind?

Is it for the following reasons or others?

https://opentelemetry.io/docs/languages/java/automatic/spring-boot/
![image](https://github.com/open-telemetry/opentelemetry.io/assets/14811066/ccf70af7-fd03-443b-a6f9-deee6a7acc71)

**Comment by cartermp** [comment]
Those are good reasons, yes, although I think there's a few more:

- Runtime overhead of the agent being unacceptable (we've seen people report up to 20% increase cpu utilization)
- General desire not to run an agent

**Comment by jeanbisutti** [comment]
> * Runtime overhead of the agent being unacceptable (we've seen people report up to 20% increase cpu utilization)

You probably mean the Java agent overhead after the application startup.

In this case, the user could try to turn off some Java agent instrumentations.

**Comment by cartermp** [comment]
> You probably mean the Java agent overhead after the application startup.

Nope, in this case what we observed had nothing to do with startup. The only way forward was to explicitly turn on just a few instrumentations in-app and focus on manual instrumentation.
