### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by HarryAtMove** [open-telemetry/opentelemetry.io#248]
It would be great to see support for the Ruby language

**Comment by ffe4** [comment]
There is a link to the OpenTelemetry [Ruby OpenTelemetry client](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/README.md) under `Documentation` on the website. Do you mean something else?

**Comment by HarryAtMove** [comment]
I obviously did not dig deep enough, thank you!

https://opentelemetry.io/ homepage should have the following section updated then.
![image](https://user-images.githubusercontent.com/4128444/92756451-b139cb00-f341-11ea-8863-ca8a63eb2fff.png)

**Comment by ffe4** [comment]
I think the Ruby client might not be in Beta yet, and therefore not listed in that section.
