### ISSUE TITLE
Logs conceptual docs: write 'em

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#2495]
It's currently a tiny paragraph today. Lots more to document.

For help: https://docs.google.com/presentation/d/1fGrdeZxNakp0ZIy17ERhu-OLns_Sm9cpFvyyi6doeCw/edit#slide=id.p

**Comment by svrnm** [comment]
https://opentelemetry.io/docs/concepts/signals/logs/ looks much better now, so I close this one, although their is always more we can do:-)
