### ISSUE TITLE
Registry search result item produces invalid url 

### ISSUE THREAD

**Issue by yianni** [open-telemetry/opentelemetry.io#2509]
**What happened?** 
You can just search for an item in the registry and visit the URL of a list item.  
All items link to `https://opentelemetry.io/ecosystem/registry/$%7brepo%7d`.

**What did you expect would happen?** 
The item links to the correct URL.

**What is the name + path of the page where you encountered the issue?**
https://opentelemetry.io/ecosystem/registry/?s=kafka&component=&language=

**Comment by svrnm** [comment]
Oh, thanks for calling this out!. @chalin do you know how to fix that?
