### ISSUE TITLE
Demo Documentation - Update `Ad` and `Recommendation` Logs

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry.io#2521]
### Demo Documentation Update
Whenever https://github.com/open-telemetry/opentelemetry-demo/pull/796 gets merged, the following pages need to be updated:

- [ ] https://opentelemetry.io/docs/demo/services/ad/#logs
- [x] https://opentelemetry.io/docs/demo/services/recommendation/#logs

**Comment by svrnm** [comment]
#796 is merged, any updates, @julianocosta89 ?

**Comment by julianocosta89** [comment]
Hello @svrnm, I'm currently in paternity leave.
If nobody takes that till I'm back, I can take it.

**Comment by svrnm** [comment]
> Hello @svrnm, I'm currently in paternity leave. If nobody takes that till I'm back, I can take it.

@julianocosta89, apologies for pinging you during your parental leave, I'll ping the other maintainers or we revisit it when you are back, no hurry! Have a great & healthy time with your family.

@open-telemetry/demo-approvers can anyone take care of this?

**Comment by mviitane** [comment]
Hello @svrnm, I can do this at the end of June if no one takes if before that.

**Comment by julianocosta89** [comment]
>
> @julianocosta89, apologies for pinging you during your parental leave, I'll ping the other maintainers or we revisit it when you are back, no hurry! Have a great & healthy time with your family.
> 

Thank you 👶

**Comment by theletterf** [comment]
@julianocosta89 Time to retake this one? :)
