### ISSUE TITLE
Erlang/Elixir tabs not working

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry.io#2525]
**What happened?** Describe the problem that occurred.

Go to Getting Started for Erlang. Click on Elixir tab above code example. Nothing happens

**What did you expect would happen?**

All or at least this one code block switched to Elixir version

**What is the name + path of the page where you encountered the issue?** The

https://opentelemetry.io/docs/instrumentation/erlang/getting-started/

**What browser, OS, and platform were you using when you encountered the
problem?**

Arc browser, macos

**Additional context**: looks like was already mentioned in #1772

**Comment by svrnm** [comment]
thanks for reporting
