### ISSUE TITLE
Instructions at https://opentelemetry.io/docs/collector/about/ are out of date

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry.io#255]
I've downloaded https://github.com/open-telemetry/opentelemetry-collector.git today and it appeared to me that instructions from https://opentelemetry.io/docs/collector/about/ , section `Local` are out of date.

There is no `examples/main.go` anymore but there is `examples/demo/app/main.go`.

I'd be happy to submit a PR to fix that.

**Comment by flands** [comment]
This appears to be updated -- closing.
