### ISSUE TITLE
Document how to change the span status

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry.io#2557]
**Desired feature or idea**: What would you like to see happen?

Document how people can change the span status using the [Collector's Span Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanprocessor).

This could be documented here: https://opentelemetry.io/docs/collector/transforming-telemetry/

**Additional context**: 

I have seen frequently questions how people can change "false negative" error span status for 404 HTTP Client calls or NOT_FOUND gRPC calls.

**Comment by svrnm** [comment]
@alejandraquintero018 are you still interested in helping with this?

**Comment by Gaurang-Patel** [comment]
Hi @alejandraquintero018 , @svrnm  I would like to work on this issue, should I document using a span processor or transform processor ?

**Comment by svrnm** [comment]
Thank you @Gaurang-Patel, update https://opentelemetry.io/docs/collector/transforming-telemetry/ with instructions for the SpanProcessor. We should have a dedicated section on the TransformProcessor eventually as well, so that could be a follow up thing.
