### ISSUE TITLE
Agent Configuration

### ISSUE THREAD

**Issue by freshgeek** [open-telemetry/opentelemetry.io#2561]
-Dotel.instrumentation.common.db-statement-sanitizer.enabled=false

is invaild in my springboot app ,Version 1.24.0 
  
https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.24.0

**Comment by freshgeek** [comment]
[https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7413](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7413)
[https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7400](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7400)

**Comment by cartermp** [comment]
Thanks for filing this issue @freshgeek!

@open-telemetry/java-instrumentation-approvers -- do you think we should document the nuances in the `otel.instrumentation.common.db-statement-sanitizer.enabled` config setting?

**Comment by mateuszrzeszutek** [comment]
Hmm, perhaps we could add

> Disabling this property might not have the desired effect if the instrumented application is already using `PreparedStatement`s

or something similar?

**Comment by trask** [comment]
or

> Note: JDBC bind parameters are not captured in `db.statement` (see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7413 if you are looking to capture bind parameters)

**Comment by freshgeek** [comment]
If possible, it will reduce some development debugging time
