### ISSUE TITLE
Offer FAQ

### ISSUE THREAD

**Issue by mhausenblas** [open-telemetry/opentelemetry.io#2563]
**Desired feature or idea**: What would you like to see happen?

I'd like to see a comprehensive FAQ page on OpenTelemetry topics. This could be structured along specification, collector, and SDKs and should reference docs on and off the site (for example, to GitHub for new work).

**Additional context**: anything else you can think about that would be helpful.

We could source questions from [StackOverflow](https://stackoverflow.com/questions/tagged/open-telemetry) and Slack. I would volunteer to own this.

**Comment by austinlparker** [comment]
Not to ask the obvious question, but what would the threshold be for something to be in a FAQ vs. being added to the docs itself? I agree broadly that we do need a way to collect frequently asked questions and publish answers to them in an indexable location, but I also feel like a lot of those questions need to be turned into docs (or perhaps 'troubleshooting' sections in the existing doc pages; random example, there's a somewhat frequent set of slack questions that amount to 'data not being exported properly' - is the answer here better signposting to existing docs, updates to existing docs, a set of troubleshooting workflows based on topic vs. component, etc.)

That said, I don't necessarily want to turn this into com.yak.shaving so perhaps a FAQ would be a good place to start, and then we can go from there? @svrnm @chalin @cartermp thoughts?

**Comment by chalin** [comment]
Thanks for the suggestion. Let me play on offence here, while thinking out loud. 

I'm glad that y'all are seeing a FAQ as an "MVP for a docs entry" (that is my preferred perspective too), but it has been my experience that FAQs become stale quickly because they don't get the love they need/deserve to sustain the "MVP for a docs entry" vision. So a FAQ is high maintenance, and when it isn't well maintained, folks tend to fall back [StackOverflow](https://stackoverflow.com/questions/tagged/open-telemetry) and web search anyways.

That being said, it might make sense to maintain a dynamic list generated from SO? Or somehow just direct folks to SO?

We could keep a **curated list of SO Q&A's tagged with `#otel-faq`** instead, and direct folks to that list: https://stackoverflow.com/questions/tagged/otel-faq (and/or use any other filtering criteria). Again, just thinking out loud here.

**Comment by mhausenblas** [comment]
Patrice thanks!

> FAQs become stale quickly 

In my experience this is the core problem. That's why I added "I would volunteer to own this." meaning I would do a monthly scrub and sync. Does this make sense?

**Comment by cartermp** [comment]
I think in general I'd be in favor, although I don't think I'd have bandwidth to help maintain int.

**Comment by mhausenblas** [comment]
Ok, thanks for all your feedback! Wondering, what's the next step now?

**Comment by svrnm** [comment]
Having a FAQ would be great, but I agree with the concern of the maintainability. 

> That's why I added "I would volunteer to own this." meaning I would do a monthly scrub and sync.
&
> Ok, thanks for all your feedback! Wondering, what's the next step now?

 If you are willing to run & maintain the FAQ @mhausenblas I am happy to support that.
Let's discuss this on one of our SIG calls*, I think it is easier that way to come to a conclusion.

--

* I will not be around for the one next Monday, so either you discuss without me or we postpone to the one after KubeCon

**Comment by mhausenblas** [comment]
Thanks @svrnm and agreed, let's continue in the SIG (also off next Monday due to public holiday). We could use KubeCon though …

**Comment by chalin** [comment]
Works for me, thanks! (Late to chime in given I was OOO.)

**Comment by mhausenblas** [comment]
Cool cool, then let me first get the Deployment PR finally sorted and I'll draft something via a GDoc we can discuss (seed FAQ items)

**Comment by svrnm** [comment]
@mhausenblas any updates? :-)

**Comment by mhausenblas** [comment]
Yup, still on my radar, aiming for next week

**Comment by theletterf** [comment]
@mhausenblas Any update?

**Comment by mhausenblas** [comment]
@theletterf afraid no progress and I don't think that I will get to it in the foreseeable future. Should we try to find someone else to take this on?

**Comment by chalin** [comment]
Just a thought but, another option is to drop this request. WDYT?

**Comment by mhausenblas** [comment]
@chalin I'd prefer to archive it or put it on the attic rather than drop but yeah agreed ;)

**Comment by cartermp** [comment]
I think we can close, and if anyone is curious about this we can re-open it.
