### ISSUE TITLE
Instrumenting libraries page in spec states metrics API is not stable and needs to be updated to reflect stable status

### ISSUE THREAD

**Issue by CharlieTLe** [open-telemetry/opentelemetry.io#2575]
Visit https://opentelemetry.io/docs/concepts/instrumenting-library/#metrics and you'll read (emphasis mine):

Metrics API is not stable yet and we don’t yet define metrics conventions.
But the section to which "not stable yet" links to has been updated from

Feature-freeze -- https://github.com/open-telemetry/opentelemetry-specification/blob/e30aa7da8f28328adb67b4804c4dcddf4f413c1d/specification/metrics/api.md

to

stable -- https://github.com/open-telemetry/opentelemetry-specification/pull/2104

So the "Metrics API is not stable yet" paragraph needs some editing. Who can tackle this (or let me know how to update it)?

cc: @alolita

**Comment by chalin** [comment]
Thanks for noticing and reporting the issue. The "stable" status that you are referring to, is the spec's status for metrics. 

@cartermp et al. can correct me if I'm wrong, but the status being referred to in "Metrics API is not stable" is the implementation across supported languages: which is about 50% at the moment -- that is 50% of languages have "stable" metrics in contrast to some other status (beta, alpha, experimental or not implemented). So, in a sense, the statement is 50% correct 😅.

But I agree that that sentence could be clearer. Maybe what we need is actual content for that section as opposed to just a clarification about status. Folks are quite busy with KubeCon approaching, but I'll let @cartermp @svrnm share their thoughts.

**Comment by cartermp** [comment]
Yeah this is a problematic paragraph. I think we should just nix it + the section altogether for now. It's really not relevant for most end-users of opentelemetry anyways, and sows confusion on a mixed topic. I'd propose we just remove that section.

**Comment by chalin** [comment]
@CharlieTLe - do you want to remove that section, as @cartermp suggested? If not I'll submit a patch.

**Comment by CharlieTLe** [comment]
@chalin Yes, I can help with removing the section. Thanks for the quick feedback, @cartermp.

**Comment by CharlieTLe** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry.io/pull/2581
