### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by kumarankit999** [open-telemetry/opentelemetry.io#2582]
The footer Section should be Darker or Black color so to be looking Better ,Since grey color is not looking so good. As it is not a combo ,Make in Black color Background color of footer section ,whether there is a grey change it by black color.

Make it Black, So to look Aesthetic and Contrast.

![cncf](https://user-images.githubusercontent.com/111564362/230459638-a530dba8-796d-41e2-9035-9668e8f51c05.jpg)

**Comment by chalin** [comment]
The WCAG contrast ratio is just fine (10+). We'll stick with our current color scheme, thanks -- unless @cartermp @svrnm @austinlparker think otherwise.

**Comment by cartermp** [comment]
I am fine with it for now, yep.

**Comment by austinlparker** [comment]
Yeah it's fine as is.
