### ISSUE TITLE
Create a Cloud Function section in the docs [Lambdas]

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry.io#2586]
The FAAS sig is progressing on community releases for AWS lambda layers. We'd like to create a generic Cloud Functions section in the documentation like we have for Kubernetes Operator. The children of this generic section would be dedicated AWS, GCP, and Azure docs starting with Lambdas.

We will move some content from the [ADOT site](https://aws-otel.github.io/docs/getting-started/lambda).

We are also working with GCP and Azure contributors to create best practices doc sections for their respective offerings.

**Comment by cartersocha** [comment]
@Aneurysm9 what doc or doc sections do you think are relevant in the ADOT docs?

My initial thought is we have a home page and then dedicated pages by language similar to the ADOT docs and update for the stand alone Collector.

**Comment by cartersocha** [comment]
@tylerbenson I see the ADOT site has an SDK and an agent layer. Are we planning on providing both as well?

**Comment by tylerbenson** [comment]
I'm open to considering it, but I'm not as familiar with that layer, so I wanted to focus on the javaagent for now.

**Comment by cartermp** [comment]
In theory I think this is fine - this is valuable content and what you proposed seems like a good layout. But I'll defer to @chalin on the general information architecture here. We've clearly got space on the side bar, I just don't have enough expertise on if it's the right call to make it a top-level node or not.

We'll also probably want to figure out where to plop this puppy https://opentelemetry.io/docs/instrumentation/js/serverless/

**Comment by svrnm** [comment]
> In theory I think this is fine - this is valuable content and what you proposed seems like a good layout. But I'll defer to @chalin on the general information architecture here. We've clearly got space on the side bar, I just don't have enough expertise on if it's the right call to make it a top-level node or not.

+1, I second that

> We'll also probably want to figure out where to plop this puppy https://opentelemetry.io/docs/instrumentation/js/serverless/

This should either be incorporated or updated with the new content.

**Comment by chalin** [comment]
Top level seems like a good call for now -- and I can't think of anything better atm. Thanks to redirects, we can always change our mind later on.

**Comment by cartermp** [comment]
@cartersocha and there you have it! Looking forward to reviewing.

**Comment by cartersocha** [comment]
Thanks all! 

We'd probably retire the JavaScript serverless doc. Initial docs will be auto-instrumentation focused. @chalin do we have an ability to create doc tabs on the OTel website? The Python, JavaScript, and Java instructions will all be very similar. See below

https://aws-otel.github.io/docs/getting-started/lambda/lambda-java-auto-instr
https://aws-otel.github.io/docs/getting-started/lambda/lambda-js
https://aws-otel.github.io/docs/getting-started/lambda/lambda-python

**Comment by chalin** [comment]
> do we have an ability to create doc tabs on the OTel website?

@cartersocha - If I understand what you're asking for, then the short answer is yes: use the `tabpane` shortcode (like other places in the docs), with the `text=true` as an argument:

```liquid
<!-- prettier-ignore -->
{{< tabpane text=true >}}
{{% tab Java %}}

Some **Java** content.

<!-- prettier-ignore -->
{{% /tab %}}
{{% tab Python %}}

...

<!-- prettier-ignore -->
{{% /tab %}}
{{< /tabpane >}}
```

The longer answer is that you should use such a feature only if the text tabs don't contain any headings (well, they can, but they'd need to be encoded in HTML), otherwise it messes up the autogeneration of the ToC. Also keep in mind that if folks print the docs, they can't control which tabs get printed. (Technically, we don't support a printed version of the docs (yet), and you might argue that that's a bug/deficiency of the shortcode, but anyway, I just wanted to mention the limitation).
