### ISSUE TITLE
Baggage - confusing documentation about non-sensitive data

### ISSUE THREAD

**Issue by kylepl** [open-telemetry/opentelemetry.io#2591]
As a user new to OpenTelemetry, I find the following quotes on [Baggage](https://opentelemetry.io/docs/concepts/signals/baggage/) contradictory.

> OTel Baggage should be used for non-sensitive data that you’re okay with potentially exposing to third parties. This is because it’s stored in HTTP headers alongside the current context.

and

> This can include things like Account Identification, User Ids, Product Ids, and origin IPs, for example

At least Account Identification, User Ids and origin IPs are all sensitive. Am I missing something obvious?

**Comment by cartermp** [comment]
Yeah, there's clearly value in placing that kind of data in there, so let's update the wording to be about secure/insecure
