### ISSUE TITLE
How to execute otelcol as regular user

### ISSUE THREAD

**Issue by schea12** [open-telemetry/opentelemetry.io#2601]
How can we execute opentelemetry command as a regular user, please?

The given command requires root access.

https://opentelemetry.io/docs/collector/getting-started/
sudo yum update
sudo yum -y install wget systemctl
wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.75.0/otelcol_0.75.0_linux_amd64.rpm
sudo rpm -ivh otelcol_0.75.0_linux_amd64.rpm
sudo systemctl start otelcol

**Comment by cartermp** [comment]
@open-telemetry/collector-approvers is it expected that you need root access to run otelcol?

**Comment by codeboten** [comment]
If you download the collector binary, you can run it as a regular user. The service is run as the user `otel`, the sudo commands in the documentation is to install the service.

**Comment by schea12** [comment]
May I have the path to the collector binary, please?

**Comment by schea12** [comment]
Hi,

We observed we need to at least run rpm with sudo access to install otelcol-contrib 1st in order to get the executable binary.
May I know how can I get the executable binary using a regular user access, please? Is there a path for regular user to download the collector executable binary straight away, please?


https://opentelemetry.io/docs/collector/getting-started/

sudo yum update
sudo yum -y install wget systemctl
wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.75.0/otelcol_0.75.0_linux_amd64.rpm
sudo rpm -ivh otelcol_0.75.0_linux_amd64.rpm


Thanks
-Christine-

**Comment by schea12** [comment]
Cheah, Suan Ching would like to recall the message, "[open-telemetry/opentelemetry.io] How to execute otelcol as regular user (Issue #2601)".

**Comment by svrnm** [comment]
@schea12 you will find the binaries here: https://github.com/open-telemetry/opentelemetry-collector-releases/releases

**Comment by svrnm** [comment]
Note: We do not link those binaries for linux in the docs (only mac, windows), we should update the docs accordingly
