### ISSUE TITLE
Manual Instrumentation - Java Context Propagation guidance is unclear

### ISSUE THREAD

**Issue by AlexChesser** [open-telemetry/opentelemetry.io#2627]
Specifically, there appears to be a high degree of pre-requisite knowledge required to make use of this code.

For each example, there are questions left unanswered like, what type of class do I write this in? Where do I place it in my application? 

What libraries or dependencies have to be imported?  For example,m in the case of `HttpExchange` there is one instance of that class in `com.sun.net.httpserver` and two more available under `org.springframework.<stuff>`

For the `HttpExchange` example, is this a standalone class which has to be registered with my app? 

What does `<Library Specific Annotation> HttpHeaders` mean in the `HttpHeaders` example? Where or how is that registered with the server? 

Perhaps links to working examples or further expansion of the sample code, or some implementation of an auto-configure option within the autoinstrumentation java agent?

The end goal being tracecontext headers are added to all HttpResponses and HttpRequests originating from the app (and if this isn't the right mechanism for dealing in GRPC requests additional guidance on how to ensure GRPC does propagation as well)

Note that this ticket was created by clicking the "create a documentation issue" link on this page: https://opentelemetry.io/docs/instrumentation/java/manual/#context-propagation

**Comment by svrnm** [comment]
@open-telemetry/java-approvers

**Comment by trask** [comment]
> and if this isn't the right mechanism for dealing in GRPC requests additional guidance on how to ensure GRPC does propagation as well

hi @AlexChesser! sorry for the late reply

for grpc, if you aren't using the java agent, we recommend using the grpc library instrumentation, check out: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/grpc-1.6/library#library-instrumentation-for-grpc-160

**Comment by trask** [comment]
I have two thoughts, but maybe these are better opened as separate issues(?)

* adding a "Libraries" page similar to https://opentelemetry.io/docs/instrumentation/net/libraries/ might help?
  * (recommending to install ["Standalone Library Instrumentation"](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks) for any libraries you are using, e.g. grpc, kafka, log4j)
* make it more clear somehow that "manual instrumentation" is recommended to supplement auto-instrumentation and standalone library instrumentation

**Comment by svrnm** [comment]
> * adding a "Libraries" page similar to https://opentelemetry.io/docs/instrumentation/net/libraries/ might help?
>   * (recommending to install ["Standalone Library Instrumentation"](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks) for any libraries you are using, e.g. grpc, kafka, log4j)

+1 for that one. Overall we need to do a better job to explain people the different "shapes" of instrumentation, but this would improve the situation for java and also create some consistency across languages.

> * make it more clear somehow that "manual instrumentation" is recommended to supplement auto-instrumentation and standalone library instrumentation

+1

**Comment by AlexChesser** [comment]
I eventually abandoned this path of implementation in favour of the javaagent auto-instrumentation method.   Both of those remediations to this issue sound reasonable. 

I am not comfortable enough with the details of how this all works to write clear tickets for the two suggested above, but I do think that if those two tickets are written that would be a suitable outcome to this one.
