### ISSUE TITLE
[OTel Demo] - Quote Service Metrics

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry.io#2669]
This [OTel Demo PR](https://github.com/open-telemetry/opentelemetry-demo/pull/878) added metrics to the PHP service.
We need to add the process to the docs.

**Comment by svrnm** [comment]
thanks for raising this @julianocosta89 !

**Comment by svrnm** [comment]
@open-telemetry/demo-approvers @open-telemetry/php-approvers is this still relevant?

**Comment by julianocosta89** [comment]
Yes, we need to update this section: https://opentelemetry.io/docs/demo/services/quote/#metrics

I can take care of this

**Comment by svrnm** [comment]
thanks @julianocosta89

**Comment by kennykguo** [comment]
if this issue is still active, please assign this issue to me, thanks

**Comment by svrnm** [comment]
hey @kennykguo, Please note that we are not assigning issues, as per our [contribution guidelines](https://github.com/open-telemetry/opentelemetry.io/blob/main/CONTRIBUTING.md#want-to-work-on-an-existing-issue), if you are interested to work on this issue let us know, and we keep track and wait for a PR from you. I recommend that you pick 1 or 2 issues you fill confident to provide a PR for within ~2 weeks.

**Comment by julianocosta89** [comment]
@brettmc do you think we have something to add to the Metrics section of the PHP service in the docs?

Otherwise I'll just close this issue

**Comment by brettmc** [comment]
> do you think we have something to add to the Metrics section of the PHP service in the docs?

Yes, I've just submitted a PR to add some manual metrics to quote service (there are some auto-generated ones there already), then I'll update the Metrics and Logs sections of the docs.
