### ISSUE TITLE
Visual Asset Needs

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#267]
A thing that'd be nice to have is some sort of library of visual assets we can use for the website and slide decks. This issue exists to track what we can think of/might need.

- Iconography for OTel components (API, SDK, Collector)
- Diagrams of the telemetry pipeline (akin to https://user-images.githubusercontent.com/1859948/95499822-db4bd080-0973-11eb-8dc3-9bcd5b8185e4.png)
- Iconography per-SIG? (otel .net, otel go, etc.)
- "Well instrumented" system diagram
- ???

Please add ideas

**Comment by austinlparker** [comment]
Yeah.. to expand a bit, I think we'll need icons (or at least styles) for the 'included' processors/exporters, or at least a way to represent them in a pipeline.

So for propagation, that's W3C and B3. Zipkin/Jaeger/Console exporters. The SIG list is currently under 'Documentation' on the site, but it's basically languages (so C#, Java, Node, etc.) I think the best thing there would be a 'standard' way of combining the text of the language with the otel mark, so like the telescope with C# or Java or whatever in place of the 'opentelemetry' text.

**Comment by austinlparker** [comment]
Insofar as 'well instrumented system', not really - there's plenty of "example microservice applications" like google's ecommerce app, or MS eshop, spring petclinic, whatever. There's nothing quite in the 'sweet spot' of simple to understand but complex enough to demonstrate concepts.

**Comment by jkowall** [comment]
**Components in app:**
- API
- SDK
- Processing
- Exporter

**Components in Otel**
- Collector
-Exporter

**Protocols:**
- W3c Tracecontext https://www.w3.org/TR/trace-context/ 
- B3 https://github.com/openzipkin/b3-propagation

**Exporters:**
- Jaeger (can get idea from their page)
- Zipkin (can get idea from their page)
- OTLP (OpenTelemetry Protocol) 
- Prometheus (can get idea from their page)

**Special Interest Groups (SIGs) - I don't think we need to have the "SDK" represented in the icon.**
- Agent/Collector
-.NET SDK
- C/C++ SDK
- GoLang SDK
- Java SDK
- Java Auto-Instrumentation
- JavaScript SDK
- Python SDK
- Ruby SDK
- Erlang/Elixir SDK

@austinlparker do you think we need icons for these or just use their icons?
MySQL | Redis | Django | Kafka | Jetty | Akka | RabbitMQ | Spring | Flask | net/http | gorilla/mux | WSGI | JDBC | PostgreSQL

**Comment by jkowall** [comment]
Update on content which is in progress. Let me know what you think. Thanks to Ella for her work on them!

![image](https://user-images.githubusercontent.com/1859948/97621545-665f3a00-19f9-11eb-9dbd-3e364c891c4a.png)

**Comment by austinlparker** [comment]
ooh this is neat

**Comment by austinlparker** [comment]
re: integration icons for the main page, I think it might be nice to have those redrawn to look consistent with the rest of the icon set since i presume people will also want to use these with slides

**Comment by jkowall** [comment]
Which integration icons do you mean?

**Comment by austinlparker** [comment]
The ones you listed in the comment before the WIP
>MySQL | Redis | Django | Kafka | Jetty | Akka | RabbitMQ | Spring | Flask | net/http | gorilla/mux | WSGI | JDBC | PostgreSQL

**Comment by jkowall** [comment]
Yep, we will be getting to those, there was a little miscommunication, but they are on the list. They are all vector graphics, so we'll be able to keep the originals in GH, we are working off figma right now.

**Comment by austinlparker** [comment]
cool. i like it so far tho!

**Comment by Ella-bz** [comment]
I'm working on other icons now. Correct me, guys, if I'm doing something wrong or it's ok
![image 1](https://user-images.githubusercontent.com/73476445/98209625-eb8da600-1f47-11eb-81f1-4921c2b5d2fb.jpg)

**Comment by jkowall** [comment]
Looks good to me @Ella-bz . See what @austinlparker thinks :)

**Comment by austinlparker** [comment]
I like it! legibility on the 'sdk' bug on those language icons is pretty low, but i'm not really sure how to improve it. Maybe use iconography rather than letters (like a wrench?)

**Comment by Ella-bz** [comment]
About SDK I will try to make something like a suitcase with a wrench maybe? Ill work on options. 

I need help with a "Well instrumented" system diagram. Can I have some reference or concrete examples of what it is? Visually I mean. And in general, all diagrams that you guys have and want to change attache please here, then it will be much easier for me to understand which elements need to be done.

**Comment by Ella-bz** [comment]
What if to make SDK as a tool kit but with a wrench inside?
![image 1](https://user-images.githubusercontent.com/73476445/98467061-0415ee80-21dc-11eb-9b60-9eb004d1203d.jpg)

**Comment by austinlparker** [comment]
The wrench is pretty clear, yeah.

**Comment by austinlparker** [comment]
@Ella-bz there's some diagrams linked in #308 that we can use as a starting point for the 'well architected system'. cc @flands

**Comment by Ella-bz** [comment]
![Graph](https://user-images.githubusercontent.com/73476445/98824244-c0212480-243b-11eb-8deb-7a676f4c3b20.jpg)
Some updates about icons. Correct me- what I need to change or upgrade

**Comment by austinlparker** [comment]
Lookin' pretty good! What font is that? Ideally we can use something that's available in google slides.

**Comment by jkowall** [comment]
We probably want slides, jpeg, and also the vector graphics so that they can be used for anything, no @austinlparker ? These are in figma, but I am sure @Ella-bz has them in vector format (ai or something of the sort).

**Comment by austinlparker** [comment]
Yeah, I think they can be exported from figma as SVG?

**Comment by Ella-bz** [comment]
From Figma, I can transfer it to SVG, pdf,  jpeg, and png. I can export each icon to png and svg let's say (make ai out of it if necessary). And about google slides -it's possible to create an editable slide.

**Comment by Ella-bz** [comment]
So here is the link that I hope will work  for  you guya with the latest updates. I'm waiting to hear from you what am I doing with that. am I exporting it in a certain way, or I need to correct something. https://www.figma.com/file/PZ1zSzBeNOjJkHTbmRSEcK/?node-id=191%3A2

**Comment by jkowall** [comment]
I think they look great. @austinlparker how do you want these exported and added to the repo?

**Comment by austinlparker** [comment]
Can we export them as png/svg and put them in a zip file? We can host the zip file on the site and link to it from the 'about' page.

**Comment by Ella-bz** [comment]
Guys, I finally organized it for SVG and png. Took a bit longer cause of specific glitches while exporting from Figma. Check it out and tell me if I need to do something else
[OT_Project.zip](https://github.com/open-telemetry/opentelemetry.io/files/5628092/OT_Project.zip)

**Comment by jkowall** [comment]
@austinlparker do you want us to make a dir for these or how did you want to proceed? Did you want vector graphics as well or just these formats? I can submit a PR.

**Comment by austinlparker** [comment]
Yeah, a PR would be great. Maybe link to it in the 'workshop resources' page?

**Comment by jkowall** [comment]
Do you want them in a subdir in /static/iconography or something of the sort, or stored in a different location?

**Comment by austinlparker** [comment]
Actually it might make the most sense to keep the zip out of the website assets and just have it in git, then we can link to the raw zip on github? That way we aren't getting dinged on netlify for bandwidth when people download it.

**Comment by flands** [comment]
This appears to be done -- closing
