### ISSUE TITLE
Found a couple of issue with the python instrumentation getting started document

### ISSUE THREAD

**Issue by LucaLanziani** [open-telemetry/opentelemetry.io#2682]
**What needs to be changed?**

There are a couple of typos

The first one is [here](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/instrumentation/python/getting-started.md?plain=1#L106-L109), the default port for Flask is 5000 and the documentation says to go to port 8080.

Similar issue is present [here](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/instrumentation/python/getting-started.md?plain=1#L436) but at least the documentation doesn't say anything about visiting port 8080.

The last one is an issue with a code snippet [here](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/instrumentation/python/getting-started.md?plain=1#L407) where the function parameter should be a string. 

**What is the name + path of the page that needs changed?**

https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/instrumentation/python/getting-started.md

**Additional context**

I would be more than happy to fix the typos myself if possible.

**Comment by LucaLanziani** [comment]
Here you can find the proposed changes: https://github.com/open-telemetry/opentelemetry.io/compare/main...LucaLanziani:opentelemetry.io:patch-2

**Comment by svrnm** [comment]
thanks for reporting! looks like https://github.com/open-telemetry/opentelemetry.io/pull/2689 is addressing some of that. 

Please raise a PR for the remaining issues, makes it easier for us to review them and gives you credit when we merge them in!

**Comment by LucaLanziani** [comment]
I believe the rest was fixed here #2688
