### ISSUE TITLE
Erlang references should be styled 'Erlang/Elixir' consistently

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#269]
per #268

**Comment by harshita19244** [comment]
Is help on this issue still required?

**Comment by shelbyspees** [comment]
should this be moved to the Erlang/Elixir repo?

**Comment by theletterf** [comment]
Looking at https://github.com/open-telemetry/opentelemetry-erlang/tree/main/website_docs, this seems to have been solved already.

**Comment by cartermp** [comment]
This one is indeed complete, yep. All the erlang/elixir docs either say this directly, or only one of the languages when there is something mentioned specific to that language.
