### ISSUE TITLE
TypeORM plugin does not appear in the website registry

### ISSUE THREAD

**Issue by nirsky** [open-telemetry/opentelemetry.io#270]
Hey,
TypeORM plugin is [in the repo](https://github.com/open-telemetry/opentelemetry.io/blob/master/content/registry/instrumentation-js-typeorm.md).
But I can't find it in the registry search: https://opentelemetry.io/registry/

Edit: I now noticed some other registry files got excluded as well.
Made a PR to fix this: https://github.com/open-telemetry/opentelemetry.io/pull/271

**Comment by austinlparker** [comment]
closed by #271, thanks for catching this!
