### ISSUE TITLE
OpenTelemetry Operator for Kubernetes

### ISSUE THREAD

**Issue by anwesh-b** [open-telemetry/opentelemetry.io#2710]
Getting this issue when creating an OpenTelemetry Collector (otelcol) instance
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling
webhook "mopentelemetrycollector.kb.io": failed to call webhook: Post
"https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/mutate-opentelemetry-io-v1alpha1-
opentelemetrycollector?timeout=10s": dial tcp 10.109.65.200:443:
connect: connection refused
```

Kubectl version
```
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.3
```

**Comment by svrnm** [comment]
Thanks for raising this, is this related to a certain point of the documentation or specific to the Operator? You may consider raising this issue with https://github.com/open-telemetry/opentelemetry-operator

cc @open-telemetry/operator-approvers

**Comment by frzifus** [comment]
@anwesh-b did you verify that the operator is running? Seems that the `opentelemetry-operator-webhook-service` is not reachable.

**Comment by anwesh-b** [comment]
I faced with following the docs, will add solution after finding one

**Comment by svrnm** [comment]
@anwesh-b did @frzifus question help?

**Comment by pavolloffay** [comment]
@anwesh-b did you install cert-manager and was it ready when you installed the OTEL operator?
