### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by runtu666** [open-telemetry/opentelemetry.io#2716]
composer require open-telemetry/opentelemetry-logger-monolog:*

  Problem 1
    - Root composer.json requires open-telemetry/opentelemetry-logger-monolog * -> satisfiable by open-telemetry/opentelemetry-logger-monolog[0.0.1].
    - open-telemetry/opentelemetry-logger-monolog 0.0.1 requires open-telemetry/api >=1.0.0beta7 <2 -> found open-telemetry/api[dev-main, 1.0.0beta7, 1.0.0beta8, 1.0.0beta9, 1.0.x-dev (alias of dev-main)] but it does not match your minimum-stability.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require open-telemetry/opentelemetry-logger-monolog:*" to figure out if any version is installable, or "composer require open-telemetry/opentelemetry-logger-monolog:^2.1" if you know which you need.

**Comment by svrnm** [comment]
@runtu666 following up on this since I ran into this issue as well, what you need to do is add ` "minimum-stability": "beta"` to your composer.json.

**Comment by svrnm** [comment]
We need to update the PHP docs accordingly that ` "minimum-stability": "beta"` is required to be set in the composer.json
