### ISSUE TITLE
Bug: Blog navigation no longer points to medium

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry.io#273]
The blog link in the navigation goes to https://opentelemetry.io/blog/ (which looks like a test feature) instead of https://medium.com/opentelemetry

**Comment by mtwo** [comment]
Yikes, fixing

**Comment by mtwo** [comment]
Nevermind, I don't know how to fix this since the top nav is automatically generated from the content sections. @austinlparker can you redirect the Blog navigation link to the Medium blog?

**Comment by austinlparker** [comment]
I really need to start squashing locally, but there's a PR up for it.

**Comment by austinlparker** [comment]
Closed by #275
