### ISSUE TITLE
Update website to spec 1.21.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry.io#2747]
The spec 1.21.0 was released yesterday, but https://opentelemetry.io/docs/specs/ show 1.20.0

What steps are needed to update it?

**Comment by svrnm** [comment]
@tigrannajaryan it's still a manual process that needs to be triggered by us. Some folks (including myself) have been out of office for some days last week so that's why we have a delay. We will take care of this as soon as possible.

**Comment by chalin** [comment]
> <img width="882" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/3045c1c5-a2bf-420a-b8f9-8ca40548118a">

**Comment by tigrannajaryan** [comment]
Thanks a lot for updating!
