### ISSUE TITLE
Dead links to supported frameworks on homepage

### ISSUE THREAD

**Issue by taylor-sutton** [open-telemetry/opentelemetry.io#277]
I'm referring to the three links to `https://tktk` here: https://github.com/open-telemetry/opentelemetry.io/commit/2b4c3ebd9f8bb76781d7171b46bc27f1491875da#diff-f1f180e860deaa9c82eefe2a7a7102cc1cfeb159e7271758996b608ccf81cef9R56

Not sure what these links are supposed to go to; happy to make a PR if you let me know.

**Comment by josemaia** [comment]
I didn't see this issue, but I submitted a PR just a bit ago: https://github.com/open-telemetry/opentelemetry.io/pull/281

**Comment by austinlparker** [comment]
Closed by #281, ty
