### ISSUE TITLE
Add OpAMP spec to the specs list

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry.io#2795]
We have OTLP specs at https://opentelemetry.io/docs/specs/otlp/

It would be great to have OpAMP specs as a sibling of that page, and show the content of https://github.com/open-telemetry/opamp-spec/blob/main/specification.md

## Tasks

- [x] #2926
- [x] Ensure that GitHub page-meta links are working

**Comment by svrnm** [comment]
I love that 👍 

@chalin how complicated would it be to add yet another spec?

**Comment by chalin** [comment]
Will gladly look into it.

**Comment by chalin** [comment]
The OpAMP spec page is quite long. Might it make sense to break it up? I've filed an issue over the OpAMP repo:

- https://github.com/open-telemetry/opamp-spec/issues/145

**Comment by chalin** [comment]
Closed by #2926
