### ISSUE TITLE
collector / configuration doc: "A full list of processors can be found here" needs to include link for core as well

### ISSUE THREAD

**Issue by jf** [open-telemetry/opentelemetry.io#2802]
https://opentelemetry.io/docs/collector/configuration/#processors says that `A full list of processors can be found [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor)`, but the single link given is NOT the complete list and misses out on the list of processors found in core (https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor)

**Comment by svrnm** [comment]
Thanks for raising this @jf! Feel free to raise us a PR to fix this. @open-telemetry/collector-approvers PTAL!

**Comment by jf** [comment]
> Thanks for raising this @jf! Feel free to raise us a PR to fix this. @open-telemetry/collector-approvers PTAL!

sure. I've raised #2819 :)
