### ISSUE TITLE
 redirect `/docs/concepts/data-collection/` to `/docs/concepts/components/#collector` instead

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2848]
@svrnm @cartermp - not sure if you missed this comment (https://github.com/open-telemetry/opentelemetry.io/pull/2761#pullrequestreview-1468048564):

> @svrnm - I'm wondering if it would make more sense to redirect `/docs/concepts/data-collection/` to `/docs/concepts/components/#collector` instead, that way it stays within the Concepts section.

WDYT?

_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry.io/issues/2761#issuecomment-1582420696_

**Comment by chalin** [comment]
Thanks for surfacing the issue @svrnm. So, WDYT? 😄

**Comment by svrnm** [comment]
It would keep the visitor within the concept pages, which might make more sense, yes. From there they have a jump off point to collector pages.

**Comment by cartermp** [comment]
Agreed with @svrnm
