### ISSUE TITLE
Documentation - Python

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#285]
Tracking issue for the Python documentation section. See `./templates/language-docs` for markdown templates.

Content should live at `./content/en/docs/python/`

- [x] Index
- [ ] Getting Started
- [ ] Instrumentation
- [ ] Export and Config

**Comment by svrnm** [comment]
Playing around also with the python part of the docs. I just checked if I can almost 1:1 copy from [javascript](https://github.com/open-telemetry/opentelemetry.io/issues/287) and "only" change the example code:

https://github.com/svrnm/opentelemetry.io/tree/master/content/en/docs/python

I think that works fairly well. I am still digging into hugo, but maybe it's even possible to reuse text/instructions and have things as similar as possible for different techs.

**Comment by austinlparker** [comment]
Python getting started docs exist, closing.
