### ISSUE TITLE
Codify common page weights

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2850]
Follow up to https://github.com/open-telemetry/opentelemetry.io/issues/2829: to avoid drift we should find a way to codify the page weights so that new pages have them set properly ootb or that existing pages are not changed by accident.

**Comment by svrnm** [comment]
@chalin question, would it be possible to use a variable for the weight, e.g. something like

```
---
title: Manual Instrumentation
linkTitle: Manual
weight: {{ .weights.manual }}
---
```

**Comment by chalin** [comment]
Unfortunately, Hugo doesn't support the use of template expressions in front matter. I'll need to think about a solution bit more.
