### ISSUE TITLE
New FaaS docs missing required lambda layer ARNs

### ISSUE THREAD

**Issue by pranavmarla** [open-telemetry/opentelemetry.io#2859]
Both the [lambda collector config doc](https://opentelemetry.io/docs/faas/lambda-collector/) as well as the [lambda auto-instrumentation doc](https://opentelemetry.io/docs/faas/lambda-auto-instrument/) tell the user to copy the ARN of the desired lambda layer, but the lambda layer ARNs are not actually provided anywhere.

As far as I can tell this means that as of now, since the documentation is missing such key information, this approach to monitoring lambdas is basically unusable.

**What needs to be changed?**
Documentation needs to include ARNs of available lambda layers for users to copy.

**What is the name + path of the page that needs changed?**
- Lambda Collector Configuration: https://opentelemetry.io/docs/faas/lambda-collector/
- Lambda Auto-Instrumentation: https://opentelemetry.io/docs/faas/lambda-auto-instrument/

**Comment by svrnm** [comment]
@pranavmarla can you verify that this is fixed with https://github.com/open-telemetry/opentelemetry.io/pull/2894?

**Comment by pranavmarla** [comment]
Hey @svrnm , thanks for reaching out! Yes, it looks like it's fixed now. Please feel free to close both this issue as well as my [duplicate issue](https://github.com/open-telemetry/opentelemetry-lambda/issues/747) in the opentelemetry-lambda repo
