### ISSUE TITLE
Documentation - .NET

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#286]
Tracking issue for the .NET documentation section. See `./templates/language-docs` for markdown templates.

Content should live at `./content/en/docs/dotnet/`

- [x] Index
- [ ] Getting Started
- [ ] Instrumentation
- [ ] Export and Config

**Comment by shelbyspees** [comment]
These docs now live in the [dotnet repo](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/getting-started), yes? Should this ticket get moved there?

**Comment by austinlparker** [comment]
I guess they're going to take care of it on release by updating these themselves? https://github.com/open-telemetry/opentelemetry-dotnet/pull/1951

**Comment by austinlparker** [comment]
I think we can probably close it out either way.
