### ISSUE TITLE
Documentation - JS (Browser + Node)

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#287]
Tracking issue for the JS documentation section. See `./templates/language-docs` for markdown templates.

Content should live at `./content/en/docs/js/`

- [ ] Index
- [ ] Getting Started
- [ ] Instrumentation
- [ ] Export and Config

_Note_: Browser and Node documentation should be shared where appropriate but split into subpaths where needed (i.e., `./content/en/docs/js/browser` and `./content/en/docs/js/node`)

**Comment by svrnm** [comment]
I will look into this: I can take the existing "Getting Started" guide from https://github.com/open-telemetry/opentelemetry-js/tree/master/getting-started copy it over and change it to fit the outlined template at https://docs.google.com/document/d/1YyGax0fXZau17hV0lePnGc0LDvKokjFqWb2AhdlbyO4/edit#

**Comment by austinlparker** [comment]
That sounds great!

**Comment by svrnm** [comment]
https://github.com/svrnm/opentelemetry.io/tree/master/content/en/docs/js

Not doing a PR yet, it's a big draft & playground as of now. Asking for feedback&thoughts:

- How much explaining should the guide do, or should it reference the specification as often as possible?

- The sample code lives in the docs now, at some point it could be helpful to have a repository holding all the tutorials (again taking rabbitmq as an example;-) -> https://github.com/rabbitmq/rabbitmq-tutorials/tree/master/javascript-nodejs)

- "Browser and Node documentation should be shared where appropriate but split into subpaths where needed" --> I just focused on Node.JS so far. The example in "Getting Started" is a simple webserver. Maybe there is a better example code that works in both browser/nodejs, will think about it.

**Comment by austinlparker** [comment]
I think the guide should do some explaining and cross-reference the conceptual docs that are coming into the site when needed. I like the idea of doing a big sample code repo, but I think for now we should reference the samples that are in the upstream repos as much as possible since they're most likely to be accurate.

**Comment by svrnm** [comment]
Okay. I'll work on it and do a Pull Request. I saw also that there has been some work done for the other languages, so I can also pick inspiration from there.

**Comment by austinlparker** [comment]
JS Getting Started docs exist, closing
