### ISSUE TITLE
PHP automatic instrumentation docs do not install everything they claim to

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry.io#2871]
I am not super experienced with PHP so I may be missing something here.

**What needs to be changed?**

The PHP autoinstrumentation page (https://opentelemetry.io/docs/instrumentation/php/automatic/#supported-libraries-and-frameworks) says

> Automatic Instrumentation comes with a number of instrumentation libraries for commonly used PHP libraries. For the full list, see [instrumentation libraries on packagist](https://packagist.org/search/?query=open-telemetry&tags=instrumentation).

However, the instructions in the page only install the `opentelemetry.so` extension which provides the hooking mechanism. I don't think this installs any of the API, SDK, exporters, instrumentations, etc. For example, [the example immediately after the installation instructions](https://opentelemetry.io/docs/instrumentation/php/automatic/#manual-setup-for-automatic-instrumentation) does not work.

**What is the name + path of the page that needs changed?**
`docs/instrumentation/php/automatic/#supported-libraries-and-frameworks`

**Additional context**: anything else you can think about that would be helpful.

**Comment by svrnm** [comment]
is this still valid, @aabmass @open-telemetry/php-approvers ?

**Comment by aabmass** [comment]
I'm not sure I'll defer to PHP folks, or we can just stale close this as it doesn't have any +1's in over a year

**Comment by bobstrecansky** [comment]
I believe this is fixed.
