### ISSUE TITLE
PHP OTLP Exporter documentation leads to exception

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry.io#2874]
**What needs to be changed?** Describe the update that is required.

Following the OTLP directions leads to an exception https://opentelemetry.io/docs/instrumentation/php/exporters/#otlp:

First `composer require open-telemetry/exporter-otlp`.

Then, following the "protobuf" tab in the code snippet, I ran this script
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use OpenTelemetry\Contrib\Otlp\OtlpHttpTransportFactory;
use OpenTelemetry\Contrib\Otlp\SpanExporter;
use OpenTelemetry\SDK\Trace\SpanProcessor\SimpleSpanProcessor;
use OpenTelemetry\SDK\Trace\TracerProvider;

$transport = (new OtlpHttpTransportFactory())->create('http://collector:4318/v1/traces', 'application/x-protobuf');
$exporter = new SpanExporter($transport);

?>
```
  
  Immediately fails with
  
  ```
  Fatal error: Uncaught LogicException: You cannot use the "Symfony\Component\HttpClient\Psr18Client" as the "psr/http-client" package is not installed. Try running "composer require php-http/discovery psr/http-client-implementation:*". in /app/vendor/symfony/http-client/Psr18Client.php:37
Stack trace:
#0 /app/vendor/composer/ClassLoader.php(576): include()
#1 /app/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/app/vendor/com...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 /app/vendor/php-http/discovery/src/ClassDiscovery.php(192): is_callable(Array)
#4 /app/vendor/php-http/discovery/src/ClassDiscovery.php(80): Http\Discovery\ClassDiscovery::evaluateCondition(Array)
#5 /app/vendor/php-http/discovery/src/Psr18ClientDiscovery.php(25): Http\Discovery\ClassDiscovery::findOneByType('Psr\\Http\\Client...')
#6 /app/vendor/open-telemetry/sdk/Common/Export/Http/PsrTransportFactory.php(69): Http\Discovery\Psr18ClientDiscovery::find()
#7 /app/vendor/open-telemetry/exporter-otlp/OtlpHttpTransportFactory.php(30): OpenTelemetry\SDK\Common\Export\Http\PsrTransportFactory::discover()
#8 /app/ex.php(10): OpenTelemetry\Contrib\Otlp\OtlpHttpTransportFactory->create('http://collecto...', 'application/x-p...')
#9 {main}
  thrown in /app/vendor/symfony/http-client/Psr18Client.php on line 37
  ```
  
I also tried the gRPC variant and it was much worse because you have to choose gRPC and protobuf implementsat

**What is the name + path of the page that needs changed?**

`docs/instrumentation/php/exporters/#otlp`

**Comment by svrnm** [comment]
@aabmass I think the issue is this:https://opentelemetry.io/docs/instrumentation/php/#dependencies

@open-telemetry/php-approvers PTAL

**Comment by brettmc** [comment]
Hi @aabmass 
can you detail the steps you followed to get all of your composer dependencies? I will probably need to update our doco, but I'd like to retrace your steps: how did you get symfony http client? Was it auto-installed by `php-http/discovery` scripts?

**Comment by brettmc** [comment]
Thanks @aabmass 
So this is a two-parter:

Firstly, whilst we are in beta you need to set minimum-stability to dev/beta as @svrnm said earlier. Perhaps we need to update our documentation to call that our more loudly. I think it's a quirk of composer that `0.0.1` is considered stable and installed before `1.0.0beta`, and it keeps tripping up our early adopters and beta testers.

Once you fix that and get the most recent versions, it's still broken due to the default http client installed by `php-http/discovery` having an unmet dependency on `psr/http-client`.
It would be easy enough for us to add that as an SDK dependency, but I feel like it's something that should be addressed upstream. I created https://github.com/php-http/discovery/issues/248 so let's see what they say.

**Comment by svrnm** [comment]
> Perhaps we need to update our documentation to call that our more loudly.

We can have a call out on every (relevant) page that we drop the moment PHP is out of beta.

**Comment by brettmc** [comment]
> We can have a call out on every (relevant) page that we drop the moment PHP is out of beta.

I've added an alert to the getting-started page: https://github.com/open-telemetry/opentelemetry.io/pull/2883 - not sure if I should assume everybody read the getting started page first, though.

@aabmass I've got a PR in to add psr/http-client as an SDK dependency (which really should have been there all along, now that I've looked again). There's also a PR against the discovery package to ensure you get `psr/http-client` when it auto-installs symfony http client.

**Comment by aabmass** [comment]
Nice, really appreciate you tracking everything down :)

**Comment by theletterf** [comment]
What's the current status?

**Comment by brettmc** [comment]
Resolved, and can be closed now.
