### ISSUE TITLE
Open Telemetry - Clarifications

### ISSUE THREAD

**Issue by banandh** [open-telemetry/opentelemetry.io#2881]
I have enabled automatic instrumentation in the java application and able to view metrics and traces in the respective backends. Have below questions related to productionizing this solution.

1. What will happen if the Otel Collector is not reachable by the application. Will the telemetry data lost or any other config options to collect those failures and retry from application?

2.How to ensure high availability of this Otel collector in production?

3. Do we have any agent for informix & Kafka

4. DO we have the automatic instrumentation jar kind of implementation for CPP applications?

**Comment by svrnm** [comment]
Thank you for your questions @banandh! I'll try to give some guidance here, but in general we recommend that you ask questions via StackOverflow (with tags opentelemetry) or in the CNCF slack channels #opentelemetry or those related to your question (e.g. #otel-java)

> I have enabled automatic instrumentation in the java application and able to view metrics and traces in the respective backends. Have below questions related to productionizing this solution.
> 
> 1. What will happen if the Otel Collector is not reachable by the application. Will the telemetry data lost or any other config options to collect those failures and retry from application?

Assuming you use the OTLP exporter, the spec provides some guidance for language specific implementations here:

https://github.com/open-telemetry/opentelemetry-specification/blob/37ab6b056172ad36d31ce217927e47bbe031d831/specification/protocol/exporter.md#retry

How this is implemented for java specifically is a question you should ask the java community.

> 2.How to ensure high availability of this Otel collector in production?

https://opentelemetry.io/docs/collector/deployment/gateway/

> 3. Do we have any agent for informix & Kafka

What do you mean by agent in this context?

> 4. DO we have the automatic instrumentation jar kind of implementation for CPP applications?

No, c++ is manual instrumentation only.

**Comment by banandh** [comment]
Do we have any agent for informix & Kafka
What do you mean by agent in this context?

> Thank you for your questions @banandh! I'll try to give some guidance here, but in general we recommend that you ask questions via StackOverflow (with tags opentelemetry) or in the CNCF slack channels #opentelemetry or those related to your question (e.g. #otel-java)
> 
> > I have enabled automatic instrumentation in the java application and able to view metrics and traces in the respective backends. Have below questions related to productionizing this solution.
> > 
> > 1. What will happen if the Otel Collector is not reachable by the application. Will the telemetry data lost or any other config options to collect those failures and retry from application?
> 
> Assuming you use the OTLP exporter, the spec provides some guidance for language specific implementations here:
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/37ab6b056172ad36d31ce217927e47bbe031d831/specification/protocol/exporter.md#retry
> 
> How this is implemented for java specifically is a question you should ask the java community.
> 
> > 2.How to ensure high availability of this Otel collector in production?
> 
> https://opentelemetry.io/docs/collector/deployment/gateway/
> 
> > 3. Do we have any agent for informix & Kafka
> 
> What do you mean by agent in this context?
    To support automatic instrumentation , we have agent jar for Java based application , similarly do we have any way for checking the informix and Kafka telemetry data using open telemetry collector?
> > 4. DO we have the automatic instrumentation jar kind of implementation for CPP applications?
> 
> No, c++ is manual instrumentation only.

**Comment by svrnm** [comment]
@banandh it looks like your previous answer is incomplete as it only takes some quotes from previous comments.
