### ISSUE TITLE
Sentence in docs for tracing does not make sense

### ISSUE THREAD

**Issue by svsk417** [open-telemetry/opentelemetry.io#2887]
Hello! :) 
**What needs to be changed?** 
The sentence 
"Each Context object is associated with a span and can be accessed specification on spans." 
in 
https://github.com/open-telemetry/opentelemetry.io/blame/ec41fee5d43eb04e0005dba2898d77fef8e6c892/content/en/docs/concepts/signals/traces.md#L157 
does not make sense.

**What is the name + path of the page that needs changed?** 
https://opentelemetry.io/docs/concepts/signals/traces/#context-propagation

**Additional context**: 
Better describe how the association between "Trace Context" and "Span Context" is established.

**Comment by cartermp** [comment]
Rewrote a bit in here: https://github.com/open-telemetry/opentelemetry.io/pull/2891
