### ISSUE TITLE
Overview: define OTLP on first use?

### ISSUE THREAD

**Issue by kDot** [open-telemetry/opentelemetry.io#2890]
Refering to diagram on main page https://opentelemetry.io/docs/

Short form OTel is explained in text and used in diagram, BUT
OTLP (guessing OpenTelemetryProtocol) is only used in diagram but not introduced for the reader.

**Comment by svrnm** [comment]
Thank you for raising this @kDot. Do you have yourself any suggestions how to improve? Feel free to provide it via a PR

**Comment by kDot** [comment]
I did not want to come up with a solution but rather want to point out a very minor issue. But as you have asked for PR, here we go..

I could have added OTLP into the textual representation but as i am a fan keep things simple, i just removed the OTLP from the arrows in the svg.
The term is still introduced in the documentation quite early (https://opentelemetry.io/docs/what-is-opentelemetry/).
