### ISSUE TITLE
npm run failure

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2897]
_Originally posted by @cartersocha in https://github.com/open-telemetry/opentelemetry.io/issues/2894#issuecomment-1599778584_

> @cartermp I did and it fails 😢 Initial debugging didn't raise any obvious issues. I'm on a Mac M2 and tried it on an M1. Tried a fresh fork. 
> <img width="933" alt="Screenshot 2023-06-20 at 5 27 09 PM" src="https://github.com/open-telemetry/opentelemetry.io/assets/43380952/715c5a60-38ae-489c-932f-5e8099c49887">

**Comment by svrnm** [comment]
@cartersocha can you share some additional details, e.g. what version of nodejs are you using? when you say you started from a clean fork, what commands have you run before going through `npm run test`

**Comment by cartermp** [comment]
Yeah, I don't have an M2 mac, but on M1 and cloud environments it all works for me.

**Comment by chalin** [comment]
So this error appears on M2 macs only?

**Comment by cartersocha** [comment]
My work laptop is a m1. Upgraded from 19.7 js to latest and hugo from 111 to 114. Still happening. I found some vaguely related threads but no obvious solution. https://discourse.gohugo.io/t/tocss-failed-to-transform/43057

initial log

"> _build
> hugo --cleanDestinationDir -e dev -DFE

Start building sites … 
hugo v0.114.1+extended darwin/arm64 BuildDate=unknown

ERROR render of "page" failed: "/Users/carter.socha/opentelemetry.io/layouts/_default/baseof.html:19:7": execute of template failed: template: _default/single.html:19:7: executing "_default/single.html" at <partialCached "scripts.html" .>: error calling partialCached: "/Users/carter.socha/opentelemetry.io/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR render of "page" failed: "/Users/carter.socha/opentelemetry.io/themes/docsy/layouts/blog/baseof.html:33:7": execute of template failed: template: blog/single.html:33:7: executing "blog/single.html" at <partial "scripts.html" .>: error calling partial: "/Users/carter.socha/opentelemetry.io/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR render: failed to render pages: render of "page" failed: "/Users/carter.socha/opentelemetry.io/layouts/_default/baseof.html:19:7": execute of template failed: template: _default/search.html:19:7: executing "_default/search.html" at <partialCached "scripts.html" .>: error calling partialCached: "/Users/carter.socha/opentelemetry.io/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
Total in 1550 ms
Error: error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): "/Users/carter.socha/opentelemetry.io/themes/docsy/assets/scss/main.scss:1:1": File to import not found or unreadable: ../vendor/bootstrap/scss/functions.
ERROR: "check:links" exited with 1."

**Comment by chalin** [comment]
@cartersocha - We've had issues in the past when the officially supported version of Node (`lts/*`, that is, v18) isn't used. Could you run the following commands from your repo directory -- save all local changes first:

```sh
git clean -xdf
nvm install # v18
nvm use # switch to v18
npm install
npm run test
```

**Comment by cartersocha** [comment]
@chalin worked like a charm! Thanks guy
