### ISSUE TITLE
Questioning language support section for logs and metrics

### ISSUE THREAD

**Issue by longility** [open-telemetry/opentelemetry.io#2898]
https://opentelemetry.io/docs/concepts/signals/logs/#language-support The language support for logs pertain to metrics and should be specific to logs.

However, do we update this to be logs or should we remove language support for both logs and metrics? I think to have less documentation to maintain at this time, I would remove or at least reference this perhaps: https://opentelemetry.io/docs/instrumentation/#status-and-releases

Thoughts?

**Comment by svrnm** [comment]
That's a copy & paste error mostly, so thanks for catching it. The table is filled from a central place so it's not a lot of additional maintenance overhead. I added it just recently to provide guidance to people from different places.

**Comment by svrnm** [comment]
@longility can we close this issue?

**Comment by longility** [comment]
I am not familiar with the accuracy and overall direction of documentation. If y'all are familiar and believe it is handled. By all means close! I merely pointed out an obvious mistake.

**Comment by cartermp** [comment]
I believe this should be fixed based on the PR, yes.
