### ISSUE TITLE
Link to OpenTelemetry approach in instrumentation/php/manual.md is broken

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry.io#2902]
On page https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/instrumentation/php/manual.md, section [Logging](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/instrumentation/php/manual.md#logging), the link to OpenTelemetry approach is broken: https://github.com/open-telemetry/opentelemetry.io/blob/main/docs/concepts/signals/logs

**Comment by svrnm** [comment]
The links in the markdowns don't work, as they are designed to work on the website:

https://opentelemetry.io/docs/concepts/signals/logs/

As far as I remember there is not much we can do about that, so reading the docs on github is not recommended. 

@chalin any thoughts?

**Comment by chalin** [comment]
> The links in the markdowns don't work, as they are designed to work on the website:
> 
> https://opentelemetry.io/docs/concepts/signals/logs/
> 
> As far as I remember there is not much we can do about that, so reading the docs on github is not recommended.

@svrnm summarized it well: pages are meant to be viewed and navigated from on the production server. Our link checker ensures that we don't have any broken links in production. Closing.
