### ISSUE TITLE
span links - casually or causally?

### ISSUE THREAD

**Issue by david-hodgson-at-sky** [open-telemetry/opentelemetry.io#2903]
The page https://opentelemetry.io/docs/instrumentation/python/manual/

says "span links that causally link it" and in the example code "The link in 'span-2' is casually associated".  Which is correct/

I think it should be causally (ref: [Span Links](https://opentelemetry.io/docs/concepts/signals/traces/#span-links) "Links exist so that you can associate one span with one or more spans, implying a causal relationship") but I don't have rights to edit the page nor the necessary depth of knowledge.

**Comment by svrnm** [comment]
Yes, I think this should be `causally`, feel free to raise a PR to fix it, thanks!
