### ISSUE TITLE
Drop 1.21.0 schema

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#2923]
The schema was published by mistake. For context, see:

- https://github.com/open-telemetry/opentelemetry-specification/issues/3572
- https://github.com/open-telemetry/opentelemetry.io/pull/2918#discussion_r1245161004
  > Ok, that's news to me. It has been served since the OTel spec 1.21.0 was released in May. Back then the website served whatever schemas are found under the OTel spec's schemas folder and no one from the specs team has informed us otherwise.

**Comment by jsuereth** [comment]
Thanks @chalin !

**Comment by chalin** [comment]
@jsuereth - let me know if there is anything else to be done here relative to the schemas.
