### ISSUE TITLE
Consider switching license to CC BY 4.0

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry.io#294]
k8s documentation uses a different license for the website.

**Comment by austinlparker** [comment]
Let me look into this, I think it'd be fine.

**Comment by austinlparker** [comment]
See https://github.com/open-telemetry/community/issues/565 for tracking.

**Comment by austinlparker** [comment]
This change has been approved by the GC to apply to the creative work (documentation, visual assets, etc.) Apache 2 remains the license for the technical work (code, etc.)
