### ISSUE TITLE
Move Adopters from community repo to website?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry.io#2947]
**Desired feature or idea**:

Move [ADOPTERS.md](https://github.com/open-telemetry/community/blob/main/ADOPTERS.md) from the community repo to the website, as a new section under https://opentelemetry.io/ecosystem/.

**Additional context**: The list of adopters is currently buried in the community repo and not many people update it. I originally raised the question whether we should remove it since it's not being used much, but it turns out list of adopters is a CNCF graduation requirement.

cc @open-telemetry/governance-committee 

---

Tasks: 

- [x] Move [ADOPTERS.md](https://github.com/open-telemetry/community/blob/main/ADOPTERS.md) to this repo - #2961
- [ ] Remove it from https://github.com/open-telemetry/community - https://github.com/open-telemetry/community/pull/1570

**Comment by chalin** [comment]
Related:

- #2178

Moving the file to this repo and surfacing the page on the website makes sense to me! Just say when :).

**Comment by svrnm** [comment]
+1

**Comment by svrnm** [comment]
@trask / @open-telemetry/governance-committee is it mandatory to have that adopters list live on the /community github repo or can we have it on the website?

Having Adopters here would be my preferred place:

https://opentelemetry.io/ecosystem/

**Comment by svrnm** [comment]
> > is a CNCF graduation requirement.
> 
> Oh no, I foresee a marketing push to get the countless orgs that adopt it to put their name somewhere

The question is how high we set the bar, e.g. what about requiring people to have a blog post published about OTel or any other evidence of their adoption?

**Comment by trask** [comment]
> Moving the file to this repo and surfacing the page on the website makes sense to me! Just say when :).

I think we're good to go

> @trask / @open-telemetry/governance-committee is it mandatory to have that adopters list live on the /community github repo or can we have it on the website?

I believe we can just move it and remove it from community repo

> what about requiring people to have a blog post published about OTel or any other evidence of their adoption?

I personally like this because it makes the adopters page much more interesting when you can dive in and read their blog posts

**Comment by yurishkuro** [comment]
+1 to require a link to a blog post

**Comment by yurishkuro** [comment]
> Oh no, I foresee a marketing push to get the countless orgs that adopt it to put their name somewhere

Sounds like a good thing, for the project.

**Comment by austinlparker** [comment]
> > Oh no, I foresee a marketing push to get the countless orgs that adopt it to put their name somewhere
> 
> Sounds like a good thing, for the project.

Yes, it is. A blog post (or at least a footnote identifying how they 'adopt' it - prod, preprod, etc?) would be great.
