### ISSUE TITLE
Links in "Configuration" page are broken

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry.io#2949]
Links in "Configuration" page are broken:

![image](https://github.com/open-telemetry/opentelemetry.io/assets/4345663/2250686a-26ec-4001-bcb8-a5d0c4893435)

Looking at the page I'm not sure what is wrong, maybe rendering because of the images?

**Comment by svrnm** [comment]
Thanks for calling this out @tomkerkhove, it seems to be a markdown bug (?)

**Comment by chalin** [comment]
Dang! Looking into this.

**Comment by chalin** [comment]
Thanks for reporting this @tomkerkhove.

**Comment by tomkerkhove** [comment]
That's fast, thanks!
