### ISSUE TITLE
Observability Primer

### ISSUE THREAD

**Issue by AndrewWPhillips** [open-telemetry/opentelemetry.io#2962]
The observability primer says:
> Reliability answers the question: “Is the service doing what users expect it to be doing?”

There are various definitions of reliability as a software quality attribute (eg see https://www.softwaretestinghelp.com/what-are-the-quality-attributes/#1_Reliability) but what that paragraph is talking about what is universally called "correctness" not "reliability".

As for the example, if selecting black plants _always_ gives red pants that is a defect in the software (ie bug) or more likely config and is an example of lack of "correctness".  If selecting black plants has unpredictable results (red pants, shoes, or something else) then that is an exmaple of lack or "reliability".

**Comment by cartermp** [comment]
Addressed by https://github.com/open-telemetry/opentelemetry.io/pull/2964

I...don't know if I completely agree with you here, but I do think the example could be made more clear so as not to imply that it always adds red pants instead of black pants.
