### ISSUE TITLE
Registry search breaks markdownify

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2979]
**What happened?** 

Go to https://opentelemetry.io/ecosystem/registry/, verify that descriptions are successfully "markdownified", e.g. use the browser search option (!) to look for  github.com/jinzhu/gorm

If I now use the search engine of the website (e.g. putting in gorm), the results are not "markdownified" any more:

https://opentelemetry.io/ecosystem/registry/?s=gorm&component=&language=

**What did you expect would happen?** 

Search should not break the formatting of descriptions

**Comment by svrnm** [comment]
@chalin FYI

**Comment by chalin** [comment]
Duplicate of

- #2491
