### ISSUE TITLE
List of sample native instrumented libs/frameworks

### ISSUE THREAD

**Issue by damienburke** [open-telemetry/opentelemetry.io#2992]
**Desired feature or idea**: What would you like to see happen?
I would like to see a list, ideally driven by a registry, where folks can share there native otel libs, etc.

**Additional context**: anything else you can think about that would be helpful.
This page might be less confusing then - https://opentelemetry.io/docs/concepts/instrumentation/libraries/
I am 99% sure that none of https://opentelemetry.io/ecosystem/registry/?component=instrumentation&language=java would be classified as Native Otel libs. Yet this page does provide a lot of info around how to go about creating such a lib. That said, these instructions are pertinent to both Otel-ifying libs natively AND  via "library hooks or monkey-patching library code"

**Comment by svrnm** [comment]
> I would like to see a list, ideally driven by a registry, where folks can share there native otel libs, etc.

The registry is for sure a place where we should have those as well, maybe we can come up with some good tagging for them that shows "look this thing has native OpenTelemetry"

Beyond that, we wanted to update/improve [Integrations](https://opentelemetry.io/ecosystem/integrations/) eventually as a page where such kind of native otel support can be showed off (e.g. I am not sure if we should have k8s or docker buildx in the registry as "supports otel natively"

**Comment by svrnm** [comment]
https://opentelemetry.io/ecosystem/integrations/ provides this now, the registry also has a feature to set an entry is "native"
