### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by runtu666** [open-telemetry/opentelemetry.io#2993]
<img width="899" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/32669202/20507b7c-6272-4003-9e30-71bbddb72528">

Are these metrics already set up for us? Or do we need to implement it ourselves

**Comment by runtu666** [comment]
@cartermp I just want to ask a question, that is, if we have access to the metrics SDK, are the indicators I have screenshots already implemented in the SDK or do I need to define these indicators by myself and implement them?

**Comment by cartermp** [comment]
Ah, I see. No, these are just examples of things you can capture with metrics. I don't believe that there are any components that capture all of these automatically. There are some components, such as the opentelemetry hostmetrics receiver, that will capture some of that information.

**Comment by runtu666** [comment]
ok get it ,thank you

**Comment by runtu666** [comment]
@cartermp 
1. Is it necessary to monitor and alarm for tracing, and if so, how should it be done? Which indicators should be alerted? Or is it just a means to troubleshoot problems, and check the tracing after there are error logs and performance monitoring alarms (Prometheus)
2. Can span be directly calculated as metrics?
