### ISSUE TITLE
Textlint: add rule for ID

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3001]
From [The Chicago Manual of Style](https://www.chicagomanualofstyle.org/search.epl?ShowNext=1&q=initialism&site=bblive&client=live&output=xml_no_dtd&proxystylesheet=cmosdev&filter=0&proxyreload=1&search_edition=16&total=54&first=11&last=20&prv_set=10&nxt_set=10#:~:text=According%20to%20CMOS%2C%20%22ID%22,capitalized%20and%20used%20without%20periods.):

> "ID" is an initialism (http://www.chicagomanualofstyle.org/16/ch10/ch10_sec002.html) and should be capitalized and used without periods.

**Comment by svrnm** [comment]
👍 ... while looking for the PHP stuff I saw that the textlint plugin also has some defaults you can load:

https://github.com/sapegin/textlint-rule-terminology/blob/master/terms.jsonc

We could enable it and see if it fits?

**Comment by chalin** [comment]
Sure, let's give it a try. If we adopt it, we can trim our own ruleset.

**Comment by svrnm** [comment]
fixed
