### ISSUE TITLE
Searches in registry result in duplicated items

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry.io#302]
Steps to reproduce: Search for anything for example `splunk`

Behavior: Every entry listed twice

Expected behavior: Entry only listed once

**Comment by jaoord** [comment]
This appears to be fixed. Tested with https://opentelemetry.io/registry/?s=splunk

![image](https://user-images.githubusercontent.com/6464609/102195097-6d191200-3ebe-11eb-89fa-942a040015c7.png)

Or am I missing something?

**Comment by bogdandrutu** [comment]
@flands Ping, please close the issue if fixed

**Comment by flands** [comment]
yes, fixed!
