### ISSUE TITLE
Blog post GraphQL & OpenTelemetry

### ISSUE THREAD

**Issue by SonjaChevre** [open-telemetry/opentelemetry.io#3054]
Hi! I'm the author of this blog post about OpenTelemetry and GraphQL: https://tyk.io/blog/observing-graphql-errors-with-opentelemetry/

I'd like to submit it to be published on the opentelemetry blog. 
Would that be ok? Happy to work on the pull request if so.

thanks in advance!
Sonja

**Comment by svrnm** [comment]
Hey @SonjaChevre,

thanks for checking in before raising a PR for the blog post. It's good to discuss this first. We had a blog post around GraphQL in the past (https://opentelemetry.io/blog/2023/end-user-q-and-a-01/) already, but in general I don't see an issue with picking this topic up once again. 

Reading through your blog post, I stumbled upon 2 things:

First:

> Unfortunately, when using the [GraphQL instrumentation library for node.js](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-graphql), GraphQL errors are not reported automatically. If you look at the distributed trace for that transaction, it doesn’t contain any information about that error.

I would assume that this is something the OpenTelemetry JS community is able to fix upstream, have you checked if there is an open issue with https://github.com/open-telemetry/opentelemetry-js-contrib/ to fix this? If not, please raise one and maybe even provide a PR for it?

Second:

> Lucky for us, the OpenTelemetry projects make it very easy to generate RED metrics from OpenTelemetry traces by configuring the span metrics connector on the OpenTelemetry collector.

I don't see any configuration for that in your blog post, can you share them please? I am also curious what is special around GraphQL in this context?

**Comment by SonjaChevre** [comment]
hey @svrnm - thanks for the quick answer!

First:

about the GraphQL errors not being reported, I thought this might need to be discussed at the semantic conventions level and already opened an issue to get better semantic conventions for GraphQL here: https://github.com/open-telemetry/semantic-conventions/issues/182

Any recommendation from your side? Happy to enter something specific for the javascript instrumentation. 

Second:

> I don't see any configuration for that in your blog post, can you share them please? 

Happy to add the configuration for that in the blog post version to be published on the OTel blog. 

> I am also curious what is special around GraphQL in this context?

In that specific example, there is nothing that special - just a reminder for people that are unaware of the span metrics connector that it is very helpful to generate metrics from your traces. As I do find most people that get started with OTel don't know about it. 

But this deserves a follow up for GraphQL (maybe another blog post): it is not enough to generate RED metrics for the GraphQL server. As a GraphQL server is like a database, its performance depends highly on the queries that user are sending to you. Some users might overload your server by sending them "bad" queries. So it might be more helpful to monitor RED metrics based on your queries (if small number of different queries - because it is only been used by 1 internal application), by API client (if your GraphQL endpoint is available externally) or even by resolver (function that determines how to retrieve the data for a specific field in a GraphQL query and maps it to the corresponding data source).

Actually this topic was mentioned today on the cncf slack in the opentelemetry channel: https://cloud-native.slack.com/archives/CJFCJHG4Q/p1689916250365829

**Comment by svrnm** [comment]
> hey @svrnm - thanks for the quick answer!
> 
> First:
> 
> about the GraphQL errors not being reported, I thought this might need to be discussed at the semantic conventions level and already opened an issue to get better semantic conventions for GraphQL here: [open-telemetry/semantic-conventions#182](https://github.com/open-telemetry/semantic-conventions/issues/182)
> 
> Any recommendation from your side? Happy to enter something specific for the javascript instrumentation.

Since the main use case in the blog post is error reporting, I would suggest that you check how far you get with existing semantics for errors&exceptions:

https://github.com/open-telemetry/semantic-conventions/blob/main/docs/exceptions/README.md

Apply those changes to the Node.JS implementation and bring it to the JavaScript community. 

> We have only tried the Node.js instrumentation so far, but noticed that this library doesn’t respect the semantic conventions.

Apparently there is also some work that needs to be done here.

Don't get me wrong, the current blog post on the Tyk website adds values to end-users of OpenTelemetry and this is appreciated, as it calls out a deficit with the current implementation and how you can fix it yourself _easily_. But since this is the OpenTelemetry blog by the OpenTelemetry community we should rather fix this deficit and then have a blog post about what otel can do for GraphQL.

> Second:
> 
> > I don't see any configuration for that in your blog post, can you share them please?
> 
> Happy to add the configuration for that in the blog post version to be published on the OTel blog.

Thanks.

> > I am also curious what is special around GraphQL in this context?
> 
> In that specific example, there is nothing that special - just a reminder for people that are unaware of the span metrics connector that it is very helpful to generate metrics from your traces. As I do find most people that get started with OTel don't know about it.

Fair point, but then it might be worthwhile to put it into the collector documentation somewhere. 

> But this deserves a follow up for GraphQL (maybe another blog post): it is not enough to generate RED metrics for the GraphQL server. As a GraphQL server is like a database, its performance depends highly on the queries that user are sending to you. Some users might overload your server by sending them "bad" queries. So it might be more helpful to monitor RED metrics based on your queries (if small number of different queries - because it is only been used by 1 internal application), by API client (if your GraphQL endpoint is available externally) or even by resolver (function that determines how to retrieve the data for a specific field in a GraphQL query and maps it to the corresponding data source).
> 
> Actually this topic was mentioned today on the cncf slack in the opentelemetry channel: [cloud-native.slack.com/archives/CJFCJHG4Q/p1689916250365829](https://cloud-native.slack.com/archives/CJFCJHG4Q/p1689916250365829)

Why not have all of that in one blog post? The current blog post is very sparse and what you outlined here is what I would find interesting to learn: all those things that are special for GraphQL.

**Comment by SonjaChevre** [comment]
All good feedback, appreciate the thoughtful comments and explanations.

The reason the blog post is very sparse is because most of our users come from the API/GraphQL world and OTel is still very new to them. Don't want to overwhelm them. 

But I get your point that OTel blog post readers are a different audience and will have different expectations.

Let me sit on your feedback for a couple of days and come back with a new proposal.

**Comment by svrnm** [comment]
@SonjaChevre I will close this issue now, feel free to open a new one or bring a PR with a blog post if you still want to continue on this topic
