### ISSUE TITLE
Improve doc on `Bring your own backend` section.

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry.io#3065]
**What needs to be changed?** 

This section needs to be update: https://opentelemetry.io/docs/demo/kubernetes-deployment/#bring-your-own-backend

After discussing this PR https://github.com/open-telemetry/opentelemetry.io/pull/2876 with the SIG team, we have decided to update the docs instead of adding a new pipeline to the demo.
Creating this issue to track it.

**Comment by theletterf** [comment]
Any update?

**Comment by julianocosta89** [comment]
I don't think this change is still necessary.
Closing it, but feel free to re-open it.
