### ISSUE TITLE
Meeting recording icon not valid

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3067]
_Originally posted by @svrnm in https://github.com/open-telemetry/opentelemetry.io/pull/2636#discussion_r1270364821_
            
> <img width="919" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/3d47f4dc-ba0e-42f2-8036-db90e573f696">

I had assumed that the icon would be valid, but apparently it isn't:

> <img width="315" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/c857c353-c0f7-44b2-b2cf-f6b95da7385d">

/cc @svrnm @mattmccleary

**Comment by svrnm** [comment]
oh... I used the fontawesome v4 search and not the recent one, let me fix that
