### ISSUE TITLE
Need architecture diagrams in documentation

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry.io#308]
People should know what the architecture of OpenTelemetry looks like. This includes:

- Instrumentation library components
- Collector components
- Reference architecture

**Comment by flands** [comment]
Here is a proposal: https://docs.google.com/presentation/d/1UvN_ag52n3FVqOr4T7vtU6ohLidz74SntVVcCK0rxJ0/edit?usp=sharing

**Comment by austinlparker** [comment]
Could you change sharing settings on that, I can't access it @flands

**Comment by flands** [comment]
@austinlparker thought I had... try now!

**Comment by austinlparker** [comment]
Ah, yep, I can see it now.

**Comment by Ella-bz** [comment]
![Diagram 2](https://user-images.githubusercontent.com/73476445/98817938-906e1e80-2433-11eb-8765-5e8730d760a8.jpg)

Guys. Made one diagram from the presentation. Is that ok? or I need to change something?

**Comment by Ella-bz** [comment]
![image](https://user-images.githubusercontent.com/73476445/98953671-a3e9ba00-2505-11eb-8b94-a9ca3a2a3847.png)
update. need for feedback

**Comment by austinlparker** [comment]
Looks nice - @flands are the 'back-ends' supposed to be analysis tools (jaeger, splunk, etc)? Might be better to label them as 'Jaeger' and 'Prometheus' in the reference architecture diagram.

**Comment by flands** [comment]
Nice! Yes, the back-ends would be analysis tools. The metrics line is easy: prometheus. The metrics + traces line may be tricky... perhaps just change it traces and make it go to Jaeger?

**Comment by flands** [comment]
> ![Diagram 2](https://user-images.githubusercontent.com/73476445/98817938-906e1e80-2433-11eb-8765-5e8730d760a8.jpg)
> 
> Guys. Made one diagram from the presentation. Is that ok? or I need to change something?

looks great! one nit would be that receivers, processors, exporters, and extensions are all components however in the diagram they are represented differently (receivers/exporters are non-filled dotted lines while others are solid filled solid line).

one other nit that is likely very hard to address is that both receivers and exporters are push or pull based -- the icons make it seem like it is one direction. I do not have any solutions to this problem though...

**Comment by Ella-bz** [comment]
Is it more correct that way?
![image](https://user-images.githubusercontent.com/73476445/99233442-e8be6b00-27fb-11eb-839b-79f8f0ee14b0.png)

**Comment by flands** [comment]
> Is it more correct that way?
> ![image](https://user-images.githubusercontent.com/73476445/99233442-e8be6b00-27fb-11eb-839b-79f8f0ee14b0.png)

This one is more consistent, but now pipelines are hard to read -- other one is likely better. Really nice, thanks!!

**Comment by jkowall** [comment]
Forgot about this PR for a bit, @austinlparker when do you want to incorporate into docs or should I submit PRs?

**Comment by austinlparker** [comment]
if you've got the time to add them to the docs that'd be fantastic!

**Comment by jkowall** [comment]
I would be happy to, but I need to understand how to contribute/change things on that side or how the build/release process works. If you can provide that I can do that or find someone over here to make the changes to the docs and or the site.

**Comment by austinlparker** [comment]
https://github.com/open-telemetry/opentelemetry.io/blob/main/CONTRIBUTING.md has some instructions on how to get set up for development.

**Comment by flands** [comment]
This should mostly be addressed in #393 and #399. A few issues were uncovered and are tracked in #392, #409 and #411

**Comment by cartermp** [comment]
I think we've got this more or less covered now with the work here and in recent updates, such as in https://opentelemetry.io/docs/

I think we could probably add more diagrams to help things, but we've got some now and I think we could track the need for topic-specific ones in separate issues.
