### ISSUE TITLE
Libraries Status: Node.js vs Javascript

### ISSUE THREAD

**Issue by mayurkale22** [open-telemetry/opentelemetry.io#31]
Navigate to [https://opentelemetry.io/](https://opentelemetry.io/) and look for **Status** item, in the list of libraries you will see the Node.js and Javascript. I think we should only keep one, which is **Javascript**.

**Comment by austinlparker** [comment]
Given that the JS project will support both, yeah, this makes sense to me. I'll adjust it. Thanks!
