### ISSUE TITLE
Concept page "Traces" needs clarifications

### ISSUE THREAD

**Issue by varmehta** [open-telemetry/opentelemetry.io#3105]
- The introduction of spans is arbitrary. While 1st para talks a bit about tracers, immediately 3 spans are introduced. This is full of friction & a clear explanation would be helpful for people.
- The correlation between spans is not explicitly mentioned. It is left to the reader to figure out that `hello span` is parent to rest of the 2 spans.
- Also, re-ordering of spans with the hello span at the top would be helpful

**Comment by svrnm** [comment]
@varmehta thanks for raising this issue, I assume you are referring to https://opentelemetry.io/docs/concepts/signals/traces/ ?

**Comment by varmehta** [comment]
Yes 👍

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by svrnm** [comment]
Going through that page, yes I agree with some of your feedback. If you have any suggestions to improve, feel free to raise a PR.

**Comment by mercybassey** [comment]
Based on my research on Traces in OpenTelemetry, a trace represents the complete path of a request through a distributed system, while a span signifies a specific operation or event within that trace. In the documentation on the Traces page, a paragraph briefly explains what traces are, followed by code snippets for three spans. However, these spans are presented without proper introduction, potentially hindering readability. This oversight poses a challenge in terms of ensuring straightforward comprehension. I can work on this, @svrnm. I'll refine the content and create a Pull Request.

**Comment by mercybassey** [comment]
see #3202

**Comment by cartermp** [comment]
This should be resolved now in https://github.com/open-telemetry/opentelemetry.io/pull/3202
