### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by mtwo** [open-telemetry/opentelemetry.io#312]
I noticed that neither opentelemetry.io nor the Medium blog rank in the first two pages of Google or Bing search results for 'opentelemetry'. We should find a way to improve our rankings for both.

**Comment by austinlparker** [comment]
I think our best bet there is gonna be getting more content up on the site, and having it linked to from other places, right?

**Comment by mtwo** [comment]
I think so as well, I’m just wondering if there’s any actions that we could take like meta tags or more links back to the site from GitHub (we already do this).

________________________________

**Comment by austinlparker** [comment]
Oh, it seems like one problem might be that I've got something configured incorrectly and a lot of pages are set to NOINDEX, NOFOLLOW in the robots meta. Lemme tweak that.

**Comment by austinlparker** [comment]
Ok #316 flipped the robots flag, so we should at least be getting indexed now.

**Comment by austinlparker** [comment]
it's been about a week and it looks like that helped a boatload - 'opentelemetry' now ranks #1 on bing/google (private window), and 'opentelemetry blog' is also #1 for our medium page.

**Comment by austinlparker** [comment]
It's been a few more weeks, I think this is sorted out. We're getting the top spot on google/bing/whatever now.
