### ISSUE TITLE
Style issue in Collector "building" pages

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3146]
For example, see https://opentelemetry.io/docs/collector/trace-receiver/#reading-and-validating-your-receiver-settings:

> <img width="707" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/2035c63c-24c7-47b0-8efc-0812fa85bc38">

Notice the lack of space between the code block and the "check your work" callout.

/cc @svrnm

**Comment by mayankag32** [comment]
Hi @chalin, I would like to work on this issue. I think @svrnm suggestion [PR ](https://github.com/open-telemetry/opentelemetry.io/issues/3146)- would fix the issue.
