### ISSUE TITLE
Add performance optimization docs

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry.io#3153]
Splunk has a decent doc on how to evaluate the performance overhead of the OTel Java Agent:
https://docs.splunk.com/Observability/gdi/get-data-in/application/java/performance.html

I think it would be great if OTel had similar content on our doc site. Jason suggested Splunk could possibly contribute their content. 

cc @theletterf @breedx-splk

**Comment by svrnm** [comment]
+1 for these ones as well :-)

**Comment by cartermp** [comment]
Yep, contributions welcome for this. I'd say that a new doc called "Performance" under the "Automatic" folder would work.

**Comment by tylerbenson** [comment]
@theletterf Thanks for contributing #3459.  Gentle reminder/nudge to consider contributing this doc as well.

**Comment by theletterf** [comment]
Happy to! @breedx-splk WDYT?

**Comment by breedx-splk** [comment]
> Happy to! @breedx-splk WDYT?

I'm all about it. Thanks again!!

**Comment by theletterf** [comment]
I think we can continue with this one. Let me reach out to Legal.

**Comment by tylerbenson** [comment]
Any update @theletterf ?

**Comment by theletterf** [comment]
Thanks for the reminder! Waiting for legal response this week.

**Comment by theletterf** [comment]
Almost there. Final phase of legal review...

**Comment by theletterf** [comment]
Got legal approval! Will create a PR soon.

**Comment by tylerbenson** [comment]
Nice job!
