### ISSUE TITLE
Docs for instrumenting various App Servers

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry.io#3154]
In the Java SIG today, @trask suggested it would be nice if we had docs for adding auto instrumentation for the various popular Java App servers.  Splunk has such a doc on their site:
https://docs.splunk.com/Observability/gdi/get-data-in/application/java/instrumentation/java-servers-instructions.html

Perhaps Splunk could contribute such content to the OTel doc site.

cc @breedx-splk

**Comment by svrnm** [comment]
+1 -- happy to have them :-)

**Comment by cartermp** [comment]
Yep, happy to have these as well.

**Comment by theletterf** [comment]
Will gladly open a PR for this!

**Comment by theletterf** [comment]
I've opened https://github.com/open-telemetry/opentelemetry.io/pull/3459

**Comment by tylerbenson** [comment]
This is awesome, thanks!
