### ISSUE TITLE
CNCF branding page is down 

### ISSUE THREAD

**Issue by zmrfzn** [open-telemetry/opentelemetry.io#3166]
**What needs to be changed?** Describe the update that is required.
The Netlify page that was added as part of the #543, listing all the CNCF branding is not available anymore 

**What is the name + path of the page that needs changed?** The relative path
and page title where you found a problem.
https://cncf-branding.netlify.app/projects/opentelemetry/

**Comment by chalin** [comment]
AFAIK, this was fixed 3 weeks ago, see: https://github.com/open-telemetry/opentelemetry.io/pull/3076/files.

I'm not aware that the old link is used anywhere else. Closing this issue. Feel free to reopen and/or comment if there is somewhere else where the link needs to be updated, thanks.
