### ISSUE TITLE
Add published security vulnerabilities to website

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry.io#3176]
The security sig would like to start spotlighting the security work the community component owners do and emphasize publicly the community takes security seriously. To that end, we would like to mimic the security disclosure page that Kubernetes maintains - https://kubernetes.io/docs/reference/issues-security/official-cve-feed/

We have a couple initial potential options but generally open to solutions
* Copy the Kubernetes approach fully - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-security-trusted.yaml#L93
* Rely on Webhooks / GitHub Events to populate the data but that leaves an open question for data storage
* Use the GitHub API

**Comment by cartersocha** [comment]
@open-telemetry/sig-security-maintainers

**Comment by cartermp** [comment]
I would prefer to do what Kubernetes does -- I'll defer to the security SIG on where this should run. But if the output is the text (e.g., a yaml file) that we can pull in and then render as a table like the K8s page, then that would be good for me.

**Comment by svrnm** [comment]
> like the K8s page

+1

**Comment by chalin** [comment]
What's the relative priority here?

**Comment by cartersocha** [comment]
Compared to what? I just finished building a potential data source for this but we might need to store the data elsewhere depending on website requirements. The data is currently in GitHub and I’ve been able to connect grafana to that but I’m unsure if the website has similar capabilities

**Comment by cartersocha** [comment]
We have a front end engineer that was potentially going to spend some time here late November / early December

**Comment by theletterf** [comment]
@cartersocha Any update?

**Comment by cartersocha** [comment]
Yes, this is completed 

https://opentelemetry.io/docs/security/cve/
