### ISSUE TITLE
Demo code updates needed?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3179]
_Originally posted by @julianocosta89 in https://github.com/open-telemetry/opentelemetry.io/pull/3177#discussion_r1294758811_

> <img width="786" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/9e1a02c4-9f73-4e52-89c5-c6f505195295">

@julianocosta89, I'm noticing that `hipstershop.ShippingService` is used elsewhere in the demo code, maybe those need to be updated too?

**Comment by julianocosta89** [comment]
I'll take a look
