### ISSUE TITLE
A JS library with native OpenTelemetry integration

### ISSUE THREAD

**Issue by haines** [open-telemetry/opentelemetry.io#3182]
https://opentelemetry.io/docs/instrumentation/js/libraries/

>**Help wanted**
>As of today, we don’t know about any JavaScript library that has OpenTelemetry natively integrated. If you know about such a library, [let us know](https://github.com/open-telemetry/opentelemetry.io/issues/new).

We provide [OpenTelemetry integration](https://github.com/cerbos/cerbos-sdk-javascript/tree/main/packages/opentelemetry) with the [Cerbos JS SDK](https://github.com/cerbos/cerbos-sdk-javascript/tree/main#readme).

**Comment by svrnm** [comment]
@haines, thanks for sharing this! I'll follow up with you in a while

**Comment by svrnm** [comment]
Thank you for waiting @haines, I am back now and had some time to look into this.

It's great to see that Cerbos is providing OpenTelemetry support! I have raised a PR to add your instrumentation library to the registry: https://github.com/open-telemetry/opentelemetry.io/pull/3265

The call for "help wanted" is looking for libraries with what we call a **native integration**, to promote one of the project's vision objectives [Telemetry should be built-in](https://opentelemetry.io/community/mission/#telemetry-should-be-built-in) on our page of [integrations](https://opentelemetry.io/ecosystem/integrations/). The difference is explained in the [overview doc of the spec like the following](https://opentelemetry.io/docs/specs/otel/overview/#instrumentation-libraries): "_The inspiration of the project is to make every library and application observable out of the box by having them call OpenTelemetry API directly. However, many libraries will not have such integration, and as such there is a need for a separate library which would inject such calls, using mechanisms such as wrapping interfaces, subscribing to library-specific callbacks, or translating existing telemetry into the OpenTelemetry model. A library that enables OpenTelemetry observability for another library is called an Instrumentation Library_"

If the Cerbos project would consider upgrading from an instrumentation library to a native integration, it would be highly appreciated, especially if you are willing to share your experience and learnings, similar to what @AlexanderWert offered to do for their learnings on providing native support for the elastic search java api, as mentioned in https://github.com/open-telemetry/opentelemetry.io/issues/3221#issuecomment-1717161506

Also, cc @open-telemetry/javascript-approvers

**Comment by AlexanderWert** [comment]
> **Help wanted**
> As of today, we don’t know about any JavaScript library that has OpenTelemetry natively integrated. If you know about such a library, [let us know](https://github.com/open-telemetry/opentelemetry.io/issues/new).

BTW, [Next.js](https://nextjs.org/docs/app/building-your-application/optimizing/open-telemetry) has native OTel instrumentation.

**Comment by svrnm** [comment]
> > **Help wanted**
> > As of today, we don’t know about any JavaScript library that has OpenTelemetry natively integrated. If you know about such a library, [let us know](https://github.com/open-telemetry/opentelemetry.io/issues/new).
> 
> BTW, [Next.js](https://nextjs.org/docs/app/building-your-application/optimizing/open-telemetry) has native OTel instrumentation.

https://github.com/open-telemetry/opentelemetry.io/pull/3278 will have both Cerbos and Next.JS as integrations :-)

**Comment by svrnm** [comment]
#3790 will fix this
