### ISSUE TITLE
Feature Flag Service

### ISSUE THREAD

**Issue by agardnerIT** [open-telemetry/opentelemetry.io#3199]
Is this sentence still true: 

```
This service is written in Erlang/Elixir and it is responsible for creating,
reading, updating and deleting feature flags in a PostgreSQL DB.
It is called by Product Catalog and Shipping services.
```

The current architecture diagram suggests it is called by many more now:

https://opentelemetry.io/docs/demo/architecture/

happy to create a PR

**Comment by cartermp** [comment]
@agardnerIT please create a PR! We can just remove that last sentence.

**Comment by svrnm** [comment]
is this still the case? @agardnerIT , @open-telemetry/demo-approvers ?

**Comment by mviitane** [comment]
@svrnm, it's called by other services as well. I think this sentence is unnecessary detail, hard to keep updated, and could be removed:
`It is called by Product Catalog and Shipping services.`

**Comment by puckpuck** [comment]
I agree with @mviitane . It would be best to remove that sentence.

**Comment by puckpuck** [comment]
We are making several changes to how the feature flag service is configured which will also require some docs changes. Let's make sure to do this as part of those changes as well.

**Comment by svrnm** [comment]
thanks

**Comment by theletterf** [comment]
Feature flag has been removed recently (https://github.com/open-telemetry/opentelemetry.io/issues/4265). Closing.
