### ISSUE TITLE
There is only "About" on the footer

### ISSUE THREAD

**Issue by kmlhsn** [open-telemetry/opentelemetry.io#321]
There should have more links like "Community","Blog" along with About

Steps to:
1. Go to https://opentelemetry.io/
2. scroll Down to footer

screen shot
![image](https://user-images.githubusercontent.com/32615215/99188006-03ed9400-2784-11eb-8035-67cfb7dd8903.png)

**Comment by flands** [comment]
Is it better to just remove About? The link are in the top right and they follow you.

**Comment by kmlhsn** [comment]
Yes. I think it is better to remove it from the footer as top menu is always in view-port

**Comment by austinlparker** [comment]
The linked PR removes the extraneous 'about' from the footer. Doesn't really look great there anyway.
