### ISSUE TITLE
Excessive width of the gray area under "Registry" 

### ISSUE THREAD

**Issue by kmlhsn** [open-telemetry/opentelemetry.io#322]
Width of the gray area under "Registry" excess and horizontal scrollbar appears

Steps:
1. Go to https://opentelemetry.io/
2. Click "Community"
3. Scroll down to "Registry"

Screen Shot:
![image](https://user-images.githubusercontent.com/32615215/99188591-deae5500-2786-11eb-97ff-37fef33c871a.png)

**Comment by flands** [comment]
I believe it's because it is a preformatted box. If the `repo:` line is wrapped or reduced in length it will go away.

**Comment by austinlparker** [comment]
This issue was fixed by #394
