### ISSUE TITLE
.Net documentation: Manual Instrumentation - create new root activities - example unlcear.

### ISSUE THREAD

**Issue by technimad-splunk** [open-telemetry/opentelemetry.io#3247]
It is unclear where `source` comes from in the code example about [setting up a new root](https://opentelemetry.io/docs/instrumentation/net/manual/#creating-new-root-activities). 

Should source in the example given be replaced by MyActivitySource?

```
public static void DoWork()
{
    var previous = Activity.Current;
    Activity.Current = null;

-    var newRoot = source.StartActivity("NewRoot");
+    var newRoot = MyActivitySource.StartActivity("NewRoot");

    // Re-set the previous Current Activity so the trace isn't messed up
    Activity.Current = previous;
}
```
If not, can we explain what the `source` variable holds?

**Comment by svrnm** [comment]
@open-telemetry/dotnet-approvers please take a look

**Comment by cijothomas** [comment]
Look like that particular doc page is broken.

In the 1st snippet `var serviceName = "MyServiceName";` is done, presumable to use for OTel Resource. But the next snippet `var serviceName = "MyCompany.MyProduct.MyService";` looks like trying to define `ActivitySource` name... But the 3rd snippet `public static readonly ActivitySource MyActivitySource = new(TelemetryConstants.ServiceName);` is defining `ActivitySource` with a name from `TelemetryConstants` class, which is not shown before... There is also usage of `DemoSource` but that is not defined either.

I think the following should get what you are looking for 
`var newRoot = MyActivitySource.StartActivity("NewRoot");`

(The name of `ActivitySource` used to create Span/Activity must be added to the `TracerProvider` via `AddSource()` calls. This is the key thing.)

Please check if this helps. The doc fixes might take some time.

**Comment by cartermp** [comment]
Yes, for this specifically it should just use `MyActivitySource`

**Comment by cartermp** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry.io/pull/3250
