### ISSUE TITLE
Improving the NodeJs Getting Started page.

### ISSUE THREAD

**Issue by James-Kaguru** [open-telemetry/opentelemetry.io#3274]
**What needs to be changed?** 
Describe the update that is required.
- Lack of initilisation of typescript causes an  error
(This module is declared with  export = , and can only be used with a default import when using the  esModuleInterop  flag) when im porting express. It a minor issue since the code is able to run. This can be solved simply adding the npx tsc --init command

- The documentation needs to explictly state that it only gives an example on tracing since no logging or metric is shown . This will make it clear that the reader shouldn't expect to see logs and metrics example. This is due to the in the header "You will learn how you can instrument a simple application automatically, in such a way that traces, metrics and logs are emitted to the console." at the beginning of the page

- Since the metrics arent being collected I think it would be better to remove the code that has it for clarity.

- Provide a short description of the package that are being installed and what they are used for. In the example only auto-instrumentations-node has a clear example.

**What is the name + path of the page that needs changed?** 
https://opentelemetry.io/docs/instrumentation/js/getting-started/nodejs/

**Comment by svrnm** [comment]
hey @James-Kaguru , thanks for raising this issue!

> Lack of initilisation of typescript causes an error

There was an `tsc --init` in the past, this might got lost while we re-organised things, so thanks for calling that one out!

> The documentation needs to explictly state that it only gives an example on tracing since no logging or metric is shown .

Metrics are shown by that example, it takes the sample app a while until they show up. You are right about logs, we should remove that until they are part of the default setup.

> Since the metrics arent being collected I think it would be better to remove the code that has it for clarity.

Again, the code **should** produce metrics, if this is not the case, let us know again and I will double check on that

> Provide a short description of the package that are being installed and what they are used for. 

Let us take a look into that.

cc @open-telemetry/javascript-approvers

**Comment by James-Kaguru** [comment]
My apologies on the metrics point @svrnm . It does take sometime to show up. 

Id be happy to help with the below tasks and would kindly request to be assigned the issue.
- [ ] Adding a description of the libraries.
- [ ]   Typescript initialisation.

**Comment by svrnm** [comment]
Thanks @James-Kaguru for double checking on the metrics issue. A potential way to improve that is decreasing the timeout of the reader.

As a general policy, we only assign issues to community members who have already made contributions to the otel projects, please go ahead and raise the PR, it is noted that you plan to work on this.

**Comment by James-Kaguru** [comment]
Noted with thanks @svrnm lemmi work start working on it.

**Comment by James-Kaguru** [comment]
@svrnm . I believe I was able to adress these some of the issues here besides the one about adding a short description of the libraries being installed. Im thinking we add a description of the packages in the main Javascript page add a link to them.

I was also taking a look at the manual page where they talk about about whether one should install OpenTelemtry SDK or the API I believe we could link to the descriptions to there as well.

**Comment by James-Kaguru** [comment]
@svrnm addtionally we could also add some description here https://opentelemetry.io/docs/instrumentation/js/manual/#dependencies

**Comment by James-Kaguru** [comment]
Well noted @svrnm . Ill just leave it as it. I believe that I can now proceed to close this issue
