### ISSUE TITLE
Update exporters intro with advantages of OTLP

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3295]
If there is a refactor in the future, consider adding something along the lines of:

1. OTLP Exporters are built to carry OTel data model without any loss of information. (Other exporters may have info loss, like some exporters may not have a good place to store resources, instrumentation scope etc. but OTLP carry everything).
2. OTLP is the only exporter that supports all 3 signals (logs/metrics/traces).

_Originally posted by @cijothomas in https://github.com/open-telemetry/opentelemetry.io/pull/3276#discussion_r1330205694_

**Comment by pegasas** [comment]
I create an PR for fixing this.

**Comment by chalin** [comment]
@cijothomas @svrnm et al., now that @pegasas has submitted a PR for this (#3902 thanks!), I have a question regarding this claim:

- "OTLP [exporters are] the only exporter[s] that supports all 3 signals (logs/metrics/traces)." 

Is this true?  E.g., https://opentelemetry.io/docs/languages/go/exporters/ only mentions traces. Btw, even if it were true that statement will be subject to change over time.

**Comment by svrnm** [comment]
OTLP exporters SHOULD support all 3 signals, and they do already for the collector and many of the language SDKs, but maybe not all. 

I am not aware of any other exporter that does all 3 signals so far, but to be still correct in the future we might weaken that down to OTLP is one of few exporters that supports ...?

**Comment by theletterf** [comment]
Not sure if I understand the issue fully, but there are already other exporters that handle the three signal types:

* https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter
* https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter

And even if there weren't any, I don't see why a future exporter couldn't. It should not be an exclusive feature of the OTLP exporter, unless specced otherwise for some reason.

**Comment by pegasas** [comment]
> 不确定我是否完全理解这个问题，但已经有其他导出器可以处理这三种信号类型：
> 
> * https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter
> * https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter
> 
> 即使没有，我也不明白为什么未来的出口商不能。它不应该是 OTLP 导出器的专有功能，除非出于某种原因另有说明。

Thanks @theletterf for sharing.
It may be a outdate knowledge.

**Comment by cartermp** [comment]
I think the thing to emphasize here is just that OTLP is the common standard for OTel-shaped data, so it's the default you should consider using unless your tool doesn't accept OTLP.

**Comment by cijothomas** [comment]
> @cijothomas @svrnm et al., now that @pegasas has submitted a PR for this (#3902 thanks!), I have a question regarding this claim:
> 
> * "OTLP [exporters are] the only exporter[s] that supports all 3 signals (logs/metrics/traces)."
> 
> Is this true? E.g., https://opentelemetry.io/docs/languages/go/exporters/ only mentions traces. Btw, even if it were true that statement will be subject to change over time.

That is not true.

**Comment by chalin** [comment]
> I think the thing to emphasize here is just that OTLP is the common standard for OTel-shaped data, so it's the default you should consider using unless your tool doesn't accept OTLP.

@cartermp - sounds good. Can you propose specific wording over on #3905? (Otherwise I'll see what I can cook up later this week.)

**Comment by cartermp** [comment]
Left comment here: https://github.com/open-telemetry/opentelemetry.io/pull/3905/files#r1475248714
