### ISSUE TITLE
Remove remaining use of jaeger exporter

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3324]
Although [deprecated](https://opentelemetry.io/blog/2023/jaeger-exporter-collector-migration/) the Jaeger exporters are still mentioned at a few places through out the doc, we need to remove those and replace them with OTLP:

- [x] ./en/docs/collector/trace-receiver.md
- [x] ./en/docs/collector/custom-collector.md
- [ ] ./en/docs/kubernetes/helm/collector.md
- [ ] ./en/docs/collector/configuration.md

There are also some blog posts mentioning the jaeger exporter, we might consider adding a note to them that the collector is deprecated but it is left like that because the blog post is "historical"

cc @open-telemetry/collector-approvers

**Comment by codeboten** [comment]
I can tackle the first two items on this list

**Comment by codeboten** [comment]
The last item (configuration.md) is referencing the jaeger receiver and export to jaeger via OTLP. I don't think anything needs to be done for that one.

**Comment by cartermp** [comment]
@codeboten thanks! Marked off the first two.

**Comment by svrnm** [comment]
> The last item (configuration.md) is referencing the jaeger receiver and export to jaeger via OTLP. I don't think anything needs to be done for that one.

I only did a quick `grep` across all files, might be me not looking at the individual items properly, let me double check

**Comment by svrnm** [comment]
> The last item (configuration.md) is referencing the jaeger receiver and export to jaeger via OTLP. I don't think anything needs to be done for that one.

I only did a quick `grep` across all files, might be me not looking at the individual items properly, let me double check

**Comment by codeboten** [comment]
@svrnm i confirmed the same is true for helm/collector.md, all references are to the jaeger receiver

**Comment by svrnm** [comment]
thanks @codeboten, then we can close this issue :-)
