### ISSUE TITLE
[meta] Document environment variables in Sampling

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry.io#3325]
I think we should also document setting the environment variable in a top-level section in this guide. That can be especially helpful for development since you can just use the default, but then have production do something different.

_Originally posted by @cartermp in https://github.com/open-telemetry/opentelemetry.io/pull/3318#pullrequestreview-1647152522_

Also https://github.com/open-telemetry/opentelemetry.io/pull/3318#discussion_r1338917095

---
(edit by @svrnm)

Tracking:

- [ ] C++
- [ ] .NET
- [ ] Erlang/Elixir
- [ ] Java
- [ ] JavaScript
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Swift

**Comment by pellared** [comment]
Resource: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md

We should also probably call out that using [`trace.WithSampler`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#WithSampler) overrides the env vars.

**Comment by svrnm** [comment]
is this only a go thing?

**Comment by pellared** [comment]
IMO not only Go. I think that the default value is wrongly defined in other languages. And also I think the clarification is needed for all languages.

**Comment by svrnm** [comment]
Ok. I removed the "Go" from the title :)

**Comment by svrnm** [comment]
@pellared turning this into a meta issue since it is relevant for all languages

**Comment by nerudadhich** [comment]
Hi @svrnm, I would like to start working on this. Will start from Java first.
Do we have any ideal format that we need to follow for this ? Any example from existing one's ?

**Comment by svrnm** [comment]
> Hi @svrnm, I would like to start working on this. Will start from Java first. Do we have any ideal format that we need to follow for this ? Any example from existing one's ?

Apologies for the late reply, I was out of office. We currently have https://github.com/open-telemetry/opentelemetry.io/pull/4199 open, so it might need that to be closed before we can add some words about variables. You can review that PR if you like and create a follow up when merged.
