### ISSUE TITLE
ASP.NET Core Services setup update

### ISSUE THREAD

**Issue by Antzy21** [open-telemetry/opentelemetry.io#3340]
https://opentelemetry.io/docs/instrumentation/net/manual/

`AddAspNetCoreInstrumentation()`

This method is required to get the telemetry information printing to the console.
The current documentation is out of date.

This documentation explains it correctly:
https://grafana.com/docs/opentelemetry/instrumentation/dotnet/manual-instrumentation/

**Comment by cartermp** [comment]
Ahh, good catch, yes, the call to the instrumentation registration is missing in the init block.
