### ISSUE TITLE
Broken links in registry

### ISSUE THREAD

**Issue by tvvignesh** [open-telemetry/opentelemetry.io#337]
Hi guys. Just wanted to report that quite a few links in https://opentelemetry.io/registry/ are broken I guess because of migration to contrib repositories.

For eg. the link points to https://github.com/open-telemetry/opentelemetry-js/tree/master/plugins/node/opentelemetry-instrumentation-graphql whereas it should be https://github.com/open-telemetry/opentelemetry-js-contrib/tree/master/plugins/node/opentelemetry-instrumentation-graphql

https://github.com/open-telemetry/opentelemetry-python/tree/master/exporter/opentelemetry-exporter-datadog does not work
https://github.com/open-telemetry/opentelemetry-python/tree/master/instrumentation/opentelemetry-instrumentation-aiopg does not work
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/instrumentation/java-classloader does not work

Not sure if there is anything else which is broken. Thanks.

**Comment by ShubhamSonawane** [comment]
I can look into this. Please assign it to me. Would be my first contribution to open source! :)

**Comment by austinlparker** [comment]
Sure thing, thanks!

**Comment by ShubhamSonawane** [comment]
Hi @austinlparker, I have fixed 22 of 25 broken links. However, I am not able to find relevant links for the below 3 broken links. Any suggestions where to look for them? -
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/instrumentation/java-classloader
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/instrumentation/java-concurrent
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/instrumentation/scala-concurrent

**Comment by austinlparker** [comment]
looks like they got renamed in this PR https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1733

**Comment by ShubhamSonawane** [comment]
I have raised a PR #358 for the fix

**Comment by austinlparker** [comment]
thanks, merged!
