### ISSUE TITLE
Auto Update Version is broken

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3384]
https://github.com/open-telemetry/opentelemetry.io/actions/workflows/auto-update-versions.yml

Not sure what the issue is exactly.

Last successful run:
* https://github.com/open-telemetry/opentelemetry.io/actions/runs/6475390285

First broken run:
* https://github.com/open-telemetry/opentelemetry.io/actions/runs/6475833566

cc @chalin @cartermp

**Comment by chalin** [comment]
I can reproduce the problem locally:

```console
$ .github/workflows/scripts/auto-update-version.sh opentelemetry-specification spec scripts/content-modules/adjust-pages.pl
...
+ git fetch
From https://github.com/open-telemetry/opentelemetry-specification
 * [new tag]         v1.25.0    -> v1.25.0
+ git switch --detach v1.26.0
fatal: invalid reference: v1.26.0
```

We've faced a similar issue before (#3103). The fix is the same too: when setting `DEPTH` appropriately (see #3385), the command shown above works.

**Comment by chalin** [comment]
It is working now, see:

- https://github.com/open-telemetry/opentelemetry.io/actions/runs/6537081204/job/17750139013

Resulting in:

- #3386
- #3387

**Comment by chalin** [comment]
The script worked, but the individual PRs are failing. I suspect that it's because they are mutually dependent on each other. 👀
