### ISSUE TITLE
Trace, metric, and resource semantic conventions are 404'ing

### ISSUE THREAD

**Issue by heidmotron** [open-telemetry/opentelemetry.io#3393]
While the root for semantic conventions appears to be up:
https://opentelemetry.io/docs/concepts/semantic-conventions/

Trace, metric, and resource semantic conventions now 404:
https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/
https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/
https://opentelemetry.io/docs/specs/otel/resource/semantic_conventions/

**Comment by svrnm** [comment]
Thanks for raising this issue @heidmotron.

The semantic conventions have been moved from the otel spec into their own repository from where we source them, let me fix that. Here are the URLs you are looking for:

https://opentelemetry.io/docs/specs/semconv/general/trace/
https://opentelemetry.io/docs/specs/semconv/general/metrics/
https://opentelemetry.io/docs/specs/semconv/resource/

**Comment by chalin** [comment]
This is a known and temporary issue:

- #3392

I'm starting work on this now.
