### ISSUE TITLE
[CI] Enforce capitalization of Collector?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3411]
What chatting with @theletterf, about the capitalization of Collector.

We currently have a text linter for “OpenTelemetry Collector”, enforcing the title-case capitalization. If “collector” is used to mean “OpenTelemetry Collector” in our doc pages, then it should be capitalized too. I'd argue that in almost all cases, “collector” will refer to the OTel Collector in our docs, so we should have a text linter rule for that.

WDYT @svrnm?

This arose in discussing with @theletterf.

**Comment by svrnm** [comment]
I personally find it really hard to define what needs to be capitalized and what not, while I agree that we in 99.9% of the cases mean "OpenTelemetry Collector" when we write "[C|c]ollector", there are a few other instances I see similar:

* Agent
* Supervisor

My feeling so far was "OpenTelemetry Collector" and "collector", but since I am not a native speaker (in German you would always write nouns with upper case letters), I'll leave it to the judgment of others what needs to be done

**Comment by svrnm** [comment]
> I think using upper case here will facilitate connecting the word with OpenTelemetry Collector ("ah, it's that Collector!"). A little thing really, but as I've seen inconsistent usage across the docs we should stick to one of the options.

That works for me, then let's see that we enforce that via textlinter rules eventually

**Comment by chalin** [comment]
Ok, let's wait on the following to be merged before moving ahead:

- #3443

**Comment by danielgblanco** [comment]
I think using "Collector" as a short for OpenTelemetry Collector and "collector" for any other use of the word, e.g. another process that collects data, makes it clearer. Although we'll use the capitalised version 99% of the time, it's never a bad idea to avoid any source of confusion if we can.

**Comment by svrnm** [comment]
> I think using "Collector" as a short for OpenTelemetry Collector and "collector" for any other use of the word, e.g. another process that collects data, makes it clearer. Although we'll use the capitalised version 99% of the time, it's never a bad idea to avoid any source of confusion if we can.

I think this is a good point (although it makes automatic checking of how it is written when difficult/impossible)

**Comment by svrnm** [comment]
I am closing this now, since it is concensus that we use collector this way, and it doesn't like like anything else needs to be done for that.
