### ISSUE TITLE
Blog: ensure that current year is open in the sidebar

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3415]
Context:

- https://github.com/open-telemetry/opentelemetry.io/pull/3414#issuecomment-1771047217

Some ideas on how to solve this:

1. Use `/blog/<YEAR>` as the top-nav **Blog** entry path.
1. Use a little bit of JS to open the corresponding sidebar entry
1. Replace the top-nav Blog path by `/blog/this-year`, then add a redirect rule to this year's page

**Comment by nerudadhich** [comment]
Hi @chalin I would like to contribute as my `good-first-issue` on this, do you mind assigning it to me ?
Thank you.

**Comment by chalin** [comment]
Hi @nerudadhich - thanks for trying your hand at solving this! Kindly note that the issue wasn't marked as a good first issue because there are some design considerations that need to be assessed first before we jump into implementing any solution. Also, we'll be opting for an OTel specific solution (at least at first), rather than a change to Docsy -- you submitted your PR over the Docsy repo.

**Comment by nerudadhich** [comment]
Hi @chalin Thanks for details. Should I raise the PR in this repo then or you have some other idea to solve this ?

**Comment by chalin** [comment]
I have other ideas (as outlined in the opening comment). A JS solution isn't my first choice.
