### ISSUE TITLE
Getting Started: Send telemetry to an OpenTelemetry Collector Issue

### ISSUE THREAD

**Issue by lek18** [open-telemetry/opentelemetry.io#3444]
**What happened?** Describe the problem that occurred.
Hi Team, 

I am following the instructions of Getting Started: Send telemetry to an OpenTelemetry Collector and i am getting the following error:

```
(otel-getting-started-py3.11) lek18@m-ljp9nw6v2n otel-getting-started % opentelemetry-instrument flask run -p 8080
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8080
Press CTRL+C to quit
127.0.0.1 - - [26/Oct/2023 11:29:53] "GET /rolldice HTTP/1.1" 200 -
Transient error StatusCode.UNAVAILABLE encountered while exporting traces to localhost:4317, retrying in 1s.
Transient error StatusCode.UNAVAILABLE encountered while exporting traces to localhost:4317, retrying in 2s.
```
If turn on:

```
export GRPC_VERBOSITY=debug
export GRPC_TRACE=http,call_error,connectivity_state
```
I get:

```
 Connecting to server localhost:4317 via HTTP proxy ipv4:10.225.228.14:8080
I1026 11:22:54.177084000 6184808448 subchannel.cc:744]                 subchannel 0x118704f60 {address=ipv4:10.225.228.14:8080, args={grpc.client_channel_factory=0x600001698640, grpc.default_authority=localhost:4317, grpc.http_connect_server=localhost:4317, grpc.internal.channel_credentials=0x600001698630, grpc.internal.event_engine=0x6000016b8040, grpc.internal.security_connector=0x600000188180, grpc.internal.subchannel_pool=0x600003f9c620, grpc.primary_user_agent=grpc-python/1.59.0, grpc.resource_quota=0x600001a9d0b0, grpc.server_uri=dns:///localhost:4317}}: connect failed (UNKNOWN:HTTP proxy returned response code 403 {created_time:"2023-10-26T11:22:54.17051-05:00"}), backing off for 822 ms
````

**What did you expect would happen?** Describe the expected result/output.
No error, Same as documentation. 

**What is the name + path of the page where you encountered the issue?** The
relative path and page title where you found a problem.
https://opentelemetry.io/docs/instrumentation/python/getting-started/

**What browser, OS, and platform were you using when you encountered the
problem?** Include the browser version if you know it as well.

Edge, Safari.

**Additional context**: anything else you can think about that would be helpful.

Sending telemetry data to console only, works without issue.

_Please delete paragraphs that you did not use before submitting._

**Comment by svrnm** [comment]
Thanks for reporting this issue @lek18. Can you share some additional details about your collector setup? Is it running standalone on the same machine or within a docker container, have you verified that the port 4317 is open? Can you use a tool like [telemetrygen](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/telemetrygen) to send spans and see if they arrive?

Also, I see the following in your error message:
```
Connecting to server localhost:4317 via HTTP proxy ipv4:10.225.228.14:8080
```
and
```
UNKNOWN:HTTP proxy returned response code 403
```

Can you verify that traffic is not flowing through a proxy for localhost connections?
