### ISSUE TITLE
Demo doc: How to change port of frontend-proxy?

### ISSUE THREAD

**Issue by jachstet-sea** [open-telemetry/opentelemetry.io#3473]
It should be documented how to change the tcp port used for the frontend proxy.

https://opentelemetry.io/docs/demo/docker-deployment/

I tried running the demo using the steps provided at the demo/docker page. However, it failed since on my machine, port 8080 was already in use. The documentation page does not mention that port 8080 will be used until the "Verify the web store and Telemetry" section. I didn't read that far yet ;)

Thus, it should be documented that port 8080 needs to be free OR it should be documented how one can change the port. I tried setting the "FRONTEND_PORT" env var to some other value but it didn't have any effect, the demo still fails to start.

**Comment by svrnm** [comment]
@open-telemetry/demo-approvers PTAL!

**Comment by jachstet-sea** [comment]
@open-telemetry/demo-approvers, @svrnm : Polite ping

**Comment by svrnm** [comment]
Thanks for the ping @jachstet-sea, you may also go to #otel-demo on [CNCF slack](https://slack.cncf.io) and ask for some help here
