### ISSUE TITLE
[CI] Textlint: convert rc file to YAML so we can add comments etc

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3499]
Some of the patterns in the textlintrc file would warrant some explanation. It's easier to use YAML in such a case, since it supports comments. Textlint supports YAML, among other [formats for its config file](https://textlint.github.io/docs/configuring.html).

I'll wait for the currently pending PRs over textlint config to be merged before making this change -- **waiting on the merge of**:

- #3497
- #3496
- #3491

**Comment by svrnm** [comment]
great stuff, merged :-)
