### ISSUE TITLE
HTTP semantic convention v1.23.0 content not synchronized to the website

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry.io#3510]
This page https://opentelemetry.io/docs/specs/semconv/http/http-spans/ currently says it's for Semantic Conventions 1.23.0:

> [Docs](https://opentelemetry.io/docs/) > [Specs](https://opentelemetry.io/docs/specs/) > [Semantic Conventions 1.23.0](https://opentelemetry.io/docs/specs/semconv/) > [HTTP](https://opentelemetry.io/docs/specs/semconv/http/) > Spans

But the content is not the same as https://github.com/open-telemetry/semantic-conventions/blob/v1.23.0/docs/http/http-spans.md

E.g. it still says

> Status: [Experimental, Feature-freeze](https://opentelemetry.io/docs/specs/otel/document-status/)

and other content on that page also appears to be from an older version.

**Comment by svrnm** [comment]
@chalin can you take a look?

**Comment by chalin** [comment]
I'm on it!

**Comment by chalin** [comment]
Dang, should have caught that! Anyhow, a fix is ready:

- #3511

**Comment by chalin** [comment]
Apologies for the oversight and not having caught that earlier. I had just assumed that the bot-generated PR updated everything that needed updating -- but that wasn't the case.

**Comment by trask** [comment]
thanks @chalin!
