### ISSUE TITLE
Collector config: don't link to deprecated `ServiceTelemetryMetrics struct`

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3514]
_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry.io/pull/3443#discussion_r1385523021_

> As I mentioned in the other PR making changes to this section, I don't think we should be linking out to the source file. Especially because that [**config file has been deprecated**](https://github.com/open-telemetry/opentelemetry-collector/blob/50f013d0d242bf7b600eddf5cfe484e087c1de0c/CHANGELOG.md?plain=1#L1237)!
> 
> We should just list the "full options" (there aren't that many) here.
> 
> ---
> 
> If you choose to keep the link for now, I'd at least suggest the following rewording to avoid a "here" link:
> 
> ```markdown
> for scraping at <http://localhost:8888/metrics>. For the full list of options
> for the `metrics` subsection, see the 
> [`ServiceTelemetryMetrics struct`](https://github.com/open-telemetry/opentelemetry-collector/blob/7666eb04c30e5cfd750db9969fe507562598f0ae/config/service.go#L99-L111) comments.
> ```

### References

This is the link info the config file:

- https://github.com/open-telemetry/opentelemetry-collector/blob/7666eb04c30e5cfd750db9969fe507562598f0ae/config/service.go#L99-L111

/cc @open-telemetry/collector-approvers @theletterf

**Comment by tiffany76** [comment]
I think we can close this issue. The link in question was removed in #4504.

**Comment by svrnm** [comment]
@chalin PTAL for closing this

**Comment by chalin** [comment]
Thanks, I'll take @tiffany76's word for it.
