### ISSUE TITLE
Website add i18n support 

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry.io#352]
I saw the #203  and working on how to make OTel website support a language.

Personally, I would like to be able to support i18n (e.g. Chinese) before OTel GA. I have done some research. some work needs to do.

1. Extracting common vocabulary
   for example

```
  ...
[[menu.main]]
  name = "Blog"
  ...
// need change to
[[languages.en.menu.main]]
  name = "Blog"
  
  
// if nav "Blog" need translate, k8s website is translate it.
```

2. base page need translate
   - Index.md
   - About.md
   - Registry.md
   - Community.md
3. document translate

---

For me, there are three points of confusion

1. whether i18n can be included in the GA plan 
2. whether the base page (e.g. about / Community content is ready, as a stable version for translation
3. whether need to create a i18n process for the website, so that other languages (e.g. Chinese, Japanese, etc.) can contribute

**Comment by austinlparker** [comment]
For the overall project GA, i18n is certainly in scope. I don't believe the base page is necessarily stable yet, we need to have a bit of a larger discussion around what should go on there (specifically around features that aren't specced out all the way yet and when they're coming in relative to project GA) - but I think that relates to your third point about a process for community contributions of translations. 

We'll discuss this on the next comms SIG call (1/14)

**Comment by WPH95** [comment]
> For the overall project GA, i18n is certainly in scope. I don't believe the base page is necessarily stable yet, we need to have a bit of a larger discussion around what should go on there (specifically around features that aren't specced out all the way yet and when they're coming in relative to project GA) - but I think that relates to your third point about a process for community contributions of translations.
> 
> We'll discuss this on the next comms SIG call (1/14)

Thanks! I'll keep an eye out and try to attend the 1/14 SIG call :) Hope to contribute to OTel's localization :)

**Comment by svrnm** [comment]
See https://github.com/open-telemetry/opentelemetry.io/discussions/4302 for future discussions on this matter.
