### ISSUE TITLE
Blog Template instructions incorrect

### ISSUE THREAD

**Issue by davidgs** [open-telemetry/opentelemetry.io#3546]
The page https://github.com/open-telemetry/opentelemetry.io/blob/main/archetypes/blog.md says: 

> [Top-level heading](https://github.com/open-telemetry/opentelemetry.io/issues/new#top-level-heading)
> 
> Top-level headings start at level 2, as shown above.

But there is no top-level heading shown above, so the instruction is unclear, at best.

**Comment by davidgs** [comment]
Blog template page also has the following issues: 

<img width="1059" alt="2023-11-15_08-16-37" src="https://github.com/open-telemetry/opentelemetry.io/assets/2071898/ba730ab8-45fa-41d1-907f-75b61f579de0">

1. That error message is confusing on the template page. 
2. For anyone that is not already familiar with Hugo and the mustache-templates, the line 
`{{ replaceRE "[-_]" " " .Name | title }}` is confusing. Are they to replace that line with the title? 
3. `linkTitle: ADD A SHORT TITLE HERE # Mandatory, make sure that your short title.` is an incomplete sentence. Make sure that the short title is what? 
4. `author: >- ` do we replace this `>-` with the author's name? Are those characters required? 
5. Including the `TODO: ` in instructions lines leaves it ambiguous as to if the submitter is to replace these? Or if it's a TODO item for the maintainers.

**Comment by svrnm** [comment]
> But there is no top-level heading shown above, so the instruction is unclear, at best.

Above that line is `## Top-level heading` as top-level heading example. All it wants to say is don't use `# Top-level heading` in your blog post since the `title:` is going to be h1

> That error message is confusing on the template page.

There is nothing we can do against that, because this file is not intended to be viewed on GitHub, it should be used at outlined in the README.md: `npx hugo new content/en/blog/2023/short-name-for-post.md` will make a copy of that file for you

> {{ replaceRE "[-_]" " " .Name | title }}

See my comment above, the `npx hugo` will take care of that

> Make sure that the short title is what?

Make sure that your title is short, let me fix that.

> `author: >-` do we replace this `>-` with the author's name? Are those characters required?

No, the authors are listed one by one as shown in the lines below. We very often have blog posts with multiple authors, that's why we use this structure.

> Including the TODO: in instructions lines leaves it ambiguous as to if the submitter is to replace these? 

This is for the submitter. If you run `npx huo new...` this will remain part of your template and leave it to you to fix that

**Comment by svrnm** [comment]
@open-telemetry/docs-approvers let's review the template and improve it accordingly. I think we can add a `## Front matter` section explaining some of the things in a little bit more detail

**Comment by davidgs** [comment]
As a single data-point, when I ran the `npc hugo new ...` command, it did *not* use this template to create the new file. It created the front-matter as 
```
--
title: "Adding OpenTelemetry support to the Otterize network mapper"
_build:
  render: never
  list: never
  publishResources: false
---
```
Thanks for looking into this.

**Comment by davidgs** [comment]
> Can you look into your history and share the exact command that you did run? I just tried it myself and the right template was used

`npx hugo new content/en/blog/2023/otterize-otel/index.md`

**Comment by svrnm** [comment]
> > Can you look into your history and share the exact command that you did run? I just tried it myself and the right template was used
> 
> `npx hugo new content/en/blog/2023/otterize-otel/index.md`

Thanks! This works as expected for me, so I am not 100% sure what went wrong there, but I think we don't need to spend too much time into that, just copy the front matter from the template or an existing blog post

**Comment by davidgs** [comment]
Also, see PR #3548

**Comment by svrnm** [comment]
We reworked some of those instructions, @davidgs if you think that further improvements are required, raise a new issue, thanks!

**Comment by davidgs** [comment]
LGTM! Thanks for tackling this!
