### ISSUE TITLE
Exporters

### ISSUE THREAD

**Issue by cparkins** [open-telemetry/opentelemetry.io#3550]
In the section OTLP Endpoint there is a flaw in the code provided in the third and fourth code example. If this example is used then the data will not make it to the HTTP Endpoints.  This is because of a flaw in the .NET Library but there is a workaround.  Here's the example code for reference:
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenTelemetry()
  .WithTracing(b =>
{
    b
    .AddOtlpExporter(opt =>
    {
        opt.Endpoint = new Uri("your-endpoint-here");
        opt.Protocol = OtlpExportProtocol.HttpProtobuf;
    })
    // The rest of your setup code goes here too
});
```

If this code is used with the default endpoint "http://localhost:4318" it will fail!  To workaround this issue the Endpoint can be specified using an Environment Variable instead.  To set the endpoint and get the default path set use the Environment Variable OTEL_EXPORTER_OTLP_ENDPOINT.

**Comment by cartermp** [comment]
Thanks for the issue @cparkins -- I see you filed an issue here: https://github.com/open-telemetry/opentelemetry-dotnet/issues/5054

Is the nature of this issue that you must specify `/v1/traces` to the end of the URI string to make this work to a local collector?

**Comment by cparkins** [comment]
@cartermp Yes, that is the problem; With traces. For Logs /v1/logs needs to be added and /v1/metrics for Metrics.  This isn't necessarily a problem with just local collectors though.  But the code in the example does not actually work when connecting to a local collector if you specify the Endpoint using the ExporterOptions.  I realize that there are other ways to set the endpoints for each Signal type; As this is how I'm addressing the issue in my Application.  I think setting the Endpoint should be consistent and do not understand why allowing it in one place is allowed and not in the other.  Otherwise I probably would have submitted a PR as well.

**Comment by cartermp** [comment]
I'll defer to @open-telemetry/dotnet-approvers on what the intended behavior should be, and we'll document that.

In the interim, we can certainly accept a change that uses `localhost:4318/v1/traces` as the example and maybe a code comment saying that you can plug your own endpoint in there.

I can also buy the argument that if the environment variable correctly appends the right signal type to the URL, then that should also happen if you do this programmatically (and forget it to do it yourself). I'd also prefer that behavior, but that's also the .NET SIG's call.

**Comment by cparkins** [comment]
@cartermp - There's only one problem with the Interim solution. You can only append the /v1/traces if you are only sending Traces. If you are sending Logs, Metrics and Traces the only way to set the Endpoint with the Exporter Options (which is what is in the Documentation) is to use the Environment Variable.  Obviously if you are specifying the endpoint for each Signal this problem goes away, and I assume that may be why it was written that way.

**Comment by cartermp** [comment]
Today if you're doing things programmatically, you do need to specify an exporter for each signal. There's no current way to specify a single exporter with an HTTP endpoint for all signals - you need to add each signal support and within each configure an endpoint.

**Comment by cparkins** [comment]
@cartermp - Sorry, you're right! I got confused with the .NET Library and the Library that our teams have been using which allows a single Exporter Options to be passed in for all three types! I think the interim solution is fine.  Just noticed the disparity between doing it one way versus another.
