### ISSUE TITLE
[Meta] Standardize exporters docs 

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3559]
# Description

Based on #3355 all exporter pages should follow a _similar_ structure (where applicable). In a second step we can extract common text blocks into snippets managed at one place.

- [x] C++ (#3998)
- [x] .NET
- [ ] Erlang/Elixir
- [ ] Go
- [x] Java (#3558)
- [x] JavaScript (#3355)
- [ ] PHP
- [x] Python (#3515)
- [ ] Ruby
- [ ] Rust
- [ ] Swift

# How you can help

Take a language of your choice and use the structure of the [JavaScript Exporters](https://opentelemetry.io/docs/instrumentation/js/exporters/) page as template (the "browser" part is not applicable for other languages and can be skipped)

**Comment by kumarankit999** [comment]
I would also love to add value on this issue!

**Comment by svrnm** [comment]
> I would also love to add value on this issue!

Thanks @kumarankit999, what's a language you feel comfortable with tackling?

**Comment by vallss** [comment]
Hi @svrnm, I would like to contribute to this issue! Amongst the listed languages I'm most comfortable with PHP.

**Comment by kennykguo** [comment]
if this issue is still active, please assign this issue to me, thanks

**Comment by svrnm** [comment]
@kennykguo this is a meta issue, which will not be assigned. You can take a look at an individual language and see if you can help with that.

**Comment by kumarankit999** [comment]
I would like to work in GO!

**Comment by svrnm** [comment]
@kumarankit999 that's great to hear! Please take a look at some of the docs that are completed already ([Python](https://opentelemetry.io/docs/languages/python/exporters/), [C++](https://opentelemetry.io/docs/languages/cpp/exporters/), [JS](https://opentelemetry.io/docs/languages/js/exporters/). Pick one as your starting point, pick the underlying markdown file and build the updated version from there. 

You can also take a look at this ongoing PR for .NET to see how you can tackle this:

https://github.com/open-telemetry/opentelemetry.io/pull/4016

Thank you
