### ISSUE TITLE
missing attributes on metrics

### ISSUE THREAD

**Issue by cinekqw1** [open-telemetry/opentelemetry.io#3574]
Is it able to add some attributes to metric counter like for example service_name, group_name? Based on API we can simpy add attribute in function Add(value, attrib), but once I capture the data (in open telemetry collector from docker) I only see Metrics structure (name , description, unit, kind). I dont see any attributes. I also add this in config to collector.
 processors:
  attributes:
    actions:
      - key: "attr_name"
        action: "insert"
        from_attribute: "attr_name"

Could you help?

**Comment by cartermp** [comment]
The metrics spec allows for adding attributes whenever you create a new measurement. For example, here's how you can do it in JS: https://opentelemetry.io/docs/instrumentation/js/manual/#adding-attributes

Each language's API will be a little different, though. Does that help? Which language are you using?

**Comment by cinekqw1** [comment]
ok, I fixed it. 

**working code:**
`std::map<std::string, std::string> labels = {{"key", "value"}};
auto labelkv = common::KeyValueIterableView<decltype(labels)>{labels};
double_counter->Add(val, labelkv);`

**not working code:**
`double_counter->Add(val, {"key", "value"});`
