### ISSUE TITLE
Replace CODEOWNERS with component owners

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3581]
Right now almost all SIGs have write permissions to the opentelemetry.io repository, this is required because of the `CODEOWNERS` file. Other otel repos have fixed this issue already by implementing @dyladan's component-owner:

https://github.com/dyladan/component-owners

Relevant for https://github.com/open-telemetry/community/pull/1793 (cc @austinlparker)

**Comment by chalin** [comment]
Reopening until component owners actually works.

**Comment by svrnm** [comment]
they work now, closing this
