### ISSUE TITLE
Code example with wrong class name in Manual Instrumentation for OpenTelemetry PHP

### ISSUE THREAD

**Issue by isiryder** [open-telemetry/opentelemetry.io#3603]
Versions:
PHP 8.2.12
guzzlehttp/guzzle 7.8.0       
guzzlehttp/psr7 2.6.1       
open-telemetry/api 1.0.0      
open-telemetry/sem-conv 1.23.0beta1 

I was trying to run the example here https://opentelemetry.io/docs/instrumentation/php/manual/#example but I got the following error:

`Uncaught Error: Class "OpenTelemetry\SDK\Logs\LogsProcessor\SimpleLogsProcessor" not found`

So I checked and found out that the class name was changed some time ago.

I made it work by changing
`use OpenTelemetry\SDK\Logs\Processor\SimpleLogRecordProcessor;`
instead of
`use OpenTelemetry\SDK\Logs\Processor\SimpleLogsProcessor;`

**Comment by cartermp** [comment]
This looks like it's by design, as ~4 months ago the type was renamed to match the spec: https://github.com/open-telemetry/opentelemetry-php/pull/1073

I think to address this you'll need to update your packages.

**Comment by svrnm** [comment]
@isiryder looking at the issue @cartermp linked this needs to be changed in the docs as well, please feel free to raise a PR to fix that. cc @open-telemetry/php-approvers
