### ISSUE TITLE
Update Java Exporter Pages to use autoconfigure

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3608]
Via https://github.com/open-telemetry/opentelemetry.io/pull/3558#pullrequestreview-1751340802

Java pages about Exporters need to be updated to make use of autoconfigure

**Comment by MeenuyD** [comment]
Hello @svrnm I would like to work on this issue can you please assign me and guide how changes to be done?

**Comment by svrnm** [comment]
@MeenuyD we do not assign issues ([see our guidelines on this topic](https://github.com/open-telemetry/opentelemetry.io/blob/main/CONTRIBUTING.md#want-to-work-on-an-existing-issue)), but it is noted that you want to take a look into it and provide a PR.

What needs to be changed:
* Take a look at how manual instrumentation is making use of auto configure: https://opentelemetry.io/docs/instrumentation/java/manual/#automatic-configuration, the exporter docs should built on top of that
* The structure of the document should remain, since we aim for consistency across languages
* You can provide updates incrementally, e.g. start with OTLP (or any other of the listed exporters) and provide a PR, after merging, the same should be replicatable for other exporters as well

@open-telemetry/java-approvers any additional comments?

**Comment by nerudadhich** [comment]
Hi @MeenuyD 👋 , Have you started working on this, Do you need any help or anything let me know.

**Comment by nerudadhich** [comment]
Hi @svrnm , I have started working on this. Will let you know once it's ready for review.

**Comment by svrnm** [comment]
Thank you!

**Comment by theletterf** [comment]
@nerudadhich Any update?

**Comment by nerudadhich** [comment]
Hi @theletterf . I have amended the details, But wondering if we should add `gradle` config as well as `RollController` instead of referring to dice app example links ?
 
What do you think ?

**Comment by svrnm** [comment]
> But wondering if we should add gradle config as well as RollController instead of referring to dice app example links ? 

that's probably a question for the ongoing PR and @open-telemetry/java-approvers

**Comment by trask** [comment]
> But wondering if we should add gradle config as well as RollController instead of referring to dice app example links ?

hi @nerudadhich!

I see gradle config here already: https://opentelemetry.io/docs/languages/java/exporters/#otlp-dependencies

or are you referring to another place?

> RollController instead of referring to dice app example links 

i'm not sure what you mean here, can you explain a bit more? thanks

**Comment by nerudadhich** [comment]
Hi @trask Could you please check the PR [here](https://github.com/open-telemetry/opentelemetry.io/pull/4194) and the Preview [here](https://deploy-preview-4194--opentelemetry.netlify.app/docs/languages/java/exporters/)

I have added all the details (Working sample app code) explicitly instead of referring to example link.
I hope this make sense to you ?

**Comment by svrnm** [comment]
we refactored the java docs, so this issue might longer be applicable
