### ISSUE TITLE
Remove usage of `io.spring.dependency-management` and document issue it causes

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry.io#3613]
The Java examples at https://opentelemetry.io/docs/instrumentation/java/getting-started/#dependencies and in #3568 currently use:

```
id("io.spring.dependency-management") version "1.1.0"
```

However, we've seen this cause issues for many users, and I think we should implement @jack-berg's suggestion instead: https://github.com/open-telemetry/opentelemetry-java/issues/6018#issuecomment-1828809517

Additionally, given it's come up several times, it's probably worth adding a note about this issue on https://opentelemetry.io/docs/instrumentation/java/automatic/spring-boot/

cc @open-telemetry/java-approvers @open-telemetry/java-instrumentation-approvers @jeanbisutti

**Comment by jeanbisutti** [comment]
I would like to look at it in the next days. Could you please assign me this issue?

**Comment by cartermp** [comment]
@jeanbisutti we don't typically assign people, so feel free to just submit the PR.

**Comment by professorabhay** [comment]
Hey @cartermp! Can you provide some more exposure to it?

**Comment by jeanbisutti** [comment]
There are two ways to import a BOM with Gradle and Spring Boot: https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#managing-dependencies Issues can happen when the user is mixing up the two ways. I have created a PR explaining the things for the Spring Boot page: https://github.com/open-telemetry/opentelemetry.io/pull/3672

**Comment by trask** [comment]
I think so, thanks!
