### ISSUE TITLE
CI for docs' code snippets

### ISSUE THREAD

**Issue by ekquasar** [open-telemetry/opentelemetry.io#3633]
# What's wrong?
The docs are currently include broken code. This is harmful for the adoption of OpenTelemetry as it degrades the project's reputation and ability of users to onboard. See [this earlier discussion](https://github.com/open-telemetry/opentelemetry.io/issues/3610) for more detail.

# How to fix?
Let's get CI for the code snippets in the docs so we can ensure they work - or at the very least improve visibility for when they're broken.

# Where to start?
I'll propose starting with the [Python "Getting Started" docs](https://opentelemetry.io/docs/instrumentation/python/getting-started) as that's where I can probably help, and the issue with those docs is [documented](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2079).

**Comment by ekquasar** [comment]
I wonder if there's not an incremental path to *right*, as such. If we get  the desirables defined and the problem decomposed, there should be an MVP that stands out as an achievable result within a Sprint's worth of effort, I imagine.

I'm looking forward to understanding the issues here, because broken documentation is a critical issue.

**Comment by chalin** [comment]
As @svrnm mentioned, this is a known issue, that has been discussed in the past, see:

- #1635

This repo briefly used a simple include shortcode, but that falls short of what we really need IMHO.

I have had a solution on the back burner (which is successfully being used in other projects), and would be glad to work on a similar feature in the context of OTel if @open-telemetry/docs-maintainers feel that it's a priority.

In a nutshell, the approach relies on code repos to have CI to ensure that their example code is functional. In this repo we'd use tooling to extract example-code snippets from the CI-tested code of the code repos. The extracted code snippets are caches, so we don't always need to extract from the code repo.

What would help me is if you could identify a few target code-snippets in the docs, and point me to the corresponding code in a code repo. I could work on prototyping the code-snippet sync for a few examples to start off with.

(I'll look into the tooling as soon as I can, but most likely I won't have much time until the new year.)

**Comment by ekquasar** [comment]
These sophisticated solutions would do wonders for improving the reliability of the documentation. But I wonder if something much simpler might 80/20 the time-to-value issue: keeping a single, end-to-end, working example CI-tested.

**Comment by chalin** [comment]
> keeping a single, end-to-end, working example CI-tested.

I believe that the demo (or a subset thereof) is meant to serve that purpose. Smaller-scale examples would be good too.

Once you have an end-to-end example, inevitably one ends up wanting to refer to code snippets from the docs, so we're back to the need of keeping the docs and code snippets in sync.

We discussed this during the Comms meeting. I proposed to drop a PR (early next year) that illustrates how code snippets can be kept in sync; I'll probably start with [go/example/dice](https://github.com/open-telemetry/opentelemetry-go/tree/main/example/dice) since the snippets we'd need are in code repo already. (An alternative would be do use the demo docs.)

**Comment by chalin** [comment]
> That's what moved us _away_ from CI-checked samples at Microsoft

I agree that we don't want to add CI code checks to this repo. In that sense, could we close this issue in favor of #1635 (@svrnm was looking for #1635 but didn't find it at the time) and continue the code-snippet-sync discussion over there? @svrnm WDYT?

**Comment by svrnm** [comment]
Yes, let's continue this discussion on #1635, copy/link the items you want to continue discussing there
