### ISSUE TITLE
Python auto-instrumentation example does not work

### ISSUE THREAD

**Issue by ekquasar** [open-telemetry/opentelemetry.io#3634]
As described in the [auto-instrumentation section of the Python OpenTelemetry docs](https://opentelemetry.io/docs/instrumentation/python/automatic/example/#execute-the-automatically-instrumented-server), running:
```sh
opentelemetry-instrument --traces_exporter console --metrics_exporter none python auto.py
```
should produce telemetry output in the console. Unfortunately, it only produces 'None'.

https://github.com/open-telemetry/opentelemetry.io/assets/123695626/be44d63a-20e7-4f3d-b322-728b4ca97c4c

Please note that the docs, linked above, do not have the `flask<3` version constraint, but in my environment I've installed both `3` and `<3` versions, each yielding the same error in the video above.

**Comment by svrnm** [comment]
this is fixed now
