### ISSUE TITLE
fix:recache run failed, semconv commit id not found?

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3650]
https://github.com/open-telemetry/opentelemetry.io/actions/runs/7099707912

> fatal: Fetched in submodule path 'content-modules/semantic-conventions', but it did not contain 73720582560b5a020df8aee90504fcb411f62713. Direct fetching of that commit failed.

**Comment by svrnm** [comment]
yeah, probably something like that, not urgent, but I wanted to keep track of it

**Comment by chalin** [comment]
Yes, that could be it. Maybe try setting the branch in the .gitmodules file -- but from memory, that is just a placedo. We might be required to clone and check out all branches first (or in the case of semver, the actual branch being used) before attempting the `switch`.

**Comment by svrnm** [comment]
This seems to work now?

**Comment by chalin** [comment]
I'd vote to keep this open, at least a bit longer. I'd still like to investigate this branch issue since it might surface again. WDYT @svrnm?

**Comment by chalin** [comment]
Closing, all seems good now.
