### ISSUE TITLE
Baggage doc should be modified to make it less tied to tracing singnal

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry.io#3674]
**What needs to be changed?**

Baggage doc is tied too much to tracing. We need to modify it making it clear that Baggage is applicable across all signals, and potentially show examples on Baggage can be used across signals.

**What is the name + path of the page that needs changed?** 
https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/concepts/signals/baggage.md

**Additional context**: Noticed in https://github.com/open-telemetry/opentelemetry.io/pull/3657#discussion_r1420851652.

**Comment by svrnm** [comment]
Thanks for raising this, I agree, this page needs some attention

**Comment by theletterf** [comment]
Thanks for raising this. We had a similar conversation on this @flands and I.

**Comment by svrnm** [comment]
Yeah, the baggage doc needs some attention...
