### ISSUE TITLE
[Meta] Create and standardize pages on "Context & Propagation" across languages

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3688]
As of today only JavaScript, Erlang & PHP have pages on propagation:

* [PHP](https://opentelemetry.io/docs/instrumentation/php/propagation/)
* [JavaScript](https://opentelemetry.io/docs/instrumentation/js/propagation/)
* [Erlang](https://opentelemetry.io/docs/instrumentation/erlang/propagation/)

Javascript additionally has a page on Context:

* [JavaScript](https://opentelemetry.io/docs/instrumentation/js/context/)

The following languages have a section on Context and/or Propagation in their manual instrumentation docs:

* [Go](https://opentelemetry.io/docs/instrumentation/go/manual/#propagators-and-context)
* [C++](https://opentelemetry.io/docs/instrumentation/cpp/manual/#context-propagation)
* [Java](https://opentelemetry.io/docs/instrumentation/java/manual/#context-propagation)
* [Ruby](https://opentelemetry.io/docs/instrumentation/ruby/manual/#context-propagation)

I would like to create consistency for this across languages:

* Context Propagation is an important enough topic to have a dedicated page below each language (like PHP, JS, Erlang today)
* In the manual instrumentation doc (and others if applicable) the subsection should still exist but link out to that dedicated page
* (Open Question): Do we want to merge the JS pages on Context/Propagation or do we want to have 2 dedicated pages? Or do we want to have a parent page?

**Comment by theletterf** [comment]
As a counter-suggestion: We usually have quite a bit of pages under "Automatic": Why not doing the same for "Manual" and have the Propagation doc there? Manual instrumentation docs for languages like Java have grown to a huge size and are a bit unwieldy.

**Comment by svrnm** [comment]
As long as we say "Manual" and "Automatic" instrumentation this would give people the feeling that this is only relevant for their manual instrumentation (see https://github.com/open-telemetry/opentelemetry.io/issues/3228 for this discussion as well). But I see your point, our menu is growing quickly and might require some care & love in 2024 as well

**Comment by cartermp** [comment]
FWIW I'm fine with splaying things out right now and condensing later. I think we're just going to face the ugly reality that it's complex and there'd gonna be a lot of topics to lay out.
