### ISSUE TITLE
Advice to use GlobalOpenTelemetry is misleading

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry.io#3692]
The library instrumentation page [says](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/concepts/instrumentation/libraries.md#getting-a-tracer) that "libraries should obtain tracer from global TracerProvider by default". It goes on to say that "its useful for libraries to have an API that allows applications to pass instances of TracerProvider explicitly".

This isn't necessarily wrong, but the advice is flipped in java and the code snippet (along with [another that shortly follows](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/concepts/instrumentation/libraries.md#public-apis)) use `opentelemetry-java` as an example. See [language in the java manual instrumentation page](https://github.com/open-telemetry/opentelemetry.io/blame/main/content/en/docs/instrumentation/java/manual.md#L641-L651) which directly contradicts this advice:

> if you are writing library instrumentation, it is strongly
recommended that you provide your users the ability to inject an instance of
`OpenTelemetry` into your instrumentation code. If this is not possible for some
reason, you can fall back to using an instance from the `GlobalOpenTelemetry`
class

Options:
- Clarify that the preference for global versus providing instances TracerProvider may vary by language
- Use an example language that isn't java, and maybe add a footnote that at least in java the behavior is flipped

**Comment by svrnm** [comment]
Yeah, that page is fairly dated, needs some love :)
