### ISSUE TITLE
RSS Feed Broken on OpenTelemetry Blog

### ISSUE THREAD

**Issue by nirlya** [open-telemetry/opentelemetry.io#3720]
Hi,

I've encountered an issue with the RSS feed on the OpenTelemetry blog. It seems that the historical feed is not functioning correctly. Here's the link to the RSS feed: https://opentelemetry.io/blog/index.xml.

**Steps to Reproduce:**

Navigate to the OpenTelemetry blog RSS feed link.
Observe the 404 error.

**Expected Behavior:**
The RSS feed should load correctly, displaying the latest blog posts in an RSS format.

**Comment by svrnm** [comment]
we dropped the feed a few weeks ago assuming no one is using it, see https://github.com/open-telemetry/opentelemetry.io/pull/3616 -- we might need to review that decision.

**Comment by cartermp** [comment]
also noticed in cncf slack

**Comment by svrnm** [comment]
@chalin please take a look when you get a chance.

**Comment by chalin** [comment]
Yes, thanks for letting us know. I'll close this in favor of #3740.

**Comment by chalin** [comment]
@nirlya - FYI, the RSS feed is back:

- https://opentelemetry.io/blog/index.xml
- Via #3780
