### ISSUE TITLE
Learn how to instrument NGINX with OpenTelemetry

### ISSUE THREAD

**Issue by WIP42** [open-telemetry/opentelemetry.io#3726]
Updated article for instrumenting alpine-based nginx would be handy; I have attempted it in another project: https://gitlab.com/logius/beveiligd-koppelvlak-extern/base-images/nginx-unprivileged

But still get the error: "Error loading shared library libcrypt.so.1", even when adding gcompat due to musl use in Apline, I have not been able to integrate OTEL; I suspect switching to the suggested ubunutu-based images is recommended but it would be nice if a lightweight Apline image can be instrumented too

**Comment by svrnm** [comment]
@WIP42 this repository is for the documentation and blog posts, please comment on this existing issue that you are interested in alpine support for the nginx webserver module: https://github.com/open-telemetry/opentelemetry-cpp-contrib/issues/302

**Comment by svrnm** [comment]
I will close this issue now, please comment if you think that the website can help with anything here
