### ISSUE TITLE
[CI] Disable cSpell inside code blocks for mermaid, and others?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3747]
This was inspired by work on #3651. There are too many false positives in running cSpell over `mermaid` code blocks, but I'm starting to think that we might want to disable spelling checks for all code blocks. WDYT @open-telemetry/docs-maintainers?

**Comment by theletterf** [comment]
Wholeheartedly agree on disabling spell checks for code blocks. The only risk I see is getting typos in code comments, but I'm not that concerned about it if the net outcome is lowering friction for contributors.
