### ISSUE TITLE
Add more details about "service" to the Resource page

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3763]
With `service.name` having a clear description now (https://github.com/open-telemetry/semantic-conventions/pull/630) and `service.type` coming (https://github.com/open-telemetry/semantic-conventions/pull/575), we should expand on this important topic on our concept pages (https://opentelemetry.io/docs/concepts/resources/#semantic-attributes-with-sdk-provided-default-value)

**Comment by cartermp** [comment]
I'm thinking we're also due for another rewording of this to clarify what resources are exactly. One thing I've noted seems to work well with people is framing it up explicitly like this:

Spans, Logs, Metrics, and their attributes tell you _what_ is happening.
Resources tell you _where_ it is happening.

There's...a little bit of nuance lost there, like how a span also kinda tells you the "where", and how a resource isn't just about concrete things, but can represent a virtual entity like a service. But it's a framing that I've seen work well.

**Comment by svrnm** [comment]
The related PRs have been closed or rolled back, so my initial request is no longer applicable
