### ISSUE TITLE
Turn on GitHub Discussions for project related discussions

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3798]
> Btw, just a suggestion: we could host discussions under the [Discussions](https://github.com/open-telemetry/opentelemetry.io/discussions) section of this repo :). That would help keep discussion topics out of our already-busy Issues list.

via @chalin's comment (https://github.com/open-telemetry/opentelemetry.io/issues/3791#issuecomment-1895729157)

We have a few discussion issues going right now that we could move over there, e.g.

* https://github.com/open-telemetry/opentelemetry.io/issues/3791
* https://github.com/open-telemetry/opentelemetry.io/issues/3792
* https://github.com/open-telemetry/opentelemetry.io/issues/3793
* https://github.com/open-telemetry/opentelemetry.io/issues/3783
* https://github.com/open-telemetry/opentelemetry.io/issues/3779
* https://github.com/open-telemetry/opentelemetry.io/issues/3642
* https://github.com/open-telemetry/opentelemetry.io/issues/3381
...

In total there are 27 issues marked as "discussion", not all of them would qualify to be moved, but we could reduce our issue count by that.

Downsite of enabling discussions is that we have to manage one more thing, and we will have people create discussions around otel questons, which we then politely need to close or move somewhere else (community? tbh, I am not sure)

Discussion categories could be:
* Information Architecture
* Terminology
* CI & Build Tooling

@open-telemetry/docs-approvers wdyt?

**Comment by theletterf** [comment]
Discussions can be healthy! I vote Yes to this idea. :)

**Comment by chalin** [comment]
I'd vote to try it too. 👍🏻 

Btw, [Converting an issue to a discussion](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion) might come in handy. :)

**Comment by simi** [comment]
I have good experience using discussions and separate them from issues too.

**Comment by cartermp** [comment]
Yep, let's turn them on
