### ISSUE TITLE
Links into oncallmemaybe.com site aren't available and so podcast links yield 404s

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3818]
Hey @avillela, I'm working on:

- #3804

and the links to the On-call Me Maybe podcast are yielding 404s. Here they are:

- https://oncallmemaybe.com
- https://oncallmemaybe.com/episodes/adventures-in-open-source-software-with-riaan-nolan-of-servian
- https://oncallmemaybe.com/episodes/opentelemetry-nomad-with-luiz-aoqui-of-hashicorp
- ~https://oncallmemaybe.com/episodes/adventures-in-open-source-software-with-riaan-nolan-of-servian~ Oops, this is actually the same as an earlier entry in this list

What should these be replaced by? Links into YouTube or Spotify? Could you provide the exact links? Thanks!

References:

- https://www.youtube.com/@oncallmemaybepodcast
- https://open.spotify.com/show/4ZI6pQwChwm4sVULdtHFMe

**Comment by avillela** [comment]
@chalin I think the easiest thing is to replace it with the Spotify links:

* https://oncallmemaybe.com/ should be https://open.spotify.com/show/4ZI6pQwChwm4sVULdtHFMe
* https://oncallmemaybe.com/episodes/adventures-in-open-source-software-with-riaan-nolan-of-servian should be https://open.spotify.com/episode/5YrBEsXoJV3UjrHRrLRqBP?si=BpWISRD0SLytJF-vJ02sSA
* https://oncallmemaybe.com/episodes/opentelemetry-nomad-with-luiz-aoqui-of-hashicorp should be https://open.spotify.com/episode/7ww8y3fy49MgEbcyFGvsNV?si=BMvp8u-dRgyPEkTkYxfDAA
https://oncallmemaybe.com/episodes/adventures-in-open-source-software-with-riaan-nolan-of-servian should be https://open.spotify.com/episode/5YrBEsXoJV3UjrHRrLRqBP?si=BpWISRD0SLytJF-vJ02sSA
