### ISSUE TITLE
Drop teletrace.io from vendors?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3819]
Hi @ophiryael: is [docs.teletrace.io](https://docs.teletrace.io/) still meant to be up?

- The site is down:
  ```console
  $ curl -I https://docs.teletrace.io/ 
  curl: (6) Could not resolve host: docs.teletrace.io
  ```
- The org doesn't seem to have active development: https://github.com/teletrace

Related:

- #2606
- #3804

**Comment by ophiryael** [comment]
Teletrace is no longer maintained. It can be removed from the list of vendors.
I can open a PR if it helps.
