### ISSUE TITLE
Community meeting time

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry.io#3836]
https://github.com/open-telemetry/opentelemetry.io?tab=readme-ov-file#contributing Page lists community meeting at 9AM PT. But the calendar shows 10 AM PT.

![image](https://github.com/open-telemetry/opentelemetry.io/assets/5232798/a259ef53-2ced-4173-b162-05aa5826ad30)

Also https://github.com/open-telemetry/community?tab=readme-ov-file#special-interest-groups is missing information about docs group? Is that omitted intentionally?

I can send PRs to fix them, if the owners can confirm the actual time.

**Comment by svrnm** [comment]
> [open-telemetry/opentelemetry.io#contributing](https://github.com/open-telemetry/opentelemetry.io?tab=readme-ov-file#contributing) Page lists community meeting at 9AM PT. But the calendar shows 10 AM PT.

that needs to be fixed, thanks!

> Also [open-telemetry/community#special-interest-groups](https://github.com/open-telemetry/community?tab=readme-ov-file#special-interest-groups) is missing information about docs group? Is that omitted intentionally?

We are listed as "Communications (Website, etc.)" under Instrumentation SIGs, might be worth to add "Documentation" and also move it into a different place?
 
> I can send PRs to fix them, if the owners can confirm the actual time.

That would be awesome, thank you!

**Comment by cijothomas** [comment]
> We are listed as "Communications (Website, etc.)" under Instrumentation SIGs, might be worth to add "Documentation" and also move it into a different place?

Aah! I missed that! Adding the word "docs or documentation" would make it easy to search/find. Moving to a diff. place probably requires more discussion.

**Comment by svrnm** [comment]
> > We are listed as "Communications (Website, etc.)" under Instrumentation SIGs, might be worth to add "Documentation" and also move it into a different place?
> 
> Aah! I missed that! Adding the word "docs or documentation" would make it easy to search/find. Moving to a diff. place probably requires more discussion.

yeah, adding the word documentation is step 1 :-)

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/community/pull/1889
