### ISSUE TITLE
CSS for links needs to be fixed when primary color is used

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry.io#384]
If the background for a section is set to the primary color (blue) then links are hard to see on hover.

![Screen Shot 2021-02-14 at 11 31 53 PM](https://user-images.githubusercontent.com/645366/107905584-fda2bb80-6f1c-11eb-9c42-601b194053f5.png)

![Screen Shot 2021-02-14 at 11 31 58 PM](https://user-images.githubusercontent.com/645366/107905591-01364280-6f1d-11eb-9eb6-08328e112c7f.png)

In addition, even without hover the "white" color is not apparent enough and should be fixed.

**Comment by WPH95** [comment]
we have different link color 
![image](https://user-images.githubusercontent.com/2732352/108177227-e8f13e00-713d-11eb-8199-050a70da046c.png)
![image](https://user-images.githubusercontent.com/2732352/108177248-f0b0e280-713d-11eb-9d8c-7acf7ee716a7.png)
