### ISSUE TITLE
The getting started doc for .NET is incorrect

### ISSUE THREAD

**Issue by wmeints** [open-telemetry/opentelemetry.io#3865]
**What needs to be changed?**

[The .NET getting started guide](https://opentelemetry.io/docs/languages/net/getting-started/) mentions a prerelease version of the instrumentation library. Except that it's released now and I think we should prefer a released version of a library.

**What is the name + path of the page that needs changed?**
`languages/net/getting-started/`

**Comment by wmeints** [comment]
I'm willing to update the docs. So please let me know if that's what you prefer.

**Comment by cartermp** [comment]
This page also needs updating since the HTTP and ASP.NET instrumentations are stable: https://opentelemetry.io/docs/languages/net/libraries/#example-with-aspnet-core-and-httpclient

@wmeints if you're up for it, we'll gladly accept the PR!

**Comment by cartermp** [comment]
Yes, this is now resolved.
