### ISSUE TITLE
Migrate the Collector Troubleshooting docs to OpenTelemetry.io

### ISSUE THREAD

**Issue by theletterf** [open-telemetry/opentelemetry.io#3894]
As of now, the [Collector troubleshooting docs](https://opentelemetry.io/docs/collector/troubleshooting/) are disappointingly terse — all they do is linking to https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md

I suggest that we migrate them to the docs site and recommend in the Collector repo that the official OTel.io doc is maintained instead. Right now, it does not invite contributions.

**Comment by theletterf** [comment]
+CC @open-telemetry/collector-maintainers

**Comment by mx-psi** [comment]
Relates to open-telemetry/opentelemetry-collector/issues/8886 I guess?

**Comment by theletterf** [comment]
@tiffany76 Could you reference this issue when you migrate the document using "Fixes #3894"?

**Comment by tiffany76** [comment]
> Could you reference this issue when you migrate the document using "Fixes #3894"?

Sure, will do!
