### ISSUE TITLE
Remove processor from glossary

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry.io#3895]
https://opentelemetry.io/docs/concepts/glossary/#processor talks about Instrumentation Library, but not sure what is the connection between Instrumentation Library and processor here....

**Comment by cijothomas** [comment]
It may be better to remove it, as it is a collector specific term. (There are other processors like spanprocessor/logrecordprocessor, but not in the glossary, and don't think we should have it for the processor in the collector in the main glossary).

**Comment by svrnm** [comment]
Thanks for calling this out. We had a few places in the past already that mixed instrumentation libraries with other components (here I would say it's language specific SDK)

Feel free to raise a PR

**Comment by theletterf** [comment]
@cijothomas Will you open the PR? Thanks!

**Comment by ricardoamaro** [comment]
https://github.com/open-telemetry/opentelemetry.io/pull/4307

**Comment by svrnm** [comment]
@ricardoamaro please look above that @IrisDyr asked to pick this first and we should give people some time to provide their PR after volunteering. This is a trivial change, but I want to be respectful here. @IrisDyr please let us know if you are OK with us merging @ricardoamaro's PR.

**Comment by IrisDyr** [comment]
It's okay for me to merge it. Thank you @svrnm

**Comment by ricardoamaro** [comment]
Thank you, @IrisDyr 👍🏽! I would also be ok waiting more. Taking the opportunity here to learn the ropes :)
