### ISSUE TITLE
Native libraries list

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry.io#3896]
https://opentelemetry.io/docs/languages/net/libraries/#use-natively-instrumented-libraries 
This is asking for list of any such libraries:
here's some:

Azure SDKs.
https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/

MassTransit .NET client:
https://masstransit.io/documentation/configuration/observability

I can also add HttpClient, and Asp.Net Core as they produce logs and metrics (but not yet traces - traces are produced but without much attributes).

**Comment by svrnm** [comment]
Love it, thank you for sharing!

**Comment by svrnm** [comment]
Labeling this as good first issue, since it has clear instructions: take a look at the items listed here and add them to 

https://opentelemetry.io/ecosystem/integrations/

**Comment by mgurrie** [comment]
I am working on this and submitting a pr soon.

**Comment by tiffany76** [comment]
Fixed by #4337
