### ISSUE TITLE
Site needs to redeploy at some interval in order to update project status chart.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#39]
The project status chart re-populates information every time the site is rebuilt, we should have a trigger to re-deploy the site every day in order to get fresh data. GitHub Actions might be suitable for this, need to investigate.

**Comment by lucperkins** [comment]
@austinlparker I set up a Zapier Zap to do this. A log of the first automated deploy can be viewed here: https://app.netlify.com/sites/opentelemetry/deploys/5d939d38552d588b8b1a8dec.
