### ISSUE TITLE
The "submit a blog" link is dead

### ISSUE THREAD

**Issue by pirgeo** [open-telemetry/opentelemetry.io#3907]
In the main [README.md](https://github.com/open-telemetry/opentelemetry.io/blob/main/README.md), the link to "Submit a new blog post" is broken: https://github.com/open-telemetry/opentelemetry.io/blob/main/README.md?plain=1#L21
It points to https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/contributing/blog (no extension), but I think it should point to https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/contributing/blog.md (added `.md`) or directly to https://opentelemetry.io/docs/contributing/blog/. 

Happy to send a PR, just not sure which one is preferred, the opentelemetry.io link or the link to the markdown file.

**Comment by svrnm** [comment]
thanks for reporting @pirgeo 

@chalin , @theletterf please take a look you have the best insights which places from the contribution guidelines need to be used here.

**Comment by chalin** [comment]
Right, it should point to https://opentelemetry.io/docs/contributing/blog/. A PR would be welcome, thanks!

**Comment by theletterf** [comment]
L10 also needs fixing then! Using absolute URLs here: https://github.com/open-telemetry/opentelemetry.io/pull/3914

**Comment by chalin** [comment]
Thanks @theletterf!
