### ISSUE TITLE
Additional icon requests

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry.io#392]
Loving the icons! I was wondering if a few more could be created:

- gRPC (to go with HTTP)
- service and extension (to go with receivers/processors/exporters). These may be challenging...
- Fluent Bit (to go with Jaeger and Prometheus)

**Comment by flands** [comment]
@jkowall

**Comment by jkowall** [comment]
Yes, we can do these. I can chat with Ella on these items.

Can you please clarify the second bullet "service and extension"? @flands

**Comment by flands** [comment]
> Can you please clarify the second bullet "service and extension"? @flands

In addition to receivers/processors/exporters in the Collector there are extensions: https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension. I am hoping to add an icon to this section: https://opentelemetry.io/docs/collector/configuration/#extensions and ideally to the collector image: https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/Otel_Collector.svg

**Comment by flands** [comment]
In addition, the following languages need icons:

- PHP
- Rust
- Swift

**Comment by Ella-bz** [comment]
![image](https://user-images.githubusercontent.com/73476445/108969122-4a5b6480-768a-11eb-87a0-f56e85a55c0c.png)
Feedback?

**Comment by cviebrock** [comment]
@Ella-bz The official PHP logo is an oval.  Maybe consider changing the rounded rectangle? :)

**Comment by Ella-bz** [comment]
[PHP.svg.zip](https://github.com/open-telemetry/opentelemetry.io/files/6706676/PHP.svg.zip)
Got it. Like this is good?

**Comment by cviebrock** [comment]
Looks great!

**Comment by svrnm** [comment]
looks like this never got implemented & the issue is stuck. I like those additional icons very much, @jkowall, @Ella-bz: if the SVGs of those still exist, I would be happy to put them in https://github.com/open-telemetry/opentelemetry.io/tree/main/iconography/512x512 & use them accordingly through out the docs.
