### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by oliver-sturrock** [open-telemetry/opentelemetry.io#3929]
This page goes into a lot of detail about the content of the configuration file, but never states what the configuration file is called or where it is located.

**Comment by svrnm** [comment]
@oliver-sturrock what page are you talking about, can you provide a link?

**Comment by oliver-sturrock** [comment]
Sorry - that would have been useful info... This page: https://opentelemetry.io/docs/collector/configuration/ I did find the file in /etc/otelcol/, but it took some searching.

**Comment by cartermp** [comment]
Mmm, yes, we should clarify where you'll generally find (or need to place) a config file.

**Comment by oliver-sturrock** [comment]
As a minor, related point: I created this issue by clicking on the "Create documentation issue" link within the documentation. I assumed (wrongly) that it would automatically provide you the context/page link when I did that. Probably others will make the same assumption.

Thanks,
Oliver.
________________________________

**Comment by svrnm** [comment]
> As a minor, related point: I created this issue by clicking on the "Create documentation issue" link within the documentation. I assumed (wrongly) that it would automatically provide you the context/page link when I did that. Probably others will make the same assumption. Thanks, Oliver.

Thanks for calling this out, GitHub allows to send some properties with a new issue link, maybe that can be added to those links, cc @chalin
