### ISSUE TITLE
[CI] Create an action to run `npm run sync`

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3950]
_Originally posted by @svrnm in https://github.com/open-telemetry/opentelemetry.io/issues/3948#issuecomment-1929932840_:

> First: +1 for `npm run sync` fixing 80% of that, I used it the other day and it does a perfect job, maybe we can turn this into a `/fix:sync` as well?

Great idea to have a `/fix:*` trigger for `npm run sync`. Candidate command names:

- `/fix:submodules`
- `/fix:modules`
- `/sync:submodules` -- we don't really _have to_ stick to the `fix` prefix

Other suggestions are welcome.

**Comment by svrnm** [comment]
`/fix:submodules` sounds good to me
