### ISSUE TITLE
Python Exporters page links to Node packages

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry.io#3964]
https://opentelemetry.io/docs/languages/python/exporters/#otlp-dependencies has links to the Node packages for [HTTP/protobuf](https://www.npmjs.com/package/@opentelemetry/exporter-trace-otlp-proto) and [gRPC](https://www.npmjs.com/package/@opentelemetry/exporter-trace-otlp-grpc). Shouldn't this point to the Python dependencies, or are these using Node as just an example?

**Comment by pegasas** [comment]
nice catch,
I create a PR for fixing this.
