### ISSUE TITLE
[C++] Use find_package insead of adding include directories 1 by 1

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#3974]
via https://github.com/open-telemetry/opentelemetry.io/pull/3423#discussion_r1473666572 from @ThomsonTan 

> Could here use find_package(opentelemetry-cpp CONFIG) instead of adding include directories 1 by 1?

cc @Akhaled19

**Comment by svrnm** [comment]
Tagged this as `good first issue` and `help wanted`. Note that this is only a good first issue if someone knows C++ well enough to tackle it (since this is required, not so much being able to work with our docs)

**Comment by ricardoamaro** [comment]
Giving a try on this one
