### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by asafm** [open-telemetry/opentelemetry.io#4023]
**Desired feature or idea**: What would you like to see happen?
I would like to read the website at night comfortably, hence I would like the site to support dark mode automatically, based on the operating system setting.

---

- [x] #4389
- [x] #4391
- [x] https://github.com/google/docsy/issues/1943
- [x] https://github.com/google/docsy/issues/1961
- [x] https://github.com/google/docsy/issues/1967
- [x] https://github.com/google/docsy/issues/1970
- [x] #4347
- [x] #4346
- [ ] Bring in last Docsy light/dark mode related element color fixes

**Comment by svrnm** [comment]
hey @asafm, we use [docsy](https://www.docsy.dev/) as hugo template, so it might be an option to bring this feature there to get it for the opentelemetry.io website.  @chalin wdyt?

**Comment by theletterf** [comment]
Notice that https://github.com/google/docsy/issues/331 is still open.

**Comment by chalin** [comment]
Yes, there's base work that needs to be done first -- migrating to Bootstrap 5.3. That should get some attention in the next release (or so) :).

**Comment by theletterf** [comment]
@chalin Support for custom themes will unlock this?

**Comment by chalin** [comment]
Yes, the feature is on its way -- probably next week, via version 0.10.0 of Docsy.

**Comment by svrnm** [comment]
As this has a clear outcome ("implement dark mode when docsy has it") I remove the `discussion` label, but I add `blocked` since this depends on docsy being 0.10

**Comment by cartermp** [comment]
The little collapsy arrow would probably look more visually distinct if it had a brighter color 
![Uploading image.png…]()

**Comment by pellared** [comment]
Registry and Status pages look incorrect

**Comment by chalin** [comment]
Thanks all for your feedback, it's much appreciated! I'll look into each issue. Keep'm coming ✨

**Comment by tiffany76** [comment]
Many of the code snippets have faded to illegibility, at least for me. This screenshot is from the [Collector Quick start](https://deploy-preview-4347--opentelemetry.netlify.app/docs/collector/quick-start/) page, but the issue is present on many other pages as well.

![Screenshot from 2024-04-25 11-36-06](https://github.com/open-telemetry/opentelemetry.io/assets/30397949/3d9cae4d-5dbd-40b8-a5d6-41281e86b68d)

**Comment by asafm** [comment]
Thanks a lot for this!
