### ISSUE TITLE
Updates for Javaagent 2.2.0

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry.io#4027]
- Spring starter
  - [x] document resource providers, including the spring resource providers for service.name and service.version: https://github.com/open-telemetry/opentelemetry.io/pull/3999
  - [x] all of SDK auto-config available: https://github.com/open-telemetry/opentelemetry.io/pull/4167
  - [x] How to add a AutoConfigurationCustomizerProvider: https://github.com/open-telemetry/opentelemetry.io/pull/4167
  - [x] include dependencies for propagators: https://github.com/open-telemetry/opentelemetry.io/pull/4167
  - [x] enable resource providers: https://github.com/open-telemetry/opentelemetry.io/pull/4138

**Comment by cartermp** [comment]
Closing out, as all PRs are now merged. Thanks @zeitlinger!
