### ISSUE TITLE
`java/automatic/configuration` links out to pages that should be moved to docs

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry.io#4032]
https://opentelemetry.io/docs/languages/java/automatic/configuration/ links to pages in other repos, e.g. https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-span-metric-and-log-exporters

This content should be moved to this repo.

---

(**Edit: @chalin**)

- [x] Move content to this repo
- [ ] Remove content from otel-java repo
- [ ] update contribution guidelines

**Comment by jaydeluca** [comment]
If there's anything else needed just let me know, but otherwise I believe this issue is now ready to be closed.

**Comment by svrnm** [comment]
@zeitlinger can you take a look if this issue can be closed?

**Comment by zeitlinger** [comment]
looks good
