### ISSUE TITLE
Inconsistent usage of automatic vs instrumentation library

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry.io#4054]
The following 2 docs uses the word "Instrumentation Libraries" and "Auto-instrumentation" respectively, likely referring to the same thing?
https://opentelemetry.io/docs/demo/telemetry-features/trace-coverage/
https://opentelemetry.io/docs/demo/telemetry-features/metric-coverage/

I think the metric-coverage doc should be using "Instrumentation Libraries" as well.

Related to https://github.com/open-telemetry/opentelemetry.io/discussions/3809 and many other discussions on this topic!

**Comment by svrnm** [comment]
Yes, this is unfortunately a common issue across the documentation (and other places), that those two words are used interchangable, although they mean different things. Thanks for calling this out

@open-telemetry/demo-approvers please take a look
