### ISSUE TITLE
General SDK Configuration

### ISSUE THREAD

**Issue by willie** [open-telemetry/opentelemetry.io#4059]
Apparently, [environmental variables are optional](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables), but the SDK documentation does not indicate this. 

For example, the C++ SDK does not implement `OTEL_SERVICE_NAME`. https://github.com/open-telemetry/opentelemetry-cpp/issues/2559

**Comment by cijothomas** [comment]
Good point! We may need to do an audit and make sure the docs page is not promising something not implemented by the language sdks!

**Comment by cartermp** [comment]
Huh, TIL. I would have figured at least `OTEL_SERVICE_NAME` would be required for all SDKs.

**Comment by cijothomas** [comment]
> Huh, TIL. I would have figured at least `OTEL_SERVICE_NAME` would be required for all SDKs.

Maybe its worth exploring is spec is willing to make some env variables mandatory? I am not sure what was the reason it was optional in the spec. (That'll, unfortunately, open up other heated discussion about priority - code or env-var  who wins! From my own experience, languages vary in this regard)

**Comment by svrnm** [comment]
From a docs perspective the first thing to do is indeed adding a disclaimer that says what is state of the spec right now, but from an overall perspective I agree that providing some more consistency here would be very end-user friendly.

**Comment by svrnm** [comment]
@willie would you be willing to provide a PR with such a disclaimer?

**Comment by willie** [comment]
Resolved by #4099
