### ISSUE TITLE
Update connectors document wording

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry.io#4072]
**What needs to be changed?**  On https://github.com/open-telemetry/opentelemetry.io/blob/aa893b38c3603fa1e5bccc9229844341a2e3e97d/content/en/docs/collector/building/connector.md?plain=1#L35-L37 we mention the `spanmetrics` processor and the `servicegraph` processor. Both of this processors have now been removed from the Collector contrib distribution, so I think we should change the introductory paragraph to either mention the historical fact that these components existed or reword it differently.

**What is the name + path of the page that needs changed?** content/en/docs/collector/building/connector.md

**Comment by MinalAC** [comment]
Hi @svrnm I would like to take this up.

**Comment by MinalAC** [comment]
I have created this PR --> https://github.com/open-telemetry/opentelemetry.io/pull/4086

Let me know any feedback as this is my first contribution.

**Comment by svrnm** [comment]
thank you @MinalAC

**Comment by theletterf** [comment]
Closing as done (#4086)
