### ISSUE TITLE
Reference architecture image: updates needed

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry.io#411]
Two changes required:

- `OT Library` should be `OTel Library`
- `Otel Collector` should be `OTel Collector`

source: https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/Reference_Architecture.svg

@jkowall FYI

**Comment by jkowall** [comment]
Thanks! Can get those changed.

**Comment by Ella-bz** [comment]
<img width="784" alt="Reference Architecture@2x" src="https://user-images.githubusercontent.com/73476445/108337814-34f3bf80-71de-11eb-9854-860bc1aca34c.png">
fixed

**Comment by jkowall** [comment]
Thanks @Ella-bz!

@flands do you want the icon images updated from the zip too?

**Comment by flands** [comment]
yes please!

**Comment by mnadeem** [comment]
I have tried doing something similar with **Microsoft power point** it is not as classy as the one above :( 

![image](https://user-images.githubusercontent.com/476145/109039153-79a5bc00-76f2-11eb-84c5-fbe3c1c22779.png)


[OTel.pptx](https://github.com/open-telemetry/opentelemetry.io/files/6037710/OTel.pptx)

**Comment by mnadeem** [comment]
Did something similar for other image as well, attaching it so that it could be reused by community.

![image](https://user-images.githubusercontent.com/476145/109109953-3b44e700-775c-11eb-98ff-08a25f731fbb.png)

[OTel.pptx](https://github.com/open-telemetry/opentelemetry.io/files/6040795/OTel.pptx)

Glad That I have learnt creating nice ppt from community as I have learned java, Javascript and Go :)

**Comment by jkowall** [comment]
Here is a new ppt from @Ella-bz https://docs.google.com/presentation/d/19woronewjAZT1GF0jgbr0XaTh9_x8DrnyhqyGD2OGLI/edit?usp=sharing

**Comment by jkowall** [comment]
The design is in Figma if you want to have access to it there that is possible. https://www.figma.com/file/PZ1zSzBeNOjJkHTbmRSEcK/Materials-(pics%2C-screens-etc.)?node-id=378%3A0 

I can export it if you want, or we can ask Ella for changes.

**Comment by chalin** [comment]
Thanks for the link! (Who owns the file?)

As far as I can tell, the changes were made, and it seems like I can export the SVG, so I'll submit a PR soon.
