### ISSUE TITLE
Java Metrics Documentation could use an update

### ISSUE THREAD

**Issue by jaydeluca** [open-telemetry/opentelemetry.io#4123]
I would like to re-write the Java Metrics documentation to follow a format similar to other languages, and include missing information on Exporters, Readers, and Views.

## What needs to be changed?

The current [java instrumentation -> metrics documentation](https://opentelemetry.io/docs/languages/java/instrumentation/#metrics) is missing a lot of information. As a new user who wants to start using java OpenTelemetry metrics, there is not enough information provided on this page to actually get started. Right now it only provides a brief introduction to the different instrument types supported, with very basic code examples.

Other languages like [Go](https://opentelemetry.io/docs/languages/go/instrumentation/#metrics), [C++](https://opentelemetry.io/docs/languages/cpp/instrumentation/#metrics) and [Javascript](https://opentelemetry.io/docs/languages/js/instrumentation/#metrics) follow a more in depth and organized structure / content that cover several things that the current java documentation doesn't include.

I plan to re-write this section of the java documentation to follow the structure of:

- Intro
- Initialize Metrics (MeterProvider)
- Acquiring a Meter
- Using Counters
- Using UpDown Counters
- Using Histograms
- Using Observable (Async) Counters
- Using Observable (Async) UpDown Counters
- Using Observable (Async) Gauges
- Adding Attributes
- Metric Views

## Path of the page that needs changed?

https://opentelemetry.io/docs/languages/java/instrumentation/#metrics

## Additional Context / Notes

I wasn't sure if I should open this issue in the [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java) repo or this one, if I need to do anything else before contributing this change, please let me know.

**Comment by svrnm** [comment]
Hey @jaydeluca, thanks for raising this issue and offering your help, this is the right place to ask for this (although I cc @open-telemetry/java-approvers for visibility).

Please go ahead and provide these updates to the Instrumentation Documentation, all I ask you to do is use the JavaScript and other documentation that is already in place as a blueprint for your additions. We try to create consistent documentation across languages right now, such that most of the non-code part of the documentation is the same, see
https://github.com/open-telemetry/opentelemetry.io/issues/3229

**Comment by trask** [comment]
yes ❤️❤️❤️
