### ISSUE TITLE
doc(kubernetes): update configuring auto-instrumentation for nodejs

### ISSUE THREAD

**Issue by atsu85** [open-telemetry/opentelemetry.io#4130]
**What needs to be changed?**
After [this merged PR](https://github.com/open-telemetry/opentelemetry-operator/pull/2745) is released, documentation about no way to configure auto-instrumentations becomes outdated

**What is the name + path of the page that needs changed?**

* The relative path: [content/en/docs/kubernetes/operator/automatic.md](https://github.com/open-telemetry/opentelemetry.io/blob/2115d76bd581535b4aced617cf2ab38ae5d64a22/content/en/docs/kubernetes/operator/automatic.md?plain=1#L283-L290)
* page: Kubernetes Operator / Auto-instrumentation -> Configure Automatic Instrumentation > Node.js > [Excluding auto-instrumentation](https://opentelemetry.io/docs/kubernetes/operator/automatic/#js-excluding-auto-instrumentation)

**Additional context**: 
It becomes outdated after the next release of opentelemetry-operator.

**Comment by cartermp** [comment]
Thanks, so it sounds like it can be changed to say something to the effect of:

"You can include only specific instrumentations by using the `OTEL_NODE_ENABLED_INSTRUMENTATIONS` environment variable. For example, here's how you can include only `http` and `nestjs-core` instrumentations:

```
export OTEL_NODE_ENABLED_INSTRUMENTATIONS="http,nestjs-core"
```
"

**Comment by IrisDyr** [comment]
Seems that this task was already done in this [PR](https://github.com/open-telemetry/opentelemetry.io/pull/4137) and can be closed.

**Comment by svrnm** [comment]
Ah yes, but there were some outstanding points with that PR (I assumed this issue is the follow up to that), let me double check on that.

**Comment by svrnm** [comment]
Here's what's missing but indeed that should be an issue on it's own while this one here is closed, apologies for overlooking that

https://github.com/open-telemetry/opentelemetry.io/pull/4137#discussion_r1560953944

(this follow up issue is a little bit more complicated since we need to see that also the JS repo will be updated accordingly)
