### ISSUE TITLE
Point URL for VuNet Systems to documentation

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#4151]
Follow up to #4115, as my comment has not been addressed before merging:

```
url: 'https://vunetsystems.com/vuapp360/'
```

This URL does not point to a documentation showing OTLP integration. We also need to know where and how the distribution looks like as `distrubtion: true` is set.

cc @rahjesh-vunet, @cartermp

**Comment by rahjesh-vunet** [comment]
@svrnm 

The vuapp360 is our application observability solution. It uses traces, logs and metrics from application to get the insights on application performance. It uses the opentelemetry for traces collection from the applications. We use the opentelemetry auto instrumentation for collecting traces from Java, .NET, NodeJS and JavaScript applications. We are using our own distribution of Opentelemetry collector.

In the product page of vuapp360 (https://vunetsystems.com/vuapp360/)  in the "Instrumentation and Ingestion through OpenTelemetry" section, you can see high level architecture which explains what I mentioned above.

**Comment by svrnm** [comment]
@rahjesh-vunet, from your description this sounds like you are not providing native OTLP ingestion for your endpoint (I am inferring that from "with our own exporter")

**Comment by rahjesh-vunet** [comment]
@svrnm 

Applications are sending the traces to our OTel collector distribution using grpc and http receivers. We are having a set of processors which we use in our distribution. We are using the Kafka exporter from the contrib to send it to our backend. The otlp and otlphttp exporters are available in our distribution. Sometimes we use these for sending the traces to other systems. 

The data ingestion uses the OTLP only.

**Comment by rahjesh-vunet** [comment]
@svrnm

You can see the below diagram in our product documentation page. https://vunetsystems.com/vuapp360/

![image](https://github.com/open-telemetry/opentelemetry.io/assets/70252532/88bbfe6f-2886-4469-ba7f-e1b1ddf157bf)

As you can see, the vuapp360 contains everything including the Otel collector. The vuapp360 is not a saas product like others. It is installed in the customer premises. It can also be available as saas in the future.

We will install vuapp360 on the customer premises and provide the ingestion URL to them. The ingestion url is the URL of the OTel collector. Our client will use the otel SDK to instrument their application and send the traces to Otel collector of vuapp360.

**Comment by svrnm** [comment]
That image does not really indicate where the opentelemetry collector lives, but I can infer that from your text. So if I understand you correctly the OpenTelemetry collector is part of your solution, to provide OTLP ingestion. So then, yes, this makes sense. Thanks for clarification.

**Comment by rahjesh-vunet** [comment]
@svrnm 

Yes. 


Thanks.
