### ISSUE TITLE
Add instructions for linting and formatting back to CONTRIBUTING.md 

### ISSUE THREAD

**Issue by jaydeluca** [open-telemetry/opentelemetry.io#4169]
**What needs to be changed?**
As a contributor, I would like documentation for how to ensure my code is formatted properly before submitting PRs.  

There used to be a section titled "[Submitting a change](https://github.com/open-telemetry/opentelemetry.io/blob/9ffdd3f68b9131e450d3aa88af39b887510eb980/CONTRIBUTING.md#submitting-a-change)" that documented the `npm run test-and-fix` command, which can catch issues recommends running `npm run fix:format` to fix them.

This information was removed in [this PR](https://github.com/open-telemetry/opentelemetry.io/pull/3651), so I want to raise this issue before going ahead and adding it back, in case it was intentional and preferred not to be there.

I would like to add these back if there is no objection.

**What is the name + path of the page that needs changed?**
/CONTRIBUTING.md

**Comment by theletterf** [comment]
Hi Jay! Thanks for filing this issue.

The missing info is here now: https://opentelemetry.io/docs/contributing/pr-checks/
