### ISSUE TITLE
Python Benchmark page layout is not in a proper format

### ISSUE THREAD

**Issue by Cvr421** [open-telemetry/opentelemetry.io#4170]
Describe the problem that occurred.
Python Benchmark page layout is not in a proper format . The charts are overflowing . 

**What did you expect would happen?** Describe the expected result/output.
![image](https://github.com/open-telemetry/opentelemetry.io/assets/82499697/748326ce-f0cd-4c79-add6-3fbb42f7d904)

The relative path and page title where you found a problem.
https://opentelemetry.io/docs/languages/python/benchmarks/

**What browser, OS, and platform were you using when you encountered the
problem?** 
Browser: Chrome
OS : Ubuntu22.04

**Comment by Cvr421** [comment]
Hello @chalin @svrnm I am a outreachy applicant 2024. I am creating the PR about this issue please review and   let me know your thoughts .  Thanks

**Comment by cartermp** [comment]
@Cvr421 thanks for offering to contribute a fix! To do this you'll need to fork the repo, create a branch, and create a PR from your fork.

**Comment by Cvr421** [comment]
> @Cvr421 thanks for offering to contribute a fix! To do this you'll need to fork the repo, create a branch, and create a PR from your fork.

Thanks  @cartermp i have done the same things as you mention above. I think the issue with my github setting configuration .

**Comment by Cvr421** [comment]
@cartermp @chalin  I have created the PR please review and let me know thoughts . Thanks

**Comment by cartermp** [comment]
Thanks for the fix!
