### ISSUE TITLE
NodeJS auto instrumentation does not generate metrics (docs/languages/js/automatic)

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry.io#4171]
**What needs to be changed?**

The page should mention that metrics will not be generated when using `--require @opentelemetry/auto-instrumentations-node/register`

https://opentelemetry.io/docs/languages/js/automatic/#configuring-the-module tells the user they can configure `export OTEL_METRICS_EXPORTER="otlp"`, but this doesn't produce any metrics. Digging into this a bit, `@opentelemetry/sdk-node` does not support configuring a MeterProvider from just environment variables ([you need code](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-sdk-node#:~:text=//%20Optional%20%2D%20If%20omitted%2C%20the%20metrics%20SDK%20will%20not%20be%20initialized)).

This seems more like a bug in the Node SDK (possibly https://github.com/open-telemetry/opentelemetry-js/issues/3871).

**What is the name + path of the page that needs changed?**

https://opentelemetry.io/docs/languages/js/automatic/#configuring-the-module

**Comment by cartermp** [comment]
@open-telemetry/javascript-approvers what's your preferred resolution here? Remove the section about configuring metrics with env vars and making a notice about lacking support?

**Comment by pichlermarc** [comment]
> This seems more like a bug in the Node SDK (possibly https://github.com/open-telemetry/opentelemetry-js/issues/3871).

Yep, that's a missing feature.

> @open-telemetry/javascript-approvers what's your preferred resolution here? Remove the section about configuring metrics with env vars and making a notice about lacking support?

Yes I think that would be the best solution.

**Note:** if anyone's stumbling upon this issue, we're looking for contributors to pick up the following two issues (just split them from https://github.com/open-telemetry/opentelemetry-js/issues/3871 to make them easier to find):
- https://github.com/open-telemetry/opentelemetry-js/issues/4551
- https://github.com/open-telemetry/opentelemetry-js/issues/4552

**Comment by cartermp** [comment]
Thanks @pichlermarc and @aabmass! This should address it in the interim: https://github.com/open-telemetry/opentelemetry.io/pull/4181

**Comment by garysassano** [comment]
I was very confused about why my Lambda function wasn't emitting any metrics.

I was just setting up the following environment variables:

```env
AWS_LAMBDA_EXEC_WRAPPER: "/opt/otel-handler",
OTEL_SERVICE_NAME: "sqs-lambda",
OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf",
OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io:443",
OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=$HONEYCOMB_API_KEY",
```

**Comment by garysassano** [comment]
I was very confused about why my Lambda function was emetting traces but not metrics.

I was just setting up the following environment variables:

```env
AWS_LAMBDA_EXEC_WRAPPER: "/opt/otel-handler",
OTEL_SERVICE_NAME: "sqs-lambda",
OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf",
OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io:443",
OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=$HONEYCOMB_API_KEY",
```

**Comment by garysassano** [comment]
I was quite puzzled as to why my Lambda function was emitting traces but not metrics.

Here are the environment variables I had configured:

```env
AWS_LAMBDA_EXEC_WRAPPER: "/opt/otel-handler",
OTEL_SERVICE_NAME: "sqs-lambda",
OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf",
OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io:443",
OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=$HONEYCOMB_API_KEY",
```

**Comment by svrnm** [comment]
@garysassano can you raise a new issue with your comment/question, otherwise it gets losed since this is an already closed issue
