### ISSUE TITLE
Automatic Instrumentation

### ISSUE THREAD

**Issue by AntonKrug** [open-telemetry/opentelemetry.io#4252]
The [Microsoft Windows Server 2022](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) and [Ubuntu 20.04 LTS](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) links are 404

**Comment by theletterf** [comment]
Not sure this is a docs issue. @svrnm ?

**Comment by svrnm** [comment]
@AntonKrug can you let us know where those links are referenced?

**Comment by svrnm** [comment]
@AntonKrug feel free to reopen this issue with more details

**Comment by svrnm** [comment]
OK, it looks like this is related to this page: https://opentelemetry.io/docs/languages/net/automatic/ ? I can not verify that those links are 404
