### ISSUE TITLE
Add note to Contribution Guide that it's for docs and link to community guidelines

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#4292]
Reference: https://cloud-native.slack.com/archives/CJFCJHG4Q/p1713119897822229

The page under https://opentelemetry.io/docs/contributing/ talks about contributing to docs, although people might expect a page on how to contribute to the OpenTelemetry project in general. You have to read down a little bit to run into `See also the general [OpenTelemetry Contributor Guide](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md), which provides details on the Contributor License Agreement and the Code of Conduct.`

I think we should have this at the very top that this document is for contributing to docs and that the other document is where people find general guidelines.

**Comment by theletterf** [comment]
Fixed by #4296
