### ISSUE TITLE
Create a content card for OpenTelemetry Tuesdays.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#43]
Similar to the card for latest blog content, we should have a card that links to the OpenTelemetry Tuesday streams and archive. In addition, this card should have some visual assets (maybe even a logo for the stream?)

**Comment by maenad** [comment]
Hello! I want to give this a go! Do you have any link for the stream and archive? If not, I'll put a placeholder for it. Same with the logo bit.
