### ISSUE TITLE
Docmentation - TOC for Azure Messaging is titled as GooglePubSub under Docs / Specs / Semantic Conventions 1.25.0 / Messaging Systems

### ISSUE THREAD

**Issue by amccool** [open-telemetry/opentelemetry.io#4326]
in https://opentelemetry.io/docs/

the link in the TOC under Docs / Specs / Semantic Conventions 1.25.0 / Messaging Systems
for Azure Messaging is titled as GooglePubSub

https://opentelemetry.io/docs/specs/semconv/messaging/azure-messaging/

<img width="226" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/191144/112bfb5e-36ed-4134-8de1-bc8e450e9596">

**Comment by cartermp** [comment]
Handing this one over here: https://github.com/open-telemetry/semantic-conventions/pull/944
