### ISSUE TITLE
[Go] Document logs

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry.io#4373]
Document OTel Go Logs API, SDK and bridges under https://opentelemetry.io/docs/languages/go/instrumentation/#logs. Use https://opentelemetry.io/docs/languages/java/instrumentation/#logs as a reference.

Document log exporters under https://opentelemetry.io/docs/languages/go/exporters/

**Comment by pellared** [comment]
@open-telemetry/docs-maintainers Do you have any guidance on how to document Logs for Go? I think of using https://opentelemetry.io/docs/languages/java/instrumentation/#logs as a reference.

**Comment by cartermp** [comment]
@pellared I think using the Java docs as a model is a good start. We may eventually sweep through and apply some different kind of standardized format like we have done with other signals over time. But I see that happening once we have sufficient documentation of logs across the languages.
