### ISSUE TITLE
Semantic Attributes

### ISSUE THREAD

**Issue by kevintatou** [open-telemetry/opentelemetry.io#4385]
I am looking for Semantic Attributes that i can use, instead of having to manually type in the semantic conventions, similar to how it is done in java and nodejs. Any ideas? Am i missing something?  (https://opentelemetry.io/docs/languages/net/instrumentation/)

**Comment by svrnm** [comment]
@kevintatou does the following issue help with your question:

https://github.com/open-telemetry/opentelemetry.io/issues/1539
