### ISSUE TITLE
Create an exporter configuration guide for Jaeger

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#44]
We need a quick start guide for configuring traces to be sent to the Jaeger exporter, which should also include setting up Jaeger (locally, at least?). Basically the idea is "here's what you need to do in order to run Jaeger so you can see traces" as a starting point.

**Comment by Bhargavamacha** [comment]
Can I take this up? I have done it successfully locally.

**Comment by austinlparker** [comment]
Sure!

**Comment by Bhargavamacha** [comment]
I am planning on using opentelemetry-js' one of the examples to send data to Jaeger. Would that suffice?

**Comment by austinlparker** [comment]
That's fine for a start, yeah. We can add other languages to it after the initial work is done.

**Comment by Bhargavamacha** [comment]
I have created a document explaining how to get Jaeger up and running. 
https://docs.google.com/document/d/1On-NA39ra9c6EO8AuBC-Zc0NfUSBjKgnm528drvqp3E/edit?usp=sharing
Any suggestions on which way I should be going right now?

**Comment by austinlparker** [comment]
It'll need to be in markdown for us to use it on the site. I think it will be most useful if you could cover how to configure the opentelemetry exporter to Jaeger itself, and discuss any configuration options and what they do.

**Comment by Bhargavamacha** [comment]
Cool, I'll do that

**Comment by Bhargavamacha** [comment]
I made a rough draft of the Quickstart:
https://github.com/Bhargavamacha/jaegerforot/blob/master/Exporter%20configuration%20guide%20for%20Jaeger.md
Let me know if there are any edits

**Comment by mtwo** [comment]
Looks great! Can you create a PR to put it into the website repo? I'll add comments there

**Comment by ffe4** [comment]
@Bhargavamacha are there any updates on this issue or #45 ?

**Comment by Bhargavamacha** [comment]
The issue has been solved, it was merged to the master branch. [#119 ](https://github.com/open-telemetry/opentelemetry.io/pull/119#issue-383294712)

**Comment by ffe4** [comment]
@Bhargavamacha same with #45 ?

**Comment by Bhargavamacha** [comment]
I haven't opened a PR for it yet, will do it.

**Comment by austinlparker** [comment]
#119 only added guides for JavaScript. IMO, it'd be nice if there was a 'generic' landing page for Jaeger/Zipkin configs that had instructions for each language independently.

**Comment by Bhargavamacha** [comment]
Yeah, I think that's a good idea. Maybe a page saying integrations with all the integrations and options to choose the language for the specific documentation? I haven't been active for a few months, so I am not entirely sure if it's in the works or is already present.

**Comment by austinlparker** [comment]
There's a bit of a longer-term plan for this fall to rework the docs page entirely, where this would be a good fit.

**Comment by ffe4** [comment]
@austinlparker So, do we basically want a page with generic text for all languages and boxes with code where you can choose a tab for the language you are interested in?

**Comment by Bhargavamacha** [comment]
> There's a bit of a longer-term plan for this fall to rework the docs page entirely, where this would be a good fit.

Sure, sounds good. In the meantime, we can get started with it right, collecting the resources and creating them if there aren't any?

**Comment by austinlparker** [comment]
Yeah, I think a generic page with different tabs would be great. @Bhargavamacha if you'd like to take point on this, feel free!

**Comment by Bhargavamacha** [comment]
Cool, I'll get a basic framework of the webpage ready. Should a new issue be created?

**Comment by austinlparker** [comment]
Sure thing.

**Comment by austinlparker** [comment]
I'm going to close these because each language will have specific guides on export.
