### ISSUE TITLE
New Blog Post: Insights from the OpenTelemetry Collector Survey

### ISSUE THREAD

**Issue by IAMebonyhope** [open-telemetry/opentelemetry.io#4403]
Creating a blogpost to summarize the Open telemetry collector survey that was done by the End User SIG

Sponsors:
@musingvirtual 
@avillela

**Comment by musingvirtual** [comment]
Hello! I am sponsoring this post and have already reviewed the content in the Google Doc!

**Comment by musingvirtual** [comment]
@open-telemetry/blog-approvers for visibility

**Comment by svrnm** [comment]
Thanks, both!
