### ISSUE TITLE
Unclear use of variable client in Go OTLP trace exporter example

### ISSUE THREAD

**Issue by chrj** [open-telemetry/opentelemetry.io#4412]
**What needs to be changed?** Describe the update that is required.

It's not clear where the variable `client` comes from and the API reference documentation doesn't mention such a parameter https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp#New

**What is the name + path of the page that needs changed?** The relative path
and page title where you found a problem.

https://github.com/open-telemetry/opentelemetry.io/blob/1ba0c6cc16efbd36abb31a8a82d8e1e60770619c/content/en/docs/languages/go/exporters.md#otlp-traces-over-http

_Please delete paragraphs that you did not use before submitting._

**Comment by cartermp** [comment]
Hmmm, I think we're missing some code as of at least 8 months ago. At least in my app using the latest SDK, I have:

```go
import (
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
)
// ...
client := otlptracehttp.NewClient()
exp, err := otlptrace.New(ctx, client)

**Comment by cartermp** [comment]
Aha, indeed, my above code is redundanet with just `otlptracehttp.New(ctx)`. Should be a simple fix.
