### ISSUE TITLE
[IA] Zero-code as top-level section

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4427]
As [discussed during the 2024-05-06 Comms meeting](https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY/edit#bookmark=id.psd7kvp6ejwz), we're moving ahead with the proposal discussed via #3809. This meta issue will be used to track the migration work (and possibly some new additions). We'll be starting with Java.

Languages whose "Automatic" section will be moved to the new Zero-code top-level section:

- [x] .NET
  - [x] #4532 
  - [x] #4570
- [x] JavaScript
  - [x] #4527
  - [x] #4571
- [x] Java - #4428
- [x] PHP - #4716
- [x] Python - #4717
- [x] (Go) -- does not exist as of today

/cc @svrnm @zeitlinger

**Comment by svrnm** [comment]
this is completed
