### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by jason-visotrust** [open-telemetry/opentelemetry.io#4441]
Can't access slack channels if you're not a member of the CNCF and you seem to only be able to become a paid member

**Comment by svrnm** [comment]
We might want to replace the link to the #opentelemetry slack channel with [slack.cncf.io](https://slack.cncf.io/), which redirects people to the page that invites them to CNCF slack, they will unfortunately not land where we want to have them, but the other link is worthless without being registered already.

OR, we introduce a page with instructions via https://opentelemetry.io/community/end-user/slack-channel/

**Comment by cartermp** [comment]
We can close this one now with https://github.com/open-telemetry/opentelemetry.io/pull/4449
