### ISSUE TITLE
Create `docs-zh-approvers` etc

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4465]
@open-telemetry/docs-maintainers : given that we'll soon have Chinese language `content`, shall we create an OTel org-level team, say, `docs-zh-approvers`. That would make official who the custodians of those pages are, and make it possible to set CODEOWNERS, etc.

### Tasks

- [x] https://github.com/open-telemetry/community/issues/2107
- [x] Update CODEOWNERS - #4522
- [ ] #4584

### Reference

- https://github.com/orgs/open-telemetry/teams/docs-approvers

**Comment by svrnm** [comment]
Yes, we need that. There are `docs-cn-approvers` and `docs-cn-maintaines` already, who own https://github.com/open-telemetry/docs-cn. Not sure why there are no groups for docs-ja repo.

**Comment by svrnm** [comment]
As a point of reference, kubernetes has https://kubernetes.io/zh-cn/

**Comment by windsonsea** [comment]
IMO, all of these language code for Chinese are easy to understand. One concern is to keep consistency in the entire OTel org. We can pick one and use it throughly:

- zh
- zh-cn
- cn

**Comment by svrnm** [comment]
Thanks @windsonsea

A few more data points from CNCF

* https://glossary.cncf.io/zh-cn/
* Kubernetes uses `zh-cn` (see above) but the github team is `zh`: https://github.com/kubernetes/website/blob/main/data/i18n/zh-cn/OWNERS

**Comment by chalin** [comment]
I'd vote for `zh`, like GH. While `zh-cn` is an official language code, AFAIK, `cn` is not.

**Comment by chalin** [comment]
@svrnm - how about creating a label for Chinese page changes -- such as, say, `lang:zh`?

**Comment by windsonsea** [comment]
Yes, it would be helpful to add a label to clearly identify zh translations. Additionally, we should set the CODEOWNERs to `docs-zh-approvers` and assign PRs with the `lang:zh` label to this team.

If possible, I would greatly appreciate becoming a member of the `docs-zh-approvers` team. 😄

**Comment by svrnm** [comment]
label `lang:zh` created, I also provided a PR (#4480) to get it automatically applied on changes to content/zh

**Comment by svrnm** [comment]
See https://github.com/open-telemetry/community/issues/2107

**Comment by chalin** [comment]
Reopening until we answer the following question:

_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry.io/pull/4522#discussion_r1616433150_

>   I'd like to suggest that `content/zh/` also have @open-telemetry/docs-approvers, if only initially, as we iron out the wrinkles in the process. @open-telemetry/docs-approvers can always RSLGTM for PRs that are pure content, but as we ramp up there are likely to be "structural" / Hugo / Docsy / tooling related issues.

**Comment by windsonsea** [comment]
Could we grant `zh-approvers` the permission to merge only the `content/zh` docs? This would apply to PRs labeled with [lang:zh](https://github.com/open-telemetry/opentelemetry.io/pulls?q=is%3Apr+is%3Aopen+label%3Alang%3Azh).

**Comment by svrnm** [comment]
> Could we grant `zh-approvers` the permission to merge only the `content/zh` docs? This would apply to PRs labeled with [lang:zh](https://github.com/open-telemetry/opentelemetry.io/pulls?q=is%3Apr+is%3Aopen+label%3Alang%3Azh).

Tbh, I am not exactly sure if/how we can configure the repository to make this possible.

**Comment by chalin** [comment]
I'd keep it simple, and for the next couple of months, just add @open-telemetry/docs-maintainers over the `zh` folder.

**Comment by chalin** [comment]
Here's my proposal for now:

- #4584
