### ISSUE TITLE
Dark mode not working for java page

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry.io#4473]
Dark mode not working for java page: https://opentelemetry.io/docs/languages/java/automatic/configuration/#enable-resource-providers-that-are-disabled-by-default

![image](https://github.com/open-telemetry/opentelemetry.io/assets/2832627/164f4978-c973-4ee8-8de1-3fac45932c44)

**Comment by zeitlinger** [comment]
@svrnm not sure if we want to fix this - since I also saw that we want to document env vars only?

**Comment by cartermp** [comment]
@chalin we got ourselves a fun one

**Comment by chalin** [comment]
Oh yes, thanks for reporting that -- it is one I forgot. I _should_ be a quick fix. If not, I'll let this be given that you'll be dropping the use of the shortcode that generates those page elements, is that right?

**Comment by svrnm** [comment]
if it is a quick fix, maybe let's fix it even if we decide to drop that (except the dropping is a quick thing in itself)
