### ISSUE TITLE
Clarify use of double colon (::) notation in Collector config YAML paths

### ISSUE THREAD

**Issue by tiffany76** [open-telemetry/opentelemetry.io#4484]
**Desired feature or idea**: The use of a double colon (::) is valid syntax for configuring nested settings in a Collector config (for example, `service::telemetry::metrics::level: detailed`), but the double colon is not standard YAML notation. The use of the double colon should be explained in the [Collector Configuration](https://opentelemetry.io/docs/collector/configuration/) page.

**Additional context**: For reference, see https://github.com/open-telemetry/opentelemetry.io/pull/4322#discussion_r1597070512.

**Comment by svrnm** [comment]
@open-telemetry/collector-approvers @open-telemetry/collector-maintainers please take a look

**Comment by mx-psi** [comment]
To be clear: `service.telemetry.metrics.level` is also not standard YAML notation. There is no standard to refer to nested keys in a YAML document as far as I am aware.

**Comment by theletterf** [comment]
I'd rather use the dot notation, which is more Pythonesque and hence closer to Python? Although depending on the language one might recognize `::` as a namespace notation. Slashes are another option.

See https://github.com/wwkimball/yamlpath/wiki/Segments-of-a-YAML-Path

**Comment by svrnm** [comment]
> The main downside of dot notation I see (which is the reason we use :: for referring to nested keys) is that OpenTelemetry semantic conventions use dots for namespacing and we occasionally use semantic conventions as the name of configuration settings.

That's a great reason and we should put it that way in the doc, what do you think @tiffany76 ?

**Comment by tiffany76** [comment]
Sounds good to me, @svrnm, @mx-psi . I will make the addition today. Thanks!
