### ISSUE TITLE
[blog] Notice about removal of Go Contrib modules and call for Code Owners

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry.io#4502]
**Desired feature or idea**:

The Go SIG [plans to remove deprecate and remove Contrib modules](https://github.com/orgs/open-telemetry/projects/92/views/1) (instrumentation libraries, resource detectors, samplers, propagators) that have no [Code Owners](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/CONTRIBUTING.md#code-owners) unless we find some.

We think that it may be good to have some public announcement (blog post?) so that:
1. users will be notified that some modules are not maintained and they are going to be removed
1. we might actually find devs who would like to be code owners so some modules will not get removed

I think it would be good if the blog post would
- say that some modules and explain why are planned to be removed
- list all the Go modules that are planned to be removed and link it to an issue that tracks the deprecation/removal (e.g. https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5551).

**Additional context**:

Example deprecation PR:
- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5598

**Example blog post content:**

> The Go maintainers identified that some Contrib modules do not have any [Code Owner](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/CONTRIBUTING.md#code-owners). Because of this the following modules are [planned to be deprecated and later removed](https://github.com/orgs/open-telemetry/projects/92/views/1):
>
> - ...
> - [`go.opentelemetry.io/contrib/instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo`](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5551)
> - ...
>
> For each module, the removal is planned for no sooner than August 21, 2024 unless a Code Owner is found.

**Comment by pellared** [comment]
CC @open-telemetry/go-approvers

**Comment by theletterf** [comment]
@svrnm Did we publish similar call to actions / calls for volunteers in the past?

**Comment by svrnm** [comment]
> @svrnm Did we publish similar call to actions / calls for volunteers in the past?

I don't think so, but I am OK with doing that

**Comment by dmathieu** [comment]
Should it be something we do across several languages rather than just Go?

**Comment by svrnm** [comment]
> Should it be something we do across several languages rather than just Go?

I am OK with having it for go only, other SIGs can follow up with their own call to action whenever they are ready. Although if other SIGs want to do it jointly we can have it, maybe you check in #otel-maintainers

**Comment by theletterf** [comment]
Draft is ready for review! https://github.com/open-telemetry/opentelemetry.io/pull/4543
