### ISSUE TITLE
Configuration Docs Debugging

### ISSUE THREAD

**Issue by Wraith2** [open-telemetry/opentelemetry.io#4509]
For anyone trying to work out how to use processors it would be a good idea to mention the debug processor and link to the troubleshooting guide that tells you how to use it. https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md

**Comment by tiffany76** [comment]
Thanks, @Wraith2! We are currently working to build out the troubleshooting docs as part of #4192. The third PR, which addresses troubleshooting and the `debug` exporter, should be going up this week.

**Comment by svrnm** [comment]
Thanks @Wraith2 , @tiffany76 !

@Wraith2 feel free to take a look at the PR #4192 already and provide your feedback if this will introduce what you are looking for

**Comment by Wraith2** [comment]
It looks like that PR includes the presence of debug and how to use it.
