### ISSUE TITLE
New Blog Post: Observability on the Edge: Enhancing OTel support in Envoy and Istio

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/opentelemetry.io#4534]
Creating this issue following the guide here: https://opentelemetry.io/docs/contributing/blog/#before-submitting-a-blog-post

### Short description and outline of your blog post

I contributed several OTel features to both [Envoy](https://github.com/envoyproxy/envoy/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ajoaopgrassi+is%3Amerged) and [Istio](https://github.com/istio/istio/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ajoaopgrassi+is%3Amerged) and I think it would be cool to share those with the broader community to raise awareness. Those new features are:

- OTLP HTTP Exporter
- Resource detectors (shipped with environment one)
- Sampler API - There's now the ability for anyone to define their samplers

My idea and possible outline is:

- **Where we are now**: Envoy is deprecating OpenTracing and had limited OTel feature support
- **New OTel tracing features Envoy/Istio**: Explain what new features are about and how the community can benefit from it
- Maybe a quick set up demo with screenshots
- **Next up**: Talk about next improvements to be added there, for example align Envoy with the now stable HTTP semconv

### Technologies

- [Envoy](https://www.envoyproxy.io/)
- [Istio](https://istio.io/)
- C++, Go

### Related SIG

I think this spans over multiple, but I'd say the Spec SIG is the most relevant. I talked with @jsuereth as the SIG sponsor which he gladly accepted (thanks!).

**Comment by svrnm** [comment]
Thanks for following the process! This sounds like a blog post we should have indeed 

Independent of that would you mind adding envoy/istio to the integrations page? https://opentelemetry.io/ecosystem/integrations/
