### ISSUE TITLE
MassTransit Messaging Library

### ISSUE THREAD

**Issue by KaydenMiller** [open-telemetry/opentelemetry.io#4560]
The MassTransit library supports a large portion of the Open Telemetry tooling in .NET https://masstransit.io/documentation/configuration/observability#open-telemetry

Noticed on the https://opentelemetry.io/docs/languages/net/libraries/ page that you were looking for libraries that support OTEL.

**Comment by svrnm** [comment]
Thanks @KaydenMiller. [This PR](https://github.com/open-telemetry/opentelemetry.io/pull/4337) by @mgurrie should have added it to the list but I think there is a minor change missing to make this happen, let me check
