### ISSUE TITLE
Flesh out the contributor's guide/get involved page.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#46]
The page on how to get involved is, quite sadly, bare! (https://opentelemetry.io/get-involved/) We need to add content here -
* Links to each SIG
* Links to the community repo
* Links to the website repo
* Code of conduct
* Links to public calendar (maybe even a widget?)
* Etc.

**Comment by michellejae** [comment]
Working on this now :)

**Comment by austinlparker** [comment]
Closed by #54, thanks!
