### ISSUE TITLE
Explain how to change the collector in documentation

### ISSUE THREAD

**Issue by RichardJECooke** [open-telemetry/opentelemetry.io#4611]
### Describe the bug

On this page, https://github.com/open-telemetry/opentelemetry-java-instrumentation?tab=readme-ov-file, you say "By default, the OpenTelemetry Java agent uses OTLP exporter configured to send data to OpenTelemetry collector at http://localhost:4317." and you link three times to the Java documentation at https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config. 

But nowhere on that page does it mention how to change the collector or port 4317. 

1) How do we change it?
2) Please add this to the readme file and the documentation.

**Comment by RichardJECooke** [comment]
Thanks.

1. This page is good! https://opentelemetry.io/docs/languages/java/configuration You need to link to that in the readme. The zero code link you have isn't helpful (and it's silly to link to it twice).
2. Search works today for 4317. Yesterday it was returning blank results on your site. Weird.
3. It would be great to mention on the configuration page that the "endpoint" value is an endpoint to a collector. "Collector" isn't mentioned once on that page, though it's a core concept in OpenTelemetry. I was wondering "endpoint to what? what i'm monitoring?"

**Comment by jaydeluca** [comment]
The documentation has now been updated and a link has been added to the instrumentation repo readme pointing at the configuration page
