### ISSUE TITLE
fix supported python version for Python SDK in main page

### ISSUE THREAD

**Issue by emdneto** [open-telemetry/opentelemetry.io#4644]
**What needs to be changed?** Describe the update that is required.
Update [here](https://opentelemetry.io/docs/languages/python/#version-support) to clarify python SDK support python3.8 and higher 

**What is the name + path of the page that needs changed?** The relative path
and page title where you found a problem.
https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/languages/python/_index.md

**Comment by emdneto** [comment]
Maybe it's better to just use the text from: https://github.com/open-telemetry/opentelemetry-python?tab=readme-ov-file#python-version-support and reference the link, something like that: For more details on python version support [see](https://github.com/open-telemetry/opentelemetry-python?tab=readme-ov-file#python-version-support)

**Comment by Ronald-TR** [comment]
Thanks for the report, I'ld like to update it.

**Comment by xrmx** [comment]
I would bump the version here to fix the issue and keep an explicit version. We may discuss any eventual followup inside the Python SIG.

**Comment by svrnm** [comment]
@emdneto @xrmx anyone of you open to create the PR for that?

**Comment by emdneto** [comment]
@svrnm Sure. I'll open a PR for this one
