### ISSUE TITLE
New Blog Post: Getting Started Survey

### ISSUE THREAD

**Issue by AnaMMedina21** [open-telemetry/opentelemetry.io#4662]
Blog post to summarize results of OTel ["getting started" survey](https://forms.gle/PWNxzHo2unPj77CP8) 
Related: https://github.com/open-telemetry/sig-end-user/issues/9 

Reviewers: @open-telemetry/sig-end-user-maintainers

**Comment by svrnm** [comment]
Thanks for raising this issue, happy to have this blog post

**Comment by AnaMMedina21** [comment]
Blog Post is out now https://opentelemetry.io/blog/2024/otel-get-started-survey/
