### ISSUE TITLE
Process for authoritative 'getting started' guides

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#472]
Per comments in maintainers meeting, SIG maintainers desire a more clear process for handling website 'getting started' docs updates. Suggested process is this -

- SIG maintainers create a new `website_docs` directory at the root of their repo.
- The structure of this directory should mirror the subdirectory structure appropriate to that language
  - For example, Java would maintain the contents of `./content/en/docs/java` in their `website_docs` directory, and so forth.
- Upon a release of the associated package, a member of that SIG should open a PR with the content of their `website_docs` directory applied to the appropriate location in the `opentelemetry.io` repository.
  - Alternately, they may open an issue for a comms SIG maintainer to perform this update.

cc @open-telemetry/docs-approvers @open-telemetry/docs-maintainers for discussion before 3/8 Maintainer's Meeting.

---

**Edits**(@chalin)  

Renamed `website-docs` to `website_docs` in the text above, since that is what seems to be used across the language repos.

Here is a list of the code repos with an indication of their status (as of 2021/09/25):

Repo* | Has `website_docs` folder | Has `docs-update` GH Action | Note
---|:---:|:---:|---
[opentelemetry-collector][] | ~☑️~ | ~☑️~ | **Docs are back** in this repo - [#4042]
[opentelemetry-cpp][] | ✖️ | ✖️ | Docs in this repo. Doc update via documented process.
[opentelemetry-dotnet][] | ✖️ | ✖️ | Docs in this repo. Doc update via documented process.
[opentelemetry-erlang][] | ✅ | ✅ | 
[opentelemetry-go][] | ✅ | ❌ | Setup as submodule in this repo by #690
[opentelemetry-java][] | ✅ | ✅ | Setup as submodule in this repo by #739
[opentelemetry-js][] | ~☑️~ | ~✖️~ | **Docs are back** in this repo - #722
[opentelemetry-php][] | ✅ | ✅ | 
[opentelemetry-python][] | ✅ | ✅ 
[opentelemetry-ruby][] | ✅ | ❌ | Setup as submodule in this repo by #765
[opentelemetry-rust][] | ✅ | ❌ |
[opentelemetry-swift][] | ✅ | ❌ |

*The repo link, is the link to the PR that created the `website_docs` folder.

[opentelemetry-collector]: https://github.com/open-telemetry/opentelemetry-collector/pull/2839
[opentelemetry-cpp]: https://github.com/open-telemetry/opentelemetry-cpp/pull/636
[opentelemetry-dotnet]: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1944
[opentelemetry-erlang]: https://github.com/open-telemetry/opentelemetry-erlang/pull/237
[opentelemetry-go]: https://github.com/open-telemetry/opentelemetry-go/pull/1747
[opentelemetry-java]: https://github.com/open-telemetry/opentelemetry-java/pull/3070
[opentelemetry-js]: https://github.com/open-telemetry/opentelemetry-js/pull/2051
[opentelemetry-php]: https://github.com/open-telemetry/opentelemetry-php/pull/291
[opentelemetry-python]: https://github.com/open-telemetry/opentelemetry-python/pull/1724
[opentelemetry-ruby]: https://github.com/open-telemetry/opentelemetry-ruby/pull/691
[opentelemetry-rust]: https://github.com/open-telemetry/opentelemetry-rust/pull/504
[opentelemetry-swift]: https://github.com/open-telemetry/opentelemetry-swift/pull/148
[#4042]: https://github.com/open-telemetry/opentelemetry-collector/pull/4042

**Comment by jkwatson** [comment]
What format would these docs be in?

**Comment by austinlparker** [comment]
Markdown. The only real requirement is that they have a block at the beginning like so, with appropriate frontmatter (see https://gohugo.io/content-management/front-matter/) -

```
---
title: "Automatic Instrumentation"
weight: 3
---
```

They can also use any other features available to the docs site, such as tabs by calling the appropriate blocks (as seen in the Erlang/Elixir docs) -

```
{{< tabs Erlang Elixir >}}

{{< tab >}}
$ rebar3 new release otel_getting_started
{{< /tab >}}

{{< tab >}}
$ mix new otel_getting_started
{{< /tab >}}

{{< /tabs >}}
```

**Comment by tedsuo** [comment]
How should links be handled?

**Comment by austinlparker** [comment]
Absolute links should be fine irregardless. Relative links should also be fine, as Hugo defaults to not canonifying relative links, and it tends to be kinda smart about it.. for example, in `/content/en/docs/java/getting_started.md` there's a link to `[/docs/java/#releases-1]`. Hugo will do the right thing for `[../#releases-1]` as well (the link it creates in both cases will be to `<protocol>://<host>:<port>/docs/java/#releases-1`)

The only thing I can see tripping people up is creating relative links to content outside of the `website_docs` directory.

**Comment by austinlparker** [comment]
I'm going through and making PR's mirroring the website docs to SIG repos today.

**Comment by chalin** [comment]
Superseded by #730, but I'll keep this open for now since I'm still updating the table with statuses.

**Comment by chalin** [comment]
Status table is complete. Closing in favor #730.
