### ISSUE TITLE
chinese character "軽装" should be "計装"

### ISSUE THREAD

**Issue by iwayu987** [open-telemetry/opentelemetry.io#4729]
(Hello. I'm not good at english and this is first time for me to create issue for public repository. Please forgive me if this issue is incomplete.)

In [what-is-opentelemetry page(lang:ja)](https://opentelemetry.io/ja/docs/what-is-opentelemetry/#%e3%82%aa%e3%83%96%e3%82%b6%e3%83%bc%e3%83%90%e3%83%93%e3%83%aa%e3%83%86%e3%82%a3%e3%81%a8%e3%81%af%e3%81%aa%e3%81%ab%e3%81%8b), chinese characters "_軽装_" should be "_計装_".
These two characters have same reading,  "_軽装_"  should be typo.

**Comment by svrnm** [comment]
thanks for raising this @iwayu987, you point to the Japanese documentation but say something about Chinese characters. I can unfortunately read neither, so I need @open-telemetry/docs-ja-approvers @open-telemetry/docs-zh-approvers to take a look.

**Comment by ymotongpoo** [comment]
@iwayu987 thank you for catching this. this is totally just a typo.

@svrnm this is a Japanese language issue, and @open-telemetry/docs-ja-approvers is enough for review.
