### ISSUE TITLE
[ja] CNCF localization guidelines - feedback requested

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4746]
@open-telemetry/docs-ja-approvers - feedback from you, or anyone else from the Japanese community, on the following broad CNCF localization guidelines would be appreciated:

- https://github.com/cncf/techdocs/pull/259

Opening this issue here for visibility to @open-telemetry/docs-approvers (FYI).

**Comment by ymotongpoo** [comment]
Thank you for nudging. @katzchang and I both are in the discussion happening at CNCF slack #glossary-localization-japanese channel and we both reviewed the draft of PR.

**Comment by katzchang** [comment]
I commented that the guidelines look good.

**Comment by ymotongpoo** [comment]
I also explicitly gave LGTM there. Closing the issue.

**Comment by chalin** [comment]
Wonderful, thank you both 👍🏻
