### ISSUE TITLE
New Blog Post: Hardening the Collector #1 - A new default bind address

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry.io#4760]
**Blog post category**: This would fall into the "OpenTelemetry projects updates" or "Updates from Special Interest Groups" categories.

**Short description and outline of your blog post:** The Collector SIG has been working on hardening the Collector default configuration and the Collector builds. Some of these are breaking changes. We want to write a series of blog posts to share this with the community and help users address the breaking change. This would be the first one, focusing on the `component.UseLocalHostAsDefaultHost` feature gate. See #4759 for a draft version.

**Technologies used in your blog post**:  OpenTelemetry Collector

**Name of a SIG, which is related to this blog post**: Collector SIG

**Name of a sponsor (maintainer or approver) from this SIG, who will help to review that PR. That sponsor should ideally be from a different company.** @jpkrohling and @TylerHelmuth will help review :)

**Comment by mx-psi** [comment]
We should have already addressed everything as part of #3839, but if there is anything missing we should do it now as well

**Comment by jpkrohling** [comment]
I'll review it.

**Comment by tiffany76** [comment]
Closing as completed by #4759.
