### ISSUE TITLE
[infra] Add page feedback form

### ISSUE THREAD

**Issue by theletterf** [open-telemetry/opentelemetry.io#4769]
**Desired feature or idea**: What would you like to see happen?

As discussed in the last SIG meeting, we'd like to add Docsy's feedback widget and repo link (create issue) to our site: 

- [x] https://www.docsy.dev/docs/adding-content/feedback/#user-feedback - 
  #4772
- [ ] https://www.docsy.dev/docs/adding-content/repository-links/

**Comment by chalin** [comment]
Thanks @theletterf for creating the issue. I suggest tackling the subtasks separately.

**Comment by theletterf** [comment]
@chalin Seems like repo links appeared automagically after #4772 got merged!

**Comment by svrnm** [comment]
I wonder if we could combine that feedback form with a [github issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). I played with them for the community repo a while back and they allow you to provide a more structured issue creation, i.e. you can make things mandatory or provide input fields, etc. WDYT?

**Comment by chalin** [comment]
Hmm, I like that idea!

**Comment by chalin** [comment]
Cross-referencing a relevant Docsy issue:

- https://github.com/google/docsy/issues/2054

**Comment by chalin** [comment]
Given the discussion in https://cloud-native.slack.com/archives/C06EDFPQ5EH/p1724142213551189, I've created the following issue and reexplained why this hasn't been implemented yet:

- #5091

Closing this issue now since the website has page-feedback forms enabled. Adjusting the issue title, etc., is in scope of #5091.
