### ISSUE TITLE
Clarification on docs for adding attributes via decorators

### ISSUE THREAD

**Issue by sushaanttb** [open-telemetry/opentelemetry.io#4770]
In the documentation at following link:
https://opentelemetry.io/docs/languages/python/instrumentation/#creating-spans-with-decorators 

It's mentioned that _If you need to add [attributes](https://opentelemetry.io/docs/languages/python/instrumentation/#add-attributes-to-a-span), [events](https://opentelemetry.io/docs/languages/python/instrumentation/#adding-events), or [links](https://opentelemetry.io/docs/languages/python/instrumentation/#adding-links) then it’s less convenient to use a decorator_.

<img width="883" alt="image" src="https://github.com/open-telemetry/opentelemetry-python/assets/12629751/6e5dd73f-362b-4b6c-b57a-e0183937c464">

IMO, this sounds a bit misleading statement especially in case of **attributes and links**, as the user would interpret accordingly and ignore the possibility of configuring the same via decorator. 

For ref., PFB Screenshot for adding attributes and this is certainly not inconvenient.

<img width="785" alt="image" src="https://github.com/open-telemetry/opentelemetry-python/assets/12629751/777468b6-0b15-4096-8094-ae9eae1f0a1a">

This is because both **attributes and links** are arguments of  _start_as_current_span_ method.
<img width="595" alt="image" src="https://github.com/open-telemetry/opentelemetry-python/assets/12629751/578c6326-ea29-4067-9a6e-6907c9ee50aa">

Hence, it would be helpful to know on the definition of "less convenient" here, or else we can update the documentation accordingly :)

**Comment by ocelotl** [comment]
> Inconvenience is in eye of the beholder :) As a non-native english speaker I understand as if you have many attributes the decorator would not have that much advantage over adding the span attributes manually.

You understand that but other readers may understand something else.

Being objective, the statement being discussed says that using a decorator is less convenient for a particular purpose. That statement is subjective, I think we should remove it.

**Comment by cartermp** [comment]
FWIW, as the original author of that section, what I was referring to is that if you need to add these things (especially after span creation) then you need to also make a call to get the current span, since there's no implicit span variable available. That makes it _more_ code than if you create the span yourself.

However, after re-reading this about two years later, I think it's fine to drop it.

**Comment by heyitsaamir** [comment]
I actually disagree with this issue. I think if this was in the documentation it would have saved me some time today as a new user if the library
