### ISSUE TITLE
[i18n] localization of snippets inside shortcodes

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry.io#4783]
**What needs to be changed?**

Currently, `ja` and `zh` localizations are happening. The localization is usually done in the following steps:

1. copy the original content under `content/en` and move them to the corresponding directory of each language. (eg. `content/ja`)
2. translate the content

However, some of the documents are embedded in Hugo short codes, which are out of `content` directory.

For example, This is the screenshot of the Japanese translation of [concepts > resources](https://opentelemetry.io/docs/concepts/resources/) page:

![image](https://github.com/open-telemetry/opentelemetry.io/assets/145104/9e6e4750-5653-4952-9505-59163e4cf5b1)

As you see, the first two paragraphs are not translated yet. The corresponding markdown of this page is:

```md
## はじめに

{{% docs/languages/resources-intro %}}

オブザーバビリティバックエンドに[Jaeger](https://www.jaegertracing.io/)を使用している場合、リソース属性は**Process**タブの下にグループ化されます。
```

This short code is located at `layouts/shortcodes/docs/languages/resources-intro.md`. How can we localize these short codes?

**What is the name + path of the page that needs changed?** 

`layouts/shortcodes/docs/languages`

**Additional context**:

- relevant discussion: https://github.com/open-telemetry/opentelemetry.io/discussions/4302

**Comment by svrnm** [comment]
@chalin any ideas how to address this? Should we have "localized" shortcodes or should we use translated strings and put that text into some TOML files?

**Comment by chalin** [comment]
Both approaches could be useful (or even a combination of both), but my feeling is that the complexity of a shortcode warrants it being localized, something like this, PTAL:

- #4787
