### ISSUE TITLE
[Meta] Add missing "propagation" pages

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#4798]
As a follow up to https://github.com/open-telemetry/opentelemetry.io/pull/4722 we can replicate this content across all other languages as well.

The following languages are still missing:

- [ ] C++
- [ ] .NET
- [x] Erlang/Elixir
- [ ] Go
- [ ] Java
- [x] JavaScript (#4722)
- [x] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Swift

If you want to help with this effort please do the following:
* Pages on propagation exists already for some languages, so it might be necessary to review existing content and to decide if some of that is valuable to be copied in the standardized page or if it can be replaced.
* Copy the JS page on "propagation" to the language you want to update and change the examples to the language and change content where necessary.

**Comment by theletterf** [comment]
Taking some of these.
