### ISSUE TITLE
[i18n] Better address the auto-update of versions across localizations

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4825]
- One of the main files used to update versions is:

  - https://github.com/open-telemetry/opentelemetry.io/blob/main/scripts/auto-update/all-versions.sh

  I'm thinking of generalizing the file path spec to include a glob (in place of specific language codes).

- More context: https://github.com/open-telemetry/opentelemetry.io/pull/4817#issuecomment-2221721838

**Comment by svrnm** [comment]
Hm, what if we move the versions into `data/` and source them from there, would that work?

**Comment by chalin** [comment]
@svrnm @open-telemetry/docs-ja-approvers - I just realized that we do _not_ want to update versions in pages other than `en` pages, since those are canonical. The localization pages, like `ja` need to be updated manually as they would for any other change to the corresponding `en` page (be in a page content change or a front-matter field change).

I'm considering closing this issue, and leaving the situation as is. I'll leave it open until my return towards the end of the month.

**Comment by svrnm** [comment]
Yes, that's a good point, version changes may have other implicatons as well, so by simply pumping them we might run into trouble. Let's leave it open for now and review it when you are back
