### ISSUE TITLE
[Registry] Add Log Bridge as a Component type

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry.io#4846]
I propose to add "Log Bridge" as a new type of components in the OTel Registry.

Related:
- https://github.com/open-telemetry/opentelemetry.io/pull/4845

**Comment by svrnm** [comment]
Let's change that.

**Comment by svrnm** [comment]
@pellared you should be able to add them with `registryType: log-bridge`

**Comment by pellared** [comment]
I will try it and close the issue if it works.

**Comment by pellared** [comment]
It will work

![image](https://github.com/user-attachments/assets/3fb0cc6c-a571-4ee6-90d3-df26831808f9)
