### ISSUE TITLE
Documentation: Context propagation

### ISSUE THREAD

**Issue by hyang023** [open-telemetry/opentelemetry.io#4851]
In the Propagation section of the Context propagation page https://opentelemetry.io/docs/concepts/context-propagation/#propagation, there is a reference to `Propagation APIs`:

> Propagation is usually handled by instrumentation libraries and is transparent to the user. In the event that you need to manually propagate context, you can use Propagation APIs.

Is this the same as or different from `Propagators API` (https://opentelemetry.io/docs/specs/otel/context/api-propagators/)?
Either way, it could be helpful to have some clear next step (resources or links) to learn more about Propagation APIs

**Comment by svrnm** [comment]
yes, those are the same. As a quick starting point a link from the concept page to the spec would be helpful. Would you be interested too raise a PR for that?

**Comment by tiffany76** [comment]
Closing as completed by #4878
