### ISSUE TITLE
Allow to run the website using a container locally

### ISSUE THREAD

**Issue by EzzioMoreira** [open-telemetry/opentelemetry.io#4871]
I want to run the website locally, I'd like to run the `make container-run` command and see this change on the website while writing the change to it.
I think this will make sure that people who help with the project know and see that the proposed changes won't break the website.

- Command to run the website locally.
- Commando to build container image. 

We don't need to recreate anything, we can copy examples of the Kubernetes project. 
https://github.com/kubernetes/website/blob/7093f2c54d6954762d1df83e40859f40bf1f2c64/Makefile#L103

>I'm not sure if it's necessary to run the website locally with binary hugo right now, because most people use container/docker. 

cc: @edsoncelio @svrnm @jpkrohling 👀

**Comment by svrnm** [comment]
hey @EzzioMoreira,

we have an ongoing discussion for this request here: https://github.com/open-telemetry/opentelemetry.io/discussions/3810

**Comment by EzzioMoreira** [comment]
Excellent 🤘, then I'll close this issue. ok?
