### ISSUE TITLE
[CI/Infra] Enable merge queues

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#4874]
Based on [this slack thread](https://cloud-native.slack.com/archives/C02KF2PPUV9/p1716465921426829) merge queues are now working with the EasyCLA bot and this was the last blocker for them not being available to us. If I understand it correctly this would allow us to get away from the "rebase/update branch" -> wait for CI to finish -> manually merge workflow to a more automatic thing. Therefore I would like to roll this out.

@open-telemetry/javascript-maintainers would you be able to share us some insights how well it works with the merge queues and especially would it be possible to get a screenshot of the repository settings such that we can apply them same to this repo? Thanks!

**Comment by trentm** [comment]
> Based on [this slack thread](https://cloud-native.slack.com/archives/C02KF2PPUV9/p1716465921426829)

Your link doesn't work for me. I'm guessing you mean this one:
https://cloud-native.slack.com/archives/C01NJ7V1KRC/p1722267609336729
that starts with "Hey maintainers, I saw that some of you are using merge queues already? ..."

> If I understand it correctly this would allow us to get away from the "rebase/update branch" -> wait for CI to finish -> manually merge workflow to a more automatic thing.

FWIW, my experience here had been that if I:
(a) **first** click the "Enable auto-merge" button (i.e. what would be the merge button if the PR branch wasn't out of date), and
(b) **then** click "Update branch"
... then the PR would get merged without having to re-run CI.

I am the "One of our maintainers [that was editing the commit messages before merging]" that Dan politely anonymized. ;)

Anyway, Dan's argument that is helps with PRs from "organizational forks where the maintainers can't merge main into the branch" is a stronger argument for merge queues, I think, that my penchant for fine tuned commit messages.

**Comment by trentm** [comment]
I didn't set it up on https://github.com/open-telemetry/opentelemetry-js but I believe it is a checkbox on a branch protection for the "main" repo:

![Screenshot 2024-07-30 at 6 20 56 PM](https://github.com/user-attachments/assets/15be4519-4181-46e1-96e4-bfedfee1ca80)

- click repo "Settings"
- click "Branches"

More details at https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#creating-a-branch-protection-rule

**Comment by svrnm** [comment]
thanks @trentm !
