### ISSUE TITLE
Java Agent docs refactor

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry.io#4881]
https://docs.google.com/document/d/1f761dYCNFTPJpAbLJAdmMFhwr9uy1j9gSrEmPdqnmHw/edit

**Comment by svrnm** [comment]
We try to keep issues for things that can be worked on and the issue can be closed eventually, we have a discussion for that already, let's figure out the next steps there and create issues afterwards: 

https://github.com/open-telemetry/opentelemetry.io/discussions/4853
