### ISSUE TITLE
[i18n] Ensure that fall-back redirect pages like API and Examples under Language work for non-en localizations

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4898]
This is issue (1) from:

- #4893

**Comment by zhihali** [comment]
Hey, I'd love to give this a shot. I'm keen to get more familiar with the docs setup, so fixing these links would be a great way to dive in. Happy to take a crack at it if you're cool with that! 

understand this should be implement after #4895, as you said.

**Comment by chalin** [comment]
Thanks for the offer, but I'd rather work on this given that I'm still designing the i18n support for OTel. Unless you are _very_, _very_ familiar with Hugo and the design of this site, I'd suggest you work on addressing #4893.

**Comment by chalin** [comment]
@zhihali - To give you an idea, here's an example of the kind of refactoring I wanted & needed to do before fixing this issue:

- #4900

**Comment by zhihali** [comment]
no problem, @chalin, will leave this to you! Will keep an eye on your PR and learn from it🙂

> Thanks for the offer, but I'd rather work on this given that I'm still designing the i18n support for OTel. Unless you are _very_, _very_ familiar with Hugo and the design of this site, I'd suggest you work on addressing #4893.
