### ISSUE TITLE
Add banner + form for i18n support

### ISSUE THREAD

**Issue by mangotron** [open-telemetry/opentelemetry.io#490]
(Per discussion in recent comms SIG)

Add a banner announcement to the site with a link to a short form (Google form or similar maybe) to capture details from people interested in helping to translate OTel docs. The form should include fields for: 

- Name and email address (or other contact info if preferred)
- Language(s) the person wants to help with (e.g. English > French) as a short text entry field
- Checkbox for the person to confirm that it's ok for someone from the Comms SIG to reach out with more information when available

This will allow us to contact folks when we're ready to begin i18n work on the docs, and allow us to reach back out to people who have volunteered to help.

**Comment by svrnm** [comment]
See https://github.com/open-telemetry/opentelemetry.io/discussions/4302 for future discussions on this matter.
