### ISSUE TITLE
Page feedback for zero-code PHP docs

### ISSUE THREAD

**Issue by nosilver4u** [open-telemetry/opentelemetry.io#4926]
Suggested improvements for page: https://opentelemetry.io/docs/zero-code/php/

What is the example at the top of the page? It sure doesn't look "zero code" to me, perhaps that is misplaced?
The build requirements for APT aren't accurate, as I had to install php-dev and php-pear.
Lastly, it would be helpful to see the corresponding php.ini settings, so we don't have to reverse-engineer those from the environment variables. Are they the same, are they prefixed with opentelemetry, like opentelemetry.service_name?

Thanks!

**Comment by cartermp** [comment]
Thanks for the feedback @nosilver4u.

The general idea is that each example has a copy-pastable code sample you can reproduce on your own. That said, if you just want to use the agent to instrument things, you can skip it and follow the instructions that come later.

Would it make more sense to clarify this in the text, and maybe explicitly state that you can skip on to the configuration section if you have your own app to instrument?

Also cc @open-telemetry/php-approvers for the other concerns.

**Comment by nosilver4u** [comment]
I think it could certainly use some clarification. For instance, the paragraph above that indicates one must install the PHP SDK for traces. But then, can it do traces automatically without any additional code? That is, if one just installs the PHP SDK via composer and provides the appropriate configuration via PHP, is that enough to generate traces with no additional code?

And what if we have code that doesn't use composer, are we out of luck for getting error traces? Seems strange to me, when other solutions can generate traces for errors without modifying our codebase.

**Comment by ChrisLightfootWild** [comment]
> I think it could certainly use some clarification. For instance, the paragraph above that indicates one must install the PHP SDK for traces. But then, can it do traces automatically without any additional code? That is, if one just installs the PHP SDK via composer and provides the appropriate configuration via PHP, is that enough to generate traces with no additional code?

It does indicate that at least one instrumentation library must be used in addition to the SDK under the `Important` banner. With only the SDK, you won't get any traces because the SDK doesn't hook anything on its own.

Do you have some suggested wording which might help improve this?

> And what if we have code that doesn't use composer, are we out of luck for getting error traces? Seems strange to me, when other solutions can generate traces for errors without modifying our codebase.

In short, yes. Composer autoloading is the supported route for zero-code instrumentation.

**Comment by brettmc** [comment]
> It does indicate that at least one instrumentation library must be used in addition to the SDK under the Important banner. With only the SDK, you won't get any traces because the SDK doesn't hook anything on its own.

Perhaps the confusion could be reduced by moving that code block further down the page? It's more of a low-level "this is how it works under the hood", whereas the casual user probably just needs "install these things and set these env vars"

> Lastly, it would be helpful to see the corresponding php.ini settings, so we don't have to reverse-engineer those from the environment variables. Are they the same, are they prefixed with opentelemetry, like opentelemetry.service_name?

That's a good point. It's not a widely used feature (I don't recall any reports of anybody using it at all before now), but the short version is that you don't need any reverse-engineering, just drop the environment variable name and a value into a .ini file that PHP can find, and it should work exactly the same as an env var would. I will create a PR to add an example for this.

**Comment by cartermp** [comment]
@nosilver4u Thanks to @brettmc, the page is updated quite a bit. Mind taking a look and seeing if there's anything else that could be improved?

**Comment by nosilver4u** [comment]
That certainly helps, and I think clears up my last question. Which is: If our code is a bit less "sophisticated" and doesn't use frameworks, and is a mix of procedural and OOP code, we would need to do our own instrumentation, right?

**Comment by brettmc** [comment]
> That certainly helps, and I think clears up my last question. Which is: If our code is a bit less "sophisticated" and doesn't use frameworks, and is a mix of procedural and OOP code, we would need to do our own instrumentation, right?

Yeah that's right. Your options there are manual instrumentation, or roll your own auto-instrumentation. Which you choose might come down to personal preference - auto-instrumentation has the advantage of keeping instrumentation code separate from your application code.

**Comment by nosilver4u** [comment]
@brettmc Thanks for the clarification, that helps--though I was hoping for something truly zero-code, so we'll have to stick with our current APM solution.

**Comment by cartermp** [comment]
Thanks for all the follow-ups here. I'll consider this issue closed for now, since the scope of what OTel and PHP can do is captured in the docs.

**Comment by brettmc** [comment]
Thanks for the feedback, @nosilver4u 
You might be interested in following [this issue](https://github.com/open-telemetry/opentelemetry-php/issues/1355) and the linked development - it's not zero code, but it's close and should work well with less sophisticated code :)
