### ISSUE TITLE
Remove duplicate sig:js / sig:javascript label

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#4931]
We have two labels for the SIG JavaScript, one is sig:js the other one is sig:javascript, only one should exist

via https://github.com/open-telemetry/opentelemetry.io/pull/4927#issuecomment-2261509883

Let's remove `sig:js` and replace it with `sig:javascript`. We need an issue because the auto labelling needs to be reviewed for that

**Comment by svrnm** [comment]
cc @trentm

**Comment by trentm** [comment]
@svrnm Sounds good to me. I don't have any preference for one or the other label. I opened #5003 to change the one file that is referring to `sig:js` for automation.  After that is merged, we should be able to migrate issues using `sig:js` (https://github.com/open-telemetry/opentelemetry.io/issues?q=label%253Asig%253Ajs) and remove the label.

**Comment by svrnm** [comment]
thanks @trentm, I merged your PR and updated the labels
