### ISSUE TITLE
Clarify Collector internal metric names by version

### ISSUE THREAD

**Issue by tiffany76** [open-telemetry/opentelemetry.io#4933]
**What needs to be changed?** With release v0.106.1, the names of Collector internal metrics are handled differently, depending on whether they are generated from Collector components (prefixed with `otelcol_`) or instrumentation libraries (not prefixed with `otelcol_`). 

The [list of metrics](https://opentelemetry.io/docs/collector/internal-telemetry/#lists-of-internal-metrics) is correct as-is, but we should add a note that clarifies that versions of the Collector prior to v0.106.1 append the `otelcol_` prefix to all internal metrics, both instrumentation library-generated as well as component-generated.

**What is the name + path of the page that needs changed?** https://opentelemetry.io/docs/collector/internal-telemetry/#lists-of-internal-metrics

**Additional context**: See [comment](https://github.com/open-telemetry/opentelemetry.io/pull/4867#discussion_r1700626960).

**Comment by Tharanishwaran** [comment]
Hi, I’d like to work on this issue if it’s still available.can i work on this issue ?

**Comment by tiffany76** [comment]
Hi @Tharanishwaran! Thanks for volunteering! This issue is all yours. Please go ahead and put up a PR for review.

Let us know if you have any questions. And thanks again!

**Comment by Tharanishwaran** [comment]
Hi @tiffany76 ,Thanks for assigning this to me! I'll get started and will put up a PR soon. If I have any questions along the way, I'll be sure to reach out.

Thanks again!

**Comment by tiffany76** [comment]
Hi @Tharanishwaran - have you had a chance to work on this issue? If so, please put up a draft PR so we can give you feedback. Thanks!

**Comment by Tharanishwaran** [comment]
Hi @tiffany76 ,
I’ve been dealing with some health issues, which have delayed my work on this issue. I’m currently working on it and will update you soon.
Thanks for your understanding!

**Comment by Tharanishwaran** [comment]
Hi @tiffany76 I see this pull request #5178  is not yet merged. Should there be anything to do more, or some issues still need to be fixed? I will be glad to fix those issues
