### ISSUE TITLE
[CI] spell-check failures

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4956]
When running checks locally, I get spell-check failures (over 7f31e8ee [origin/main] Restructure the logs page (#4949)):

```console
$ npm run check:spelling
> npx cspell --no-progress -c .cspell.yml content/en data 'layouts/**/*.md'

content/en/docs/concepts/signals/logs.md:17:1 - Unknown word (autoinstrumentation)
content/en/docs/concepts/signals/logs.md:31:7 - Unknown word (filelogreceiver)
content/en/docs/concepts/signals/logs.md:33:23 - Unknown word (transformprocessor)
content/en/docs/concepts/signals/logs.md:43:45 - Unknown word (autoinstrumentation)
content/en/docs/concepts/signals/logs.md:56:34 - Unknown word (semistructured)
content/en/docs/concepts/signals/logs.md:63:31 - Unknown word (semistructured)
content/en/docs/concepts/signals/logs.md:124:2 - Unknown word (filelogreceiver)
content/en/docs/concepts/signals/logs.md:152:60 - Unknown word (consitently)
content/en/docs/concepts/signals/logs.md:159:5 - Unknown word (Semistructured)
content/en/docs/concepts/signals/logs.md:161:3 - Unknown word (semistructured)
content/en/docs/concepts/signals/logs.md:165:14 - Unknown word (semistructured)
content/en/docs/concepts/signals/logs.md:171:28 - Unknown word (semistructured)
```

**Comment by cartermp** [comment]
I wonder why CI didn't pick this up?

**Comment by chalin** [comment]
@cartermp - good question. It seems that the GH action didn't find any files to check against (which is clearly a bug), https://github.com/open-telemetry/opentelemetry.io/actions/runs/10251105861/job/28358372032:

<pre>
Run streetsidesoftware/cspell-action@v6
  with:
    files: content/en/*.md
  layouts/**/*.md
  data/**/*
  
    config: .cspell.yml
    incremental_files_only: true
    inline: warning
    treat_flagged_words_as_errors: false
    strict: true
    suggestions: false
    verbose: false
    check_dot_files: explicit
    use_cspell_files: false
cspell-action
Pull Request
<b>Files checked: 0, Issues found: 0 in 0 files.</b>
</pre

**Comment by cartermp** [comment]
oof! yeah, that's a problem.

**Comment by chalin** [comment]
Reopening, since it has happened again, this time for:

- #4948
- Spell-check log, that reports no errors 🤷🏼‍♂️, https://github.com/open-telemetry/opentelemetry.io/actions/runs/10258002805/job/28380099640:
  ```
  Run streetsidesoftware/cspell-action@v6
  cspell-action
  Pull Request
  Files checked: 820, Issues found: 0 in 0 files.
  Done.
  ```

**Comment by chalin** [comment]
Maybe it's time to ditch the GH action and run our own script?
