### ISSUE TITLE
Semantic convention on enduser is deprecated and should use user

### ISSUE THREAD

**Issue by evan361425** [open-telemetry/opentelemetry.io#4967]
**What needs to be changed?** Describe the update that is required.

In the _register_ of _semantic conventions_, sidebar should place [_user_](https://opentelemetry.io/docs/specs/semconv/attributes-registry/user/) not [_enduser_](https://opentelemetry.io/docs/specs/semconv/attributes-registry/enduser/) which is already deprecated

**What is the name + path of the page that needs changed?** The relative path and page title where you found a problem.

Sidebar should place _user_ not _enduser_ and [_general attributes_](https://opentelemetry.io/docs/specs/semconv/general/attributes/#general-identity-attributes) (`/specs/semconv/general/attributes/#general-identity-attributes`) should also use _user_ attributes instead.

---

### Tasks

- [x] Temporary fix: #4994
- [ ] Upgrade Docsy once the following lands: https://github.com/google/docsy/pull/2069

**Comment by svrnm** [comment]
@chalin can you take a look here, both should be in the sidebar (since we do not remove deprecated entitites), but only `enduser` shows up. I assume something needs to be fixed in a script building the semantic conventions?

**Comment by chalin** [comment]
We surfaced a bug in Hugo the last time. I _suspect_ that might be the case again here. I'll keep you posted on the progress of my investigation.

**Comment by chalin** [comment]
Nope, it was simply due to the sidebar section-entry limit, which many of us trip on over and over again. Docsy will soon issue a warning about this, see https://github.com/google/docsy/pull/2069.

**Comment by chalin** [comment]
Oops, reopening to track removal of the workaround.

**Comment by evan361425** [comment]
Thanks for your quick response🤘
