### ISSUE TITLE
Glossary links to 'Concepts Overview' are dead

### ISSUE THREAD

**Issue by pbh101** [open-telemetry/opentelemetry.io#497]
From the Glossary, clicking on 'Baggage' https://opentelemetry.io/docs/concepts/overview/#baggage returned my a 404. Upon inspection, it appears many links in the Glossary are pointing to https://opentelemetry.io/docs/concepts/overview/ and 404'ing.

**Comment by harshita19244** [comment]
Could you assign me this issue? I want to work on it

**Comment by harshita19244** [comment]
@austinlparker this issue can be closed. The linked PR resolves it
