### ISSUE TITLE
[Demo] Page feedback - which SDK commands are used to build the demo?

### ISSUE THREAD

**Issue by nelsonestevaomartins** [open-telemetry/opentelemetry.io#4988]
Suggested improvements for page: https://opentelemetry.io/docs/demo/feature-flags/

I was expecting an explanation of which SDK commands were used in the source code to build the demo in: https://opentelemetry.io/docs/demo/docker-deployment/.

**Comment by theletterf** [comment]
@open-telemetry/demo-maintainers Thoughts on this?

**Comment by julianocosta89** [comment]
Hello @nelsonestevaomartins could you elaborate a bit?
I'm not sure I understood what you are missing.

**Comment by julianocosta89** [comment]
Revisiting this issue, I believe what @nelsonestevaomartins is actually looking for is already there, but in a different page.
@nelsonestevaomartins, you can check how each service is configured in here: https://opentelemetry.io/docs/demo/services/
