### ISSUE TITLE
Rename repository to opentelemetry-website

### ISSUE THREAD

**Issue by vitaliis** [open-telemetry/opentelemetry.io#5]
Currently the link on the [organization page (for all projects)](https://github.com/open-telemetry) doesn't work. It points to probably old location http://opentelemetry.dev .
The new fixed one is https://opentelemetry.netlify.com/ I assume.

In addition this project could be renamed. Maybe some domain neutral name would be good, such as `opentelemetry-website`.

**Comment by lucperkins** [comment]
@vitaliis What's the rationale behind using a repo name like `*-website`?

**Comment by vitaliis** [comment]
To keep it domain-independent (read abstract enough).

And by the way it is fixed by now... (both the repo name and the link on the org page)
At least for now. My intention was to keep it abstract enough so that new domain name doesn't break this repo name and therefore all the links pointing here.
