### ISSUE TITLE
Wrong language for Accounting Service in architecture.md

### ISSUE THREAD

**Issue by t03apt** [open-telemetry/opentelemetry.io#5001]
Issue: According the documentation Accounting Service is implemented in `.NET`, but it is implemented in `go`.
Path: /content/en/docs/demo/architecture.md

**Comment by svrnm** [comment]
Thanks for raising this issue, @t03apt, as per this comment https://github.com/open-telemetry/opentelemetry.io/pull/5002#pullrequestreview-2229388174 the Accounting Service is implemented in .NET now.
