### ISSUE TITLE
OpenTelemetry Tracing Shim

### ISSUE THREAD

**Issue by iamalexcater** [open-telemetry/opentelemetry.io#5006]
The documentation for the OpenTelemetry Tracing Shim contains examples that pass a description argument to the TelemetrySpan.SetStatus method. This method signature does not exist. (unless I am missing something)

`span.SetStatus(Status.Error, "Something bad happened!");`

**Comment by svrnm** [comment]
@iamalexcater thanks for reporting, I assume this is for .NET? 

https://opentelemetry.io/docs/languages/net/shim/#set-span-status

@open-telemetry/dotnet-approvers PTAL

**Comment by iamalexcater** [comment]
Correct. Thanks.

**Comment by cartermp** [comment]
Should be done in https://github.com/open-telemetry/opentelemetry.io/pull/5050
