### ISSUE TITLE
Wrong `PrometheusHttpServer` link in js exporters documentation

### ISSUE THREAD

**Issue by chenlujjj** [open-telemetry/opentelemetry.io#5018]
In the doc, https://opentelemetry.io/docs/languages/js/exporters/#prometheus, the `PrometheusHttpServer` points to a javadoc web page. I think it's a mistake.

![image](https://github.com/user-attachments/assets/51b449de-e61b-4ac7-aa51-6d0e2fa0d9fb)

**Comment by theletterf** [comment]
Thanks @chenlujjj. That seems to be a mistake, yes. Do you happen to know what the right page should be? @open-telemetry/javascript-approvers ?

**Comment by chenlujjj** [comment]
@theletterf I think it should be https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-exporter-prometheus

**Comment by svrnm** [comment]
To stay consistent with other languages and pages, I recommend linking to the JS API/SDK docs @ https://open-telemetry.github.io/opentelemetry-js/classes/_opentelemetry_exporter_prometheus.PrometheusExporter.html
