### ISSUE TITLE
Building a custom collector

### ISSUE THREAD

**Issue by fredyfredburger** [open-telemetry/opentelemetry.io#5031]
The link for the ocb has moved.  It's now under opentelemetry-collector-releases, but this shows it under opentelemetry-collector/releases.

**Comment by theletterf** [comment]
+CC @open-telemetry/collector-approvers

**Comment by mx-psi** [comment]
This is valid issue, the builder files are now here https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/cmd%2Fbuilder%2Fv0.107.0 

after we merged open-telemetry/opentelemetry-collector-releases/pull/608 and open-telemetry/opentelemetry-collector/pull/10710

**Comment by songy23** [comment]
cc @jackgopack4
