### ISSUE TITLE
Blog post: Behind the scenes of the OpenTelemetry Governance Committee

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry.io#5033]
I'd like to propose the following blog post: Behind the scenes of the OpenTelemetry Governance Committee

https://docs.google.com/document/d/1Vnu96LKcI30LOXsNqiN9gv4mYmge1lQrMXBqVVo8V7E/edit

We are scheduling this to go live by the end of the week as part of the Grafana Labs publication, and we are happy to have it published as part of the OTel publication as well, removing of course Grafana-specific parts (like the "we are hiring" part). 

Would it be acceptable to OTel's publication?

**Comment by svrnm** [comment]
I read the draft already and liked it:-)

@open-telemetry/docs-approvers please take a look as well

**Comment by theletterf** [comment]
Super interesting! Left some comments.

**Comment by theletterf** [comment]
Converting to Markdown for publication today.
