### ISSUE TITLE
[ja] need to update the link for OpenTelemetry Contributor Guide in content/ja/docs/contributing/_index.md

### ISSUE THREAD

**Issue by kmuto** [open-telemetry/opentelemetry.io#5068]
**What needs to be changed?** Describe the update that is required.

OpenTelemetry Contributor Guide URL is https://github.com/open-telemetry/community/blob/main/
README.md, not https://github.com/open-telemetry/community/blob/main/
CONTRIBUTING.md.
content/en/docs/contributing/_index.md is already modified by #4978.

**What is the name + path of the page that needs changed?** The relative path
and page title where you found a problem.

content/ja/docs/contributing/_index.md
title: コントリビューション

**Comment by tiffany76** [comment]
@open-telemetry/docs-ja-approvers, PTAL.

For reference, the complete, correct URL for the OTEL contributing guide is https://github.com/open-telemetry/community/blob/main/guides/contributor/README.md.

**Comment by ymotongpoo** [comment]
@kmuto @tiffany76 thank you for raising this. I updated the link in #5076.
