### ISSUE TITLE
OTEL_EXPORTER_JAEGER_SERVICE_NAME no longer exists

### ISSUE THREAD

**Issue by BitProcessor** [open-telemetry/opentelemetry.io#507]
On https://opentelemetry.io/docs/java/automatic_instrumentation/ there is a mention of `OTEL_EXPORTER_JAEGER_SERVICE_NAME` which is no longer a valid ENV variable.

See https://github.com/open-telemetry/opentelemetry-java/issues/3056 for more info.

(the same might be true for `OTEL_EXPORTER_ZIPKIN_SERVICE_NAME` - unverified)

**Comment by cartermp** [comment]
This is now resolved with the article being rewritten and pointing to the up to date environment variables: https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/
