### ISSUE TITLE
[ja] OTel L10N announcement blog post doesn't show up

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry.io#5075]
**What needs to be changed?**

#5044 added the Japanese translation of the announcement of [OTel docs multilingalization](https://opentelemetry.io/blog/2024/docs-localized/), but it doesn't show up on the website.

https://opentelemetry.io/ja/blog/2024/

**What is the name + path of the page that needs changed?** 

`ja/blog/2024/docs-localized/`

**Additional context**:

#5035 has the same directory structure to add, so it may cause the same issue.

**Comment by theletterf** [comment]
I seem to see it now, @ymotongpoo . Could you confirm?

https://opentelemetry.io/ja/blog/2024/docs-localized/

**Comment by ymotongpoo** [comment]
Oh, it came out now! There should be some lag t

**Comment by ymotongpoo** [comment]
Oh, it came out now! There should be some lag t

**Comment by theletterf** [comment]
Nice! Thanks for checking!
