### ISSUE TITLE
Final release versions for OpenTelemetry.Instrumentation.AspNet and OpenTelemetry.Extensions.AWS 

### ISSUE THREAD

**Issue by PampapathiS** [open-telemetry/opentelemetry.io#5078]
Team,
Currently we have only beta versions available for the below libraries and we are planning to use opentelemetry capability.
1.OpenTelemetry.Instrumentation.AspNet 
2.OpenTelemetry.Extensions.AWS 

Understand the beta versions may have security vulnerabilities or defects, and also, they are getting deprecated frequently. This is causing problem for us in the long run, as we would like to have production release and stable version, as we are planning have opentelemetry for our production applications.

Please let me know when we can get the final release version for the above libraries. Thanks .

**Comment by theletterf** [comment]
Might be a question for @open-telemetry/dotnet-approvers

**Comment by cijothomas** [comment]
For OpenTelemetry.Extensions.AWS, please check with the owners listed in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Extensions.AWS


For Instrumentation.AspNet, its maintained by OTel Contrib Maintainers, but unfortunately, there is no ETA for a stable release of this component. Noone is actively working to make that happen from what I can tell.
(I am part of the OTel Contrib Maintainer)
