### ISSUE TITLE
Python zero-code instrumentation does not use bytecode injection

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry.io#5089]
https://opentelemetry.io/docs/zero-code/python/

The intro paragraph says

> [It dynamically injects bytecode to capture telemetry from many popular libraries and frameworks.](https://opentelemetry.io/docs/zero-code/python/#:~:text=It%20dynamically%20injects%20bytecode%20to%20capture%20telemetry%20from%20many%20popular%20libraries%20and%20frameworks.)

But this is not accurate. We use monkey patching in almost all cases.

**Comment by cartermp** [comment]
Huh, I had thought maybe this was some shared text but it seems this was only written for the Python docs. Yeah, this should change.

**Comment by CFly17** [comment]
Hi @aabmass! Feel free to assign to me, I'm happy to contribute and update this documentation.
Thanks for pointing this out.

**Comment by cartermp** [comment]
@CFly17 we don't assign issues in this repo, but feel free to just send a PR and we'll gladly review it.

**Comment by CFly17** [comment]
Thanks @cartermp. This is my first contribution to open source. 
[opentelemetry.io/pull/5130](https://github.com/open-telemetry/opentelemetry.io/pull/5130)

**Comment by CFly17** [comment]
Thanks @cartermp. This is my first contribution to open source.
https://github.com/open-telemetry/opentelemetry.io/pull/5130

**Comment by CFly17** [comment]
attempting to fix failed checks for

- MARKDOWN linter
- REFCACHE updates?
- FILE FORMAT

After pushing what I _believe_ to be the fixes, I proceeded to sync with main and the checks stopped. 
I believe I need [workflow approval](https://github.com/open-telemetry/opentelemetry.io/pull/5130) from a maintainer now.

**Comment by svrnm** [comment]
is this fixed via #5130?

**Comment by CFly17** [comment]
Yes @svrnm. But my merged PR left behind an [unused refcache](https://github.com/CFly17/opentelemetry.io/blob/7d4dd956fb8d4605ef962474103cc4df0cd5f448/static/refcache.json#L1714) link. 
If the code was already merged, should I push to the same branch, or open a new PR to remove this line?

**Comment by svrnm** [comment]
> Yes @svrnm. But my merged PR left behind an [unused refcache](https://github.com/CFly17/opentelemetry.io/blob/7d4dd956fb8d4605ef962474103cc4df0cd5f448/static/refcache.json#L1714) link. If the code was already merged, should I push to the same branch, or open a new PR to remove this line?

I guess we have many of those, so do not worry about it ;-)
