### ISSUE TITLE
Available instrumentations: no instructions to apply instrumentation

### ISSUE THREAD

**Issue by VladisS-Vostok2000** [open-telemetry/opentelemetry.io#5115]
[.NET Available instrumentations](https://opentelemetry.io/docs/zero-code/net/instrumentations/) does not include instructions how to apply it.

Is it applied on `app.Run()` instruction?

Thanks!

**Comment by tiffany76** [comment]
@open-telemetry/dotnet-approvers, PTAL. Thanks!

**Comment by cijothomas** [comment]
> Instrumentations
> All instrumentations are enabled by default for all signal types (traces, metrics, and logs).

^ You don't need to apply it, as they are already enabled!

@open-telemetry/dotnet-instrumentation-approvers is better suited for follow ups, if any!

**Comment by VladisS-Vostok2000** [comment]
Ok, i just wanted to *change* them.
I found this repo by official msdn documentation.
I will ask that in specified section, thanks anyway.
