### ISSUE TITLE
[Vendors] The URL for `Learn more` of `Apache SkyWalking` has 404

### ISSUE THREAD

**Issue by linghengqian** [open-telemetry/opentelemetry.io#5139]
- The URL for `Learn more` of `Apache SkyWalking` has 404. See https://opentelemetry.io/ecosystem/vendors/ .
- ![image](https://github.com/user-attachments/assets/934e5123-8b1f-4438-abd8-4e183e82541b)
- This will point to https://skywalking.apache.org/docs/main/v9.0.0/en/setup/backend/opentelemetry-receiver/ which will 404.
- ![image](https://github.com/user-attachments/assets/ce5b9a40-913e-4f2f-af7e-daa467e2acf9)
- I don't think this is reasonable behavior.

**Comment by tiffany76** [comment]
Thanks for reporting this broken link, @linghengqian. We'll see if we can get it corrected quickly.

**Comment by tiffany76** [comment]
Hi @wu-sheng - I saw that you [added Apache Skywalking to the integrations list](https://github.com/open-telemetry/opentelemetry.io/pull/2386) last year. 

Do you know the correct link for the Apache Skywalking vendor entry? The [entry](https://github.com/open-telemetry/opentelemetry.io/blob/6fd7aa132c2da53fd4f76eb2cec249f4ef11fc59/data/ecosystem/vendors.yaml#L319) doesn't list a contact. Thanks!

**Comment by wu-sheng** [comment]
We have 3 entry(s) actually for now
- metric support, https://skywalking.apache.org/docs/main/latest/en/setup/backend/opentelemetry-receiver/
- log, https://skywalking.apache.org/docs/main/latest/en/setup/backend/log-otlp/
- tracing, https://skywalking.apache.org/docs/main/latest/en/setup/backend/otlp-trace/

**Comment by svrnm** [comment]
Since we do not support multiple pages as of today, I would suggest we pick one by preference (e.g. tracing)
