### ISSUE TITLE
Page feedback, .NET Framework

### ISSUE THREAD

**Issue by cssatkmd** [open-telemetry/opentelemetry.io#5151]
Suggested improvements for page: https://opentelemetry.io/docs/languages/net/netframework/

I would like documentation for setting up metrics collection for the full .NET Framework, 4.x.x. 
How to enable?
How to configure?
What if one is not running ASP.NET?
Do we _always_ need the TelemetryHttpModule?
Etc..

Thanks!

**Comment by cartermp** [comment]
Note that metrics are not currently documented for .NET right now, regardless of if it's on .NET Framework or .NET: https://opentelemetry.io/docs/languages/net/instrumentation/#metrics

> What if one is not running ASP.NET?

Are you using something else? In general we document ASP.NET Core, ASP.NET, and Console but that's it.

**Comment by cssatkmd** [comment]
I am using ASP.NET, but I was looking for a console example. I wanted to make sure I was doing it right.

We are however using Nancy for our ASP.NET solution, but I currently don't have the need for telemetry on requests, as we have older logging in place for that. I was looking to support memory usage tracking via OpenTelemetry, but so far I'm not getting there.

Thanks for your feedback/comment!

**Comment by cijothomas** [comment]
If looking for ConsoleApp, this doc can help. There is no difference between .NET FW vs .NET Core vs .NET for console app: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/getting-started-console

**Comment by svrnm** [comment]
@cssatkmd did @cijothomas' answer help you?

**Comment by clausndk** [comment]
Yes, thanks. The documentation led me to endpoint manipulation, by assigning metrics information to our telemetry provider. This was different from core, as full Framework apparently needed it.

**Comment by cssatkmd** [comment]
Yes, thanks. The documentation led me to endpoint manipulation, by assigning metrics information to our telemetry provider. This was different from core, as full Framework apparently needed it.
