### ISSUE TITLE
Page feedback - feature flags

### ISSUE THREAD

**Issue by szeitlin** [open-telemetry/opentelemetry.io#5154]
Suggested improvements for page: https://opentelemetry.io/docs/demo/feature-flags/

This looks very straightforward, except the repo I'm using doesn't seem to have a `src/flagd/demo.flagd.json` file.

All I see in the `src` folder is the services, there is no `flagd` folder.

**Comment by tiffany76** [comment]
Thanks for reporting your issue, @szeitlin. 

@open-telemetry/demo-approvers, PTAL!

**Comment by julianocosta89** [comment]
@szeitlin which repo are you using?
This doc page is responsible for instructions on the upstream OpenTelemetry Demo: https://github.com/open-telemetry/opentelemetry-demo

If you are using a vendor fork or some outdated version of the demo you indeed may not have that file.

In that case you can navigate to the path `/feature` of your your frontend page.
Depending on how you are running the demo, that would be:

<http://localhost:8080/feature>

The Feature Flags can be enabled/disabled in there.

I don't think we should have that explained in the upstream docs though, as we try to keep docs and demo up-to-date and in sync.

**Comment by szeitlin** [comment]
interesting, I'll try that. Yeah this is a vendor fork (and their fork isn't completely up to date with yours, it turns out). Thanks!

**Comment by tiffany76** [comment]
Thanks, all! 

@szeitlin I'm going to close this issue, but please feel free to come back with any other docs issues you encounter.
