### ISSUE TITLE
Can not download ocb binary tool

### ISSUE THREAD

**Issue by wooonderful** [open-telemetry/opentelemetry.io#5157]
When I try to download the ocb binary tool as the document fallow:
<img width="927" alt="image" src="https://github.com/user-attachments/assets/d90c621c-cdd2-4281-8dfb-a4b4944d66fa">

I just get a 404 response:
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/4b2d2cfc-082f-4dd2-a6da-590230fd776a">

So when I try to find it in the github release assets, I can't. 
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/d0d870df-9182-42e1-a429-479217664fc3">

**Comment by tiffany76** [comment]
@open-telemetry/docs-approvers: possibly related to #5124?

**Comment by chalin** [comment]
Right. Since we're tracking the source of this problem via:

- #5124

I'm going to close this now. (Also, the version has been updated since this issue was created, so the specific problem of the missing v0.108.1 is no longer relevant.)
