### ISSUE TITLE
Demo Architecture Diagram shows "unsupported markdown"

### ISSUE THREAD

**Issue by candlerb** [open-telemetry/opentelemetry.io#5168]
Suggested improvements for page: https://opentelemetry.io/docs/demo/architecture/

There is a rendering problem in the images, where there are currently lots of URLs shown as `"Unsupported markdown: link"` - both inside nodes and on edges. This makes the images hard to interpret.

Examples:

![image](https://github.com/user-attachments/assets/c5dfe83e-2678-483e-8369-217434f800c4)

The text inside the graph source is much clearer, e.g.

```
            pr-http[/"Prometheus HTTP<br/>listening on<br/>http://localhost:9090"/]
```

**Comment by svrnm** [comment]
@open-telemetry/demo-approvers PTAL>

@candlerb thanks for reporting

**Comment by julianocosta89** [comment]
@svrnm has anything changed in the docs?
I'm pretty sure this was working before 🤔

**Comment by theletterf** [comment]
This doesn't work in the Mermaid live editor either. [Example](https://mermaid.live/edit#pako:eNqVVl1P2zAU_SuWJySQ2qUdrECZeAD2KRAVdNpDgibXuU0DThzZbhkC_vtsx2nS1g2iD1FaHx8fn3uu62dMeQx4iBNBihkan0W5nE_KLyqehmNgkIEST-iCKIK-Mf54F-VIf5aw6uVvQeI4zRMUIgexMPXEYBMzTRkb5jyHjlSCP4B9P6mn7eygCqq4JuEFUjNAKlUMJKKMyJkeayxTqeFxeF1A3tANGW_oyeTuVUoFlyAWKYW9egTyOMqbQNT92D19ifD1-HL0ZSKC0-RmdB7hF8RpNxEFbcX-GI9HaHR9O3YTZkoVTfpaMA2vtVp0zhkDqrhoiK0N5LS07MPxIYHpfodyxsVwwgh9OFnFO3FhUIpBN0AhXYCwqlgqFeTGVZ6XW9LQYRAwTgmbcamGB_v9Qz01uNtgNTt4mxWZX2anGrtOexRYsKGRm2PeJQvB6e5IP0BKLuSeD5AtNVnLv_4ruFAgvHxcsXoLq0iviajbPa10eP1YBXj1NyBZK8CI25pGR2CwOmWzdXuPe8e9gBRpsOgHlkeHrhBdSVcYzIhlMEF-Qfekq2PkDWUhQm27bqAZzKU3kIVwgYTDz_1PRy2BtDqM6zUjsgX4I1IFyyRtFkxPVDKehLuNiePbi7O9TVyVzQbSpMGfea97vhRY5bY8TopXXwUoO3xL_fT45Pk5wmeCP0rXNg2xv39G-PV1Be7i1VZwWytX6om3jvck_EUgAf-hck9cDQe9uAcHLTUso2IcLunq06r1WLm34G1niiY11XWMm3XV41VdHeYdNe0PBkcDX1HLrdiiWQEeTdVga0WXHici_C7IlOTEa3JSNcr0aHLchxaTEx03sQgj7OjQrf6PMo1xt4GrfKmQ7zBmv9fzhr1c3W49eTvMy8Ov7TQy0Sxp67nO1q1zbd3WJ69M3-gjF471HqpX2tJD5VISiKC2iwx3c63E07OV4euLJbUlvqWM6UGsLy0TTkTstuaiZ83VD9zBGYiMpLG-jj2bsQjr0yGDCA_1awxTMmcqwp1ySAKd6wP06RIWwEoI4_paE-Eof9VcZK747VNO8VCJOXTwvIiJgouU6NRmeDglTOpfIU51E1-Vd0B7FXz9D3REDdo).

There seems to be an issue with Mermaid: https://github.com/orgs/community/discussions/106690#discussioncomment-8698490

I couldn't find any bug in Mermaid's repo about this, though. As Mermaid is working as intended, I'll open a PR to sanitize the links by removing "http://"

**Comment by candlerb** [comment]
There's this recent bug: https://github.com/mermaid-js/mermaid/issues/5824

**Comment by theletterf** [comment]
@candlerb Good find! Seems critical enough to get fixed soon.

@svrnm We'd either wait or pin Mermaid to a previous version. Not sure when that regression was introduced, though.

**Comment by theletterf** [comment]
I've patched the diagram, but let's follow up on that Mermaid bug.
