### ISSUE TITLE
Development troubles help request

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry.io#5194]
**What needs to be changed?** Describe the update that is required.

I am trying to create a new blog post, #5193.

I am following the steps in https://opentelemetry.io/docs/contributing/development/.

```
> _hugo
> hugo --cleanDestinationDir -e dev --buildDrafts --baseURL http://localhost

Total in 5 ms
Error: failed to load modules: module "github.com/FortAwesome/Font-Awesome" not found in "/Users/josh.macdonald/src/opentelemetry/opentelemetry.io/themes/github.com/FortAwesome/Font-Awesome"; either add it as a Hugo Module or store it in "/Users/josh.macdonald/src/opentelemetry/opentelemetry.io/themes".: module does not exist
```

Is there a step to install everything I need? I'm aware that I can manually poke around and find an installation of Font-Awesome, but it looks like there are more steps and I imagine there is a tool to set this up for me, possibly not documented?

**Comment by svrnm** [comment]
it should be installed when you run `npm install`

**Comment by jmacd** [comment]
Oops, I was confused between `nvm install` and `npm install` and left out the npm install step.
