### ISSUE TITLE
Add link to VERSIONING.md in Collector docs

### ISSUE THREAD

**Issue by tiffany76** [open-telemetry/opentelemetry.io#5197]
**Desired feature or idea**: 

In preparation for Collector v1.0 release, project maintainers have clarified the support policies for Collector artifacts. The policy document, [VERSIONING.md ](https://github.com/open-telemetry/opentelemetry-collector/blob/main/VERSIONING.md), lives in the Collector core repository. We should link to it from the website documentation.

I think the link could be worked into the [Status and releases](https://opentelemetry.io/docs/collector/#status-and-releases) section of the Collector landing page with a statement like:

> Support is guaranteed for Collector software artifacts for a certain time period based on the artifact's intended audience. This support includes, at minimum, fixes for critical bugs and security issues. See the [support policies](https://github.com/open-telemetry/opentelemetry-collector/blob/main/VERSIONING.md) for more details.

**Additional context**: 
- See [#10004](https://github.com/open-telemetry/opentelemetry-collector/issues/10004) for original issue and discussion.
- See [#11001](https://github.com/open-telemetry/opentelemetry-collector/pull/11001) for the work-in-progress PR that adds support policies.

cc: @mx-psi

**Comment by Tharanishwaran** [comment]
can i work on this issue ?

**Comment by Tharanishwaran** [comment]
Hi @tiffany76 can i work on this issue if its still available ?

**Comment by tiffany76** [comment]
Hi @Tharanishwaran. Sure, it's all yours.

**Comment by tiffany76** [comment]
Fixed by #5216.
