### ISSUE TITLE
Update status of tracing for 1.0 languages

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry.io#520]
https://opentelemetry.io/docs/python/#status-and-releases still says tracing is beta for python which has a 1.0 release. Same for .NET and Java.

**Comment by harshita19244** [comment]
I would like to work on this issue @austinlparker @flands, could you please assign me?

**Comment by aabmass** [comment]
@shelbyspees per your comment https://github.com/open-telemetry/opentelemetry.io/pull/539#issuecomment-819674722, this has been updated in the Python repo. How do we sync the changes over to this repo? Is there any documentation for that?

**Comment by austinlparker** [comment]
Each SIG needs to either manually or automatically copy changes over to this repository by making a PR of their `website_docs` content.
