### ISSUE TITLE
gh repo clone open-telemetry/opentelemetry-dotnet-instrumentation

### ISSUE THREAD

**Issue by Mitrok-Bit** [open-telemetry/opentelemetry.io#5208]
**Desired feature or idea**: What would you like to see happen?

**Additional context**: anything else you can think about that would be helpful.

_Please delete paragraphs that you did not use before submitting._

**Comment by svrnm** [comment]
@Mitrok-Bit can you provide some more details what you are trying to accomplish or where you might need help?
