### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by zursch** [open-telemetry/opentelemetry.io#5219]
The page for java exporters seems to have been deleted in the latest revision of the documentation. Used to be here: 
https://opentelemetry.io/docs/languages/java/exporters/

Could you bring it back please?

**Comment by tiffany76** [comment]
Hi @zursch, thanks for reporting your issue. As you noticed, we are currently reworking some of the SDK and API documentation, starting with Java.

@jack-berg, would you be able to help @zursch find what they're looking for?

**Comment by jack-berg** [comment]
We're re-organizing the java docs. The context from the exporters page has (largely) moved to [Manage Telemetry with SDK](https://opentelemetry.io/docs/languages/java/sdk) under the SpanExporter, MetricExporter, LogRecordExporter sections.

**Comment by tiffany76** [comment]
@zursch, I'm closing this issue, but if you still don't find the documentation you need, come back and let us know.
