### ISSUE TITLE
Demo Architecture

### ISSUE THREAD

**Issue by abhishekujjain** [open-telemetry/opentelemetry.io#5238]
Text **localhost:4318** repeated in diagram "OTel Collector" in this page https://opentelemetry.io/docs/demo/architecture/

**Comment by tiffany76** [comment]
Thanks for reporting this @abhishekujjain. Would you like to put up a PR to fix the repetition?

**Comment by Tharanishwaran** [comment]
can i work on this issue ?

**Comment by tiffany76** [comment]
Hi @Tharanishwaran. Let's give @abhishekujjain a chance to resolve this one first, if they want to. Thanks!

**Comment by Blessing-Mba** [comment]
Hi @maryliag . I am interested in fixing this good first issue as an Outreachy contributor, can you grant me permission please

**Comment by tiffany76** [comment]
Hi @Blessing-Mba, thanks for your interest! Someone else has already asked to work on this issue, so we'll need to give them a chance first.

Since we haven't heard from @abhishekujjain, I think it's okay for you to fix this issue, @Tharanishwaran, if you're still interested.

**Comment by Blessing-Mba** [comment]
I am still interested in fixing this issue @tiffany76

**Comment by tiffany76** [comment]
Hi @Blessing-Mba, I see that you already put up [a PR](https://github.com/open-telemetry/opentelemetry.io/pull/5291) to fix this. Thanks for taking the initiative! 

For the future, we do recommend that you read through all the comments on an issue before starting work, just to make sure that no one else has claimed the issue before you. @Tharanishwaran, my apologies.

**Comment by Blessing-Mba** [comment]
My apologies and this information is duly noted @tiffany76
