### ISSUE TITLE
https://opentelemetry.io/about/#what-is-observability is gone

### ISSUE THREAD

**Issue by kmt** [open-telemetry/opentelemetry.io#524]
There used to be a https://opentelemetry.io/about/#what-is-observability page that explained the "3 pillars" of observability: tracing, metrics and logging.  It's gone now.

Is this on purpose?  It was a page that my observability team was referring to often until it disapeared.

If this is on purpose, what reference do you recommend instead?

**Comment by austinlparker** [comment]
That content moved over to the 'Concepts' page in the docs - https://opentelemetry.io/docs/concepts/.
