### ISSUE TITLE
Page feedback

### ISSUE THREAD

**Issue by johnvlittle** [open-telemetry/opentelemetry.io#5255]
Suggested improvements for page: https://opentelemetry.io/docs/zero-code/java/agent/getting-started/

This page links to opentelemetry-javaagent.jar.  However, this jar is missing exporters such as jaeger, and according to stackoverflow, the correct jar is an "all" version, opentelemetry-javaagent-all.jar

It would be much better to link to opentelemetry-javaagent-all.jar, either instead of or as well as opentelemetry-javaagent.jar

opentelemetry-javaagent-all.jar is hard to find.

**Comment by tiffany76** [comment]
@open-telemetry/java-instrumentation-approvers, PTAL. Thanks!

**Comment by trask** [comment]
related: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/12338

**Comment by tiffany76** [comment]
Hi @johnvlittle, since it looks like the Jaeger exporter is deprecated and the `opentelemetry-javaagent.jar` file is up-to-date, I'm going to close this issue. If you have more questions, please feel free to raise a new issue.

Thanks!
