### ISSUE TITLE
Implement `/api-docs` as a redirect and possibly change path

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#5261]
Given that `/api-docs` is just a covenience, as @svrnm mentioned, and give that the same info appears in https://opentelemetry.io/docs/languages/#api-references, I'd like to propose that we keep things DRY and create a simple redirect rule instead of a separate page.

Also, I think that path of the redirect should be either `/docs/api`, or just `/api`. WDYT?

**Comment by chalin** [comment]
@svrnm - hmm, giving this more thought. How about pulling the API References section out of https://opentelemetry.io/docs/languages/#api-references into it's own page https://opentelemetry.io/docs/languages/api, with an alias of `/api`? (Another way of stating this is to move `/api-docs` to have it's canonical path be `/docs/languages/api`?

**Comment by svrnm** [comment]
Would you then also add a item into the navigation tree? Or just link from the index then to that page?

**Comment by chalin** [comment]
I think that we could add it as the top entry in the left-nav. WDYT?

**Comment by svrnm** [comment]
> I think that we could add it as the top entry in the left-nav. WDYT?

I have mixed feelings. The initial goal was to have a quick link where I can find all the language APIs without going docs.opentelemetry.io and click myself through to the language. This is done by just having the URL. Now if we add a top level item called "APIs" or "API Docs" side by side with "Language APIs & SDKs" we probably confuse people.

**Comment by chalin** [comment]
I don't see it as confusing, since it is a convenience page that collects together all of the language API references; in a sense, it is an [index page](https://en.wikipedia.org/wiki/Index_(publishing)), in the non web sense of the word. Given your current feelings about it, maybe it could go at the bottom of the section's left-nav entry.

Regardless, would you object to having a separate page, rather than a section in `/docs/languages` landing page?

**Comment by chalin** [comment]
I don't have a strong feeling either way. I'm ok with the list being part of the `/docs/languages` landing page for now.

**Comment by chalin** [comment]
Ok, let's go with #5272 as it is :)
