### ISSUE TITLE
Collector Pipeline Exception deprecated

### ISSUE THREAD

**Issue by rverchere** [open-telemetry/opentelemetry.io#5280]
**What needs to be changed?**

Hi, the collector pipeline documentation indicates that an `ErrDataTypeIsNotSupported` exception is reported.

It seems deprecated, using `pipeline.ErrSignalNotSupported` instead, see comment in the opentelemetry-collector [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/component.go#L18C32-L18C63).

**What is the name + path of the page that needs changed?**

Collector - Architecture:  https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/collector/architecture.md#pipelines 

**Additional context**:

I can create a PR if needed ;)

**Comment by svrnm** [comment]
Thanks for reporting this issue @rverchere 

@open-telemetry/demo-approvers @open-telemetry/collector-approvers please take a look
