### ISSUE TITLE
[Outreachy Meta] Read this issue if you are participating in the outreachy contribution period December 2024 

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5290]
> [!IMPORTANT] 
> * **Oct. 29, 2024 4pm UTC** is the deadline for applicants to record contributions and create a final application. 
> * The deadline to register for the project via the outreachy platform has been extended until **Oct 23 7am UTC**. If you want to participate, please make sure that you record at least one contribution to the "OpenTelemetry Registry" project.
> * Make sure that you work on your assigned tasks, and that you provide your timeline until **Oct 25th**. Use the remaining days until the deadline to finalize your application independently.

Hello everyone!

Thank you for participating in Outreachy and being interested in contributing to the OpenTelemetry Project! This issue will help you during the contribution phase, by providing some instructions on how to get started and it also will list contribution period tasks you can pick up, complete and then submit! 

## Getting Help

If you have any questions, any issues, or just want to chat with mentors and participants, register with [CNCF Slack](https://slack.cncf.io) and join the channels [#otel-comms](https://cloud-native.slack.com/archives/C02UN96HZH6) and [#otel-registry-uxui-mentorship-outreachy-december-2024](https://cloud-native.slack.com/archives/C07PZQMHWP4).

## Getting Started

As a good starting point to familiarize yourself with our project, we recommend you dive into our [contribution guidelines](https://opentelemetry.io/docs/contributing/), especially the section around [setting up a dev environment](https://opentelemetry.io/docs/contributing/development/) will be helpful, since you will need a local development environment to contribute to our project successfully.

**Since those guidelines are made for new comers, do not hesitate to ask any questions or call out what is unclear!**

When you have your local setup up and running I recommend that you start playing around with it by introductions minor changes and seeing how they affect the website. It’s all build using Hugo (https://gohugo.io/) and we use the docsy theme (https://www.docsy.dev/)

As you know for the project itself we will look into the UI/UX of the registry which you will find when you click on “Ecosystem” at the top and then registry. Explore it, try to find something with it, take a look if you understand how it works.

## Contribution Period Tasks

When you have set up your local development as outlined above and have yourself familiarized with our website, and the registry, you can start with the **small contribution period tasks** from the list below:

- after going to the `Getting Started` above, setting up the development environment and familiarizing yourself with the website & registry, apply a minor change to your local copy of the registry (`http://localhost:1313/ecosystem/registry/`), take a screenshot, visually highlight the change you applied on the image and attach the image as a comment to **this issue**. 
- review the [Registry](https://opentelemetry.io/ecosystem/registry/) and create a short usability report using the following form: https://forms.gle/vA3vSQv5vcsmtdzQ9. **Note**: if you'd like to redo your report or if we ask you to apply changes to your report, just fill out the form another time.

After you have completed both steps above, we will ask you to implement one or two improvements for the registry UI and submit a pull request for it. ~~Although we aim for it, we may not merge the PR during the contribution period, which will be for reasons outside of your control. In any case we will confirm with a comment, when you have completed the task successfully.~~ We will not merge any of the PRs provided until the end of the application phase, this way we ensure that every participant can build on top of the same state of the registry and nobody needs to re-do their work because of potential conflicts. We will confirm via a comment that you have completed the task. After the application phase we will aim to merge PRs, however we will not be able to merge all of them for reasons outside of **your** control. This will have no impact on you completing this task successfully. 

With your registry UI improvements done you have completed the mandatory part of the application phase. If time and your bandwidth allows it, you can now look into [outreachy/ux issues](https://github.com/open-telemetry/opentelemetry.io/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3A%22outreachy%22+label%3A%22ux%22) and contribute to those. Comment on a issue you'd like to work on and we will acknowledge your interest. Please pick only one issue at a time!

Here are a few requirements and recommendations for the implementations:

- Make yourself familiar with [Bootstrap](https://getbootstrap.com/) and [Docsy](https://www.docsy.dev/docs/), since our current design is building on top of this framework and theme. Your change should not introduce any other major design framework dependencies. If you want to use an additonal external dependency, please ask on slack upfront if what you plan to use is acceptable.
- As of today the registry is build within [hugo](https://gohugo.io), so it is a _static website_ without a proper backend and database. This is a limitation we are not going to change in this project, so do not try to change that. 
- Provide your pull request early: there is no harm to submit your unfinished work as a **draft PR**. As a new comer to any opensource project it is advicable to ask for feedback early, so you are not spending a lot of time in implementation and will then be asked to change major parts once again
- After you have provided your pull request there will be a set of CI checks running and some of them will very likely fail. Do not worry about them until told otherwise. Maintainers will help you to get them fixes as needed.

## Registry Source Code

The OpenTelemetry Registry consists of multiple components that you will need to take a look into to modify it:

* The [_index](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/ecosystem/registry/_index.md) page, which will cause hugo to render the page at `/ecosystem/registry`
* [search-form.html](https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/shortcodes/ecosystem/registry/search-form.html) shortcode which is responsible for rendering the registry formular
* [registry partials](https://github.com/open-telemetry/opentelemetry.io/tree/main/layouts/partials/ecosystem/registry) a set of templates used for rendering entries and "quick install" instructions
* [registry.scss](https://github.com/open-telemetry/opentelemetry.io/blob/main/assets/scss/_registry.scss) for the stylesheets
* [registrySearch.js](https://github.com/open-telemetry/opentelemetry.io/blob/main/assets/js/registrySearch.js) powers the search engine
* [data/registry](https://github.com/open-telemetry/opentelemetry.io/tree/main/data/registry) all the entries in the registry
* [registry.json.json](https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/ecosystem/registry.json.json) for populating the search index

Thank you once again for contributing to OpenTelemetry!

**Comment by Comfyydev** [comment]
@svrnm 
I edited a line on the registry page, and I’ve completed the usability report form.

![Screenshot from 2024-10-02 14-23-39 (1)](https://github.com/user-attachments/assets/a9996dda-3874-43dd-9402-1c30e6c26647)

**Comment by bintus-ux** [comment]
I had my name inputed as an author  for the cloud foundry article thereby validating usability report form.

![usability check](https://github.com/user-attachments/assets/08f13d15-f8d7-4b4e-aa06-31db8e5ae928)

**Comment by mercybassey** [comment]
![envoy-proxy](https://github.com/user-attachments/assets/59ca6143-4b6d-414e-bd7f-3d2c4273d8c4)
I have edited the Envoy Proxy title and also filled out the usability report form.

**Comment by taylorhelene** [comment]
Hello. I have edited index page and search form. Looking forward to the next part.
![snip2](https://github.com/user-attachments/assets/d7284f51-c3f2-4cfb-9701-3380c222f6ba)

**Comment by Naggayi-Daphne-Pearl** [comment]
Hello i added my name as an author 

![Untitled](https://github.com/user-attachments/assets/625b2d44-ce9a-4a48-af38-d723f538a0e3)

**Comment by basiratkareem** [comment]
Hello, I edited the Title and the Language & Type filter. I have also completed the usability report.

<img width="1280" alt="Screenshot 2024-10-02 at 7 43 36 PM" src="https://github.com/user-attachments/assets/b3abdeb6-fd85-493f-b876-434b342298dd">

**Comment by kemsguy7** [comment]
![open](https://github.com/user-attachments/assets/aebe20e7-92b6-483e-897d-06b3e8c3400a)
Hy  @svrnm, I've been able to successfully set up the codebase and make some edits. Moving to the form now

**Comment by Beccamak** [comment]
![image](https://github.com/user-attachments/assets/24c4cd83-5c8a-4338-8bc0-925935ae36dd)


Hi, @svrnm It's Rebecca. I have set up the dev env on my local machine using WSL for Ubuntu.
I changed the background color and color of the "Search 832 entries" to blue and white as seen in the image below. I also added "Our" to the text.

**Comment by yashi-hub** [comment]
Hello @svrnm, I am Yashi. I have been able to set up dev environment on my local and made some changes - 
![open-telemetry ](https://github.com/user-attachments/assets/138d61ee-39e3-4dd4-a627-cb27307318b9)
Have changed the background color of cloud foundry card and added black borders for the right section.
I have also filled out the usability form.
Thanks

**Comment by crocmons** [comment]
Hello @svrnm I've been able to setup my local environment successfully also I added my name here ..  Moving to the form now
![screenshot-127_0_0_1_1313-2024_10_07-02_54_04](https://github.com/user-attachments/assets/9c66b1d9-1df7-4970-9253-59eec6610332)

**Comment by Oluchi-gift** [comment]
Hi @svrnm , my name is Oluchi Gift. I have been able to set up my dev environment. And i changed the title to Registry (Edited by Oluchi) and the subtitle to "This helps to find libraries, plugins, integrations and other useful tools for using and extending opentelemetry
![Frame 3474317](https://github.com/user-attachments/assets/0f7415e6-8739-42c9-a0c0-74b1216d6ec2)

**Comment by DIANAAJAMBO** [comment]
![Screenshot (556)](https://github.com/user-attachments/assets/13ecbe81-42aa-473c-9478-5bc807c856a5)
Hello @svrnm I was able to set up my local environment and also made some changes underlines in red. I have also gone ahead to fill out the usability report.

**Comment by SusanGithaigaN** [comment]
Hi @svrnm, I have finished setting up the project locally. I have also made some edits to the registry page and filled out the usability form.
![susan-registry-edit-local](https://github.com/user-attachments/assets/cdf9aaf6-1d2e-4437-90de-d255a518b0fa)

**Comment by JennySimen** [comment]
Hi @svrnm, I have finished setting up the project locally and I have made some changes to the registry.
![Screenshot 2024-10-08 120356](https://github.com/user-attachments/assets/84825490-8230-4a07-a039-39b21ed1b010)

**Comment by MercyCherop** [comment]
Hi @svrnm i was able to make a small change to the registry
<img width="1200" alt="Screenshot 2024-10-09 at 11 14 57" src="https://github.com/user-attachments/assets/054c8fee-37a2-4018-9391-25bbaa763def">

 as highlighted below. Now moving on to the usability report

**Comment by FatumaA** [comment]
Hi,
Classic hello world 😉😅 

![A screenshot of the registry site with a title of "Hello Registry World" and a red arrow pointing to it](https://github.com/user-attachments/assets/45c8e0f2-6bf8-4a3e-9793-5d6eb9c4253a)

**Comment by ladyami** [comment]
![search bar improvement](https://github.com/user-attachments/assets/1860f357-e4a3-4512-bff0-ac01ceeefc41)
@svrnm Please review this and give me your feedback.

**Comment by bhekidaweti** [comment]
Good day, I modified the form input placeholder to " Type to search the registry.." and the input field label. 

**I am working from GitHub codespaces hence my project is not exactly reflecting "localhost:1313..." please let me know if this is not allowed.  
![oTel](https://github.com/user-attachments/assets/81be80f1-d57e-4b8f-bf0b-efed15967f73)

**Comment by ladyami** [comment]
> @ladyami while I appreciate your effort, please review the instructions in the issue description above, I ask people to show a screenshot of them successfully setting up a dev environment, and also the survey (that you filled out) is not asking for a visual design suggestion yet.

I am sorry I did the design based on what I read about the project in outreachy website here is my setup I set it up on gitpod
![index html - opentelemetry io - Gitpod Code - Google Chrome 10_12_2024 9_28_56 AM](https://github.com/user-attachments/assets/dc4fd073-6ae0-44b8-97a4-d98de78c979c)
![index html - opentelemetry io - Gitpod Code - Google Chrome 10_12_2024 9_30_32 AM](https://github.com/user-attachments/assets/5c697d50-b415-4729-80f7-39df0cb7e556)

**Comment by olamideTiana** [comment]
@svrnm Good day, I have successfully set up my local dev environment and was able to edit the index page and search button (from Submit to Search) and I also included the link to Traefik hub API management. I have also filled the usuability form.
![Screenshot registry page](https://github.com/user-attachments/assets/516bca34-041f-415a-885c-ebfb804191fa)
![Screenshot registry edit 1](https://github.com/user-attachments/assets/78d3ecea-661a-445e-b04b-38bd059f5064)
![Screenshot registry](https://github.com/user-attachments/assets/6b33414e-a6aa-420d-a767-1e5948da534f)
![Screenshot registry edit 2](https://github.com/user-attachments/assets/7198edf0-8d8a-4f9f-93e0-ec0ed0d29b00)

**Comment by mailsg** [comment]
Good day @svrnm, I have successfully set up the local dev environment and edited the registry page. I have also filled the usability form.

![OpenTelemetry](https://github.com/user-attachments/assets/e5f4e9b2-b752-42c7-ada4-9a155f9704a7)

**Comment by Caritajoe18** [comment]
Hello @svrnm, I have successfully set up my local environment.
![Caritas Edit](https://github.com/user-attachments/assets/21265842-6b3b-45e3-a0dd-8123df79ffde)

**Comment by svrnm** [comment]
> [!IMPORTANT] 
> Thank you all for participating, as announced I closed the project for new contributors. I will work with those of you who still have open tasks to work on.

**Comment by svrnm** [comment]
> [!IMPORTANT] 
> The deadline to register for the project via the outreachy platform has been extended until Oct 23 7am UTC. If you want to participate, please make sure that you record at least one contribution to the "OpenTelemetry Registry" project.
