### ISSUE TITLE
[admin] GCSE clean up

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#5305]
@austinlparker, if you visit https://programmablesearchengine.google.com/controlpanel/overview?cx=bde3d634eca9cd335, you'll see that your LightStep email is still registered as the owner of the Google Custom Search Engine. The email should be updated either to your currently active address, and/or add an OTel org/admin email address.

- [ ] Delete old GCSE [bde3d634eca9cd335](https://programmablesearchengine.google.com/controlpanel/overview?cx=bde3d634eca9cd335)
- [x] Setup projects@cncf.io as admin

**Comment by svrnm** [comment]
@chalin we swaped out the GCSE id with one owned by admin@opentelemetry.io in https://github.com/open-telemetry/opentelemetry.io/pull/4711

**Comment by chalin** [comment]
- Ah, right. How about **deleting the old GCSE**? I can't do that because I'm only an admin, not the owner, @austinlparker (via LightStep) is the owner.
- As a maintainer, can you grant my main email address access to that GCSE ID?

**Comment by svrnm** [comment]
> As a maintainer, can you grant my main email address access to that GCSE ID?

let me check

**Comment by svrnm** [comment]
> So is [admin@opentelemetry.io](mailto:admin@opentelemetry.io) registered as a verified owner (and admin) of a non-profit?

I don't know ;-)

> If not, I'm thinking that we should use [projects@cncf.io](mailto:projects@cncf.io) as the owner, and configure [admin@opentelemetry.io](mailto:admin@opentelemetry.io) as an admin.

Send an invite to become an owner to projects@cncf.io

**Comment by chalin** [comment]
Invite accepted, thanks!

**Comment by chalin** [comment]
Why didn't we keep the old GCSE and just change the admin?

**Comment by svrnm** [comment]
> Why didn't we keep the original GCSE and just change the admin? By keep the old GCSE ID we would maintain historical data. Is it because @austinlparker doesn't have access to his LightStep address anymore?

Yes, that was the reason for having a new one: https://github.com/open-telemetry/opentelemetry.io/issues/4666#issuecomment-2163321178

**Comment by austinlparker** [comment]
I'm not sure how we'd go about deleting or merging them; I have no way to get that email address back at this point.

**Comment by chalin** [comment]
Going to close this as "can't fix" 🤷🏼‍♂️
