### ISSUE TITLE
[outreachy] Registry: Redesign cards and make them smaller to enable users to view more entries at a glance

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5307]
Outreachy task for @asamiami

Based on your user experience report, please provide the following suggested improvement via a PR:

> We can design the cards better, make it smaller to enable users view more entries at a glance. The information on the cards aligned better to better display information for users

**Note**: This is an assigned issue for a participant that has completed the user experience report, if you are an outreachy participant as well, find instructions here: #5290

**Comment by crocmons** [comment]
Can I work on this issue?

**Comment by svrnm** [comment]
> Can I work on this issue?

see #5290 please

**Comment by asamiami** [comment]
Thank yu I would handle this immmediately

**Comment by svrnm** [comment]
Thank you for participating in the outreachy participation phase, @asamiami! As announced in the channel and in the [meta issue  ](https://github.com/open-telemetry/opentelemetry.io/issues/5290) I closed the project for new contributors. Since you have not registered and also not provided a PR for this issue, I will close this now
