### ISSUE TITLE
Node.JS Docs

### ISSUE THREAD

**Issue by paulmcconico** [open-telemetry/opentelemetry.io#531]
When instantiating the NodeTracerProvider an error occurs (if following the docs here: https://opentelemetry.io/docs/js/getting_started/nodejs/).
LogLevel is not exported by '@opentelemetry/core' AND LogLevel is not a property of NodeTracerConfig.

![chrome-capture (65)](https://user-images.githubusercontent.com/23711791/114445153-96a02c80-9b84-11eb-951e-8f7a77c9093c.jpg)

**Comment by shelbyspees** [comment]
Thanks for finding this! The Node.js OTel docs gets pulled into this repo from the open-telemetry/opentelemetry-js repo. We don't have permissions to move this ticket to that repo, so please open a new one over there. The change is relatively recent so thanks for your patience while we smooth out the process for managing docs issues.

[Here's a link to the specific file](https://github.com/open-telemetry/opentelemetry-js/blob/main/website_docs/getting_started/nodejs.md) that needs to be updated.

**Comment by chalin** [comment]
Actually, the JS docs are back in this repo since #720.

/assign @open-telemetry/javascript-approvers

**Comment by Rauno56** [comment]
Was fixed in https://github.com/open-telemetry/opentelemetry.io/pull/621
