### ISSUE TITLE
[outreachy] Registry: Categorize entries in a more visually appealing way

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5316]
Outreachy task for @yashi-hub

Based on your user experience report, please provide the following suggested improvement via a PR:

> Unexpected UI/UX Elements: The current user interface is functional, but it could be made more intuitive. For example, categorizing entries in a more visually appealing way [...]

**Note**: This is an assigned issue for a participant that has completed the user experience report, if you are an outreachy participant as well, find instructions here: #5290

**Comment by yashi-hub** [comment]
Thanks @svrnm, will start working on this and create a PR.

**Comment by svrnm** [comment]
Thank you for participating in the outreachy participation phase, @yashi-hub! As announced in the channel and in the [meta issue  ](https://github.com/open-telemetry/opentelemetry.io/issues/5290) I closed the project for new contributors. Since you have not registered and also not provided a PR for this issue, I will close this now

**Comment by svrnm** [comment]
> [!IMPORTANT] 
> The deadline to register for the project via the outreachy platform has been extended until Oct 23 7am UTC. If you still want to participate, please make sure that you record at least one contribution to the "OpenTelemetry Registry" project. When you are registered I will reopen this issue.
