### ISSUE TITLE
[outreachy] Registry: improve the searchbar

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5334]
Outreachy task for @Oluchi-gift

Based on your user experience report, please provide the following suggested improvement via a PR:

> The search and filter while looking good can be improved in so many ways.
> 1. Instead of just "type search" on the search input, it can be changed to "Search keywords, language, type, license or components".
> 2. On clicking the search input, a dropdown comes down showing the categories and the top three projects in each category.
> 3. The filter can be pushed to the left side of the page. On that section it lists all the categories into sections

**Comment by Oluchi-gift** [comment]
Okay @svrnm , On it already

**Comment by svrnm** [comment]
Thank you for participating in the outreachy participation phase, @Oluchi-gift! As announced in the channel and in the [meta issue  ](https://github.com/open-telemetry/opentelemetry.io/issues/5290) I closed the project for new contributors. Since you have not registered and also not provided a PR for this issue, I will close this now

**Comment by svrnm** [comment]
> [!IMPORTANT] 
> The deadline to register for the project via the outreachy platform has been extended until Oct 23 7am UTC. If you still want to participate, please make sure that you record at least one contribution to the "OpenTelemetry Registry" project. When you are registered I will reopen this issue.
