### ISSUE TITLE
[outreachy] Registry: Turn the "Add your project to the registry" into a button

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5347]
Outreachy task for @Isioma20

Based on your user experience report, please provide the following suggested improvement via a PR:

> the the add your project to the open telemetry registry link could be changed to a button since it creates an action to improve the usability.

Please also suggest a prototype design for an actual "add to the registry" page where someone can fill out the details for a new entry. 

**Note**: This is an assigned issue for a participant that has completed the user experience report, if you are an outreachy participant as well, find instructions here: https://github.com/open-telemetry/opentelemetry.io/issues/5290

**Comment by Isioma20** [comment]
Would get right on it @svrnm. Thanks!

**Comment by svrnm** [comment]
Thank you for participating in the outreachy participation phase, @Isioma20! As announced in the channel and in the [meta issue  ](https://github.com/open-telemetry/opentelemetry.io/issues/5290) I closed the project for new contributors. Since you have not registered and also not provided a PR for this issue, I will close this now

**Comment by Isioma20** [comment]
Hi @svrnm. I have opened a PR for this issue here
https://github.com/open-telemetry/opentelemetry.io/pull/5398. I also have a pending inquiry. Does my opened PR not count? Thanks

**Comment by svrnm** [comment]
> Hi @svrnm. I have opened a PR for this issue here #5398. I also have a pending inquiry. Does my opened PR not count? Thanks

The PR was not linked with this issue, I overlooked that.

However, I don't see you being registered with the project as a contributor. I can not find your github handle or PR or anything that indicates that you have applied.

**Comment by Isioma20** [comment]
I have recorded my contributions as required now. Thank you for the deadline extension @svrnm
