### ISSUE TITLE
Add a visualization to "Zero-code instrumentation"

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5354]
It would be great to have a visualization for the [Zero-code instrumentation](https://opentelemetry.io/docs/concepts/instrumentation/zero-code/) page, that demonstrates that the "Zero Code Solution" is something that injects the otel components (sdk, exporters, instrumentation libraries, etc.) from the outside into the application.

Visually it should be aligned existing visualizations, e.g. 

* https://opentelemetry.io/img/otel-diagram.svg
* https://opentelemetry.io/docs/collector/img/otel-collector.svg

**Special Note for Outreachy Contributors**: if you want to work on this issue, please make sure that you have completed the small steps and at least one assigned issue as outlined here: https://github.com/open-telemetry/opentelemetry.io/issues/5290

**Comment by mercybassey** [comment]
@svrnm can I work on this?

**Comment by svrnm** [comment]
> Hi @svrnm can I work on this?

let's finish https://github.com/open-telemetry/opentelemetry.io/pull/5330 first. I'll take another look at it tomorrow, and if things are good you can pick this one.

**Comment by svrnm** [comment]
@mercybassey with #5330 you can work on this now! Thanks.

**Comment by mercybassey** [comment]
@svrnm I did a sketch, but the SVG version doesn't look nice. 
![zero-code-1](https://github.com/user-attachments/assets/d44eb0af-65e8-48e0-8926-1620483a7ac0)
![zero-code-2](https://github.com/user-attachments/assets/897fd852-2386-4586-86ab-857bd050be78)

I'd like to know your take on the sketch if it aligns with what Zero-code does.

**Comment by mercybassey** [comment]
@svrnm I did a sketch, but the SVG version doesn't look nice. 
![zero-code-1](https://github.com/user-attachments/assets/d44eb0af-65e8-48e0-8926-1620483a7ac0)
![zero-code-2](https://github.com/user-attachments/assets/897fd852-2386-4586-86ab-857bd050be78)

I'd like to know your take on the sketch if it aligns with what Zero-code does.

**Comment by svrnm** [comment]
@mercybassey good start thank you!

A few comments:
* Can you let me know where the icons you are using come from? If you created them yourself, we are good, otherwise we need to make sure that they are covered by an open license. Note that we have some of our own icones @ https://github.com/open-telemetry/opentelemetry.io/tree/main/iconography/512x512 you can use (e.g. the exporter and SDK)
* The "application" we are talking about is in most cases a server-side application not a mobile application, if you'd like to pick from our exising iconography, service is a possible choice: https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/512x512/Service.png
* The zero code solutions bundles SDK, libraries & exporter, not sure if this can be visualized somehow. Easiest solution is labelling the lines with "bundles" or something similar
* The arrow between the zero code solution and the application should visualize an "injection", so maybe you have a good idea to make this visual, otherwise labeling is a solution ("injects")

**Comment by mercybassey** [comment]
> @mercybassey good start thank you!
> 
> A few comments:
> 
> * Can you let me know where the icons you are using come from? If you created them yourself, we are good, otherwise we need to make sure that they are covered by an open license. Note that we have some of our own icones @ https://github.com/open-telemetry/opentelemetry.io/tree/main/iconography/512x512 you can use (e.g. the exporter and SDK)
> * The "application" we are talking about is in most cases a server-side application not a mobile application, if you'd like to pick from our exising iconography, service is a possible choice: https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/512x512/Service.png
> * The zero code solutions bundles SDK, libraries & exporter, not sure if this can be visualized somehow. Easiest solution is labelling the lines with "bundles" or something similar
> * The arrow between the zero code solution and the application should visualize an "injection", so maybe you have a good idea to make this visual, otherwise labeling is a solution ("injects")

Currently, the icons are from [SVG Repo](https://www.svgrepo.com/). However, I will use Open Telemetry icons instead and address your comments. Thank you.

**Comment by svrnm** [comment]
> Currently, the icons are from [SVG Repo](https://www.svgrepo.com/). However, I will use Open Telemetry icons instead and address your comments. Thank you.

Thanks. Note, that we can use images from other sources, but we need to know under which license they are released. SVG Repo states that the icons they show are "free", but not all licenses might be compatible with our licenses, and some of their licenses would come with implications, e.g. a license that requires attribution

**Comment by svrnm** [comment]
This looks really good already, can you do the following:

* replace the OTLP image with the OTEL image (https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/32x32/Open_Telemetry.svg) in the Zero Code box
* replace the Metrics image for Instrumentation Libraries with this one https://github.com/open-telemetry/opentelemetry.io/blob/main/iconography/32x32/message_queues.svg
* add it to https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/concepts/instrumentation/zero-code.md, maybe at the top of the page to begin with, so we can add it to the code base
