### ISSUE TITLE
Add a visualization to "Library Instrumentation" page

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5355]
It would be great to have a visualization for the [Libraries concept page](https://opentelemetry.io/docs/concepts/instrumentation/libraries/), that talks about natively instrumenting your application (vs instrumentation libraries). The visualization should demonstrate the difference between the two, i.e. while the instrumentation library is something that needs to be added to an application using the instrumented library as an additional dependency, a natively instrumented application encapsulates the opentelemetry api.

Visually it should be aligned existing visualizations, e.g.
    [opentelemetry.io/img/otel-diagram.svg](https://opentelemetry.io/img/otel-diagram.svg)
    [opentelemetry.io/docs/collector/img/otel-collector.svg](https://opentelemetry.io/docs/collector/img/otel-collector.svg)

**Special Note for Outreachy Contributors**: if you want to work on this issue, please make sure that you have completed the small steps and at least one assigned issue as outlined here: https://github.com/open-telemetry/opentelemetry.io/issues/5290

**Comment by DIANAAJAMBO** [comment]
@svrnm Can this issue be assigned to me? I did work on something and would love to submit it.

**Comment by svrnm** [comment]
> @svrnm Can this issue be assigned to me? I did work on something and would love to submit it.

sure, please go ahead and provide a PR for it

**Comment by DIANAAJAMBO** [comment]
Hello @svrnm,
I tried to create a PR but failed and noticed it is the same PR with #5421.  Kindly review it and let me know of any changes. Thank you so much.

**Comment by svrnm** [comment]
> Hello @svrnm, I tried to create a PR but failed and noticed it is the same PR with #5421. Kindly review it and let me know of any changes. Thank you so much.

We need 2 separate PRs otherwise I can not accept the work on one PR without also merging the work of the other PR. What you need to do for that is the following:

* Remove the image from the other PR, e.g. move the file out of your working directory and commit that change back
* Then switch back to the `main` branch of git (git checkout main) and create a new branch from main (git checkout -B <new name>)
* Add that file into the branch with the new name and create a new PR

**Comment by DIANAAJAMBO** [comment]
@svrnm I have removed the image and "libraries page" edits from this PR #5421 and created another PR for this issue. #5480

**Comment by cartermp** [comment]
Closing as completed by https://github.com/open-telemetry/opentelemetry.io/pull/5480
