### ISSUE TITLE
Rework OpAMP visualization

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5357]
The [Management](https://opentelemetry.io/docs/collector/management/) page shows an image that demonstrates how OpAMP works. It would be great if that image (https://opentelemetry.io/docs/collector/img/opamp.svg), would look similar to other images in the documentation, e.g. https://opentelemetry.io/docs/collector/img/otel-gateway-sdk.svg

**Special Note for Outreachy Contributors**: if you want to work on this issue, please make sure that you have completed the small steps and at least one assigned issue as outlined here: https://github.com/open-telemetry/opentelemetry.io/issues/5290

**Comment by taylorhelene** [comment]
Can I work on this task?

**Comment by svrnm** [comment]
> Can I work on this task?

sure! please go ahead and provide a PR for that change

**Comment by svrnm** [comment]
fixed via #5529
