### ISSUE TITLE
Rework "Building a Connector" images

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5358]
The [Building a connector](https://opentelemetry.io/docs/collector/building/connector/) page shows a few images that have a different look and feel to other pages. It would be great if those images would look similar to other images in the documentation, e.g. [opentelemetry.io/docs/collector/img/otel-gateway-sdk.svg](https://opentelemetry.io/docs/collector/img/otel-gateway-sdk.svg)

**Special Note for Outreachy Contributors**: if you want to work on this issue, please make sure that you have completed the small steps and at least one assigned issue as outlined here: https://github.com/open-telemetry/opentelemetry.io/issues/5290

**Comment by svrnm** [comment]
> @svrnm Please can I work on this?

Yes, please go ahead.

**Comment by Beccamak** [comment]
@svrnm Alright. Thank you.

**Comment by Beccamak** [comment]
@svrnm Please check the SVG files I have worked on. Thank you, sir.
![New Architecture](https://github.com/user-attachments/assets/dcf387db-dbc9-4311-8720-4a110d512862)
![Old Architecture](https://github.com/user-attachments/assets/23432236-2492-42c1-bb15-6e54ca21f107)

**Comment by svrnm** [comment]
This is looking a lot better, thank you! One important thing: it's not super obvious in the current image, but it's important that the connector in the traces pipeline is the same connector as in the metrics pipeline, so if you can visualize that better, this would be great. Not sure if an arrow that goes from right to left looks any good, but maybe you have a creative idea to make this clearer than the current "what is green, is the same thing" solution.

**Comment by Beccamak** [comment]
@svrnm Thank you so much for the feedback. I'll look into it now, and give you an update.

**Comment by svrnm** [comment]
Note, that you can also put your work into a PR already, just replace the current image with your work and we can review it from there

**Comment by Beccamak** [comment]
@svrnm Alright. Thank you. I'll do that.

**Comment by Beccamak** [comment]
@svrnm I have submitted a PR for this. https://github.com/open-telemetry/opentelemetry.io/pull/5407
#5407

**Comment by svrnm** [comment]
fixed via #5407
