### ISSUE TITLE
Build fails when within a folder with spaces

### ISSUE THREAD

**Issue by FatumaA** [open-telemetry/opentelemetry.io#5359]
**What needs to be changed?**
Add a note that `npm run build` will fail if the cloned repo is within a folder that has spaces

**What is the name + path of the page that needs changed?** 
content/en/docs/contributing/development.md

**Additional context**:
This might only be an issue if you run the build command within a terminal that you've changed to (cd into). That is, if you are within the parent folder and you cd'd into the repo via the terminal then run `npm run build` from there.

**Comment by svrnm** [comment]
thanks for reporting, I can reproduce that error on MacOS as well. Root cause for this issue is at the top of https://github.com/open-telemetry/opentelemetry.io/blob/main/scripts/content-modules/cp-pages.sh, because the space in the dir name leads to the following problems:

```shell
> cp:spec
> scripts/content-modules/cp-pages.sh

scripts/content-modules/cp-pages.sh: line 4: cd: too many arguments
scripts/content-modules/cp-pages.sh: line 22: /Users/neumanns/Folder: No such file or directory
OTEL SPEC pages: copied and processed
scripts/content-modules/cp-pages.sh: line 41: /Users/neumanns/Folder: No such file or directory
OTLP SPEC pages: copied and processed
OTLP SPEC protos copied and processed
scripts/content-modules/cp-pages.sh: line 68: /Users/neumanns/Folder: No such file or directory
COMMUNITY pages: copied and processed
scripts/content-modules/cp-pages.sh: line 86: /Users/neumanns/Folder: No such file or directory
SEM CONV  pages: copied and processed
scripts/content-modules/cp-pages.sh: line 103: /Users/neumanns/Folder: No such file or directory
OpAMP SPEC page: copied and processed
```

**Comment by FatumaA** [comment]
In that case, a fix there would make more sense than adding the note.

Is that something I can attempt as I wait for the official Outreachy issue?

**Comment by svrnm** [comment]
> In that case, a fix there would make more sense than adding the note.
> 
> Is that something I can attempt as I wait for the official Outreachy issue?

If you know how to fix a shell script by applying proper escaping&quoting yes, you can give it a try!

**Comment by FatumaA** [comment]
> > In that case, a fix there would make more sense than adding the note.
> > Is that something I can attempt as I wait for the official Outreachy issue?
> 
> If you know how to fix a shell script by applying proper escaping&quoting yes, you can give it a try!

Not really but I attempted regardless
