### ISSUE TITLE
Review visualizations for dark/light mode compatibility

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5361]
While we have dark mode for a while now, some of the visualizations on our website have a white background and/or colors that are made for light mode, e.g.

* https://opentelemetry.io/img/otel-diagram.svg on https://opentelemetry.io/docs/
* https://opentelemetry.io/img/waterfall-trace.svg on https://opentelemetry.io/docs/concepts/observability-primer/
* https://opentelemetry.io/docs/collector/img/otel-collector.svg on https://opentelemetry.io/docs/collector/
* ...

It would be great if at a minimum the background for those images could be set to be transparent, so that they either are black or white, and then to check if some colors need to be adjusted to still work with light&dark mode at the same time. The overall color schema & theme should remain untouched.

**Special Note for Outreachy Contributors**: if you want to work on this issue, please make sure that you have completed the small steps and at least one assigned issue as outlined here: https://github.com/open-telemetry/opentelemetry.io/issues/5290

**Comment by Tharanishwaran** [comment]
@svrnm can i work on this issue ?

**Comment by svrnm** [comment]
@SuvineetSingh @Tharanishwaran we are currently running the participation phase for [outreachy](https://www.outreachy.org/), and we need to reserve some good first issues for the participants. If you participate in outreachy please take a look in #5290, otherwise I can currently not assign this issue to you. When the participation phase ends, and this issue is still available, I am happy to assign it.

**Comment by SusanGithaigaN** [comment]
@svrnm, I am an outreachy participant, can I work on this issue?

**Comment by svrnm** [comment]
> @svrnm, I am an outreachy participant, can I work on this issue?

@SusanGithaigaN let's finish your PR and then you can work on this. Since this is similar to your current work, I can imagine well that this is something you can help with. Thank you.

**Comment by Naggayi-Daphne-Pearl** [comment]
hey @svrnm, 
can i work on this issue

**Comment by svrnm** [comment]
fixed
