### ISSUE TITLE
[fr] Create homepage for French localization

### ISSUE THREAD

**Issue by iguitton** [open-telemetry/opentelemetry.io#5384]
- [x] Localize index page to French
- [x] Create an issue label for lang:fr
- [x] [Create org-level groups for fr approvers](https://github.com/open-telemetry/community/issues/2396)
- [x] [Update code/component owners](https://github.com/open-telemetry/opentelemetry.io/pull/5402)

**Comment by dmathieu** [comment]
I am volunteering to help out with this.

**Comment by svrnm** [comment]
Thank you @iguitton and @dmathieu! Happy to get the French localization started! 🎉 🇫🇷

**Comment by bertysentry** [comment]
Add me to the reviewers as well! 💙🤍❤️ (<-- sorry, it's the only way I found to get a French emoji flag)

**Comment by pierrehilbert** [comment]
I would be happy to pitch in and help as well!

**Comment by codeboten** [comment]
+1, happy to help reviews!

**Comment by jeanbisutti** [comment]
You can add me as a reviewer.

**Comment by marcalff** [comment]
Plus on est de fous, plus on rit (the more, the merrier).
 
Please add me as reviewer as well.

**Comment by svrnm** [comment]
Seems we have a big french speaking community as well, exciting! I will tag you all when we will create the team, this will be the next step after merging https://github.com/open-telemetry/opentelemetry.io/pull/5386, which you all by the way can review and approve already :-)

**Comment by SylvainJuge** [comment]
You can also add me as a reviewer
