### ISSUE TITLE
[outreachy] Registry: Search Result Highlights

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5399]
Outreachy task for @ladyami

Based on your user experience report, please provide the following suggested improvement via a PR:

> Search Result Highlights: Once the user inputs a search query, highlight the matching terms in the search results to make it easier for users to visually confirm they found what they were looking for.

**Comment by ladyami** [comment]
@svrnm will start working on it

**Comment by svrnm** [comment]
> @svrnm When you request suggested improvements, do you mean a UI design or an explanation of the user flow? Or can I provide both?

What I am asking for, is that you implement this feature as part of the OpenTelemetry registry. You can take a look how your peers are doing it: https://github.com/open-telemetry/opentelemetry.io/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+label%3Aoutreachy

**Comment by svrnm** [comment]
Thank you for participating in the outreachy participation phase, @ladyami! As announced in the channel and in the [meta issue  ](https://github.com/open-telemetry/opentelemetry.io/issues/5290) I closed the project for new contributors. Since you have not registered and also not provided a PR for this issue, I will close this now

**Comment by svrnm** [comment]
> [!IMPORTANT] 
> The deadline to register for the project via the outreachy platform has been extended until Oct 23 7am UTC. If you still want to participate, please make sure that you record at least one contribution to the "OpenTelemetry Registry" project. When you are registered I will reopen this issue.
