### ISSUE TITLE
[ja|pt] Drop temporary link-checking rules

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#5423]
- #5276 required that we disable link checking for some `ja` and `pt` pages
- This issue is a reminder to drop the temporary rule in https://github.com/open-telemetry/opentelemetry.io/blob/main/.htmltest.yml after the `ja` and `pt` pages are updated

### Tasks

- [x] `ja` page patch - #5609
- [x] `pt` page patch - #5603

/cc 
  @open-telemetry/docs-pt-approvers
  @open-telemetry/docs-ja-approvers

**Comment by chalin** [comment]
@open-telemetry/docs-ja-approvers can you submit a PR similar to what the `pt` team did?

**Comment by katzchang** [comment]
@chalin Thank you for your heads-up, I'll take a look!
