### ISSUE TITLE
Page feedback for Spring Boot Starter

### ISSUE THREAD

**Issue by robenie-cwt** [open-telemetry/opentelemetry.io#5445]
Suggested improvements for page: https://opentelemetry.io/docs/zero-code/java/spring-boot-starter/out-of-the-box-instrumentation/

1. I think the documentation does not state that the trace and span ids are not populated automatically when using the Spring Boot Starter.  This was automatic when using the Java Agent and Micrometer Tracing so I was expecting that it was automatic as well for the Spring Boot Starter
2. Not sure if this was also mentioned somewhere, but the [logback-mdc-1.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-mdc-1.0/library) did not also say that the OpenTelemetryAppender should be the appender wrapping the AsyncAppender and not the otherway around.

**Comment by theletterf** [comment]
@jeanbisutti WDYT?

**Comment by robenie-cwt** [comment]
I reread my initial comment, and I guess I was not clear that what I'm referring to item 1 is the LogBack MDC not containing the trace id and span id. :)

**Comment by jeanbisutti** [comment]
@robenie-cwt Thank you for you feedback!

About 1, the trace and span IDs will be automatically added by the OpenTelemetry starter to the Logbback MDC from the next release in November. I will update the opentelemetry.io documentation after the release.

About 2, do you want to create a PR in the [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation) repository?

**Comment by robenie-cwt** [comment]
sure, I think I can create a PR for the documentation

**Comment by robenie-cwt** [comment]
Fixed on version 2.10.0
