### ISSUE TITLE
[docs/collector/internal-telemetry] Document how to enable traces on the Collector

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry.io#5446]
**What needs to be changed?** Move documentation on [experimental trace telemetry in the Collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/observability.md#experimental-trace-telemetry) to the 'Internal Telemetry' page.

**What is the name + path of the page that needs changed?** `docs/collector/internal-telemetry`

**Additional context**: This is an experimental feature and it should be reflected as such in the documentation (maybe adding some explicit warning block is a good idea).

**Comment by jade-guiton-dd** [comment]
I'll work on this.

**Comment by codeboten** [comment]
thanks @jade-guiton-dd
