### ISSUE TITLE
Releases page doesn't render markdown

### ISSUE THREAD

**Issue by shelbyspees** [open-telemetry/opentelemetry.io#545]
published page: https://opentelemetry.io/releases/
line in releases page in repo: https://github.com/open-telemetry/opentelemetry.io/blame/main/content/en/releases/_index.md#L52
hugo shortcode implementation: https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/shortcodes/release_notes.html#L14

The content of the releases is rendered in a `<pre>` block:

![latest .NET release on the releases page, rendered in a preformatted block](https://user-images.githubusercontent.com/5217772/115127337-9344e080-9f8a-11eb-97f6-d16156c0c456.png)

Since releases are already written in markdown, it'd be nice to take advantage of that and render it as markdown. Hugo has this functionality so I don't think it's a huge change.

**Comment by chalin** [comment]
Yeah, I still see this problem. For the record, release info is now published under https://opentelemetry.io/status/.
