### ISSUE TITLE
`make ci-link-check` fails on MacOS

### ISSUE THREAD

**Issue by shelbyspees** [open-telemetry/opentelemetry.io#546]
https://github.com/open-telemetry/opentelemetry.io/blob/21f56859b3faff5418601182e0f3350937195f16/Makefile#L9-L11

There's an [open issue](https://github.com/wjdp/htmltest/issues/146) in which cURL fails to download htmltest on MacOS.

For local development on MacOS, running `make test` or `make ci-link-check` fails on the cURL command. I was able to work around this by downloading htmltest from the browser and just running `bin/htmltest` to check links.

A couple ways we could address this:
1. add a note to the [dev setup docs](https://github.com/open-telemetry/opentelemetry.io/blob/main/CONTRIBUTING.md#dev-setup) not to run `make test` or `make ci-link-check` on MacOS and instead download and run htmltest directly
2. update the makefile to skip the cURL step if `bin/htmltest` already exists. MacOS users will still need to download it manually until the cURL issue gets fixed, but after that first download they'd be able to use `make test` for local development

**Comment by chalin** [comment]
I'm in favor of (2), and this is in fact the solution I adopted for other website repos.

**Comment by chalin** [comment]
> 2\. MacOS users will still need to download it manually

FYI, there's a [brew formula for htmltest](https://formulae.brew.sh/formula/htmltest) now.
