### ISSUE TITLE
Document internal metrics being renamed when exporting with Prometheus

### ISSUE THREAD

**Issue by jade-guiton-dd** [open-telemetry/opentelemetry.io#5468]
**What needs to be changed?**

The [Collector "Internal telemetry" page](https://opentelemetry.io/docs/collector/internal-telemetry) at `/docs/collector/internal-telemetry` mentions metrics emitted by the RPC and HTTP clients/servers, such as `rpc.server.duration`, but gives their names with the dots replaced by underscores (`rpc_server_duration`). This is presumably because the Prometheus exporter performs such a renaming, and it is the default method for exposing internal telemetry. I believe it would be useful to explicitly document this behavior when using Prometheus on the page, as well as the original names of these metrics, for the benefit of users exporting internal telemetry in some other way.

**Comment by svrnm** [comment]
@open-telemetry/collector-approvers ptal
