### ISSUE TITLE
State of Profiling blog post

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/opentelemetry.io#5477]
Following the release of the Profiling signal in the OpenTelemetry Collector, the Profiling SIG wishes to write a blog post showcasing the progress of the profiles signal since we announced the beginning of that work back in March.

The writing of this post has happened in a Google Doc with various folks from the Profiling SIG.
https://docs.google.com/document/d/1RgsP_XJOhgB4e19RqXc_yN0gJ-1o9ZB_uqQRbjotVCU/edit

**Comment by svrnm** [comment]
happy to have that blog post 👍

**Comment by dmathieu** [comment]
The post has now been published.
