### ISSUE TITLE
Remove mention of internal telemetry that does not exist

### ISSUE THREAD

**Issue by jade-guiton-dd** [open-telemetry/opentelemetry.io#5483]
**What needs to be changed?**

The ["Values observable with internal metrics" section in the Collector "Internal telemetry" page](https://opentelemetry.io/docs/collector/internal-telemetry/#values-observable-with-internal-metrics) (`docs/collector/internal-telemetry`) mentions a number of metrics which (as far as I know) are not actually implemented, or listed in the detailed table of metrics below. To list some: data reception / export rates in bytes, data drop rates caused by throttling / invalid data, incoming connection rate, queue size in bytes, end-to-end and per-component latency, etc.

It looks like this list was taken from an old "Observability Vision" document [added to the core repo years ago](https://github.com/open-telemetry/opentelemetry-collector/pull/188), and the wording somehow changed from "these values need to be observable" to "these values *are* observable" along the way. (Thank you to @mx-psi for finding this PR.)

The simplest solution would be to delete the section, and let people rely on the table below it. A more involved solution would be to rewrite the section to only include things that actually ended up being implemented. We may want to keep the current contents around somewhere to serve as a roadmap for future new internal metrics.

**Comment by svrnm** [comment]
@open-telemetry/collector-approvers ptal

**Comment by jpkrohling** [comment]
@jade-guiton-dd, you probably have the best context right now about what we _actually_ have there available at the moment. Would you be open to adjusting this page?

**Comment by jade-guiton-dd** [comment]
Sure, I can do the change.
