### ISSUE TITLE
[fr] missing docsy i18n config for page feedback 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry.io#5500]
**What happened?**

Clicked on https://opentelemetry.io/fr/docs/what-is-opentelemetry/ and saw the following at the bottom:

![Screenshot 2024-10-29 at 7 41 22 AM](https://github.com/user-attachments/assets/3ca5330a-288a-48b9-8566-4b4ffedb0d91)

**What did you expect would happen?**

See the page full translated.

**Comment by codeboten** [comment]
Submitted a fix for this in docsly https://github.com/google/docsy/pull/2105

**Comment by pierrehilbert** [comment]
Just added a small suggestion to your PR.
