### ISSUE TITLE
Page feedback

### ISSUE THREAD

**Issue by DorinC2k** [open-telemetry/opentelemetry.io#5508]
Suggested improvements for page: https://opentelemetry.io/docs/demo/development/#java

add link to the demo repo

**Comment by tiffany76** [comment]
Thanks for the suggestion, @DorinC2k. It's a good one. Would you like to put up a PR to add the URL to intro text on the page?

**Comment by svrnm** [comment]
cc @open-telemetry/demo-approvers

**Comment by puckpuck** [comment]
We should have a link to the GitHub repo at the top of the Demo -> Development page
