### ISSUE TITLE
Document how the docs update GitHub action works for releasing from language repos

### ISSUE THREAD

**Issue by shelbyspees** [open-telemetry/opentelemetry.io#554]
It requires a personal access token from @austinlparker at this point in time.

Here's how the Java SDK repo has it set up:
https://github.com/open-telemetry/opentelemetry-java/blob/main/.github/workflows/docs-update.yml#L8-L35

**Comment by cartermp** [comment]
I think we can probably close this out - Go and Ruby are the remaining languages with submodules and we're likely to move those in this repo like the other languages. It's also relatively easy to update the submodule now and shouldn't require any specific person's credentials.
