### ISSUE TITLE
Page feedback

### ISSUE THREAD

**Issue by mccallua** [open-telemetry/opentelemetry.io#5579]
Suggested improvements for page: [ADD PAGE-URL-HERE](https://opentelemetry.io/docs/languages/go/getting-started/)

I have a client program that calls the RollDice sample service.  
How do I initialise tracing in the client program so that when the call to RollDice fails, the client program can log a message "error calling RollDice, check traceID xxxx"

I imagine I need to create a new root span / trace in the client program, then use that to call RollDice, but I can't see anyway to create a new root span.  Every time I call AddSpan to an empty context, the traceID and spanID are empty strings.

**Comment by theletterf** [comment]
Hi @mccallua! Could you state which page you sent the feedback from? Thanks!
