### ISSUE TITLE
Blog post for OpenTelemetry Generative AI updates

### ISSUE THREAD

**Issue by drewby** [open-telemetry/opentelemetry.io#5581]
Title: OpenTelemetry for Generative AI

This blog post introduces enhancements to OpenTelemetry specifically tailored for generative AI technologies, focusing on the development of Semantic Conventions and the Python Instrumentation Library.

Samples are in Python

SIG: [GenAI Observability](https://github.com/open-telemetry/community/blob/main/projects/gen-ai.md)

Sponsors: @tedsuo @lmolkova

**Comment by svrnm** [comment]
Thanks @drewby! Happy to have this PR!:-)
