### ISSUE TITLE
PST Timezone is not acceptable

### ISSUE THREAD

**Issue by vberegov** [open-telemetry/opentelemetry.io#5640]
Hi team, 
I have very simple configuration for syslog interception with location value. I need to change it to PST - however the value is not acceptable. (not: EST works fine)
Version : otelcol-contrib version 0.114.0

receivers:
 syslog:
    udp:
      listen_address: "0.0.0.0:55552"
    protocol: rfc3164
    location: PST

Error:
Error: failed to build pipelines: failed to create "syslog" receiver for data type "logs": failed to resolve syslog config: failed to load location PST: unknown time zone PST
2024/11/19 20:13:53 collector server run finished with error: failed to build pipelines: failed to create "syslog" receiver for data type "logs": failed to resolve syslog config: failed to load location pst: unknown time zone PST

Any ideas?

**Comment by vberegov** [comment]
Nope, try all the options listed - PT/PDT/PST
I cannot get to this workspace ... what is it name?

**Comment by tiffany76** [comment]
> I cannot get to this workspace ... what is it name?

It's the CNCF OpenTelemetry Slack. You can [request an invitation](https://communityinviter.com/apps/cloud-native/cncf).

**Comment by tiffany76** [comment]
Also, based on the example given in the docs, maybe you could try `America/Los_Angeles`.

**Comment by vberegov** [comment]
That worked!!!!! Very strange - UTC and EST supported, while PST not :)
Thanks anyway

**Comment by tiffany76** [comment]
Glad it worked. I'll close this issue now.
