### ISSUE TITLE
Adopters page: some links have empty link text

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#5643]
See https://opentelemetry.io/ecosystem/adopters/, e.g.:

> <img width="585" alt="image" src="https://github.com/user-attachments/assets/7db9404a-358b-4c18-ad04-a1925c9f5047">

Note that the "Learn more" link text for `Bureau.id` is empty. By chance we're generating an external link icon, otherwise, the link wouldn't appear at all.

**Comment by svrnm** [comment]
They miss a referenceTitle in https://github.com/open-telemetry/opentelemetry.io/blob/main/data/ecosystem/adopters.yaml

**Comment by Yuvraj-Achrekar** [comment]
Can i attempt this ?

**Comment by svrnm** [comment]
> Can i attempt this ?

sure!
