### ISSUE TITLE
Instrumentation

### ISSUE THREAD

**Issue by dprotaso** [open-telemetry/opentelemetry.io#566]
This page has references to a `label` package which seems to be removed

**Comment by theletterf** [comment]
@dprotaso Could you add a link to the page? And, did you check if the package is effectively gone?

**Comment by dprotaso** [comment]
I believe it was here: https://opentelemetry.io/docs/go/instrumentation/ but I think it was fixed.


Note I created this issue by clicking 'Create documentation issue` which opens up the link
https://github.com/open-telemetry/opentelemetry.io/issues/new?title=Instrumentation

It's probably worth adding some additional details or body to that url so it links to the page version & url.
