### ISSUE TITLE
[Page feedback]: Add instructions to end-user Slack page on how to join CNCF Slack

### ISSUE THREAD

**Issue by jleonarddev** [open-telemetry/opentelemetry.io#5665]
### URL

https://opentelemetry.io/community/end-user/slack-channel/

### Description

Not able to join the slack channels. No instructions on how to gain access.

**Comment by tiffany76** [comment]
Thanks for reporting this @jleonarddev. We will update that page to include instructions on joining CNCF Slack.

In the meantime, you can visit https://communityinviter.com/apps/cloud-native/cncf to request an invitation.

**Comment by svrnm** [comment]
cc @open-telemetry/sig-end-user-approvers

**Comment by jleonarddev** [comment]
Thanks, @tiffany76. That was the piece I was missing.

**Comment by reese-lee** [comment]
Thank you for the feedback @jleonarddev, and thank you for the heads up on this @svrnm! I submitted [this PR](https://github.com/open-telemetry/opentelemetry.io/pull/5671) to clarify instructions.
