### ISSUE TITLE
[Page feedback]: Divergence on Metrics Gauge definitions  

### ISSUE THREAD

**Issue by vitorvasc** [open-telemetry/opentelemetry.io#5669]
**What needs to be changed?**

Hi there! While contributing with the translation of the documents, I found a divergence on the English version of the Metrics Instruments definitions on the following pages:

* [Concepts -> Signals -> Metrics -> Metric Instruments](https://opentelemetry.io/docs/concepts/signals/metrics/#metric-instruments)
   * Here, when listing the instrument kind, we say that Gauge are always asynchronous.  
* https://opentelemetry.io/docs/languages/go/instrumentation/#metrics
   * When listing the same kind of instrument on the Metrics section, we split Gauge into both synchronous and asynchronous option. 

**What is the name + path of the page that needs changed?** 

docs/concepts/signals/metrics/#metric-instruments

**Additional context**: anything else you can think about that would be helpful.

By checking the [Specs of the Metrics API](https://opentelemetry.io/docs/specs/otel/metrics/api/#gauge), we can see Gauge and Asynchronous Gauge, so, I assume that the first page, the Concepts one, doesn't have the most recent version of these definitions.

**Comment by svrnm** [comment]
good finding, @vitorvasc! Would you be interested in fixing that?

**Comment by vitorvasc** [comment]
Thanks, @svrnm! Sorry for the delay here, been a busy week.

Sure! I'll create a new PR fixing this and will let you know as soon as possible. 

cc @maryliag what we've been talking on Slack :)

**Comment by maryliag** [comment]
discussed with Vitor offline and I took over. PR for all 3 existing languages of this page are now open

**Comment by svrnm** [comment]
thank you @vitorvasc for reporting and @maryliag for fixing it (across 3 languages:-))
