### ISSUE TITLE
Search results showing up blank

### ISSUE THREAD

**Issue by tiffany76** [open-telemetry/opentelemetry.io#5673]
**What happened?** When searching for `prometheus` while looking into #5670, I found that every search returns a blank screen. I also tried searching for `telemetry` and `profiles`. The result was still a blank page. 

**What did you expect would happen?** Was hoping to see results since those terms certainly appear on the website.

**What is the name + path of the page where you encountered the issue?** The search box in the website header. Here are the URLs of the results pages: 
https://opentelemetry.io/search/?q=prometheus
https://opentelemetry.io/search/?q=telemetry
https://opentelemetry.io/search/?q=profiles

**What browser, OS, and platform were you using when you encountered the
problem?** macOS Sonoma 14.7.1, Chrome Version 131.0.6778.86 (Official Build) (arm64)

<img width="1175" alt="Screenshot 2024-11-22 at 5 30 45 PM" src="https://github.com/user-attachments/assets/aecafed5-09a4-4e85-b525-b46df9c5ba6b">

**Comment by chalin** [comment]
Thanks for noticing and reporting the issue. I had noticed that search stopped working for the Docsy site too yesterday: https://github.com/google/docsy/issues/2134. Let me investigate.

**Comment by chalin** [comment]
Ah, search stopped working after we merged:

- #5642

**Comment by chalin** [comment]
It's a Hugo 0.139.0 issue:

- https://github.com/gohugoio/hugo/issues/13082
