### ISSUE TITLE
Add docs for updated collector internal telemetry features

### ISSUE THREAD

**Issue by mowies** [open-telemetry/opentelemetry.io#5680]
**Desired feature or idea**

[This PR](https://github.com/open-telemetry/opentelemetry-collector/pull/10544) added features to directly send collector internal telemetry logs to an external provider. That feature is not yet added to the docs on the [internal telemetry page](https://opentelemetry.io/docs/collector/internal-telemetry/).

**Comment by codeboten** [comment]
I've started on adding this
