### ISSUE TITLE
Include examples on how to set up endpoints in security best practices doc

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry.io#5706]
**What needs to be changed?** Add open-telemetry/opentelemetry-collector/pull/10562 changes to opentelemetry.io

**What is the name + path of the page that needs changed?**  /docs/security/config-best-practices/#protect-against-denial-of-service-attacks

@tiffany76 Do you think this makes sense to copy as is?

**Comment by tiffany76** [comment]
Hey @mx-psi! We do link to those examples in the README from the DOS section of the docs:

<img width="757" alt="Screenshot 2024-12-02 at 5 15 53 PM" src="https://github.com/user-attachments/assets/54fa6bf2-3c80-408d-8a6c-2ea9767a6c19">


Do you think it's better if they live on the website? If so, I'll work on porting them into that section. It will probably be a copy-paste job with a few edits to make everything fit.

**Comment by mx-psi** [comment]
@tiffany76 Since the examples are focused on end users and not on Collector developers I think it makes sense to move them over to opentelemetry.io. Do you feel like they should remain on Github?

**Comment by tiffany76** [comment]
Nope, I agree. If the examples are for end users, they should live on .io. I'll put up a PR this week. Thanks!
