### ISSUE TITLE
[Page feedback]: otel collector cannot be reached

### ISSUE THREAD

**Issue by tkkubacki** [open-telemetry/opentelemetry.io#5708]
### URL

https://opentelemetry.io/docs/languages/python/getting-started/

### Description

The instructions says to to start the otel collector using command:
```
docker run -p 4317:4317 \
    -v /tmp/otel-collector-config.yaml:/etc/otel-collector-config.yaml \
    otel/opentelemetry-collector:latest \
    --config=/etc/otel-collector-config.yaml
```
Then it claims the app will be able to send logs to it (in: https://opentelemetry.io/docs/languages/python/getting-started/#modify-the-command-to-export-spans-and-metrics-via-otlp):

> By default, opentelemetry-instrument exports traces and metrics over OTLP/gRPC and will send them to localhost:4317, which is what the collector is listening on.

It seems the logs do not reach localhost:4317 because it is a local address in the container running the app. For this to work (while using localhost) the collector should be started with '--network' option like:
`docker run --network container:app_container -v ... otel/opentelemetry-collector:latest`
Where the `app_container` is the name of the container with the (previously) started application.

**Comment by mx-psi** [comment]
The example above: https://opentelemetry.io/docs/languages/python/getting-started/#configure-and-run-a-local-collector has the endpoint set to `0.0.0.0:4317`, so this should not be a problem, right?

**Comment by tkkubacki** [comment]
You are right. It is my mistake - I was trying to extend the example to run into container and confused my work with the example (which runs in console). I am sorry for taking up you time.

**Comment by mx-psi** [comment]
No problem! I am closing this as wontfix then, but if you run into any trouble feel free to comment again :)
