### ISSUE TITLE
Java Context API example uses the wrong context

### ISSUE THREAD

**Issue by teofr** [open-telemetry/opentelemetry.io#5753]
**What needs to be changed?**
The Java Context API site has an example where the current context instead of the local one should be used.

**What is the name + path of the page that needs changed?** 
`content/en/docs/languages/java/api.md`

**Additional context**: 
Tiny fix, just not worth signing a CLA. See https://github.com/open-telemetry/opentelemetry.io/pull/5752

**Comment by jack-berg** [comment]
Thanks for the find. Code for the excerpt lives over here: https://github.com/open-telemetry/opentelemetry-java-examples/blob/main/doc-snippets/api/src/main/java/otel/ContextUsage.java#L39

I'll get to this soon enough, but just sharing in case anybody beats me to it.
