### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by c2main** [open-telemetry/opentelemetry.io#5774]
In https://opentelemetry.io/docs/concepts/signals/metrics/:

> **Gauge**: Measures a current value at the time it is read. An example would be the fuel gauge in a vehicle. Gauges are **asynchronous**.
> **Asynchronous Gauge**: Same as the Gauge, but is collected once for each export. Could be used if you don’t have access to the continuous changes, but only to the aggregated value.

Are Gauge asynchronous or synchronous ? It looks like it's a typo ?

**Comment by svrnm** [comment]
It looks like a typo yes, would you be interested in raising a PR for it?

**Comment by c2main** [comment]
> It looks like a typo yes, would you be interested in raising a PR for it?

sure, just did.
