### ISSUE TITLE
New Blog Post: Insights from the OpenTelemetry Docs Usability Survey

### ISSUE THREAD

**Issue by tiffany76** [open-telemetry/opentelemetry.io#5793]
This blog post will summarize and visualize [the results](https://docs.google.com/spreadsheets/d/1kpJQYiEGtpZorICbl-QfYL3mKfeoRLiUywvKcV8fcNA/edit?resourcekey=&gid=439437959#gid=439437959) from the OTel docs usability survey conducted by the End-User SIG. 

Related SIGs: Communications, End-User

Sponsor: @svrnm @chalin

**Comment by svrnm** [comment]
🎉
