### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by zroslaw** [open-telemetry/opentelemetry.io#5795]
the guide is an absolutely shitty thing.
doesn't help start using the tool at all; it just causes confusion and raises a bunch of unanswered questions.

**Comment by svrnm** [comment]
hey @zroslaw

thanks for your feedback. From your issue I can not figure out about which getting started guide you are talking, is it for a specific language, the collector or any other component? It seems to raise strong anger with you, so I am curious to hear, what unanswered questions you have.

**Comment by cartermp** [comment]
Closing issue
