### ISSUE TITLE
Migrate the OpenTracing Registry to OpenTelemetry

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#59]
We should move the registry from OpenTracing to this site, and enhance it if needed.

**Comment by rajibmitra** [comment]
I am interested to contribute to this issue @austinlparker

**Comment by mayankshah1607** [comment]
Hi @austinlparker 
I noticed that this project is under the CommunityBridge program by CNCF. I would like to contribute by working on this project if no one already is :)

**Comment by SergeyKanzhelev** [comment]
@rajibmitra @mayankshah1607 thank you for your interest! CNCF will pick subset of the project sponsored for Community Bridge program. This is proposed project, not approved. In any way I will be happy to guide either or both of you on this.

As noted in community bridge submission, we want to start with porting this registry: https://opentracing.io/registry/ to this site.  You can find sources for it here: https://github.com/opentracing/opentracing.io Looking at how it's implemented in OpenTracing repo and making sure you can build this repository is a good start on this issue

**Comment by rajibmitra** [comment]
okay , I am on it @SergeyKanzhelev  thanks.

**Comment by kdanW** [comment]
Hi. Is recruiting mentees for this project finish?If not I would like to work on this

**Comment by austinlparker** [comment]
Since this project wasn't accepted for CB, I'll claim it.
