### ISSUE TITLE
otel.SetMeterProvider(pusher.MeterProvider()) no longer works

### ISSUE THREAD

**Issue by automano** [open-telemetry/opentelemetry.io#616]
otel.SetMeterProvider(pusher.MeterProvider()) no longer works   

for golang demo

**Comment by automano** [comment]
![image](https://user-images.githubusercontent.com/17286982/123726577-d09ae800-d8c2-11eb-92ae-334f4e16e410.png)
Documentation need to be modified.

**Comment by aarongreenlee** [comment]
I found this issue as well. I think you can now import `go.opentelemetry.io/otel/metric/global` and then use global.SetMeterProvider(...)`. I'm learning but the context of a "global" package makes sense. Seems like the API shifted.

**Comment by aarongreenlee** [comment]
Posted what I hope is a fix here https://github.com/open-telemetry/opentelemetry.io/pull/625

**Comment by automano** [comment]
Thanks so much. It works now.
