### ISSUE TITLE
Too much padding on Sidebar

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry.io#62]
Just feels a little pushed in.
For example, here with sidebar: https://opentelemetry.io/docs/js/metrics/
Versus here with no sidebar: https://opentelemetry.io/get-involved/

* Sidebar feels to far from the left edge
* Content is too far from the sidebar.
* Content registration is different depending on whether the sidebar is present. It "jumps" to the left when the sidebar appears.

**Comment by austinlparker** [comment]
I'm going to adjust it so that the content is pulled in towards the sidebar more but leave the left edge of the sidebar where it is (it's consistent with every other page). this should help, I think - take a look at the PR preview when its ready.
