### ISSUE TITLE
Adding Apache Camel

### ISSUE THREAD

**Issue by davsclaus** [open-telemetry/opentelemetry.io#620]
Desired feature or idea.

What are the steps, or process, for adding Apache Camel to the list of projects mentioned under "Integrates With Popular Frameworks and Libraries" and "Drop-In Instrumentation"?

Apache Camel has been integrated with open telemetry since Camel 3.5 that was released end of August 2020
https://camel.apache.org/components/latest/others/opentelemetry.html

**Comment by davsclaus** [comment]
Similar to #618

**Comment by cartermp** [comment]
Somewhere along the line Camel got added to the registry! https://opentelemetry.io/registry/?s=camel&component=&language=

I'll close as this is complete.
