### ISSUE TITLE
Getting Started:  library otel doesn’t have function Meter()

### ISSUE THREAD

**Issue by zzxwill** [open-telemetry/opentelemetry.io#646]
In this section https://opentelemetry.io/docs/go/getting-started/#creating-metric-instruments, it shows library `otel` doesn’t have function `Meter()`.

```
// Create metrics instruments
	lemonsKey := attribute.Key("ex.com/lemons")
	anotherKey := attribute.Key("ex.com/another")

	commonAttributes := []attribute.KeyValue{lemonsKey.Int(10), attribute.String("A", "1"), attribute.String("B", "2"), attribute.String("C", "3")}

	meter := otel.Meter("ex.com/basic")

	observerCallback := func(_ context.Context, result metric.Float64ObserverResult) {
		result.Observe(1, commonAttributes...)
	}
	_ = metric.Must(meter).NewFloat64ValueObserver("ex.com.one", observerCallback,
		metric.WithDescription("A ValueObserver set to 1.0"),
	)

	valueRecorder := metric.Must(meter).NewFloat64ValueRecorder("ex.com.two")

	boundRecorder := valueRecorder.Bind(commonAttributes...)
	defer boundRecorder.Unbind()
```

**Comment by zzxwill** [comment]
It seems we should create a meter by `meter := pusher.MeterProvider().Meter("example")`.

**Comment by chalin** [comment]
I believe that this is reporting the same issue as https://github.com/open-telemetry/opentelemetry-go/issues/2087? It has been fixed (https://github.com/open-telemetry/opentelemetry-go/pull/2093), but the updated docs haven't been ported.

I'm going to mark this as a duplicate, but leave it open until the docs are updated in this repo.

/cc @Aneurysm9 @lastchiliarch

**Comment by chalin** [comment]
Oh, I'm going to close this in favor of #644, which was opened earlier.
