### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by irl-segfault** [open-telemetry/opentelemetry.io#654]
https://opentelemetry.io/docs/go/getting-started/

states you should run

```
go get go.opentelemetry.io/otel@v1.0.0-RC1 go.opentelemetry.io/otel/sdk@v1.0.0-RC1 go.opentelemetry.io/otel/exporters/stdout/stdouttrace@v1.0.0-RC1 go.opentelemetry.io/otel/trace@v1.0.0-RC1
```

This produces the error ```go get go.opentelemetry.io/otel@v1.0.0-RC1 go.opentelemetry.io/otel/sdk@v1.0.0-RC1 go.opentelemetry.io/otel/exporters/stdout/stdouttrace@v1.0.0-RC1 go.opentelemetry.io/otel/trace@v1.0.0-RC1

go get: module go.opentelemetry.io/otel@v1.0.0-RC1 found, but does not contain package go.opentelemetry.io/otel/sdk
go get: module go.opentelemetry.io/otel@v1.0.0-RC1 found, but does not contain package go.opentelemetry.io/otel/exporters/stdout/stdouttrace```

**Comment by chalin** [comment]
Dup of #653. Closing.
