### ISSUE TITLE
collector Getting Started examples refer to non-existent paths in opentelemetry-collector

### ISSUE THREAD

**Issue by tmancill** [open-telemetry/opentelemetry.io#662]
This issue refers to https://opentelemetry.io/docs/collector/getting-started/ at commit https://github.com/open-telemetry/opentelemetry.io/commit/e24d9b77fb6e3391078fa6a0edec75fc82a89ec1 (according to the page footer) and the open-telemetry/opentelemetry-collector retrieved at 632ed32b5f8515da8da377d8ae34215b30301c24.

The issue is that getting started guide refers to non-existent paths.  If the docs assume a specific revision or tag of opentelemetry-collector, it would be helpful to include that in the `git clone` example statement.

### Docker example

In the [Docker](https://opentelemetry.io/docs/collector/getting-started/#docker) `collector/getting-started/#docker` example, the file `main.go` does not exist in opentelemetry-collector/examples.

```
$ git clone git@github.com:open-telemetry/opentelemetry-collector.git; \
    cd opentelemetry-collector/examples; \
    go build main.go; ./main & pid1="$!";
             ^^^^^^

$ find examples -name main.go
examples/demo/server/main.go
examples/demo/client/main.go
```

### Local example

In the [Local](https://opentelemetry.io/docs/collector/getting-started/#local) `collector/getting-started/#local` example, the example command refers to ` examples/demo/app/main.go`, but there is no `./app/` subdirectory in the `examples/demo` directory:

```
git clone git@github.com:open-telemetry/opentelemetry-collector.git; \
    cd opentelemetry-collector; make install-tools; make otelcol; \
    go build examples/demo/app/main.go; ./main & pid1="$!"; \
                           ^^^
$ find examples/demo -type d
examples/demo
examples/demo/server
examples/demo/client
```

**context**

```
➜  opentelemetry-collector git:(main) git remote -v
origin	git@github.com:open-telemetry/opentelemetry-collector.git (fetch)
origin	git@github.com:open-telemetry/opentelemetry-collector.git (push)

➜  opentelemetry-collector git:(main) git describe
cmd/issuegenerator/v0.31.0-42-g632ed32b
```

**Comment by austinlparker** [comment]
The canonical copy of these docs are located at https://github.com/open-telemetry/opentelemetry-collector/tree/main/website_docs, please open this issue in the appropriate repository. Thanks!
