### ISSUE TITLE
Don't link to raw.github.com images and resources, deploy them with the site

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#663]
For example see, https://github.com/open-telemetry/opentelemetry.io/blame/main/content/en/docs/_index.md#L36:

```html
<img src="https://raw.github.com/open-telemetry/opentelemetry.io/main/iconography/Reference_Architecture.svg" alt="Implementation of the OpenTelemetry Reference Architecture "></img>
```

---

Edit: I'm generalizing this to don't serve resources from GH. Another example is the `iconography.zip`.

Serve all of the following resources from the production server, not GH:

- [x] #2367
- [x] #2369
- [x] #2370
- [x] #2378
- [ ] Go docs:
  - [x] https://github.com/open-telemetry/opentelemetry-go/pull/3758
  - [ ] #2379
  - [ ] Drop corresponding htmltest ignore rule - #2379

Related:

- #1052
- #2373

**Comment by svrnm** [comment]
it looks like the whole issue comes down to images being located in `iconography`. 

@chalin, @cartermp: could we just move those images to static/ or any other folder that will be published or are we going to break things?

**Comment by chalin** [comment]
Once the Go docs have been updated and brought into this repo, we can close this issue.
