### ISSUE TITLE
Reinstate the authentication configuration for collector

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry.io#673]
The PR #649 removed the authentication configuration for the collector. Please, reinstate that.

cc @flands, @austinlparker

**Comment by austinlparker** [comment]
If it was removed, that's because it was removed in the canonical copy on the collector documentation, so it needs to be re-added there.

**Comment by jpkrohling** [comment]
Is this something new? Would you mind pointing me to the right place to add?

**Comment by austinlparker** [comment]
Been this way since May - https://github.com/open-telemetry/opentelemetry-collector/pull/2839

You update the docs in the collector repo then run an action to merge them over here. I'll be talking about some changes to this process we're going to introduce during today's maintainer meeting as well.

**Comment by jpkrohling** [comment]
Alright, I'll get it there. For reference, this is the PR that added the auth doc: https://github.com/open-telemetry/opentelemetry.io/pull/605

**Comment by chalin** [comment]
@jpkrohling - thanks for alerting us to the fact that #605 was mistakenly undone/overwritten by #649. As I mention in https://github.com/open-telemetry/opentelemetry-collector/pull/4041#issuecomment-920018575, we're in the process of **migrating the collector docs back into the website repo** (#731) so as to avoid such problems in the future.

Would you mind closing https://github.com/open-telemetry/opentelemetry-collector/pull/4041?

Also let me know whether you'd like to resubmit the equivalent of #605 yourself or whether you'd like me to do so.

**Comment by jpkrohling** [comment]
If it's easy for you to reinstate it, go for it! Otherwise, I can do it as well.

**Comment by chalin** [comment]
@jpkrohling - PR #734 adds the pages back.
