### ISSUE TITLE
Build should be reproducible: avoid build-time content generation

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#693]
Another way to say this is that the site build command should (to the extent practical) be idempotent. If I build the site today, touch none of the files, and build again in, say, 6 months, then the generated files should be the same.

This currently isn't the case, in particular, because [scripts/fetchMilestones.js](https://github.com/open-telemetry/opentelemetry.io/blob/main/scripts/fetchMilestones.js) is used to fetch data dynamically at build time. Instead we should run that script and commit the resulting file. At build time we can, if needed, check that the file content is fresh, and if it isn't then the build should fail.

Other solutions are possible.

**Comment by austinlparker** [comment]
FWIW we could probably deprecate the `fetchMilestones.js` script entirely, especially as we move the 'latest release' info to the docs pages.

**Comment by chalin** [comment]
Closed by #931
