### ISSUE TITLE
Blog not updating on the homepage

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry.io#70]
Why, tho?

**Comment by lucperkins** [comment]
The site build doesn’t have any awareness of the Medium blog, so the site needs to be rebuilt manually when blog posts are published.

**Comment by lucperkins** [comment]
@tedsuo It looks like the Zap that I created wasn't set up to clear the build cache. I've changed that. This *should* work for now but if issues persist feel free to re-open.
