### ISSUE TITLE
Update Elastic Support for Native OTLP

### ISSUE THREAD

**Issue by riferrei** [open-telemetry/opentelemetry.io#705]
**What happened?**

Currently, the vendor's page on the website shows Elastic as not supporting natively OTLP. This is no longer true as it has been a while since this support was added.

![image](https://user-images.githubusercontent.com/35476/131894909-ba2c01f1-a075-438e-8ad6-42135db670b1.png)

**What did you expect would happen?**

For the entry related to Elastic, change from "No" to "Yes" the question about Native OTLP.

**What is the name + path of the page where you encountered the issue?**

[https://opentelemetry.io/vendors](https://opentelemetry.io/vendors)

➡️ "Vendors Supporting OpenTelemetry"

**What browser, OS, and platform were you using when you encountered the problem?**
Please include the browser version if you know it as well.

N/A

**Comment by cyrille-leclerc** [comment]
See proposed fix https://github.com/open-telemetry/opentelemetry.io/pull/706

**Comment by austinlparker** [comment]
Closed by #706
