### ISSUE TITLE
OTEL schema files should be in a single repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#709]
OTEL schema files are duplicated across this repo and [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification). Here's some more context for this issue:

- https://github.com/open-telemetry/opentelemetry.io/pull/695#discussion_r703596784:
  > ... is there a problem if the content of these **two directories drift apart**?
  > 
  > * https://github.com/open-telemetry/opentelemetry.io/tree/main/static/schemas
  > * https://github.com/open-telemetry/opentelemetry-specification/tree/main/schemas
  > <br>
  > Should 1.6.0 be deleted from `opentelemetry-specification/schemas` too, "as if it never happened"?
- https://github.com/open-telemetry/opentelemetry.io/pull/695#discussion_r703677865
  > Good catch. Yes, it should be deleted.
  > 
  > The content of the directories should be in sync and I plan to add an action that syncs the content automatically.

The **schema files** should **reside in a single repo** (probably **[opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification)**). File copying across repos leads problems like the above, as well as those mentioned in #661, even if there is an action to sync (one way):

> **Disadvantages** of _file mirroring and copying_:
> 
> * We loose true edit/blame history
> * There's the risk of edits being done in the wrong place (since files are present in two repos)
> * There's potential confusion of where to open issues (again, since files are present in two repos)

In this case, I'd like to suggest bringing `opentelemetry-specification/schemas` into this repo via a submodule.

**Comment by austinlparker** [comment]
Yeah, I concur that this should be a submodule. Could we continue to have push-button automation from the spec side in order to do the submodule update if that's how they're doing it now?
