### ISSUE TITLE
Data Sources should include baggage signals

### ISSUE THREAD

**Issue by GaryPWhite** [open-telemetry/opentelemetry.io#711]
Noticed that [the data sources page](https://opentelemetry.io/docs/concepts/data-sources/) doesn't yet include notes about [Baggage Signals](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#baggage-signal). Should be trivial to translate the gist of the content -- I might come back and write it if nobody takes the issue :)

**Comment by austinlparker** [comment]
Feel free to pick this up if no one else does!

**Comment by GaryPWhite** [comment]
alright, i'm on it!
