### ISSUE TITLE
Glossary contains many "external" links to https://opentelemetry.io

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#713]
The [Glossary](https://opentelemetry.io/docs/concepts/glossary/) contains link references to site-local pages that are written as external links to https://opentelemetry.io. These should be change to be site-local references.

This should be fixed in all pages -- I haven't checked pages other than the glossary.

**Comment by pizzaz93** [comment]
I found a couple matching that format:

- https://github.com/open-telemetry/opentelemetry.io/blob/e8b6cb668d5936d5923cbf8b4287e9c19cd77e33/layouts/shortcodes/spec_status.html
- https://github.com/open-telemetry/opentelemetry.io/blob/3a276af6349347738d653348e3b754cd2c1121f3/content/en/docs/instrumentation/js/api/tracing.md
- https://github.com/open-telemetry/opentelemetry.io/blob/9ea83542eb0d8da1961a66dd094089940f7e7e00/content/en/docs/reference/specification/_index.md
- https://github.com/open-telemetry/opentelemetry.io/blob/ed16002fd3e4916385413323198a7c19071bd605/content/en/docs/instrumentation/java/getting-started.md
- https://github.com/open-telemetry/opentelemetry.io/blob/96fa17417417ee8d37c5932f930983c405d8fed6/content/en/blog/2022/apisix.md

There are additional links in this [search](https://github.com/open-telemetry/opentelemetry.io/search?p=1&q=opentelemetry.io) but they link to GitHub content so I'm unsure if they would need to be reformatted as well.

**Comment by chalin** [comment]
- Thanks, I'll fix those in my next PR.
- Glossary links were actually fixed in #924. Closing this issue.
- Related: #922

**Comment by chalin** [comment]
> ... I'll fix those in my next PR.

- See, #1282
