### ISSUE TITLE
docs: broken links in registry

### ISSUE THREAD

**Issue by bcdady** [open-telemetry/opentelemetry.io#717]
**What needs to be changed?**
Components that have moved from 'core' to 'contrib' need their `repo` links updated in the registry.

**What is the name + path of the page that needs changed?**
content/en/registry/collector-exporter-file.md
content/en/registry/collector-exporter-jaeger.md
content/en/registry/collector-exporter-kafka.md
content/en/registry/collector-exporter-logging.md
content/en/registry/collector-exporter-opencensus.md
...
(I can make the necessary edits and submit a PR.)

**Additional context**
See [my comment on Remove jaeger, zipkin, kafka, testbed components #3889](https://github.com/open-telemetry/opentelemetry-collector/pull/3889#issuecomment-915645871)

> It seems that (re)moving these "contrib" components has broken some of their links in the Registry.
> For example: viewing the list of available Receivers includes Kafka Collector Receiver, which ends up at a GitHub 404 page.
> It appears this has happened before. I can open an issue and submit a PR at opentelemetry.io
>

**Comment by chalin** [comment]
Thanks for the issue and the PR!

Closed by #717 -- if not, feel free to reopen the issue @bcdady.
