### ISSUE TITLE
Migrate opentelemetry-js website_docs back here as the single source of reference

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#720]
In https://github.com/open-telemetry/opentelemetry.io/issues/661#issuecomment-909484566, @dyladan wrote:

> Personally, I see huge advantages of having only one place where the documentation resides.

Ok then, @dyladan shall we move the JS [website_docs][] back into this repo? Doing so is consistent with the docs management scheme we'll be promoting moving forward. /cc @austinlparker 

---

- [x] Update the JS pages here to reflect the otel-js content of website_docs - #722 
- [x] Submit a PR over otel-js to delete `website_docs` - https://github.com/open-telemetry/opentelemetry-js/pull/2469
- [ ] Edit the JS index page to remove the custom (cascaded) fields like `github_repo` -- we'll be using the default values moving forward.

[website_docs]: https://github.com/open-telemetry/opentelemetry-js/tree/main/website_docs

**Comment by chalin** [comment]
@dyladan - if you agree, then #696 can be closed.

**Comment by dyladan** [comment]
@open-telemetry/javascript-maintainers I'm ok with this if you are

**Comment by austinlparker** [comment]
I'm good with this - in the future, docs will either live in here or be linked via submodule so that there's only one copy of them at any given time.
