### ISSUE TITLE
We want to defer the responsibility of fetcher type defining and locator definition/normalization to `fossa core`.

### ISSUE THREAD

**Issue by sirandysaunders** [open-telemetry/opentelemetry.io#727]
We want to defer the responsibility of fetcher type defining and locator definition/normalization to `fossa core`. 

If this change were in effect today, all cli uploaded builds would have a fetcher of `custom`. This means that fetcher definition in `.fossa.yml` should be removed.

Additionally, we should not attempt to normalize locators on uploads, rather we should supply the necessary fields to construct the locators for `fossa core` on each request

__Originally posted by @liftM in https://github.com/fossas/fossa-cli/issues/343__

**Comment by sirandysaunders** [comment]
Great work guys

**Comment by austinlparker** [comment]
Not sure what you meant to do but I don't think this issue belongs in this repository.
