### ISSUE TITLE
Ensure that all doc pages have a single source repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#730]
Quoting @austinlparker in https://github.com/open-telemetry/opentelemetry.io/issues/661#issuecomment-918336385:
> Per discussion during the last comms meeting, we'll be moving forward with the following -
> 
> 1. If maintainers wish to keep the canonical copy of their docs in their SIG repo, those _docs will be pulled into opentelemetry.io via **submodule**_.
> 2. Otherwise, their docs will be migrated back to the opentelemetry.io repository.
> 
> This ensures that there is only ever one copy of the documentation.
> 
> We _strongly_ recommend that maintainers choose to host the canonical copy of their documentation on opentelemetry.io repository in order to benefit from upcoming features such as internationalization and versioning.

Let's use this issue to record the **decisions made (1 or 2, per SIG)**, track the progress for each SIG.

In some cases, SIGs have docs that aren't under `website_docs` and/or aren't even in a format suitable for inclusion in the website. Let's refer to this as (0). Discussions & assessment should be made re. migration to markdown so that relevant content can be published on the website either via 1 or 2.

Note: for (2), take the opportunity to clean out any `markdown-link-check-*` markers.

---

- [x] **Collector**:
  - [x] (2) #731
  - (0) Consider migrating relevant parts of the Collector [docs][collector-docs] folder
- **C++**: (0) has a [docs][cpp-docs] folder containing `.md` files and some RST documentation (under `public`) published at [opentelemetry-cpp.readthedocs.io][].
- **.Net** (0) has a [docs][dotnet-docs] folder containing `.md` files.
- [x] **Erlang**: (2) - https://github.com/open-telemetry/opentelemetry-erlang/issues/280.
- **Go** (1) since #690
- [x] **Java**: (1) per @jkwatson - #739
- [x] **JS**:
  - [x] (2) per @dyladan (et al.?) - #720.
  - There is a [doc][js-docs] folder, but it is minimal.
- [x] **PHP**: (1) - https://github.com/open-telemetry/opentelemetry-php/issues/423, #661
- [x] **Python**:
  - (1) - https://github.com/open-telemetry/opentelemetry-python/issues/2116
  - (0) The [Python docs] (from [docs directory][python-docs-dir] published via Read the Docs) are **extensive**.
- [x] **Ruby**:
  - [x] ~(1) - #765~
  - [x] (2) - https://github.com/open-telemetry/opentelemetry-ruby/issues/1395
- [x] **Rust**: (2) - https://github.com/open-telemetry/opentelemetry-rust/issues/636, https://github.com/open-telemetry/opentelemetry-rust/pull/645
- [x] **Swift**: (2) - https://github.com/open-telemetry/opentelemetry-swift/issues/241, https://github.com/open-telemetry/opentelemetry-swift/pull/243

Note: This supersedes #472.

[collector-docs]: https://github.com/open-telemetry/opentelemetry-collector/tree/main/docs
[cpp-docs]: https://github.com/open-telemetry/opentelemetry-cpp/tree/main/docs
[dotnet-docs]: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs
[opentelemetry-cpp.readthedocs.io]: https://opentelemetry-cpp.readthedocs.io/en/latest/api/GettingStarted.html
[js-docs]: https://github.com/open-telemetry/opentelemetry-js/tree/main/doc
[python-docs-dir]: https://github.com/open-telemetry/opentelemetry-python/tree/main/docs
[Python docs]: https://opentelemetry-python.readthedocs.io/

**Comment by jkwatson** [comment]
> We strongly recommend that maintainers choose to host the canonical copy of their documentation on opentelemetry.io repository in order to benefit from upcoming features such as internationalization and versioning.

Who will be doing this work, though, to keep the docs up to date with i18n, etc? What is the plan for keeping the docs in sync as versions drift? I'd love to hand off the documentation duties to someone else and have it hosted in this repo, but in the past no one has done that work and things have rapidly gotten out of date. With I18N I can only imagine that will get much worse, since no person will be able to verify that things are being kept up to date.

**Comment by chalin** [comment]
Here's a concrete example of how things can go bad when we have doc pages in two repos, https://github.com/open-telemetry/opentelemetry-collector/pull/4041#issuecomment-919286572:

> Apparently, I opened a PR against the website repository ([open-telemetry/opentelemetry.io#605](https://github.com/open-telemetry/opentelemetry.io/pull/605)) instead of opening one here. At some point, an automated pull request ([open-telemetry/opentelemetry.io#649](https://github.com/open-telemetry/opentelemetry.io/pull/649)) between this repository here and the website repo got rid of the collector doc files I added.

**Comment by chalin** [comment]
> Who will be doing this work, though, to keep the docs up to date with i18n, etc? ...

@jkwatson - OTel maintainers would be responsible for keeping the **base-language docs** (in English) up-to-date. Other language versions are maintained by community members. That's how things work for [kubernetes.io], which has docs available in 13 languages. 

Base-language maintainers can help other community members in their task of translating doc pages into other languages by following certain conventions: use "simple/international" English (e.g., by avoiding certain idioms), line wrap markdown paragraphs (this helps diff tools create more precise diffs), etc.

Not all doc pages will be available in all languages, and that's ok. Each (natural) language community decides which pages are important enough to be worth maintaining versions of in their own native language.

[kubernetes.io]: https://kubernetes.io

**Comment by austinlparker** [comment]
Unpinning this for a minute.

**Comment by jkwatson** [comment]
When Java updates the website docs in their repo, are we supposed to notify someone that a docs update is needed here?

**Comment by chalin** [comment]
@jkwatson: you can either (A) submit the update yourself (instructions follow), or (B) [create an issue](https://github.com/open-telemetry/opentelemetry.io/issues/new) to notify us that the docs need updating, and which tag/commit we should use.

For (A): assuming you want to submit an update for the Java `website_docs` `@HEAD` then run the following command from a checked-out version of this repo:

```console
$ npm run submodule:update content-modules/opentelemetry-java
```

Submit the resulting update via a PR.

**Comment by chalin** [comment]
Reopening for Ruby:

- https://github.com/open-telemetry/opentelemetry-ruby/issues/1395

**Comment by chalin** [comment]
Done, now that Ruby docs have moved.
