### ISSUE TITLE
Sourcemaps aren't being generated

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#767]
When building or serving the site in development mode, sourcemaps aren't being generated. I see nothing in the site files that should prevent this. Using the same version of Hugo and key site files as etcd.io (in particular for `head-css.html`), we get different results -- no maps here, but they are generated for etcd.io.

For now I'm going to assume that it might have to do with an older version of docsy, or maybe some feature interaction with webpack.

**Comment by svrnm** [comment]
```
$ find . -name "*.map" | grep -v node_modules
./public/scss/main.css.map
```

There is a map file for CSS now, do we need some for JS as well or can this be closed?
