### ISSUE TITLE
Drop the banner announcing the 1.0 tracing specification?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#799]
Given that the spec is now at 1.7 (#798), it seems reasonable to drop the 1.0 announcement banner?
WDYT? @tigrannajaryan @austinlparker @tedsuo?

**Comment by tigrannajaryan** [comment]
It may be worth keeping for a while longer, since 1.0 Tracing GA was an important milestone. Perhaps we can replace it by 1.0 Metrics GA when it happens, hopefully soon.

@open-telemetry/governance-committee what do you think?

**Comment by yurishkuro** [comment]
I don't mind the banner, but perhaps it should say GA rather than 1.0.

Below the fold there is a more out of place note that should be changed:

> OpenTelemetry is in beta across several languages and is suitable for use. We anticipate general availability soon.

**Comment by lizthegrey** [comment]
agree, the latter thing is the more important thing to change

**Comment by chalin** [comment]
> Below the fold there is a more out of place note that should be changed:
> 
> > OpenTelemetry is in beta across several languages and is suitable for use. We anticipate general availability soon.

@yurishkuro @lizthegrey: what would you like it changed to, or should those two sentences simply be dropped?

**Comment by lizthegrey** [comment]
> > Below the fold there is a more out of place note that should be changed:
> > > OpenTelemetry is in beta across several languages and is suitable for use. We anticipate general availability soon.
> 
> @yurishkuro @lizthegrey: what would you like it changed to, or should those two sentences simply be dropped?

I'd say "OpenTelemetry is widely deployed, including at [...]" (pull list from ADOPTERS.MD)

**Comment by yurishkuro** [comment]
> pull list from ADOPTERS.MD

We should be careful about this, it creates unnecessary friction of who gets to be on the homepage. Just linking to ADOPTERS is ok, but I often see ADOPTERS list quickly growing stale.

**Comment by lizthegrey** [comment]
> > pull list from ADOPTERS.MD
> 
> We should be careful about this, it creates unnecessary friction of who gets to be on the homepage. Just linking to ADOPTERS is ok, but I often see ADOPTERS list quickly growing stale.

sure thing, how about saying "widely adopted" and link to ADOPTERS without naming specific names?

**Comment by chalin** [comment]
- FYI, proposed banner change for metrics RCs: #1376

**Comment by chalin** [comment]
Closed by #1376
