### ISSUE TITLE
Add 'examples' as a category into the registry

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#814]
As discussed during the SIG adding examples/tutorials to the registry seems like a good experiment: this would allow new-comers to OTel to explore different ways into getting started, also people creating those examples/tutorials can make them a little bit more visibile.

A requirement would be that those examples are vendor-agnostic.

**Comment by rquedas** [comment]
I agree with @chalin, having tutorials and examples within each SIG's website will make it easier for people to find them. 

I also believe there is a difference between example and tutorial. I would look at the [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) repo as a great source of examples, while a tutorial would be focused in guiding me through process of creating one of those examples.
