### ISSUE TITLE
Dotted arrow from OTel Collector Agent to Host is reversed

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry.io#847]
The reference architecture diagram on [the landing page of OpenTelemetry documentation](https://opentelemetry.io/docs/) has some arrows, and a couple of them should be reversed.

The orange dotted arrow from OTel Collector Agent to Host should be the one from Host to OTel Collector Agent.
<img src="https://raw.github.com/open-telemetry/opentelemetry.io/main/iconography/Reference_Architecture.svg" alt="the architecture diagram" title="the architecture diagram">

If these arrows are correct and as intended, still the arrows are confusing and I think we need an explanation of what "Host" is.

**Comment by cartermp** [comment]
This is now out of date I think, since we don't use this figure anymore on the site.

**Comment by jkowall** [comment]
If you want, I can ask Ella (the designer) to update the diagram, I like these. Please let me know.
