### ISSUE TITLE
Publish the specification via opentelemetry.io

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#852]
The spec is a core OTel resource, and as such it should be published through this repo. (#833)

- [x] Add spec pages to website
- [x] Ensure that repository links (like **Edit this page**) point to the canonical source (cf. #542)

**Comment by bhs** [comment]
@chalin Per your note elsewhere, I will raise this with the GC today.

**Comment by austinlparker** [comment]
As a first step, we should add a 'Specification' category to the left nav in `/docs` that links to the main GitHub repo for specs.

**Comment by reyang** [comment]
Couple things need to be clarified:
1. Do we only publish Stable version of specs, or we also publish Experimental specs? What to do if a spec status is Mixed?
2. Do we only publish the latest-stable version, or we publish ALL the stable versions?

**Comment by chalin** [comment]
Good questions.

I'd suggest _starting with_ the latest-stable version (no experimental).

**Comment by austinlparker** [comment]
Perhaps it should be under 'concepts'?

**Comment by chalin** [comment]
> Looking at the layout, I also suggest that the spec should not be listed so prominently in our documentation

Ok. Under the new IA (once it is defined via #770), I would imagine that it would make sense to have a **Reference** section, with the spec under that.

Until we have a new IA I can I can think of a these options:

1. Not show the Specification section in the sidenav.
2. Show the Specification in the sidenav but move it towards the end of the list.
3. Add a Referrence section now (even before we have the new IA) and place the spec there from the start.

Thoughts?

**Comment by austinlparker** [comment]
I like #3

**Comment by tedsuo** [comment]
Option 3 sounds good

**Comment by chalin** [comment]
@tedsuo @austinlparker et al - Done:

- I've implemented option 3, and
- Replaced the "Edit page" button by a "View page source"

PTAL https://deploy-preview-866--opentelemetry.netlify.app/docs/reference/specification/

**Comment by austinlparker** [comment]
Since we've addressed the issues raised here outside of automation (which would take a bit to solve in a generalized fashion), we'll commit to a less than 24 hour turnaround for updates when new spec releases are cut from notification. 

With that in mind, unless there are other blockers we'll be merging #866 next Tuesday.

**Comment by chalin** [comment]
Closed by #866
