### ISSUE TITLE
Website Wishlist!

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#87]
This is a thread to collect things that we'd like to see done to the website in a more 'big picture' sense.

**Comment by austinlparker** [comment]
It'd be nice to have the sidebar styling improved, and making it a bit easier to use.

**Comment by codeboten** [comment]
Would love to see a registry section similar to the opentracing one https://opentracing.io/registry/

**Comment by bhs** [comment]
I like @codeboten's idea, esp if it is built off of GitHub tags (in whole or in part)... that way there's no need to send a PR to a central repo.

I also like the idea of a firm and up-to-date maturity matrix across languages and the many/growing aspects of OTel (APIs, SDKs, auto-instrumentation, etc; and many of these "foreach language").

**Comment by mtwo** [comment]
Echoing @codeboten and @bhs's comments: a registry and an extremely clear status matrix for each language are my two top requests

**Comment by austinlparker** [comment]
@bhs the only thing that I don't like about building the registry off of GitHub tags is that it kinda locks people in to using GitHub for OTel stuff. What happens if someone wants to host a package on GitLab? /shrug

For the maturity matrix, it's a good idea if we can get a maturity model defined that everyone accepts.
