### ISSUE TITLE
On /status page, need to update Tracing Collector status from Experiment to Stable

### ISSUE THREAD

**Issue by horovits** [open-telemetry/opentelemetry.io#873]
**What needs to be changed?**
On opentelemetry.io/status/ page, need to update Tracing Collector status from Experiment to Stable

**What is the name + path of the page that needs changed?**
https://opentelemetry.io/status/
https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/status/_index.md

**Additional context**
to align with the achieved maturity status

**Comment by chalin** [comment]
@tedsuo - can you comment?

**Comment by chalin** [comment]
@horovits - Where are you seeing the updated tracing collector status from?

**Comment by austinlparker** [comment]
I believe the collector is tracing stable (https://medium.com/opentelemetry/opentelemetry-collector-achieves-tracing-stability-milestone-80e34cadbbf5), although the fact that the collector is versioned as a single binary makes it a bit confusing.
