### ISSUE TITLE
Docs sidenav: initial cleanup

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#895]
On desktop, the docs sidenav currently looks like this:

> <img width="150" alt="sidenav" src="https://user-images.githubusercontent.com/4140793/141189535-8eb01fbe-7bf4-4136-b0e9-094f6b04e6cb.png">

As a part of some preparatory work to #770, I'd like to _delist_ the **Workshop** and **Contribution Guidelines** entries -- they would no longer showup in the sidenav -- while preserving the pages for now.

The end result would be this:

> <img width="130" alt="sidenav cleaned up" src="https://user-images.githubusercontent.com/4140793/141190000-7ab8c613-55ae-45f6-a049-b09dfcb649d8.png">
 

@austinlparker - thoughts?

**Comment by austinlparker** [comment]
sgtm
