### ISSUE TITLE
Workshop resources seem obsolete

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#896]
The [Workshop Resources] page contains links to:

- Slides at https://docs.google.com/presentation/d/1nVhLIyqn_SiDo78jFHxnMdxYlnT0b7tYOHz3Pu4gzVQ/edit#slide=id.p
- Sample code hosted on Glitch at https://glitch.com/@opentelemetry

Both of these resources seem to have been created in 2019 (when OTel was in beta) and have not been updated since. If these resources aren't being maintained, then they should probably be dropped.

Thoughts @austinlparker?

Note that the [open-telemetry/community] repo also has a link to what is IMHO an actual [OTel slide template](https://docs.google.com/presentation/d/1Neab3OZ3c-m5kOE37iZXEVpK4Pjj6xGTJEUuUzLQJvk/edit?usp=sharing).

[open-telemetry/community]: https://github.com/open-telemetry/community
[Workshop Resources]: https://opentelemetry.io/docs/workshop/resources/

Related to #770

**Comment by austinlparker** [comment]
The glitch projects do still get used, albeit less than before... can we relocate the workshop stuff and put an (outdated) tag on it for now? It's something I'm interested in fixing in the new year.

**Comment by cartermp** [comment]
Now that we have the community demo, I'd be in favor of retiring all of this and making the page just be about that. Maybe some of the slides can get re-used but they're also only in Go, which does not represent the majority of usage of OTel for end-users.

**Comment by chalin** [comment]
So, ... do we have a thumbs-up to retire the workshop resources yet? Or to you feel that the note at the top of the page is enough? If so, then maybe this issue can be closed?

**Comment by svrnm** [comment]
yes, let's deprecate the old stuff, if someone wants to create new slides and contribute them back, we can have them again

**Comment by chalin** [comment]
Just to be sure we're on the same page: in a sense, the resources are already deprecated. I was thinking of dropping the **Workshop** (https://opentelemetry.io/docs/workshop/) section and redirecting folks to `/docs`. Ok?

(In anycase, if we add resources back, maybe they'd be better placed under `/community`.)

**Comment by cartermp** [comment]
I would agree with that change.

**Comment by svrnm** [comment]
+1

**Comment by chalin** [comment]
Closed by #2314
