### ISSUE TITLE
Glossary: Label term links to invalid spec page?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#907]
The term **Label** appeared in the glossary via #293, see [glossary.md L70-L72](https://github.com/open-telemetry/opentelemetry.io/blob/2ae73ac5474aae86e4a5714e404dbabe74ba977f/content/en/docs/concepts/glossary.md?plain=1#L70-L72). The term is linked to the following:

- https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#labels

**But the `api.md` page contains no occurrence of the term "label" or "labels"**.

Should **Label** be dropped from the glossary? If not, which reference should be used?
WDYT @flands @austinlparker?

**Comment by austinlparker** [comment]
Label has been superseded by 'Attribute'. IMO, since metric attributes are described as 'labels' in other metrics systems, it might be useful to do something like 'Label (see Attribute)' in the glossary and redirect it to that entry.
