### ISSUE TITLE
Document getting the active/current span for each language SDK

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#973]
Tracking issue for the "Getting Current Span" row here: https://docs.google.com/spreadsheets/d/1EO0HkjraZSN_7LlFpwFPoazR9xbdCCgQi-IFc0YA5rU/edit#gid=0

Emoji guide:

✔️ - this is basically good
➖ - this could be improved
❌ - this needs to exist or be rewritten

Currently documented with an example:

- [x] ✔️ Python ([link](https://opentelemetry-python.readthedocs.io/en/stable/faq-and-cookbook.html#getting-and-modifying-a-span))
- [x] ✔️ JavaScript
- [x] ✔️ Java
- [x] ✔️ Ruby
- [x] ✔️ Go

Has a section saying it exists, but needs an example of using at least one:

- [ ] ➖ C++ (doesn't have get, but has set, so it's pretty easy to figure it out from there)

Has no section at all:

- [x] ❌ .NET
- [ ] ❌ Rust
- [ ] ❌ Erlang/Elixir
- [ ] ❌ Swift
- [ ] ❌ PHP

**Comment by chalin** [comment]
@cartermp - I added checkboxes to the opening comment for subtasks. Please mark items as done when they are completed, thanks.

**Comment by svrnm** [comment]
Can this be superseded by #3229?

**Comment by cartermp** [comment]
Yep
