### ISSUE TITLE
Document creating a nested/child span

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#974]
Tracking issue for the "Nested Spans" row here: https://docs.google.com/spreadsheets/d/1EO0HkjraZSN_7LlFpwFPoazR9xbdCCgQi-IFc0YA5rU/edit#gid=0

Emoji guide:

✔️ - this is basically good
➖ - this could be improved
❌ - this needs to exist or be rewritten

Currently documented with an example:

- [x] ✔️ Java
- [x] ✔️ C++
- [x] ➖ Go (probably needs explicit section for the sample)
- [x] ➖ JavaScript (probably needs explicit section for the code sample)
- [ ] ➖ Erlang/Elixir (exists but no explicit section)
- [x] ➖ Python (it's in the quickstart but that's it, no section, no explaining the relationship)

Has no section at all:

- [ ] ❌ Ruby
- [x] ❌ .NET
- [ ] ❌ Rust
- [ ] ❌ Swift
- [ ] ❌ PHP

**Comment by svrnm** [comment]
@cartermp, Can this be superseded by #3229?

**Comment by cartermp** [comment]
Yep, let's close in favor. Whew, this one was pretty old
