### ISSUE TITLE
Document config and ENV vars (at least important ones) for each language SDK

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#975]
Tracking issue for the "Config / Env vars" row here: https://docs.google.com/spreadsheets/d/1EO0HkjraZSN_7LlFpwFPoazR9xbdCCgQi-IFc0YA5rU/edit#gid=0

Emoji guide:

✔️ - this is basically good
➖ - this could be improved
❌ - this needs to exist or be rewritten

Currently documented with an example:

- [ ] ➖ Python (in the exporters pages there are some important env vars listed)
- [ ] ➖ Go (some readmes under `/exporters/` on GitHub have some things)

Has no section at all:

- [ ] ❌ Java
- [ ] ❌ .NET
- [ ] ❌ JavaScript
- [ ] ❌ Erlang / Elixir
- [ ] ❌ C++
- [ ] ❌ Rust
- [ ] ❌ Swift
- [ ] ❌ PHP

**Comment by svrnm** [comment]
is this still a thing? @cartermp

**Comment by cartermp** [comment]
tbh I haven't seen this come up as much now that we have a lot of stuff documented under the concepts section. It's at least certainly easier to google now. I'll close for now.
