### ISSUE TITLE
Also support `docs.opentelemetry.io`  domain

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#976]
I'm unopinionated about what the main URL should be, but I think both URLs:

* opentelemetry.io/docs
* docs.opentelemetry.io

should point to the same thing. I'm not sure if this improves SEO, but I wouldn't be shocked if several folks try to go to `docs.opentelemetry.io` and get surprised at the 404.

**Comment by puckpuck** [comment]
I am one of the people who regularly type docs.opentelemetry.io and get a 404.

**Comment by austinlparker** [comment]
Let's do it

**Comment by chalin** [comment]
Closed by #1177 and #1179.
