### ISSUE TITLE
See if toc/tocstop is required for docs or not

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#980]
For example, the java docs have this at the top of the manual instrumentation page:

```

<!-- Re-generate TOC with `markdown-toc --no-first-h1 -i` -->

<!-- toc -->
- [Set up](#set-up)
- [Tracing](#tracing)
  * [Create basic Span](#create-a-basic-span)
  * [Create nested Spans](#create-nested-spans)
  * [Span Attributes](#span-attributes)
  * [Create Spans with events](#create-spans-with-events)
  * [Create Spans with links](#create-spans-with-links)
  * [Context Propagation](#context-propagation)
- [Metrics](#metrics-alpha-only)
- [Tracing SDK Configuration](#tracing-sdk-configuration)
  * [Sampler](#sampler)
  * [Span Processor](#span-processor)
  * [Exporter](#exporter)
- [Auto Configuration](#auto-configuration)
- [Logging And Error Handling](#logging-and-error-handling)
  * [Examples](#examples)
<!-- tocstop -->
```

It makes the page look kinda busy even though there's already the side-bar TOC

![image](https://user-images.githubusercontent.com/6309070/145657563-db93d9db-ce72-42fc-b734-6878a24e48b4.png)

Is it necessary to have right at the top of the page? A few other docs pages do this too (e.g., https://opentelemetry.io/docs/instrumentation/js/instrumentation/)

**Comment by chalin** [comment]
There should be no toc/tocstop for docs that live in this repo. I had started cleaning those out, but there are more to do.
