### ISSUE TITLE
Java docs: don't unnecessarily indent code

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#996]
There are some code blocks (e.g., in the Manual instrumentation page), that contain indented code like this:

        ```java
            SdkTracerProvider tracerProvider = SdkTracerProvider.builder()
              .addSpanProcessor(SimpleSpanProcessor.create(new LoggingSpanExporter()))
              .addSpanProcessor(BatchSpanProcessor.builder(new LoggingSpanExporter()).build())
              .build();
        ```

The code shouldn't be indented unless the indentation is significant, which in this (and many other cases) is doesn't seem to be.

Thoughts @cartermp?

**Comment by cartermp** [comment]
Yep, agreed. That level of indentation should only be there if it's in the context of another method or class or something. The indentation also makes it harder to copy-paste, since you then need to de-indent to match your editor 🙂
